using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;

public class DriverWhitelist
{
    private readonly List<Regex> _whitelist;

    public static readonly List<string> Whitelist = new List<string>
    {
       "ntoskrnl.exe",
            "hal.dll",
            "kd.dll",
            "CLFS.SYS",
            "tm.sys",
            "PSHED.dll",
            "BOOTVID.dll",
            "FLTMGR.SYS",
            "msrpc.sys",
            "ksecdd.sys",
            "clipsp.sys",
            "cmimcext.sys",
            "werkernel.sys",
            "ntosext.sys",
            "CI.dll",
            "cng.sys",
            "Wdf01000.sys",
            "WDFLDR.SYS",
            "WppRecorder.sys",
            "SleepStudyHelper.sys",
            "acpiex.sys",
            "msseccore.sys",
            "SgrmAgent.sys",
            "ACPI.sys",
            "WMILIB.SYS",
            "intelpep.sys",
            "WindowsTrustedRT.sys",
            "IntelTA.sys",
            "WindowsTrustedRTProxy.sys",
            "pcw.sys",
            "msisadrv.sys",
            "pci.sys",
            "vdrvroot.sys",
            "pdc.sys",
            "CEA.sys",
            "partmgr.sys",
            "spaceport.sys",
            "volmgr.sys",
            "volmgrx.sys",
            "mountmgr.sys",
            "storahci.sys",
            "storport.sys",
            "fileinfo.sys",
            "Wof.sys",
            "Ntfs.sys",
            "Fs_Rec.sys",
            "ndis.sys",
            "NETIO.SYS",
            "ksecpkg.sys",
            "tcpip.sys",
            "fwpkclnt.sys",
            "wfplwfs.sys",
            "VmsProxy.sys",
            "vmbkmclr.sys",
            "VmsProxyHNic.sys",
            "fvevol.sys",
            "volume.sys",
            "volsnap.sys",
            "rdyboost.sys",
            "mup.sys",
            "iorate.sys",
            "disk.sys",
            "CLASSPNP.SYS",
            "crashdmp.sys",
            "cdrom.sys",
            "filecrypt.sys",
            "tbs.sys",
            "UCPD.sys",
            "Null.SYS",
            "Beep.SYS",
            "dxgkrnl.sys",
            "watchdog.sys",
            "BasicDisplay.sys",
            "BasicRender.sys",
            "Npfs.SYS",
            "Msfs.SYS",
            "CimFS.SYS",
            "tdx.sys",
            "TDI.SYS",
            "netbt.sys",
            "afunix.sys",
            "afd.sys",
            "vwififlt.sys",
            "vfpext.sys",
            "pacer.sys",
            "ndiscap.sys",
            "netbios.sys",
            "Vid.sys",
            "winhvr.sys",
            "rdbss.sys",
            "csc.sys",
            "nsiproxy.sys",
            "npsvctrig.sys",
            "mssmbios.sys",
            "gpuenergydrv.sys",
            "dfsc.sys",
            "fastfat.SYS",
            "bam.sys",
            "ahcache.sys",
            "vmbusr.sys",
            "hvsocket.sys",
            "vmswitch.sys",
            "CompositeBus.sys",
            "kdnic.sys",
            "umbus.sys",
            "HDAudBus.sys",
            "portcls.sys",
            "drmk.sys",
            "ks.sys",
            "USBXHCI.SYS",
            "ucx01000.sys",
            "UcmCx.sys",
            "serial.sys",
            "serenum.sys",
            "intelppm.sys",
            "acpipagr.sys",
            "acpitime.sys",
            "wmiacpi.sys",
            "UEFI.sys",
            "vpcivsp.sys",
            "storvsp.sys",
            "ksthunk.sys",
            "Synth3dVsp.sys",
            "NdisVirtualBus.sys",
            "swenum.sys",
            "rdpbus.sys",
            "UsbHub3.sys",
            "USBD.SYS",
            "usbccgp.sys",
            "hidusb.sys",
            "HIDCLASS.SYS",
            "HIDPARSE.SYS",
            "kbdhid.sys",
            "kbdclass.sys",
            "mouhid.sys",
            "mouclass.sys",
            "win32k.sys",
            "win32kbase.sys",
            "win32kfull.sys",
            "dump_diskdump.sys",
            "dump_storahci.sys",
            "dump_dumpfve.sys",
            "dxgmms2.sys",
            "monitor.sys",
            "WUDFRd.sys",
            "hvservice.sys",
            "luafv.sys",
            "wcifs.sys",
            "cldflt.sys",
            "storqosflt.sys",
            "bindflt.sys",
            "condrv.sys",
            "hvsocketcontrol.sys",
            "vhdparser.sys",
            "FsDepends.sys",
            "vhdmp.sys",
            "lltdio.sys",
            "mslldp.sys",
            "wanarp.sys",
            "rspndr.sys",
            "nwifi.sys",
            "ndisuio.sys",
            "msquic.sys",
            "HTTP.sys",
            "bowser.sys",
            "mpsdrv.sys",
            "mrxsmb.sys",
            "mrxsmb20.sys",
            "mmcss.sys",
            "peauth.sys",
            "Ndu.sys",
            "srvnet.sys",
            "tcpipreg.sys",
            "srv2.sys",
            "rassstp.sys",
            "NDProxy.sys",
            "AgileVpn.sys",
            "rasl2tp.sys",
            "raspptp.sys",
            "raspppoe.sys",
            "ndistapi.sys",
            "ndiswan.sys",
            "winnat.sys",
            "cdd.dll",
            "USBSTOR.SYS",
            "wdiwifi.sys",
            "vwifibus.sys",
            "vwifimp.sys",
            "EhStorClass.sys",
            "kdcom.dll",
            "mcupdate_GenuineIntel.dll",
            "compbatt.sys",
            "BATTC.SYS",
            "intelide.sys",
            "PCIIDEX.SYS",
            "atapi.sys",
            "ataport.SYS",
            "msahci.sys",
            "wfplwf.sys",
            "vmstorfl.sys",
            "spldr.sys",
            "hwpolicy.sys",
            "vga.sys",
            "VIDEOPRT.SYS",
            "RDPCDD.sys",
            "rdpencdd.sys",
            "rdprefmp.sys",
            "ws2ifsl.sys",
            "termdd.sys",
            "discache.sys",
            "blbdrive.sys",
            "tunnel.sys",
            "i8042prt.sys",
            "fdc.sys",
            "dxgmms1.sys",
            "usbuhci.sys",
            "USBPORT.SYS",
            "usbehci.sys",
            "CmBatt.sys",
            "flpydisk.sys",
            "usbhub.sys",
            "HdAudio.sys",
            "Unknown dump_LSI_SAS.sys",
            "Dxapi.sys",
            "TSDDD.dll",
            "mrxsmb10.sys",
            "srv.sys",
            "spsys.sys",
            "ntdll.dll",
            "smss.exe",
            "apisetschema.dll",
            "autochk.exe",
            "normaliz.dll",
            "ws2_32.dll",
            "imagehlp.dll",
            "gdi32.dll",
            "oleaut32.dll",
            "shlwapi.dll",
            "Wldap32.dll",
            "msctf.dll",
            "wininet.dll",
            "user32.dll",
            "advapi32.dll",
            "iertutil.dll",
            "setupapi.dll",
            "sechost.dll",
            "msvcrt.dll",
            "clbcatq.dll",
            "rpcrt4.dll",
            "comdlg32.dll",
            "usp10.dll",
            "ole32.dll",
            "imm32.dll",
            "shell32.dll",
            "kernel32.dll",
            "psapi.dll",
            "urlmon.dll",
            "difxapi.dll",
            "nsi.dll",
            "lpk.dll",
            "userenv.dll",
            "api-ms-win-downlevel-advapi32-l1-1-0.dll",
            "api-ms-win-downlevel-shell32-l1-1-0.dll",
            "devobj.dll",
            "wintrust.dll",
            "cfgmgr32.dll",
            "api-ms-win-downlevel-shlwapi-l1-1-0.dll",
            "netapi32.dll",
            "api-ms-win-downlevel-ole32-l1-1-0.dll",
            "comctl32.dll",
            "api-ms-win-downlevel-user32-l1-1-0.dll",
            "api-ms-win-downlevel-normaliz-l1-1-0.dll",
            "api-ms-win-downlevel-version-l1-1-0.dll",
            "KernelBase.dll",
            "crypt32.dll",
            "srvcli.dll",
            "msasn1.dll",
            "netutils.dll",
            "profapi.dll",
            "wkscli.dll",
            "bcrypt.dll",
            "mcupdate_GenuineIntel.dll",
            "intelide.sys",
            "PCIIDEX.SYS",
            "atapi.sys",
            "ataport.SYS",
            "stornvme.sys",
            "WdFilter.sys",
            "dxgmms1.sys",
            "i8042prt.sys",
            "usbuhci.sys",
            "USBPORT.SYS",
            "usbehci.sys",
            "e1i63x64.sys",
            "vmgencounter.sys",
            "CmBatt.sys",
            "BATTC.SYS",
            "usbhub.sys",
            "HdAudio.sys",
            "udfs.sys",
            "dump_stornvme.sys",
            "TSDDD.dll",
            "mrxsmb10.sys",
            "srv.sys",
            "tunnel.sys",
            "vm3dmp_loader.sys",
            "vm3dmp.sys",
            "vmci.sys",
        // Add other known safe driver names here
    };

    public DriverWhitelist()
    {
        _whitelist = new List<Regex>
        {
            new Regex(@"(?i)[RSU][12345] BattC; .*\\Windows\\system32\\Drivers\\BattC.sys \[.+\] \(Microsoft.+\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SU][1234] (Abiosdsk|abp480n5|adpu160m|Aha154x|aic78u2|aic78xx|AliIde|amsint|asc|asc3350p|asc3550|Atdisk|cd20xrnt|Changer|CmdIde|Cpqarray|dac2w2k|dac960nt|dpti2o|hpn|i2omgmt|i2omp|ini910u|lbrtfdc|mraid35x|PCIDump|PCIIde|PDCOMP|PDFRAME|PDRELI|PDRFRAME|perc2|ql1080|perc2hib|Ql10wnt|ql12160|ql1240|ql1280|Simbad|Sparrow|Winsock|symc810|symc8xx|sym_hi|sym_u3|TosIde|ultra|ViaIde|WDICA); .* ImagePath",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] (R5U870FLx86|R5U870FUx86|5U877); .*\\Windows\\System32\\DRIVERS\\(R5U870FLx86|R5U870FUx86|5U877).sys \[.+\] \(Ricoh.*\)",
                RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] adfs; .*\\Windows\\System32\\Drivers\\adfs.sys \[.+\] \(Adobe.+\)",
                RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] ADM851X; .*\\Windows\\System32\\DRIVERS\\ADM851X.SYS \[.+\] \(ADMtek.+\)",
                RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] aeaudio; .*\\Windows\\System32\\drivers\\aeaudio.sys \[.+\] \(Andrea.+\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] AgereSoftModem; .*\\Windows\\System32\\DRIVERS\\AGRSM.sys \[.+\] \((Agere|LSI).*\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] (aksfridge|Hardlock); .*\\Windows\\system32\\drivers\\(aksfridge|Hardlock).sys \[.+\] \(Aladdin.+\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] aliide; .*\\Windows\\System32\\drivers\\aliide.sys \[.+\] \(Microsoft Windows -> Acer.+\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] (AmdLLD|PCnet|amdsbs); .*\\Windows\\System32\\DRIVERS\\(AmdLLD|amdsbs|pcntpci5).sys \[.+\] \(Microsoft Windows -> AMD.+\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] androidusb; .*\\Windows\\System32\\Drivers\\ssadadb.sys \[.+\] \(Google.*\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] anvsnddrv; .*\\Windows\\System32\\drivers\\anvsnddrv.sys \[.+\] \(AnvSoft.+\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] ApfiltrService; .*\\Windows\\System32\\DRIVERS\\Apfiltr.sys \[.+\] \(Alps.+\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] (arc|arcsas|ADP80XX); .*\\Windows\\System32\\DRIVERS\\(arc|arcsas|ADP80XX).sys \[.+\] \(Microsoft Windows -> PMC.+\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] ATSwpWDF; .*\\Windows\\System32\\Drivers\\ATSwpWDF.sys \[.+\] \(AuthenTec.+\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] AVerAF15; .*\\Windows\\System32\\Drivers\\AVerAF15.sys \[.+\] \(AVerMedia.+\)",
                RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] BENDER; .*\\Windows\\System32\\drivers\\bender.sys \[.+\] \(Pinnacle.+\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] (BMLoad|tcpipBM); .*\\Windows\\System32\\drivers\\(BMLoad|tcpipBM).sys \[.+\] \(Bytemobile.+\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] br3gmdm; .*\\Windows\\System32\\DRIVERS\\br3gmdm.sys \[.+\] \(BandRich.+\)",
                RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] Bufeap; .*\\Windows\\System32\\DRIVERS\\bufeap.sys \[.+\] \(BUFFALO.+\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] BVRPMPR5; .*\\WINDOWS\\system32\\drivers\\BVRPMPR5.SYS \[.+\] \(Avanquest.+\)",
                RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] Ca504av; .*\\Windows\\System32\\Ca504av.sys \[.+\] \(Digital.+\)",
                RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] CLFS; .*\\Windows\\System32\\CLFS.sys \[.+\] \(Microsoft.+\)",
                RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] clwvd; .*\\Windows\\System32\\DRIVERS\\clwvd.sys \[.+\] \(CyberLink.+\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] cmdide; .*\\Windows\\System32\\drivers\\cmdide.sys \[.+\] \(Microsoft Windows -> CMD Technology.+\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] CtAudDrv; .*\\Windows\\system32\\Drivers\\CtAudDrv.sys \[.+\] \(Creative.+\)",
                RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] ctxusbm; .*\\Windows\\System32\\DRIVERS\\ctxusbm.sys \[.+\] \(Citrix.+\)",
                RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] dac2w2k; .*\\Windows\\System32\\DRIVERS\\dac2w2k.sys \[.+\] \(Mylex.+\)",
                RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] DCamUSBNW802; .*\\Windows\\System32\\DRIVERS\\pcam.sys \[.+\] \(Divio.+\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] (dg_ssudbus|ssudmdm|dgderdrv); .*\\Windows\\System32\\DRIVERS\\(ssudbus|ssudmdm|dgderdrv).sys \[.+\] \(DEVGURU.+\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] (DgiVecp|SABI|SSPORT); .*\\Windows\\system32\\Drivers\\(DgiVecp|SABI|SSPORT).sys \[.+\] \(Samsung.+\)",
                RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] DKbFltr; .*\\Windows\\System32\\DRIVERS\\DKbFltr.sys \[.+\] \(Dritek.*\)",
                RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] DLABMFSM; .*\\Windows\\System32\\DLA\\DLABMFSM.SYS \[.+\] \(Roxio.*\)",
                RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] DLABOIOM; .*\\Windows\\System32\\DLA\\DLABOIOM.SYS \[.+\] \(Roxio.*\)",
                RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] DLACDBHM; .*\\Windows\\System32\\Drivers\\DLACDBHM.SYS \[.+\] \(Roxio.*\)",
                RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] DLADResM; .*\\Windows\\System32\\DLA\\DLADResM.SYS \[.+\] \(Roxio.*\)",
                RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] DLAIFS_M; .*\\Windows\\System32\\DLA\\DLAIFS_M.SYS \[.+\] \(Roxio.*\)",
                RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] DLAOPIOM; .*\\Windows\\System32\\DLA\\DLAOPIOM.SYS \[.+\] \(Roxio.*\)",
                RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] DLAPoolM; .*\\Windows\\System32\\DLA\\DLAPoolM.SYS \[.+\] \(Roxio.*\)",
                RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] DLARTL_M; .*\\Windows\\System32\\Drivers\\DLARTL_M.SYS \[.+\] \(Roxio.*\)",
                RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] DLAUDFAM; .*\\Windows\\System32\\DLA\\DLAUDFAM.SYS \[.+\] \(Roxio.*\)",
                RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] DLAUDF_M; .*\\Windows\\System32\\DLA\\DLAUDF_M.SYS \[.+\] \(Roxio.*\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] (DrvAgent32|PhnxBldr); .*\\Windows\\system32\\Drivers\\(DrvAgent32|PhnxBldr).sys \[.+\] \(Phoenix.*\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] CryptOSD; .*\\Windows\\System32\\DRIVERS\\CryptOSD.sys \[.+\] \(Phoenix.*\)",
                RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] DRVNDDM; .*\\Windows\\System32\\Drivers\\DRVNDDM.SYS \[.+\] \(Roxio.*\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] DSproct; .*\\Program Files\\DellSupport\\GTAction\\triggers\\DSproct.sys \[.+\] \(Gteko.+\)",
                RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] dsunidrv; .*\\Windows\\System32\\DRIVERS\\dsunidrv.sys \[.+\] \(Gteko.+\)",
                RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] Echo3G; .*\\Windows\\System32\\DRIVERS\\echo3G.sys \[.+\] \(Echo.+\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] elxstor; .*\\Windows\\System32\\DRIVERS\\elxstor.sys \[.+\] \(Microsoft Windows -> Emulex.*\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] (USBCamera|EMVSCARD); .*\\Windows\\System32\\Drivers\\(Bulk504|EMVSCARD).sys \[.+\] \(USB.*\)",
                RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] enecir; .*\\Windows\\System32\\DRIVERS\\enecir.sys \[.+\] \(ENE.+\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] (eFTDIBUS|FTSER2K); .*\\Windows\\System32\\drivers\\(ftdibus|FTSER2K).sys \[.+\] \(FTDI.*\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] fspad_wlh32; .*\\Windows\\System32\\DRIVERS\\fspad_wlh32.sys \[.+\] \(Sentelic.+\)",
                RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] FUJ02E3; .*\\Windows\\System32\\DRIVERS\\FUJ02E3.sys \[.+\] \(FUJITSU.*\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] GEARAspiWDM; .*\\Windows\\System32\\DRIVERS\\GEARAspiWDM.sys \[.+\] \(GEAR.+\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] cpuz135; .*\\Windows\\System32\\DRIVERS\\cpuz135_x32.sys \[.+\] \(CPUID.*\)",
                RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] HTCAND32; .*\\Windows\\System32\\Drivers\\ANDROIDUSB.sys \[.+\] \(HTC.+\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] (ewusbmbb|hwusbdev|huawei_enumerator|ewusbnet|ew_hwusbdev|ew_usbenumfilter|hwdatacard); .*\\Windows\\System32\\DRIVERS\\(ewusbnet|ew_hwusbdev|ew_usbenumfilter|ewusbmdm|ewusbdev|ewusbwwan|ew_jubusenum).sys \[.+\] \(Huawei.+\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] (HCW85BDA|hcw85cir); .*\\Windows\\System32\\drivers\\(HCW85BDA|hcw85cir).sys \[.+\] \(Microsoft Windows -> Hauppauge.+\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] hypaudio; .*\\Windows\\System32\\DRIVERS\\hypaudio.sys \[.+\] \(Universal.+\)",
                RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] IDMWFP; .*\\Windows\\System32\\DRIVERS\\idmwfp.sys \[.+\] \(Tonec.+\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] (iteatapi|iteraid); .*\\Windows\\System32\\drivers\\(iteatapi|iteraid).sys \[.+\] \(Integrated.+\)",
                RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] int15; .*\\Windows\\system32\\drivers\\int15.sys \[.+\] \(Acer.+\)",
                RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] iscFlash; .*\\SwSetup\\sp45138\\iscflash.sys \[.+\] \(Insyde.*\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] (jakndis|jakndisMP); .*\\Windows\\System32\\DRIVERS\\jakndis.sys \[.+\] \(Jaksta.+\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] (JME|JMCR); .*\\Windows\\System32\\DRIVERS\\(JME|jmcr).sys \[.+\] \(JMicron.+\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] LeapFrog-USBLAN; .*\\Windows\\System32\\DRIVERS\\btblan.sys \[.+\] \(Belcarra.+\)",
                RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] L1C; .*\\Windows\\System32\\DRIVERS\\L1C63x86.sys \[.+\] \(Qualcomm.+\)",
                RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] LMIInfo; .*\\Program Files\\LogMeIn\\x86\\RaInfo.sys \[.+\] \(LogMeIn.+\)",
                RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] lmimirr; .*\\Windows\\System32\\DRIVERS\\lmimirr.sys \[.+\] \(LogMeIn.+\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] LMIRfsDriver; .*\\Windows\\system32\\drivers\\LMIRfsDriver.sys \[.+\] \(LogMeIn.+\)",
                RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] ManyCam; .*\\Windows\\System32\\DRIVERS\\ManyCam.sys \[.+\] \(ManyCam.+\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] massfilter_hs; .*\\windows\\system32\\drivers\\massfilter_hs.sys \[.+\] \(HandSet.+\)",
                RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] mcdbus; .*\\Windows\\System32\\DRIVERS\\mcdbus.sys \[.+\] \(MagicISO.+\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] Mraid35x; .*\\Windows\\System32\\drivers\\mraid35x.sys \[.+\] \((American|LSI).+\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] (MREMP50|MRESP50); .*\\PROGRA~1\\COMMON~1\\Motive\\(MREMP50|MRESP50).SYS \[.+\] \(Printing.+\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] (NBVol|NBVolUp); .*\\Windows\\System32\\DRIVERS\\(NBVol|NBVolUp).sys \[.+\] \(Nero.*\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] (netr\d\d|rt61x86); .*\\Windows\\System32\\DRIVERS\\(netr\d\d|rt61x86).sys \[.+\] \(Ralink.+\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] nfrd960; .*\\Windows\\System32\\DRIVERS\\nfrd960.sys \[.+\] \(Microsoft Windows -> IBM.+\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] (NTIDrvr|UBHelper); .*\\Windows\\System32\\DRIVERS\\(NTIDrvr|UBHelper).sys \[.+\] \(NewTech.+\)",
                RegexOptions.Compiled),
            new Regex(
                @"(?i)[SRU][01234] ntrigdigi; .*\\Windows\\System32\\drivers\\ntrigdigi.sys \[.+\] \(N-trig Innovative.+\)",
                RegexOptions.Compiled),
                    new Regex(@"(?i)[SRU][01234] (NovaShieldFilterDriver|NovaShieldTDIDriver); .*\\Windows\\System32\\DRIVERS\\(NSKernel|NSNetmon).sys \[.+\] \(NovaShield.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] NSCIRDA; .*\\Windows\\System32\\DRIVERS\\nscirda.sys \[.+\] \(National.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] NTIPPKernel; .*\\Program Files\\Acer Arcade Deluxe\\HomeMedia\\Kernel\\DMP\\NTIPPKernel.sys \[.+\] \(Cyberlink.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (NWADI|NWUSBModem|NWUSBPort); .*\\Windows\\System32\\DRIVERS\\(NWADIenum|nwusbmdm|nwusbser).sys \[.+\] \(Novatel.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (O2MDRDR|O2SDRDR); .*\\Windows\\System32\\DRIVERS\\(o2media|o2sd).sys \[.+\] \(O2Micro.*\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] OEM02Vfx; .*\\Windows\\System32\\DRIVERS\\OEM02Vfx.sys \[.+\] \(EyePower.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] OMCI; .*\\Windows\\System32\\DRIVERS\\OMCI.SYS \[.+\] \(Dell.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] ovt519; .*\\Windows\\System32\\Drivers\\ov519vid.sys \[.+\] \(OmniVision.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] pcouffin; .*\\Windows\\System32\\Drivers\\pcouffin.sys \[.+\] \((Smith|VSO).*\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] PCTINDIS5; .*\\Windows\\system32\\PCTINDIS5.SYS \[.+\] \(Smith.*\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] PenClass; .*\\Windows\\System32\\Drivers\\PenClass.sys \[.+\] \(Wacom.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] physX32; .*\\Windows\\System32\\DRIVERS\\physX32.sys \[.+\] \(AGEIA.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (PGPdisk|pgpfs|PGPsdkDriver|PGPwded|Pgpwdefs); .*\\Windows\\System32\\Drivers\\(PGPdisk|PGPfsfd|PGPsdk|PGPwded|Pgpwdefs).sys \[.+\] \(PGP.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] pmxmouse; .*\\Windows\\System32\\DRIVERS\\pmxmouse.sys \[.+\] \(Primax.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] pmxusblf; .*\\Windows\\System32\\DRIVERS\\pmxusblf.sys \[.+\] \(Primax.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] Ptilink; .*\\Windows\\System32\\DRIVERS\\ptilink.sys \[.+\] \(Parallel.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (PSDFilter|PSDNServ|psdvdisk); .*\\Windows\\System32\\DRIVERS\\(psdfilter|PSDNServ|psdvdisk).sys \[.+\] \(Egis.+\)", RegexOptions.Compiled),
                new Regex(@"(?i)[SRU][01234] (ql1080|Ql10wnt|ql12160|ql1240|ql1280|ql2300|ql40xx); .*\\Windows\\System32\\DRIVERS\\(ql1080|Ql10wnt|ql12160|ql1240|ql1280|ql40xx|ql2300).sys \[.+\] \(Microsoft Windows -> QLogic.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] regi; .*\\Windows\\System32\\drivers\\regi.sys \[.+\] \(InterVideo.*\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (RapportEI|RapportPG); .*\\Program Files\\Trusteer\\Rapport\\bin\\(RapportEI|RapportPG).sys \[.+\] \(Trusteer.*\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] RapportIaso; .*\\programdata\\trusteer\\rapport\\store\\exts\\rapportms\\39624\\rapportiaso.sys \[.+\] \(Trusteer.*\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] RapportKELL; .*\\Windows\\System32\\Drivers\\RapportKELL.sys \[.+\] \(Trusteer.*\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234](danewFltr|Razerlow); .*\\Windows\\System32\\Drivers\\(danew|Razerlow).sys \[.+\] \(Razer.*\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] Revoflt; .*\\Windows\\System32\\DRIVERS\\revoflt.sys \[.+\] \(VS.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] RimUsb; .*\\Windows\\System32\\Drivers\\RimUsb.sys \[.+\] \(Research.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] RimVSerPort; .*\\Windows\\System32\\DRIVERS\\RimSerial.sys \[.+\] \(Research.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] SaiH075C; .*\\Windows\\System32\\DRIVERS\\SaiH075C.sys \[.+\] \(Saitek.*\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] SANDRA; .*\\Program Files\\SiSoftware\\SiSoftware Sandra Professional Business 2011\\WNt500x86\\Sandra.sys \[.+\] \(SiSoftware.*\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (sbmount|stcvsm); .*\\Windows\\System32\\Drivers\\(sbmount|stcvsm).sys \[.+\] \(StorageCraft.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] SCDEmu; .*\\Windows\\System32\\Drivers\\SCDEmu.sys \[.+\] \(PowerISO.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] SCManager; .*\\Windows\\System32\\Drivers\\SCManager.sys \[.+\] \(Impulse.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] secdrv; .*\\Windows\\System32\\Drivers\\secdrv.sys \[.+\] \(Microsoft Windows -> Macrovision.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] SenFiltService; .*\\Windows\\System32\\Drivers\\Senfilt.SYS \[.+\] \(Sensaura.\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] Sentinel; .*\\Windows\\System32\\Drivers\\SENTINEL.SYS \[.+\] \(SafeNet.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] Ser2pl; .*\\Windows\\System32\\DRIVERS\\ser2pl.sys \[.+\] \(Prolific.+\)", RegexOptions.Compiled),
               new Regex(@"(?i)[SRU][01234] (sfdrv01|sfhlp02|sfsync02); .*\\Windows\\System32\\drivers\\(sfdrv01|sfhlp02|sfsync02).sys \[.+\] \(Protection.*\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (siigPCIeSer|siigPPort); .*\\Windows\\system32\\DRIVERS\\(siigPCIeSer|siigPPort).sys \[.+\] \(SIIG.*\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (SiSRaid4|SiSRaid2|sisagp|SiS6350|SISAGP|SiSGbeLH|DSI_SiUSBXp_3_1); .*\\Windows\\System32\\DRIVERS\\(sisraid4|SiSRaid2|sisagp|SISGRKMD|SISAGPX|SiSGB6|DSI_SiUSBXp_3_1).sys \[.+\] \(Microsoft Windows -> Silicon.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] smihlp2; .*\\Program Files\\ThinkVantage Fingerprint Software\\smihlp.sys \[.+\] \(UPEK.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] SMSCIRDA; .*\\Windows\\System32\\DRIVERS\\SMSCirda.sys \[.+\] \(SMSC.*\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (ADIHdAudAddService|smwdm); .*\\Windows\\System32\\drivers\\(ADIHdAud|smwdm).sys \[.+\] \(Analog.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] ssmirrdr; .*\\Windows\\System32\\DRIVERS\\ssmirrdr.sys \[.+\] \(support.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] SSPORT; .*\\Windows\\system32\\Drivers\\SSPORT.sys \[.+\] \(Microsoft.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] stdflt; .*\\Windows\\System32\\DRIVERS\\stdflt.sys \[.+\] \(ST Microelectronics\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] stexstor; .*\\Windows\\System32\\DRIVERS\\stexstor.sys \[.+\] \(Microsoft Windows -> Promise.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] STHDA; .*\\Windows\\System32\\DRIVERS\\stwrt.sys \[.+\] \(IDT.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] STIrUsb; .*\\Windows\\System32\\DRIVERS\\irstusb.sys \[.+\] \(SigmaTel.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] SWMX00; .*\\Windows\\System32\\DRIVERS\\swmx00.sys \[.+\] \(Sierra Wireless.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] SWNC5E00; .*\\Windows\\System32\\DRIVERS\\SWNC5E00.sys \[.+\] \(Sierra Wireless.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] sxuptp; .*\\Windows\\System32\\DRIVERS\\sxuptp.sys \[.+\] \(silex Wireless.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] symc810; .*\\Windows\\System32\\DRIVERS\\symc810.sys \[.+\] \(Symbios.*\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] symsnap; .*\\Windows\\System32\\DRIVERS\\symsnap.sys \[.+\] \(StorageCraft.*\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] SynTP; .*\\Windows\\System32\\DRIVERS\\SynTP.sys \[.+\] \(Synaptics.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (tapoas|tapvpn); .*\\Windows\\System32\\DRIVERS\\(tapoas|tapvpn).sys \[.+\] \(The.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] tcusb; .*\\Windows\\System32\\DRIVERS\\tcusb.sys \[.+\] \(UPEK.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] tifm21; .*\\Windows\\System32\\DRIVERS\\tifm21.sys \[.+\] \(Texas.+\)", RegexOptions.Compiled),
               new Regex(@"(?i)[SRU][01234] tmobile_mf691_dc_enum; .*\\Windows\\System32\\DRIVERS\\tmobile_mf691_dc_enum.sys \[.+\] \(T-Mobile.*\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] TodosAgmII; .*\\Windows\\System32\\Drivers\\AgmIIusb.sys \[.+\] \(Todos.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] TpChoice; .*\\Windows\\System32\\DRIVERS\\TpChoice.sys \[.+\] \(Alps.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] tpflhlp; .*\\Program Files\\Lenovo\\System Update\\session\\7uuj07us\\tpflhlp.sys \[.+\] \(Lenovo.*\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] truecrypt; .*\\Windows\\System32\\drivers\\truecrypt.sys \[.+\] \(TrueCrypt.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] TuneUpUtilitiesDrv; .*\\Program Files\\TuneUp Utilities 2011\\TuneUpUtilitiesDriver32.sys \[.+\] \(TuneUp.*\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] TVicPort; .*\\Windows\\System32\\Drivers\\TVicPort.sys \[.+\] \(EnTech.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] uagp35; .*\\Windows\\System32\\DRIVERS\\uagp35.sys \[.+\] \(Microsoft.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] uliahci; .*\\Windows\\System32\\drivers\\uliahci.sys \[.+\] \(ULi Electronics.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] UlSat(a|a2); .*\\Windows\\System32\\drivers\\ulsat(a|a2).sys \[.+\] \(Promise.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] ultra; .*\\Windows\\System32\\DRIVERS\\ultra.sys \[.+\] \(Promise.*\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (mod7700|nmwcd|nmwcdcm|nmwcdc|nmwcdcj|nmwcdsacm|nmwcdsa|nmwcdnsu|nmwcdnsuc|nmwcdsac|nmwcdsacj|pccsmcfd|upperdev|UsbserFilt); .*\\Windows\\System32\\drivers\\(ccdcmb|dvb7700all|ccdcmbo|nmwcdsacm|nmwcd|nmwcdsa|nmwcdcm|nmwcdc|nmwcdcj|nmwcdsac|nmwcdsacj|nmwcdnsu|nmwcdnsuc|pccsmcfd|usbser_lowerflt|usbser_lowerfltj).sys \[.+\] \(Nokia.*\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (Netaapl|USBAAPL); .*\\Windows\\System32\\Drivers\\(usbaapl|Netaapl).sys \[.+\] \(Apple.+\)", RegexOptions.Compiled),
             new Regex(@"(?i)[SRU][01234] usbcm; .*\\Windows\\System32\\DRIVERS\\usbcm.sys \[.+\] \(Microsystems.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] UsbFltr; .*\\Windows\\System32\\DRIVERS\\UsbFltr.sys \[.+\] \(Waytech.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] USBIO; .*\\Windows\\System32\\Drivers\\usbio.sys \[.+\] \(Thesycon.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (VBoxDrv|VBoxNetAdp|VBoxNetFlt|VBoxUSB|VBoxUSBMon); .*\\Windows\\System32\\DRIVERS\\(VBoxDrv|VBoxNetAdp|VBoxNetFlt|VBoxUSB|VBoxUSBMon).sys \[.+\] \(Oracle.*\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] VClone; .*\\Windows\\System32\\DRIVERS\\VClone.sys \[.+\] \(Elaborate.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] vfs101x; .*\\Windows\\System32\\Drivers\\vfs101x.sys \[.+\] \(Validity.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] viaide; .*\\Windows\\System32\\drivers\\viaide.sys \[.+\] \((VIA|Microsoft).+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] vm3dmp; .*\\Windows\\System32\\DRIVERS\\vm3dmp.sys \[.+\] \(VMware.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] VMAUDIO; .*\\Windows\\System32\\drivers\\vmaudio.sys \[.+\] \(VMware.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] vmbus; .*\\Windows\\System32\\drivers\\vmbus.sys \[.+\] \(Microsoft.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] vmci; .*\\Windows\\System32\\DRIVERS\\vmci.sys \[.+\] \(VMware.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] vmdebug; .*\\Windows\\system32\\Drivers\\vmdebug.sys \[.+\] \(VMware.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] vmhgfs; .*\\Windows\\System32\\DRIVERS\\vmhgfs.sys \[.+\] \(VMware.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] vmmouse; .*\\Windows\\System32\\DRIVERS\\vmmouse.sys \[.+\] \(VMware.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (vmrawdsk|VMMEMCTL); .*\\Program Files\\VMware\\VMware Tool(s|s\\Drivers\\memctl)\\(vmrawdsk|VMMEMCTL).sys \[.+\] \(VMware.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (vmrawdsk|VMMEMCTL|vmusbmouse|vsock); .*\\Windows\\System32\\DRIVERS\\(vmrawdsk|VMMEMCTL|vmusbmouse|vsock).sys \[.+\] \(VMware.+\)", RegexOptions.Compiled),
              new Regex(@"(?i)[SRU][01234] vpnva; .*\\Windows\\System32\\DRIVERS\\vpnva.sys \[.+\] \(Cisco.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][0] volsnap; .*\\Windows\\System32\\drivers\\volsnap.sys \[.+\] \(Microsoft.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (VSTXRAID|vsmraid); .*\\Windows\\System32\\DRIVERS\\(VSTXRAID|vsmraid).sys \[.+\] \(Microsoft Windows -> VIA.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] wacmoumonitor; .*\\Windows\\System32\\DRIVERS\\wacmoumonitor.sys \[.+\] \(Wacom.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] wacommousefilter; .*\\Windows\\System32\\DRIVERS\\wacommousefilter.sys \[.+\] \(Wacom.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] wacomvhid; .*\\Windows\\System32\\DRIVERS\\wacomvhid.sys \[.+\] \(Wacom.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] WacomVKHid; .*\\Windows\\System32\\DRIVERS\\WacomVKHid.sys \[.+\] \(Wacom.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] Wd; .*\\Windows\\System32\\DRIVERS\\wd.sys \[.+\] \(Microsoft.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] WDC_SAM; .*\\Windows\\System32\\DRIVERS\\wdcsam.sys \[.+\] \(Western.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] WinVDEDrv; .*\\Windows\\system32\\WinVDEdrv.sys \[.+\] \(NewSoftwares.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (mvumis|mvusbews|yukonwlh|yukonw7); .*\\Windows\\System32\\DRIVERS\\(mvumis|mvusbews|yk60x86|yk62x86).sys \[.+\] \(Microsoft Windows -> Marvell.*\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] zntport; .*\\Windows\\system32\\drivers\\zntport.sys \[.+\] \(Zeal.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (snapman|afcdp|tdrpman273|timounter|vidsflt61); .*\\Windows\\System32\\DRIVERS\\(snapman|afcdp|tdrpm273|timntr|vidsflt61).sys \[.+\] \(Acronis.*\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (adp94xx|adpahci|aadptahci|adpu160m|adpu160m|adpu320|aic78xx|arc|arcsas|Aspi32|cercsr6|snapman|Sparrow); .*\\Windows\\System32\\DRIVERS\\(adp94xx|adpahci|adptahci|adpu160m|adpu160m|adpu320|arc|Aspi32|arcsas|cercsr6|djsvs|snapman|Sparrow).sys \[.+\] \(Microsoft Windows -> Adaptec.+\)", RegexOptions.Compiled),
               new Regex(@"(?i)[SRU][01234] (amdagp|amdiox86|amdkmdag|amdsata|amdxata|asc|asc3550|amdkmdap|AtiHDAudioService|atikmdag|atikmdap|AtiPcie|usbfilter); .*\\Windows\\System32\\drivers\\(amdiox86|amdsata|amdxata|asc|asc3550|amdagp|atikmdag|atikmpag|AtihdW73|AtiPcie|usbfilter|AtihdWT3).sys \[.+\] \(Microsoft Windows -> Advanced.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (amdkmdag|ati2mtag|amdkmdap|AtiHdmiService|atikmdag|AtiPcie|R300); .*\\Windows\\System32\\DRIVERS\\(AtiHdmi|atikmdag|ati2mtag|AtiPcie).sys \[.+\] \(ATI.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (AthBTPort|BTATH_A2DP|BTATH_BUS|BTATH_HCRP|BTATH_LWFLT|BTATH_RCP|BtFilter|athr|athrusb|AtcL001|jswpslwf|JMCR|L1C); .*\\Windows\\System32\\DRIVERS\\(BTATH_A2DP|BTATH_BUS|BTATH_HCRP|BTATH_LWFLT|BTATH_RCP|BtFilter|athr|athrusb|l160x86|jswpslwf|JMCR|L1C62x86|btath_flt).sys \[.+\] \(Atheros.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (mvumis|ItSas\d+i|megasas\d+i|LSI_SAS\di|megasas(|\di)|percsas\di); .*\\Windows\\System32\\DRIVERS\\(mvumis|ItSas\d+i|megasas\d+i|LSI_SAS\di|megasas(|\d+i)|percsas\di).sys \[.+\] \(Microsoft Windows -> Avago.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (k57nd60x|b57w2k|b06bdrv|b57nd60x|bcm4sbxp|BCM43XV|BCM43XX|btusbflt|btwaudio|btwavdt|btwl2cap|btwrchid|ebdrv); .*\\Windows\\System32\\DRIVERS\\(k57nd60x|bxvbdx|b57nd60x|bcm4sbxp|bcmwl6|btusbflt|btwaudio|btwavdt|btwl2cap|btwrchid|b57xp32|evbdx).sys \[.+\] \(Microsoft Windows -> Broadcom.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] bcmfn2; .*\\Windows\\System32\\DRIVERS\\bcmfn2.sys \[.+\] \((Microsoft|Broadcom).+ -> Broadcom.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (BrFiltLo|BrPar|BrFiltUp|BrScnUsb|BrSerIb|Brserid|BrSerIf|BrSerWdm|BrUsbMdm|BrUsbSer|BrUsbSIb|Serial); .*\\Windows\\System32\\DRIVERS\\(BrFiltLo|BrPar|BrFiltUp|BrSerIb|Brserid|BrSerIf|BrSerWdm|BrUsbMdm|BrUsbSer|BrUsbSIb|Serial).sys \[.+\] \(Microsoft Windows -> Brother.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (CAMCAUD|CAMCHALA|VSTHWATI|CnxtHdAudService|HSF_DP|HSFHWAZL|HSF_DPV|HSFHWBS2|HSXHWBS2|HSXHWAZL|mdmxsdk|SrvHsfHDA|SrvHsfV92|SrvHsfWinac|VSTHWBS2|VST_DPV|winachsf|XAudio); .*\\Windows\\System32\\drivers\\(camc6aud|camc6hal|VSTATI3|CHDRT32|HSF_DP|HSX_DP|HSFHWBS2|HSX_DPV|HSXHWBS2|HSXHWAZL|HSX_CNXT|mdmxsdk|VSTAZL3|VSTBS23|VSTDPV3|VSTAZL3|VSTCNXT3|VSTAZL3|VSTDPV3|VSTCNXT3|VSTDPV3|XAudio|XAudio32|HSF_CNXT).sys \[.+\] \(Conexant.*\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (CT20XUT|senfilt|CT20XUT.SYS|ctac32k|ctaud2k|CtClsFlt|CTEXFIFX|CTEXFIFX.sys|CTHWIUT|CTHWIUT.sys|ctprxy2k|ctsfm2k|emupia|ha20x22k|ha20x2k|OEM02Dev|ossrv); .*\\Windows\\System32\\drivers\\(CT20XUT|ctac32k|ctaud2k|CtClsFlt|CTEXFIFX|CTHWIUT|ctprxy2k|ctsfm2k|emupia2k|ha20x22k|ha20x2k|ctoss2k|senfilt|OEM02Dev).SYS \[.+\] \(Creative.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (iai2c|Accelerometer|HBtnKey|HpCISSs|hpdskflt|HpSAMD|HpqKbFiltr|Ps2); .*\\Windows\\System32\\drivers\\(Accelerometer|hpcisss|cpqbttn|hpdskflt|HpSAMD|HpqKbFiltr|Ps2|iai2c).sys \[.+\] \(Microsoft Windows -> Hewlett.*\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (e1i\d+32|iaStorAVC|MEIx64|iagpio|iaLPSS2i_GPIO2|iai2c|GPIO|IntcHdmiAddService|GPIO|iaioi2c|iaStorAV|e1iexpress|E100B|E1G60|e1yexpress|e1express|e1kexpress|HECI|iaNvStor|iaStor|ialm|iaStorV|igddim32|igdkmd32|iirsp|intelkmd|igfx|Impcd|IntcDAud|NETw4v32|NETw5v32|NETw3v32|NETw5s32); .*\\Windows\\System32\\DRIVERS\\(iaStorAVC|IntcHdmi|e100b325|E1G60I32|e1y6032|e1e6032|e1e5132|e1k6232|HECI|e1i\d+32|GPIO|iaioi2c|iaStorAV|iaNvStor|iaStor|ialmnt5|igddim32|igdkmd32|igxpmp32|igdkmd32|iaStorV|iirsp|igdkmd32|Impcd|IntcDAud|NETw5v32|e1y6232|NETw3v32|NETw4v32|NETw5s32|iaiogpio|iai2c|iagpio|iaLPSS2i_GPIO2|TeeDriverW8x64).sys \[.+\] \((Microsoft|Intel|MCG Windows).+ -> Inte.+\)", RegexOptions.Compiled),
               new Regex(@"(?i)[SRU][01234] (DozeHDD|IBMPMDRV|lenovo.smi|psadd|Shockprf|TPDIGIMN|TPPWRIF|tvtfilter|TVTI2C|tvtumon); .*\\Windows\\System32\\DRIVERS\\(DozeHDD|ibmpmdrv|smiif32|psadd|Apsx86|ApsHM86|Tppwr32v|tvtfilter|TVTI2C|tvtumon).sys \[.+\] \(Lenovo.*\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (Symc8xx|Sym_hi|Sym_u3|LSI_SAS2i|percsas2i|LSI_FC|LSI_SAS3|LSI_SAS|LSI_SAS2|LSI_SCSI|3ware|LSI_SSS|megasas|MegaSR); .*\\Windows\\System32\\DRIVERS\\(LSI_SAS2i|percsas2i|lsi_fc|LSI_SAS3|3ware|LSI_SSS|LSI_SAS|LSI_SAS2|LSI_SCSI|megasas|MegaSR|Symc8xx|Sym_hi|Sym_u3).sys \[.+\] \(Microsoft Windows -> LSI.*\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (L8042Kbd|LBeepKE|LHidKe|LMouFilt|L8042mou|LHidFilt|LHidFlt2|LHidUsbLMouFilt|LMouFlt2|LMouKE|lvpopflt|LVRS|LVUVC); .*\\Windows\\System32\\DRIVERS\\(L8042Kbd|L8042mou|LHidFilt|LHidFlt2|LHidUsb|LBeepKE|LHidKe|LMouFilt|LMouKE|LMouFlt2|lvpopflt|LVRS|LVUVC).sys \[.+\] \(Logitech.*\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (s1018bus|s1018mdfl|s1018mdm|s1018mgmt|s1018nd5|s1018unic|s816bus|zebrmdm|zebrmdmc|s115bus|s115mdfl|s115mdm|s115mgmt|s115obex|s816mdfl|s816mdm|s816mgmt|s816obex|s816nd5|s816unic|s1039bus|ss_bus|ss_mdfl|ss_mdm|s1039mdfl|s1039mgmt|s1039nd5|s1039obex|s1039unic|ssadbus|ssadmdfl|ssadmdm|ssadserd|sscdbus|sscdserd|sscdmdfl|zebrbus|zebrmdfl|sscdmdm); .*\\Windows\\System32\\DRIVERS\\(s1018bus|s1018mdfl|s1018mdm|s1018mgmt|s1018nd5|s1018unic|zebrmdmc|s816bus|s816mdfl|s816mdm|s816mgmt|s816obex|s816nd5|s816unic|s1039bus|ss_bus|ss_mdfl|ss_mdm|s1039mdfl|s1039mgmt|s115bus|s115mdfl|s115mdm|s115mgmt|s115obex|s1039nd5|zebrbus|zebrmdfl|zebrmdm|s1039obex|s1039unic|ssadbus|ssadmdfl|ssadmdm|ssadserd|sscdbus|sscdserd|sscdmdfl|sscdmdm).sys \[.+\] \(MCCI.*\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (BTCFilterService|motccgp|motccgpfl|motmodem|MotoSwitchService|Motousbnet|motusbdevice|smserial); .*\\Windows\\System32\\DRIVERS\\(motfilt|motccgp|motccgpfl|motmodem|motswch|Motousbnet|motusbdevice|smserial).sys \[.+\] \(Motorola.*\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (nusb3hub|nusb3xhc); .*\\Windows\\System32\\DRIVERS\\(nusb3hub|nusb3xhc).sys \[.+\] \(NEC.*\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (nv|NVENETFD|NVHDA|nvlddmkm|NVNET|nvoclock|nvsmu|NVR0Dev|nvraid|nvrd32|nvstor|nvstor32); .*\\Windows\\System32\\DRIVERS\\(nv4_mini|nvmfdx32|nvm60x32|nvhda32v|nvlddmkm|nvsmu|nvmf6232|nvoclock|nvm62x32|nvoclock|nvraid|nvrd32|nvstor|nvstor32).sys \[.+\] \((Microsoft Windows|NVIDIA Corporation) -> NVIDIA.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (eabfiltr|RTLE8023xp|RTL8168|MCSTRM|IntcAzAudAddService|RTL8023xp|RSUSBSTOR|DRTL8192cu|RTL8167|RTL8192su|RTL8169|rtl8192se|RTSTOR|RSUSBSTOR); .*\\Windows\\System32\\drivers\\(eabfiltr|MCSTRM|IntcAzAudAddService|Rtnicxp|RTKVHDA|RSUSBSTOR|RTL8192cu|Rtenicxp|Rt86win7|RtkHDAud|Rtlh86|Rt630x86|RTL8192su|rtl8192se|RTSTOR|RtsUStor).sys \[.+\] \(Realtek.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (rimmptsk|rimspci|rimsptsk|risdptsk|rismxdp|PxHelp20); .*\\Windows\\System32\\DRIVERS\\(rimmptsk|rimspe86|rimsptsk|risdptsk|rixdptsk|PxHelp20).sys \[.+\] \(REDC.*\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (PxHelp20|DRVMCDB|PxHelp20|SahdIa32|SaibIa32|SaibVd32); .*\\Windows\\System32\\Drivers\\(DRVMCDB|SahdIa32|SaibIa32|SaibVd32|PxHelp20).SYS \[.+\] \(Sonic.*\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (DMICall|ggflt|ggsemc|seehcri|SNC|SFEP); .*\\Windows\\System32\\DRIVERS\\(DMICall|ggflt|ggsemc|seehcri|SonyNC|SFEP).sys \[.+\] \(Sony.*\)", RegexOptions.Compiled),
              new Regex(@"(?i)[SRU][01234] (FwLnk|KR10I|KR10N|KR3NPXP|TBtnKey|tdcmdpst|Thpdrv|Thpevm|tos_sps32|toshidpt|tosporte|tosrfbd|tosrfbnp|Tosrfcom|tosrfec|Tosrfhid|tosrfnds|TosRfSnd|Tosrfusb|TVALZ); .*\\Windows\\System32\\drivers\\(FwLnk|KR10I|KR10N|KR3NPXP|TBtnKey|tdcmdpst|Thpdrv|Thpevm|tos_sps32|toshidpt|tosporte|tosrfbd|tosrfbnp|Tosrfcom|tosrfec|Tosrfhid|tosrfnds|TosRfSnd|Tosrfusb|TVALZ|TVALZ_O).sys \[.+\] \(TOSHIBA.*\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (bcmfn|HDAudBus|VKbms|htcnprot|PulseUsb|SndTAudio|speedfan|SymAFR); .*\\Windows\\System32\\DRIVERS\\(HDAudBus|VKbms|htcnprot|PulseUsb|SndTAudio|speedfan|SymAFR|bcmfn).sys \[.+\] \(Windows.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] cpuz134; .*\\Windows\\system32\\drivers\\cpuz134_x32.sys \[.+\] \(Windows.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] DRToggleSleep; .*\\Program Files\\HyperSpace\\DRToggleSleep.sys \[.+\] \(Windows.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[RSU][01234] bcmfn2; .*\\Windows\\System32\\DRIVERS\\bcmfn2.sys \[.+\] \((Microsoft|Broadcom).+ -> Windows.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (ghsmdm|massfilter|ZTEusbmdm6k|ZTEusbnmea|ZTEusbser6k); .*\\Windows\\System32\\DRIVERS\\(ghsmdm|massfilter|ZTEusbmdm6k|ZTEusbnmea|ZTEusbser6k).sys \[.+\] \(ZTE.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (Acx01000|hidspi|BthMini|BasicRender|bam|BthA2DP|BthHFAud|dc1-controller|clreg|AcpiDev|applockerfltr|AppvStrm|AppvVemgr|AppvVfs|BthLEEnum|BasicRender|buttonconverter|CapImg|fcvsc|FileCrypt|genericusbfn|GpuEnergyDrv|hidinterrupt|IoQos|BthAvrcpTg|ACPIEC|ACPI|AcpiPmi|adpu160m|aec|AFD|agp440|agpCPQ|Aha154x|aic78u2|aic78xx|alim1541|amdagp|amdide|AmdK7|AmdK8|AmdPPM|AmdK7|AmdK8|amsint|AppID|Arp1394|asc3350p|AsyncMac|atapi|Atmarpc|audstub|Avc|Beep|blbdrive|bowser|Bridge|BridgeMP|MsBridge|BthEnum|BTHMODEM|BthPan|BTHPORT|BTHUSB|cbidf|cbidf2k|cd20xrnt|Cdaudio|cdfs|cdrom|circlass|CmBatt|CNG|Compbatt|CompositeBus|Cpqarray|crcdisk|Crusoe|CSC|dac960nt|dc3d|DfsC|discache|Disk|dmboot|dmio|gencounter|dmload|DMusic|dmvsc|Dot4|Dot4Print|dot4usb|dpti2o|drmkaud|DXGKrnl|Ecache|ErrDev|exfat|fastfat|fdc|FileInfo|Filetrace|Fips|flpydisk|FltMgr|FsDepends|Fs_Rec|fssfltr|Ftdisk|fvevol|gagp30kx|Gpc|HdAudAddService|HDAudBus|HidBatt|HidBth|hidi2c|hyperkbd|HyperVideo|HidIr|GPIOClx0101|HidUsb|hpn|HTTP|hwpolicy); .*\\Windows\\System32\\drivers\\(Acx01000|acpiex|BasicRender|BthAvrcpTg|abp480n5|ACPI|ACPIEC|AcpiPmi|adpu160m|aec|AFD|agp440|agpCPQ|Aha154x|aic78u2|aic78xx|alim1541|amdagp|amdide|AmdK7|AmdK8|AmdPPM|AmdK7|AmdK8|amsint|AppID|hidi2c|hyperkbd|HyperVideo|Arp1394|asc3350p|AsyncMac|atapi|Atmarpc|audstub|Avc|Beep|blbdrive|bowser|bridge|BthEnum|BTHMODEM|BthPan|BTHPORT|BTHUSB|cbidf2k|cd20xrnt|Cdaudio|cdfs|cdrom|circlass|CmBatt|CNG|Compbatt|CompositeBus|Cpqarray|crcdisk|Crusoe|CSC|dac960nt|dc3d|DfsC|discache|Disk|dmboot|dmio|CCDECODE|msgpioclx|dmload|DMusic|dmvsc|Dot4|Dot4Prt|vmgencounter|dot4usb|dpti2o|drmkaud|DXGKrnl|Ecache|ErrDev|exfat|fastfat|fdc|FileInfo|Filetrace|Fips|flpydisk|FltMgr|FsDepends|Fs_Rec|fssfltr|Ftdisk|fvevol|gameenum|gagp30kx|msgpc|HdAudio|HDAudBus|HidBatt|HidBth|HidIr|HidUsb|hpn|HTTP|hwpolicy|buttonconverter|CapImg|fcvsc|FileCrypt|genericusbfn|GpuEnergyDrv|hidinterrupt|IoQos|BthLEEnum|AcpiDev|applockerfltr|AppvStrm|AppvVemgr|AppvVfs|registry|BthA2DP|BthHFAud|dc1-controller|bam|Microsoft.Bluetooth.Legacy.LEEnumerator|BthMini|hidspi).sys \[.+\] \(Microsoft.+ -> Microsoft.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (CimFS|MsQuic|Telemetry|dpjarohp|bindflt|afunix|WdmCompanionFilter|HwNClx0101|CAD|CldFlt|CLFS|ahcache|BasicDisplay|bcmfn2|acpipagr|acpitime|acpiex|1394ohci|Acceler|BthHFEnum|bthhfhid|cnghwassist|condrv|dam|EhStorClass|EhStorTcgDrv|FxPPM); .*\\Windows\\System32\\drivers\\(CimFS|MsQuic|dpjarohp|bindflt|afunix|WdmCompanionFilter|BthHFEnum|bthhfhid|cnghwassist|condrv|dam|bcmfn2|EhStorClass|CLFS|BasicDisplay|EhStorTcgDrv|FxPPM|1394ohci|acpipagr|acpiex|Acceler|ahcache|acpitime|CAD|CldFlt|mshwnclx|IntelTA).sys \[.+\] \(Microsoft.+ ->.+\)", RegexOptions.Compiled),
                        new Regex(@"(?i)[SRU][01234] (intelpmax|Microsoft_Bluetooth_AvrcpTransport|MbbCx|IPT|IndirectKmd|mausbip|mausbhost|NetAdapterCx|MsSecFlt|iorate|MMCSS|MQAC|i2omp|i2omgmt|i8042prt|Imapi|ini910u|intelide|intelppm|Ip6Fw|NABTSFEC|NdisVirtualBus|netvsc|intelpep|kbldfltr|IpFilterDriver|IpInIp|IPMIDRV|IPNAT|IPSec|irda|IRENUM|isapnp|iScsiPrt|k57nd60x|kbdclass|kbdhid|kmixer|KSecDD|KSecPkg|lltdio|luafv|MHNDRV|mnmdd|MODEMCSA|Modem|monitor|mouclass|mouhid|mountmgr|mpio|mpsdrv|Mraid35x|MRxDAV|mrxsmb|mrxsmb10|mrxsmb20|msahci|msdsm|MSDV|Msfs|mshidkmdf|kdnic|msgpiowin32|mshidumdf|MsLldp|NdisImPlatform|NDISWANLEGACY|Ndu|npsvctrig|MSHUSBVideo|msisadrv|MSKSSRV|MSPCLOCK|MSPQM|MsRPC|mssmbios|MSTEE|MTConfig|Mup|MXOPSWD|NativeWifiP|NDIS|NdisCap|NdisTapi|Ndisuio|NdisWan|NDProxy|NetBIOS|NetBT|NfsRdr|NIC1394|NisDrv|Npfs|nsiproxy|Ntfs|Null|nv_agp|NwlnkFlt|NwlnkFwd); .*\\Windows\\System32\\drivers\\(intelpmax|i2omp|i2omgmt|i8042prt|Imapi|ini910u|intelide|intelppm|Ip6Fw|ipfltdrv|IpInIp|IPMIDRV|IPNAT|IPSec|irda|kdnic|msgpiowin32|mshidumdf|MsLldp|NdisImPlatform|NDISWANLEGACY|Ndu|npsvctrig|IRENUM|isapnp|msiscsi|k57nd60x|kbdclass|kbdhid|kmixer|KSecDD|KSecPkg|lltdio|luafv|MHNDRV|mnmdd|MODEMCSA|Modem|monitor|mouclass|mouhid|mountmgr|mpio|mpsdrv|Mraid35x|MRxDAV|NABTSFEC|mrxsmb|mrxsmb10|mrxsmb20|msahci|msdsm|MSDV|Msfs|mshidkmdf|msisadrv|MSKSSRV|MSPCLOCK|MSPQM|MsRPC|mssmbios|MSTEE|MTConfig|Mup|MXOPSWD|nx6000|nwifi|NDIS|NdisCap|NdisTapi|Ndisuio|NdisWan|NdisVirtualBus|NDProxy|NetBIOS|netvsc63|NetBT|NfsRdr|NIC1394|intelpep|kbldfltr|NisDrvWFP|Npfs|nsiproxy|Ntfs|Null|nv_agp|NwlnkFlt|NwlnkFwd|MMCSS|MQAC|netvsc|IndirectKmd|MsSecFlt|iorate|mausbip|mausbhost|NetAdapterCx|IPT|MbbCx|Microsoft.Bluetooth.AvrcpTransport).sys \[.+\] \(Microsoft.+ -> Microsoft.+\)", RegexOptions.Compiled),
            new Regex(@"(?i)[SRU][01234] (portcfg|PktMon|rhproxy|Ramdisk|PNPMEM|storqosflt|storufs|ohci1394|omci|Parport|partmgr|streamip|Parvdm|SLIP|pci|pciide|pdc|SerCx2|stornvme|sdstor|RsFx0103|SerCx|SpbCx|spaceport|storahci|pcmcia|pcw|PEAUTH|perc2|perc2hib|Point32|PptpMiniport|Processor|Psched|Ptilink|PsxDrv|Ql10wnt|ql1240|QWAVEdrv|RasAcd|RasAgileVpn|Rasl2tp|RasPppoe|Raspti|RasSstp|rdbss|rdpbus|RDPCDD|RDPDR|RDPENCDD|RDPREFMP|RdpVideoMiniport|RDPWD|rdyboost|redbook|RFCOMM|RMCAST|ROOTMODEM|RpcXdr|rspndr|s3cap|sbp2port|scfilter|sdbus|sermouse|Serenum|Serial|sffdisk|sffp_mmc|sffp_sd|sfloppy|Sftfs|Sftplay|Sftredir|Sftvol|sisagp|SiSRaid2|Smb|Sparrow|spldr|splitter|sr|srv|srv2|srvnet|StillCam|storflt|storvsc|swenum|swmidi|Synth3dVsc|sysaudio); .*\\Windows\\System32\\drivers\\(portcfg|ohci1394|omci|Parport|partmgr|Parvdm|pdc|sdstor|SerCx|SpbCx|spaceport|storahci|pci|pciide|pcmcia|pcw|PEAUTH|perc2|perc2hib|Point32|Point32k|Ql10wnt|ql1240|raspptp|processr|PSched|pacer|PsxDrv|Ptilink|QWAVEdrv|RasAcd|AgileVpn|Rasl2tp|RasPppoe|Raspti|RasSstp|rdbss|rdpbus|RDPCDD|SLIP|RDPDR|RDPENCDD|RDPREFMP|RsFx0103|RdpVideoMiniport|RDPWD|rdyboost|redbook|RFCOMM|ROOTMODEM|RpcXdr|RMCAST|RootMdm|rspndr|vms3cap|sbp2port|scfilter|sdbus|sermouse|Serenum|Serial|sffdisk|sffp_mmc|sffp_sd|sfloppy|Sftfslh|Sftplaylh|Sftredirlh|Sftvollh|sisagp|SiSRaid2|Smb|StreamIP|Sparrow|SerCx2|spldr|stornvme|splitter|sr|srv|srv2|srvnet|serscan|mstorfl|storvsc|swenum|swmidi|sysaudio|Synth3dVsc|vmstorfl|storqosflt|storufs|PNPMEM|Ramdisk|rhproxy|PktMon).sys \[.+\] \(Microsoft.+ -> Microsoft.+\)", RegexOptions.Compiled),
                 new Regex(@"(?i)[SRU][01234] (umbus|WinQuic|UcmUcsiCx0101|UcmUcsiAcpiClient|wdnsfltr|WinNat|WUDFSensorLP|SensorsHIDClassDriver|wdiwifi|UcmCx0101|UcmUcsi|Ufx01000|UfxChipidea|ufxsynopsys|UrsChipidea|UrsCx01000|vhf|WindowsTrustedRT|WindowsTrustedRTProxy|Wof|xboxgip|xinputhid|Tcpip|TCPIP6|tcpipreg|TDPIPE|TDTCP|tdx|TermDD|UASPStor|WSTCODEC|UCX01000|UEFI|USBHUB3|USBXHCI|xusb21|VerifierExt|WFPLWFS|wpcfltr|WpdUpFltr|WUDFWpdFs|terminpt|TosIde|TPM|tssecsrv|TsUsbFlt|tsusbhub|TsUsbGD|tunnel|tunmp|udfs|uliagpkx|UmPass|Update|usb_rndisx|usbaudio\d*|usbccgp|USBCCID|usbcir|usbehci|usbhub|usbohci|usbprint|USBSTOR|usbscan|usbser|UsbserFilt|usbvideo|usbuhci|usbvideo|vdrvroot|vga|VgaSave|vhdmp|viaagp|ViaC7|VMBusHID|volmgr|volmgrx|VPCNetS2|vwifibus|vwifimp|vwififlt|VX3000|WacomPen|WANARP|Wanarpv6|Wdf01000|wdmaud|WfpLwf|WimFltr|WIMMount|WinUsb|WmiAcpi|WpdUsb|ws2ifsl|WSDPrintDevice|WSDScan|WudfPf|WUDFRd); .*\\Windows\\System32\\drivers\\(umbus|tcpip|tcpipreg|TDPIPE|TDTCP|tdx|TermDD|terminpt|TosIde|TPM|tssecsrv|tsusbhub|UASPStor|UCX01000|USBHUB3|USBXHCI|VerifierExt|WFPLWFS|wpcfltr|WpdUpFltr|WUDFWpdFs|TsUsbFlt|TsUsbGD|tunnel|tunmp|udfs|uliagpkx|UmPass|Update|usb8023x|usbaudio\d*|usbccgp|USBCCID|UEFI|usbcir|usbehci|usbhub|usbohci|WSTCODEC|usbprint|USBSTOR|usbscan|usbser|usbser_lowerfltj|usbvideo|usbuhci|usbvideo|vdrvroot|vgapnp|Vga|vhdmp|viaagp|ViaC7|VMBusHID|volmgr|VMNetSrv|volmgrx|vwifibus|vwifimp|vwififlt|VX3000|WacomPen|WANARP|Wdf01000|wdmaud|WfpLwf|WimFltr|WIMMount|WinUsb|WmiAcpi|WpdUsb|ws2ifsl|WSDPrint|WSDScan|WudfPf|xusb21|WUDFRd|UcmCx0101|UcmUcsi|Ufx01000|UfxChipidea|ufxsynopsys|UrsChipidea|UrsCx01000|vhf|WindowsTrustedRT|WindowsTrustedRTProxy|Wof|xboxgip|xinputhid|UcmCx|wdiwifi|WinNat|wdnsfltr|UcmUcsiAcpiClient|UcmUcsiCx|WinQuic).sys \[.+\] \(Microsoft.+ -> Microsoft.+\)", RegexOptions.Compiled),

            new Regex(@"(?i)[SRU][01234] (UdeCx|vmm|UcmTcpciCx\d+|UevAgentDriver|wcnfs|vmgid|volume|wcifs); .*\\Windows\\system32\\Drivers\\(vmm|UdeCx|UcmTcpciCx|UevAgentDriver|wcnfs|vmgid|volume|wcifs).sys \[.+\] \(Microsoft.+ -> Microsoft.+\)", RegexOptions.Compiled),

            new Regex(@"(?i)[SRU][01234] (CompositeBus|swenum|BasicRender|BasicDisplay); .*\\Windows\\system32\\DriverStore\\FileRepository\\.+?\\(CompositeBus|swenum|BasicDisplay|BasicRender).sys \[.+\] \(Microsoft.+ -> Microsoft.+\)", RegexOptions.Compiled),

            new Regex(@"(?i)[RSU][01234] (genericusbfn|UrsSynopsys|UEFI|UfxChipidea|umbus|UrsChipidea); .*\\Windows\\System32\\DriverStore\\FileRepository\\[^\\]+\\(genericusbfn|UrsSynopsys|UEFI|UfxChipidea|umbus|UrsChipidea).sys \[.+\] \(Microsoft.+ -> Microsoft.+\)", RegexOptions.Compiled)

    };
    }


    public bool IsWhitelisted(string input)
    {
        foreach (var regex in _whitelist)
        {
            if (regex.IsMatch(input))
            {
                return true;
            }
        }
        return false;
    }
}
