using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Wildlands_System_Scanner.Whitelist
{
    public class FirewallRulesWhitelist
    {
        public static readonly List<string> WhitelistFirewallRules = new List<string>
        {
            "SNMPTRAP-In-UDP",
            "SNMPTRAP-In-UDP-NoScope",
            "WiFiDirect-KM-Driver-In-TCP",
            "WiFiDirect-KM-Driver-Out-TCP",
            "WiFiDirect-KM-Driver-In-UDP",
            "WiFiDirect-KM-Driver-Out-UDP",
            "DeliveryOptimization-TCP-In",
            "DeliveryOptimization-UDP-In",
            "PNRPMNRS-PNRP-In-UDP",
            "PNRPMNRS-PNRP-Out-UDP",
            "PNRPMNRS-SSDPSrv-In-UDP",
            "PNRPMNRS-SSDPSrv-Out-UDP",
            "CDPSvc-In-UDP",
            "CDPSvc-Out-UDP",
            "CDPSvc-In-TCP",
            "CDPSvc-Out-TCP",
            "CDPSvc-WFD-In-TCP",
            "CDPSvc-WFD-Out-TCP",
            "CoreNet-ICMP6-DU-In",
            "CoreNet-ICMP6-PTB-In",
            "CoreNet-ICMP6-PTB-Out",
            "CoreNet-ICMP6-TE-In",
            "CoreNet-ICMP6-TE-Out",
            "CoreNet-ICMP6-PP-In",
            "CoreNet-ICMP6-PP-Out",
            "CoreNet-ICMP6-NDS-In",
            "CoreNet-ICMP6-NDS-Out",
            "CoreNet-ICMP6-NDA-In",
            "CoreNet-ICMP6-NDA-Out",
            "CoreNet-ICMP6-RA-In",
            "CoreNet-ICMP6-RA-Out",
            "CoreNet-ICMP6-RS-In",
            "CoreNet-ICMP6-RS-Out",
            "CoreNet-ICMP6-LQ-In",
            "CoreNet-ICMP6-LQ-Out",
            "CoreNet-ICMP6-LR-In",
            "CoreNet-ICMP6-LR-Out",
            "CoreNet-ICMP6-LR2-In",
            "CoreNet-ICMP6-LR2-Out",
            "CoreNet-ICMP6-LD-In",
            "CoreNet-ICMP6-LD-Out",
            "CoreNet-ICMP4-DUFRAG-In",
            "CoreNet-IGMP-In",
            "CoreNet-IGMP-Out",
            "CoreNet-DHCP-In",
            "CoreNet-DHCP-Out",
            "CoreNet-DHCPV6-In",
            "CoreNet-DHCPV6-Out",
            "CoreNet-Teredo-In",
            "CoreNet-Teredo-Out",
            "CoreNet-IPHTTPS-In",
            "CoreNet-IPHTTPS-Out",
            "CoreNet-IPv6-In",
            "CoreNet-IPv6-Out",
            "CoreNet-GP-NP-Out-TCP",
            "CoreNet-GP-Out-TCP",
            "CoreNet-DNS-Out-UDP",
            "CoreNet-GP-LSASS-Out-TCP",
            "CoreNet-Diag-ICMP4-EchoRequest-In",
            "CoreNet-Diag-ICMP4-EchoRequest-Out",
            "CoreNet-Diag-ICMP6-EchoRequest-In",
            "CoreNet-Diag-ICMP6-EchoRequest-Out",
            "CoreNet-Diag-ICMP4-EchoRequest-In-NoScope",
            "CoreNet-Diag-ICMP4-EchoRequest-Out-NoScope",
            "CoreNet-Diag-ICMP6-EchoRequest-In-NoScope",
            "CoreNet-Diag-ICMP6-EchoRequest-Out-NoScope",
            "PerfLogsAlerts-PLASrv-In-TCP",
            "PerfLogsAlerts-DCOM-In-TCP",
            "PerfLogsAlerts-PLASrv-In-TCP-NoScope",
            "PerfLogsAlerts-DCOM-In-TCP-NoScope",
            "RVM-VDS-In-TCP-NoScope",
            "RVM-VDSLDR-In-TCP-NoScope",
            "RVM-RPCSS-In-TCP-NoScope",
            "RVM-VDS-In-TCP",
            "RVM-VDSLDR-In-TCP",
            "RVM-RPCSS-In-TCP",
            "Microsoft-Windows-DeviceManagement-OmaDmClient-TCP-Out",
            "RemoteTask-In-TCP-NoScope",
            "RemoteTask-RPCSS-In-TCP-NoScope",
            "RemoteTask-In-TCP",
            "RemoteTask-RPCSS-In-TCP",
            "MsiScsi-In-TCP-NoScope",
            "MsiScsi-Out-TCP-NoScope",
            "MsiScsi-In-TCP",
            "MsiScsi-Out-TCP",
            "RemoteSvcAdmin-In-TCP-NoScope",
            "RemoteSvcAdmin-NP-In-TCP-NoScope",
            "RemoteSvcAdmin-RPCSS-In-TCP-NoScope",
            "RemoteSvcAdmin-In-TCP",
            "RemoteSvcAdmin-NP-In-TCP",
            "RemoteSvcAdmin-RPCSS-In-TCP",
            "Microsoft-Windows-DeviceManagement-deviceenroller-TCP-Out",
            "vm-monitoring-icmpv4",
            "vm-monitoring-icmpv6",
            "vm-monitoring-nb-session",
            "vm-monitoring-rpc",
            "vm-monitoring-dcom",
            "ProximityUxHost-Sharing-In-TCP-NoScope",
            "ProximityUxHost-Sharing-Out-TCP-NoScope",
            "NETDIS-UPnPHost-In-TCP-NoScope",
            "NETDIS-UPnPHost-Out-TCP-NoScope",
            "NETDIS-NB_Name-In-UDP-NoScope",
            "NETDIS-NB_Name-Out-UDP-NoScope",
            "NETDIS-NB_Datagram-In-UDP-NoScope",
            "NETDIS-NB_Datagram-Out-UDP-NoScope",
            "NETDIS-WSDEVNTS-In-TCP-NoScope",
            "NETDIS-WSDEVNTS-Out-TCP-NoScope",
            "NETDIS-WSDEVNT-In-TCP-NoScope",
            "NETDIS-WSDEVNT-Out-TCP-NoScope",
            "NETDIS-SSDPSrv-In-UDP-Active",
            "NETDIS-SSDPSrv-Out-UDP-Active",
            "NETDIS-UPnPHost-In-TCP-Active",
            "NETDIS-UPnPHost-Out-TCP-Active",
            "NETDIS-UPnP-Out-TCP-Active",
            "NETDIS-NB_Name-In-UDP-Active",
            "NETDIS-NB_Name-Out-UDP-Active",
            "NETDIS-NB_Datagram-In-UDP-Active",
            "NETDIS-NB_Datagram-Out-UDP-Active",
            "NETDIS-FDPHOST-In-UDP-Active",
            "NETDIS-DAS-In-UDP-Active",
            "NETDIS-FDPHOST-Out-UDP-Active",
            "NETDIS-LLMNR-In-UDP-Active",
            "NETDIS-LLMNR-Out-UDP-Active",
            "NETDIS-FDRESPUB-WSD-In-UDP-Active",
            "NETDIS-FDRESPUB-WSD-Out-UDP-Active",
            "NETDIS-WSDEVNTS-In-TCP-Active",
            "NETDIS-WSDEVNTS-Out-TCP-Active",
            "NETDIS-WSDEVNT-In-TCP-Active",
            "NETDIS-WSDEVNT-Out-TCP-Active",
            "NETDIS-SSDPSrv-In-UDP",
            "NETDIS-SSDPSrv-In-UDP-Teredo",
            "NETDIS-SSDPSrv-Out-UDP",
            "NETDIS-UPnP-Out-TCP",
            "NETDIS-UPnPHost-In-TCP",
            "NETDIS-UPnPHost-In-TCP-Teredo",
            "NETDIS-UPnPHost-Out-TCP",
            "NETDIS-NB_Name-In-UDP",
            "NETDIS-NB_Name-Out-UDP",
            "NETDIS-NB_Datagram-In-UDP",
            "NETDIS-NB_Datagram-Out-UDP",
            "NETDIS-FDPHOST-In-UDP",
            "NETDIS-DAS-In-UDP",
            "NETDIS-FDPHOST-Out-UDP",
            "NETDIS-LLMNR-In-UDP",
            "NETDIS-LLMNR-Out-UDP",
            "NETDIS-FDRESPUB-WSD-In-UDP",
            "NETDIS-FDRESPUB-WSD-Out-UDP",
            "NETDIS-WSDEVNTS-In-TCP",
            "NETDIS-WSDEVNTS-Out-TCP",
            "NETDIS-WSDEVNT-In-TCP",
            "NETDIS-WSDEVNT-Out-TCP",
            "EventForwarder-In-TCP",
            "EventForwarder-RPCSS-In-TCP",
            "RemoteFwAdmin-In-TCP-NoScope",
            "RemoteFwAdmin-RPCSS-In-TCP-NoScope",
            "RemoteFwAdmin-In-TCP",
            "RemoteFwAdmin-RPCSS-In-TCP",
            "MDNS-In-UDP-Private-Active",
            "MDNS-In-UDP-Domain-Active",
            "MDNS-In-UDP-Public-Active",
            "MDNS-Out-UDP-Private-Active",
            "MDNS-Out-UDP-Domain-Active",
            "MDNS-Out-UDP-Public-Active",
            "AllJoyn-Router-In-TCP",
            "AllJoyn-Router-Out-TCP",
            "AllJoyn-Router-In-UDP",
            "AllJoyn-Router-Out-UDP",
            "Microsoft-Windows-DeviceManagement-CertificateInstall-TCP-Out",
            "RRAS-GRE-In",
            "RRAS-GRE-Out",
            "RRAS-L2TP-In-UDP",
            "RRAS-L2TP-Out-UDP",
            "RRAS-PPTP-In-TCP",
            "RRAS-PPTP-Out-TCP",
            "Netlogon-NamedPipe-In",
            "Netlogon-TCP-RPC-In",
            "WFDPRINT-DAFWSD-In-Active",
            "WFDPRINT-DAFWSD-Out-Active",
            "WFDPRINT-SPOOL-In-Active",
            "WFDPRINT-SPOOL-Out-Active",
            "WFDPRINT-SCAN-In-Active",
            "WFDPRINT-SCAN-Out-Active",
            "TPMVSCMGR-RPCSS-In-TCP-NoScope",
            "TPMVSCMGR-Server-In-TCP-NoScope",
            "TPMVSCMGR-Server-Out-TCP-NoScope",
            "TPMVSCMGR-RPCSS-In-TCP",
            "TPMVSCMGR-Server-In-TCP",
            "TPMVSCMGR-Server-Out-TCP",
            "RemoteEventLogSvc-In-TCP-NoScope",
            "RemoteEventLogSvc-NP-In-TCP-NoScope",
            "RemoteEventLogSvc-RPCSS-In-TCP-NoScope",
            "RemoteEventLogSvc-In-TCP",
            "RemoteEventLogSvc-NP-In-TCP",
            "RemoteEventLogSvc-RPCSS-In-TCP",
            "WirelessDisplay-In-TCP",
            "WirelessDisplay-Out-TCP",
            "WirelessDisplay-Out-UDP",
            "WirelessDisplay-Infra-In-TCP",
            "Collab-P2PHost-In-TCP",
            "Collab-P2PHost-WSD-In-UDP",
            "Collab-P2PHost-WSD-Out-UDP",
            "Collab-PNRP-In-UDP",
            "Collab-PNRP-Out-UDP",
            "Collab-PNRP-SSDPSrv-In-UDP",
            "Collab-PNRP-SSDPSrv-Out-UDP",
            "Microsoft-Windows-Enrollment-WinRT-TCP-Out",
            "DIAL-Protocol-Server-In-TCP-NoScope",
            "DIAL-Protocol-Server-HTTPSTR-In-TCP-LocalSubnetScope",
            "WMI-RPCSS-In-TCP-NoScope",
            "WMI-WINMGMT-In-TCP-NoScope",
            "WMI-WINMGMT-Out-TCP-NoScope",
            "WMI-ASYNC-In-TCP-NoScope",
            "WMI-RPCSS-In-TCP",
            "WMI-WINMGMT-In-TCP",
            "WMI-WINMGMT-Out-TCP",
            "WMI-ASYNC-In-TCP",
            "WINRM-HTTP-In-TCP-NoScope",
            "WINRM-HTTP-In-TCP",
            "WINRM-HTTP-Compat-In-TCP-NoScope",
            "WINRM-HTTP-Compat-In-TCP",
            "Microsoft-Windows-Troubleshooting-HTTP-HTTPS-Out",
            "Wininit-Shutdown-In-Rule-TCP-RPC",
            "Wininit-Shutdown-In-Rule-TCP-RPC-EPMapper",
            "MSDTC-In-TCP-NoScope",
            "MSDTC-Out-TCP-NoScope",
            "MSDTC-KTMRM-In-TCP-NoScope",
            "MSDTC-RPCSS-In-TCP-NoScope",
            "MSDTC-In-TCP",
            "MSDTC-Out-TCP",
            "MSDTC-KTMRM-In-TCP",
            "MSDTC-RPCSS-In-TCP",
            "RemoteAssistance-In-TCP-EdgeScope",
            "RemoteAssistance-Out-TCP",
            "RemoteAssistance-PnrpSvc-UDP-In-EdgeScope",
            "RemoteAssistance-PnrpSvc-UDP-OUT",
            "RemoteAssistance-RAServer-In-TCP-NoScope-Active",
            "RemoteAssistance-RAServer-Out-TCP-NoScope-Active",
            "RemoteAssistance-DCOM-In-TCP-NoScope-Active",
            "RemoteAssistance-In-TCP-EdgeScope-Active",
            "RemoteAssistance-Out-TCP-Active",
            "RemoteAssistance-SSDPSrv-In-UDP-Active",
            "RemoteAssistance-SSDPSrv-Out-UDP-Active",
            "RemoteAssistance-SSDPSrv-In-TCP-Active",
            "RemoteAssistance-SSDPSrv-Out-TCP-Active",
            "RemoteAssistance-PnrpSvc-UDP-In-EdgeScope-Active",
            "RemoteAssistance-PnrpSvc-UDP-OUT-Active",
            "NVS-FrameServer-In-TCP-NoScope",
            "NVS-FrameServer-Out-TCP-NoScope",
            "NVS-FrameServer-In-UDP-NoScope",
            "FPS-NB_Session-In-TCP-NoScope",
            "FPS-NB_Session-Out-TCP-NoScope",
            "FPS-SMB-In-TCP-NoScope",
            "FPS-SMB-Out-TCP-NoScope",
            "FPS-NB_Name-In-UDP-NoScope",
            "FPS-NB_Name-Out-UDP-NoScope",
            "FPS-NB_Datagram-In-UDP-NoScope",
            "FPS-NB_Datagram-Out-UDP-NoScope",
            "FPS-SpoolSvc-In-TCP-NoScope",
            "FPS-RPCSS-In-TCP-NoScope",
            "FPS-ICMP4-ERQ-In-NoScope",
            "FPS-ICMP4-ERQ-Out-NoScope",
            "FPS-ICMP6-ERQ-In-NoScope",
            "FPS-ICMP6-ERQ-Out-NoScope",
            "FPS-NB_Session-In-TCP",
            "FPS-NB_Session-Out-TCP",
            "FPS-SMB-In-TCP",
            "FPS-SMB-Out-TCP",
            "FPS-NB_Name-In-UDP",
            "FPS-NB_Name-Out-UDP",
            "FPS-NB_Datagram-In-UDP",
            "FPS-NB_Datagram-Out-UDP",
            "FPS-SpoolSvc-In-TCP",
            "FPS-RPCSS-In-TCP",
            "FPS-ICMP4-ERQ-Out",
            "FPS-ICMP4-ERQ-In",
            "FPS-ICMP6-ERQ-In",
            "FPS-ICMP6-ERQ-Out",
            "FPS-LLMNR-In-UDP",
            "FPS-LLMNR-Out-UDP",
            "Microsoft-Windows-HomeGroup-ProvSvc-TCP3587-In",
            "Microsoft-Windows-HomeGroup-ProvSvc-TCP3587-Out",
            "Microsoft-Windows-HomeGroup-ProvSvc-UDP3540-In",
            "Microsoft-Windows-HomeGroup-ProvSvc-UDP3540-Out",
            "SSTP-IN-TCP",
            "Microsoft-Windows-Unified-Telemetry-Client",
            "Microsoft-Windows-WLANSvc-ASP-CP-In",
"Microsoft-Windows-WLANSvc-ASP-CP-Out",
"WMP-In-UDP-x86",
"WMP-Out-UDP-x86",
"WMP-Out-TCP-x86",
"WMP-In-UDP",
"WMP-Out-UDP",
"WMP-Out-TCP",
"WMPNSS-QWave-In-UDP-NoScope",
"WMPNSS-QWave-Out-UDP-NoScope",
"WMPNSS-QWave-In-TCP-NoScope",
"WMPNSS-QWave-Out-TCP-NoScope",
"WMPNSS-HTTPSTR-In-TCP-NoScope",
"WMPNSS-HTTPSTR-Out-TCP-NoScope",
"WMPNSS-WMP-In-UDP-NoScope",
"WMPNSS-WMP-Out-UDP-NoScope",
"WMPNSS-WMP-Out-TCP-NoScope",
"WMPNSS-In-UDP-NoScope",
"WMPNSS-Out-UDP-NoScope",
"WMPNSS-In-TCP-NoScope",
"WMPNSS-Out-TCP-NoScope",
"WMPNSS-QWave-In-UDP",
"WMPNSS-QWave-Out-UDP",
"WMPNSS-QWave-In-TCP",
"WMPNSS-QWave-Out-TCP",
"WMPNSS-SSDPSrv-In-UDP",
"WMPNSS-SSDPSrv-Out-UDP",
"WMPNSS-UPnPHost-In-TCP",
"WMPNSS-UPnPHost-Out-TCP",
"WMPNSS-HTTPSTR-In-TCP",
"WMPNSS-HTTPSTR-Out-TCP",
"WMPNSS-WMP-In-UDP",
"WMPNSS-WMP-Out-UDP",
"WMPNSS-WMP-Out-TCP",
"WMPNSS-In-UDP",
"WMPNSS-Out-UDP",
"WMPNSS-In-TCP",
"WMPNSS-Out-TCP",
"WMPNSS-UPnP-Out-TCP",
"WPDMTP-Out-TCP-NoScope",
"WPDMTP-Out-TCP",
"WPDMTP-SSDPSrv-In-UDP",
"WPDMTP-SSDPSrv-Out-UDP",
"WPDMTP-UPnPHost-In-TCP",
"WPDMTP-UPnPHost-Out-TCP",
"WPDMTP-UPnP-Out-TCP",
"MCX-SSDPSrv-In-UDP",
"MCX-SSDPSrv-Out-UDP",
"MCX-In-TCP",
"MCX-Out-TCP",
"MCX-QWave-In-UDP",
"MCX-QWave-Out-UDP",
"MCX-QWave-In-TCP",
"MCX-QWave-Out-TCP",
"MCX-HTTPSTR-In-TCP",
"MCX-TERMSRV-In-TCP",
"MCX-In-UDP",
"MCX-Out-UDP",
"MCX-MCX2SVC-Out-TCP",
"MCX-Prov-Out-TCP",
"MCX-PlayTo-In-TCP",
"MCX-PlayTo-Out-TCP",
"MCX-McrMgr-Out-TCP",
"MCX-PlayTo-Out-UDP",
"MCX-FDPHost-Out-TCP",
"PlayTo-HTTPSTR-In-TCP-NoScope",
"PlayTo-HTTPSTR-In-TCP-LocalSubnetScope",
"PlayTo-HTTPSTR-In-TCP-PlayToScope",
"PlayTo-In-UDP-NoScope",
"PlayTo-In-UDP-LocalSubnetScope",
"PlayTo-In-UDP-PlayToScope",
"PlayTo-Out-UDP-NoScope",
"PlayTo-Out-UDP-LocalSubnetScope",
"PlayTo-Out-UDP-PlayToScope",
"PlayTo-In-RTSP-NoScope",
"PlayTo-In-RTSP-LocalSubnetScope",
"PlayTo-In-RTSP-PlayToScope",
"PlayTo-SSDP-Discovery-PlayToScope",
"PlayTo-UPnP-Events-PlayToScope",
"PlayTo-QWave-In-UDP-PlayToScope",
"PlayTo-QWave-Out-UDP-PlayToScope",
"PlayTo-QWave-In-TCP-PlayToScope",
"PlayTo-QWave-Out-TCP-PlayToScope",
"{582C8BF1-622B-42FE-A726-6436686E6658}",
"{BAEA8501-6421-4EF7-8B03-43CAEA7D4B6D}",
"{9E4F1048-75E7-47FF-BC59-2B65554ADF94}",
"{5079A7C8-7E64-4D72-A3FA-9479FD21D9E9}",
"{38FA453E-C7A5-486F-AB3A-D7970F3EE997}",
"{A8B2B4EE-AFB8-4474-BF63-631137603033}",
"{A0B26224-8B36-426F-AE01-B5D7416AFBDE}",
"{C9FA3E5A-1A8B-48D1-A443-B07C9D8C99C4}",
"RemoteDesktop-UserMode-In-TCP",
"RemoteDesktop-UserMode-In-UDP",
"RemoteDesktop-Shadow-In-TCP",
"RemoteDesktop-In-TCP-WS",
"RemoteDesktop-In-TCP-WSS",
"SPPSVC-In-TCP",
"SPPSVC-In-TCP-NoScope",
"FPSSMBD-iWARP-In-TCP",
"CloudIdSvc-Allow-HTTPS-Out-TCP",
"Microsoft-Windows-PeerDist-HttpTrans-In",
"Microsoft-Windows-PeerDist-HttpTrans-Out",
"Microsoft-Windows-PeerDist-WSD-In",
"Microsoft-Windows-PeerDist-WSD-Out",
"Microsoft-Windows-PeerDist-HostedServer-In",
"Microsoft-Windows-PeerDist-HostedServer-Out",
"Microsoft-Windows-PeerDist-HostedClient-Out",
"VIRTCL-WMI-RPCSS-In-TCP-NoScope",
"VIRTCL-WMI-WINMGMT-In-TCP-NoScope",
"VIRTCL-WMI-WINMGMT-Out-TCP-NoScope",
"VIRTCL-WMI-ASYNC-In-TCP-NoScope",
"VIRT-WMI-RPCSS-In-TCP-NoScope",
"VIRT-WMI-WINMGMT-In-TCP-NoScope",
"VIRT-WMI-WINMGMT-Out-TCP-NoScope",
"VIRT-WMI-ASYNC-In-TCP-NoScope",
"VIRT-VMMS-RPC-EPMAP-In-NoScope",
"VIRT-VMMS-RPC-In-NoScope",
"VIRT-MIGL-In-TCP-NoScope",
"VIRT-REMOTEDESKTOP-In-TCP-NoScope",
"VIRT-HVRHTTPL-In-TCP-NoScope",
"VIRT-HVRHTTPSL-In-TCP-NoScope",
"HNS Container Networking - ICS DNS (TCP-In) - 1F124FF0-BC0A-4A21-AA5C-E604746AD4A4 - 0",
"HNS Container Networking - DNS (UDP-In) - 1F124FF0-BC0A-4A21-AA5C-E604746AD4A4 - 0",
"HNS Container Networking - ICS DNS (TCP-In) - 0F8E4216-038A-4D7D-830D-9232E04BC578 - 0",
"HNS Container Networking - DNS (UDP-In) - 0F8E4216-038A-4D7D-830D-9232E04BC578 - 0",
"HNS Container Networking - ICS DNS (TCP-In) - 3C9A5D45-8095-4738-9C0D-B44B918408BC - 0",
"HNS Container Networking - DNS (UDP-In) - 3C9A5D45-8095-4738-9C0D-B44B918408BC - 0",
"HNS Container Networking - ICS DNS (TCP-In) - 8BACB09A-4429-456E-B223-526B7D8F97AC - 0",
"HNS Container Networking - DNS (UDP-In) - 8BACB09A-4429-456E-B223-526B7D8F97AC - 0",
"HNS Container Networking - ICS DNS (TCP-In) - 68714369-E71A-44ED-ADF6-F4888B2E8047 - 0",
"HNS Container Networking - DNS (UDP-In) - 68714369-E71A-44ED-ADF6-F4888B2E8047 - 0",
"HNS Container Networking - ICS DNS (TCP-In) - EF34BAF0-689D-48E4-8F0B-56203FF6801F - 0",
"HNS Container Networking - DNS (UDP-In) - EF34BAF0-689D-48E4-8F0B-56203FF6801F - 0",
"{DE762F73-0E6D-4CDA-A23E-91D835B31B0D}",
"{C0D54513-12E4-43A3-A3BE-3CF94E2A1AF4}",
"HNS Container Networking - ICS DNS (TCP-In) - 2901C213-94C2-4E5A-807A-C55BDD47A334 - 0",
"HNS Container Networking - DNS (UDP-In) - 2901C213-94C2-4E5A-807A-C55BDD47A334 - 0",
"HNS Container Networking - ICS DNS (TCP-In) - FFC6DCC2-4FFF-4669-8452-DEB62709B648 - 0",
"HNS Container Networking - DNS (UDP-In) - FFC6DCC2-4FFF-4669-8452-DEB62709B648 - 0",
"HNS Container Networking - ICS DNS (TCP-In) - B07C67B2-A1DD-42F2-A631-BC25F81E7828 - 0",
"HNS Container Networking - DNS (UDP-In) - B07C67B2-A1DD-42F2-A631-BC25F81E7828 - 0",
"{999A9E82-7F12-4165-A45C-2B8500A997FC}",
"{B8607155-646F-4BD0-BB68-8601D7E33DEC}",
"{D2E2DA0A-B82C-489D-BF08-DFEAE283D634}",
"{ABA9850C-B44B-4071-92E4-B1FBB130F834}",
"{2AC8CDF7-BAA4-4613-B96A-86F982D175F0}",
"{A83F244C-AB32-4667-BB6F-D58E9F7D2ED5}",
"{9ABC01E1-6F12-4EF0-B7F8-DED180BB237A}",
"{D3C54927-0015-4EC1-AA2E-FA4357C931B5}",
"{3C88F0A1-7A4A-450E-8CFA-E393856CA895}",
"{0A5AE638-7C7D-4134-B366-19C00FA50441}",
"{0A524367-D2AE-4D59-9B5C-7321EA08F41F}",
"{4B7E409E-F2A5-4A28-AA97-8D726BC9CDBA}",
"{8C87BE7C-B69D-431B-A38B-FB7D3AEF26AA}",
"{B29E5A37-8721-46FD-A570-4A6C9698CDC8}",
"{87D52DAD-3730-4B79-A90E-EF87397A8C1C}",
"{269001C1-F8D1-4848-B6EC-C5B4352794D9}",
"{D9363A3F-8DD7-4503-B86A-04E1B5A22CC1}",
"{E2661082-599D-4026-8EF6-BB80336142B3}",
"{315E5CDF-EDFF-4804-B690-31BC5D9C4E9F}",
"{BCE7F30B-CEA1-43E7-BB7C-5FCF6AA25341}",
"{5F4088CC-A71B-449C-879A-38966B238F7A}",
"{AD5D0D73-AE7C-494B-A70D-2DF85248E241}",
"{84DB2639-812D-470D-B6EC-6F0B976DA78B}",
"{D2FC4B60-FE8B-46DB-9692-BAA2DF22A711}",
"{2F221B35-5FE2-43A0-A9ED-9FF681C74111}",
"{F2BE3304-BB85-4858-8D5D-5B7D50647B27}",
"HNS Container Networking - ICS DNS (TCP-In) - 95EF6B2F-1D03-4AE9-9309-6C45FCE71713 - 0",
"HNS Container Networking - DNS (UDP-In) - 95EF6B2F-1D03-4AE9-9309-6C45FCE71713 - 0",
"{07204C5C-EE0F-4634-8CF1-E18116BFE657}",
"HNS Container Networking - ICS DNS (TCP-In) - CF829E9D-6D0C-4541-B2C0-DFCA18CC5EE6 - 0",
"HNS Container Networking - DNS (UDP-In) - CF829E9D-6D0C-4541-B2C0-DFCA18CC5EE6 - 0",
"HNS Container Networking - ICS DNS (TCP-In) - 66D09094-78D8-4760-AECA-A69D22314253 - 0",
"HNS Container Networking - DNS (UDP-In) - 66D09094-78D8-4760-AECA-A69D22314253 - 0",
"{F130D4F1-F523-4109-8605-DB5168382946}",
"{7457C3EC-EDF7-4DFA-84DF-3F78B976572B}",
"{9322754D-6E3A-4926-B5F2-2CA3772C4C3F}",
"{988C0F90-03C9-4644-9611-ADC87B6ADB8B}",
"HNS Container Networking - ICS DNS (TCP-In) - A192702F-1931-4DF7-9939-1714772360CE - 0",
"HNS Container Networking - DNS (UDP-In) - A192702F-1931-4DF7-9939-1714772360CE - 0",
"HNS Container Networking - ICS DNS (TCP-In) - A0625639-4F0B-4ACC-93A2-596FC6430F62 - 0",
"HNS Container Networking - DNS (UDP-In) - A0625639-4F0B-4ACC-93A2-596FC6430F62 - 0",
"{9813C47B-C76B-4199-BB29-32E8F3AF47E7}",
"HNS Container Networking - ICS DNS (TCP-In) - 205DD919-B870-4F55-982E-6D34E0C6C399 - 0",
"HNS Container Networking - DNS (UDP-In) - 205DD919-B870-4F55-982E-6D34E0C6C399 - 0",
"HNS Container Networking - ICS DNS (TCP-In) - A221C42B-21A8-4318-AFFC-BA1A1410B64E - 0",
"HNS Container Networking - DNS (UDP-In) - A221C42B-21A8-4318-AFFC-BA1A1410B64E - 0",
"HNS Container Networking - ICS DNS (TCP-In) - 95D69053-1A70-4A49-BFFD-5FA88EC52A5F - 0",
"HNS Container Networking - DNS (UDP-In) - 95D69053-1A70-4A49-BFFD-5FA88EC52A5F - 0",
"HNS Container Networking - ICS DNS (TCP-In) - C35EE775-DE13-480C-97AB-3D87E5BDCD6A - 0",
"HNS Container Networking - DNS (UDP-In) - C35EE775-DE13-480C-97AB-3D87E5BDCD6A - 0",
"HNS Container Networking - ICS DNS (TCP-In) - 41C0D127-EB33-4C8E-BF7B-236FF6F97A80 - 0",
"HNS Container Networking - DNS (UDP-In) - 41C0D127-EB33-4C8E-BF7B-236FF6F97A80 - 0",
"HNS Container Networking - ICS DNS (TCP-In) - 856FF67F-0C7C-4B57-8B6E-7EF33CBD0374 - 0",
"HNS Container Networking - DNS (UDP-In) - 856FF67F-0C7C-4B57-8B6E-7EF33CBD0374 - 0",
"HNS Container Networking - ICS DNS (TCP-In) - A72B0819-A607-4C5F-AF0C-3C66DF6B70EA - 0",
"HNS Container Networking - DNS (UDP-In) - A72B0819-A607-4C5F-AF0C-3C66DF6B70EA - 0",
"{38D3DDF2-888E-4EAA-81CF-2EC45373028C}",
"{06B314D1-DD6B-46F1-AE20-73C1019D41B6}",
"Audiosrv-1",
"Audiosrv-2",
"AVEndpointBuilder-1",
"AVEndpointBuilder-2",
"AxInstSV-1",
"AxInstSV-2",
"AxInstSV-3",
"BFE-1",
"BFE-2",
"CDPSvc-1",
"CDPSvc-10",
"CDPSvc-2",
"CDPSvc-3",
"CDPSvc-4",
"CDPSvc-5",
"CDPSvc-6",
"CDPSvc-7",
"CDPSvc-8",
"CDPSvc-9",
"clr_optimization_v4.0.30319_32-1",
"clr_optimization_v4.0.30319_32-2",
"clr_optimization_v4.0.30319_64-1",
"clr_optimization_v4.0.30319_64-2",
"DeviceManagement-1",
"DeviceManagement-10",
"DeviceManagement-11",
"DeviceManagement-12",
"DeviceManagement-2",
"DeviceManagement-3",
"DeviceManagement-4",
"DeviceManagement-5",
"DeviceManagement-6",
"DeviceManagement-7",
"DeviceManagement-8",
"DeviceManagement-9",
"DHCP-1",
"DHCP-1-1",
"DHCP-2",
"DHCP-3",
"DHCP-4",
"DHCP-5",
"DisplayEnhancementService Deny All Inbound",
"DisplayEnhancementService Deny All Outbound",
"dot3svc-1",
"dot3svc-2",
"DPS-1",
"DPS-2",
"dsmsvc-1",
"Eventlog-1",
"Eventlog-2",
"Eventlog-3",
"fdphost-1",
"fdphost-2",
"fdphost-3",
"fdphost-4",
"fdphost-5",
"fdphost-6",
"fdphost-7",
"fhsvc-1",
"fhsvc-2",
"HidServ-1",
"HidServ-2",
"HomeGroup Allow In",
"HomeGroup Allow In (PRNP)",
"HomeGroup Allow Out",
"HomeGroup Allow Out (PRNP)",
"HomeGroup Block In",
"HomeGroup Block Out",
"HomeGroup Listener Block In",
"HomeGroup Listener Block Out",
"LMHosts-1",
"LMHosts-2",
"LMHosts-3",
"LMHosts-4",
"Microsoft-Windows-AllJoyn-Router-Allow-In-TCP",
"Microsoft-Windows-AllJoyn-Router-Allow-In-UDP",
"Microsoft-Windows-AllJoyn-Router-Allow-Out-TCP",
"Microsoft-Windows-AllJoyn-Router-Allow-Out-UDP",
"Microsoft-Windows-AllJoyn-Router-Block-In-AllElse",
"Microsoft-Windows-AllJoyn-Router-Block-Out-AllElse",
"MPSSVC-1",
"MPSSVC-2",
"Netman-1",
"Netman-2",
"P2P Grouping Allow In",
"P2P Grouping Allow Out",
"P2P Grouping Block In",
"P2P Grouping Block Out",
"P2P Ident Block In",
"P2P Ident Block Out",
"PcaSvc-1",
"PcaSvc-2",
"PerfHost-1",
"PerfHost-2",
"PNRP Allow In",
"PNRP Allow Out",
"PNRP Block In",
"PNRP Block Out",
"PnrpAuto Block In",
"PnrpAuto Block Out",
"PolicyAgent-1",
"PolicyAgent-2",
"PolicyAgent-3",
"PolicyAgent-4",
"PolicyAgent-5",
"SearchFilterHost-1",
"SearchFilterHost-2",
"SearchIndexer-1",
"SearchIndexer-2",
"SearchIndexer-3",
"SearchProtocolHost-1",
"SearchProtocolHost-2",
"SettingSyncHost",
"SNMPTRAP-1",
"SNMPTRAP-2",
"SNMPTRAP-3",
"SPPEXTCOMOBJ-1",
"SPPEXTCOMOBJ-2",
"SPPEXTCOMOBJ-3",
"SPPEXTCOMOBJ-4",
"Sysmain-1",
"Sysmain-2",
"TabletInputService-1",
"TabletInputService-2",
"TermServicve-Enable-LOM",
"Trkwks-1",
"Trkwks-2",
"UmRdpService-1",
"UmRdpService-2",
"VacSvc-1",
"VacSvc-2",
"VDS-1",
"VDS-2",
"vmicguestinterface-block-in",
"vmicguestinterface-block-out",
"vmicheartbeat-allow-in",
"vmicheartbeat-allow-out",
"vmicheartbeat-block-in",
"vmicheartbeat-block-out",
"vmickvpexchange-block-in",
"vmickvpexchange-block-out",
"vmicrdv-block-in",
"vmicrdv-block-out",
"vmicshutdown-block-in",
"vmicshutdown-block-out",
"vmictimesync-block-in",
"vmictimesync-block-out",
"vmicvmsession-block-in",
"vmicvmsession-block-out",
"vmicvss-block-in",
"vmicvss-block-out",
"W32Time-1",
"W32Time-2",
"wbengine-1",
"wbengine-2",
"wbengine-3",
"Wcmsvc-1",
"Wcmsvc-2",
"Wcmsvc-3",
"Wcmsvc-NTP Allow OUT",
"WdiSystemHost-1",
"WdiSystemHost-2",
"WerSvc-1",
"WerSvc-2",
"WindowsDefender-1",
"WindowsDefender-2",
"WindowsDefender-3",
"WinHttpAutoProxySvc-1",
"WinHttpAutoProxySvc-2",
"WinHttpAutoProxySvc-3",
"WLANSvc ASP CP In",
"WLANSvc ASP CP Out",
"Wlansvc-1",
"Wlansvc-2",
"wlpasvc-1",
"wlpasvc-2",
"wlpasvc-3",
"WSC Deny All Inbound",
"WSC Deny All Outbound",
"WwanSvc-1",
"WwanSvc-2",
"MDEServer-1",
"MDEServer-2",
"WMPNetworkSvc-1",
"WMPNetworkSvc-2",
"WPDBUSENUM-1",
"WPDBUSENUM-2",
"AssignedAccessManagerSvc-1",
"AssignedAccessManagerSvc-2",
"cloudidsvc-allow-HTTP",
"cloudidsvc-block-in",
"cloudidsvc-block-out",
"CscService-1",
"CscService-2",
"PeerDist Allow TCP In",
"PeerDist Allow TCP Out",
"PeerDist Allow WSD In",
"PeerDist Allow WSD In 2",
"PeerDist Allow WSD Out",
"PeerDist Allow WSD Out 2",
"PeerDist Block In",
"PeerDist Block Out",
"VMMSAllowDynOut-1",
"VMMSAllowDynOut-2",
"VMMSAllowEMPOut",
"VMMSAllowLDAPOut",
"VMMSAllowMigIn",
"VMMSAllowMigOut",
"VMMSBlockAllIn",
"VMMSBlockAllOut",
"clr_optimization_v2.0.50727_32-1",
"clr_optimization_v2.0.50727_32-2",
"clr_optimization_v2.0.50727_64-1",
"clr_optimization_v2.0.50727_64-2",
"Collab-P2PHost-Out-TCP",
"WMPNSS-RME-HTTP-In-TCP",
"NetPres-In-TCP-NoScope",
"NetPres-Out-TCP-NoScope",
"NetPres-WSDEVNT-In-TCP-NoScope",
"NetPres-WSDEVNT-Out-TCP-NoScope",
"NetPres-WSDEVNTS-In-TCP-NoScope",
"NetPres-WSDEVNTS-Out-TCP-NoScope",
"NetPres-WSD-In-UDP",
"NetPres-WSD-Out-UDP",
"NetPres-In-TCP",
"NetPres-Out-TCP",
"NetPres-WSDEVNT-In-TCP",
"NetPres-WSDEVNT-Out-TCP",
"NetPres-WSDEVNTS-In-TCP",
"NetPres-WSDEVNTS-Out-TCP",
"RemoteDesktop-In-TCP",
"{49543F63-165A-41EC-8159-9CB2F31DD429}",
"WudfSvc-1",
"WudfSvc-2",
"UI0Detect-1",
"UI0Detect-2",
"uxsms-1",
"uxsms-2",
"IPBusEnum-1",
"IPBusEnum-2",
"WindowsDefender-Out",
"WcsPlugInService-1",
"WcsPlugInService-2",
"WindowsDefender-In",
"WMPNSS-RME-HTTP-In-TCP",
"NetPres-In-TCP-NoScope",
"NetPres-Out-TCP-NoScope",
"NetPres-WSDEVNT-In-TCP-NoScope",
"NetPres-WSDEVNT-Out-TCP-NoScope",
"NetPres-WSDEVNTS-In-TCP-NoScope",
"NetPres-WSDEVNTS-Out-TCP-NoScope",
"NetPres-WSD-In-UDP",
"NetPres-WSD-Out-UDP",
"NetPres-In-TCP",
"NetPres-Out-TCP",
"NetPres-WSDEVNT-In-TCP",
"NetPres-WSDEVNT-Out-TCP",
"NetPres-WSDEVNTS-In-TCP",
"NetPres-WSDEVNTS-Out-TCP",
"{A52707B2-8094-48A9-91AF-9BFF16061575}",
"{9447D187-2E11-4D68-807B-DC163B19DF91}",
"{AA2BF3C8-6F10-4B6C-9288-7712647737D9}",
"{20EB76D7-7033-480B-9925-D13219255399}",
"{190ACDDC-0A25-4A54-988A-0A3DFD1A765F}",
"{5C97DA8E-6FEC-4278-99C3-A934E61CB648}",
"{FCABB44B-2732-45DC-98DA-47297C6C7101}",
"{3DF5D3B8-6C14-4736-BE51-4AD0FCCBC331}",
"{17899479-4A2E-4A73-89BD-08AAA6003581}",
"{7674E1C3-3DE6-4CF7-A662-C5B0ACF4FAFC}",
"{44815476-DA69-40E6-A84D-24BF69D39945}",
"{2167FFE5-E8AF-4DD4-97C6-BC19A1F49CDD}",
"{FCAE1D23-4BD7-4E0C-99F2-FCA1C9B7BE73}",
"{CFF51150-8F2A-412D-9030-03D1CCA979E0}",
"{3D29329B-5F2D-4664-86A4-E6257421E2D0}",
"{B0D62FD9-E852-4854-9EC5-E4D59BB9FC10}",
"{EFCB247C-CAF2-4A75-A7F3-27F305F851D7}",
"{C0D894D0-AC9E-48A5-BE32-2299598ED52A}",
"{EC8B2A17-F8C1-4817-8E13-E9184CE087A0}",
"{1D4BBC72-30AD-482B-AEF2-C8BD95D16D7E}",
"{26625913-8C71-41CD-9210-582014E72293}",
"{27F3BB98-CA79-497B-9C19-3466579B96AD}",
"{FE8D6AF6-1D0E-4DF7-A42A-5653716FFF33}",
"{4D654E50-C553-42DD-AC44-9E61FF97A52D}",
"{4C8C1DB0-D23C-45AB-9F70-6EA6426B9BF4}",
"{3865427B-828D-4B5F-A56E-A5D9B15AD6EB}",
"{C2434173-5379-4804-8372-D6D74F75474B}",
"WudfSvc-1",
"vmicheartbeat-allow-in-1",
"vmicheartbeat-allow-in-2",
"UI0Detect-2",
"UI0Detect-1",
"WcsPlugInService-1",
"WcsPlugInService-2",
"WudfSvc-2",
"WindowsDefender-4",
        };
    }
}
