using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Wildlands_System_Scanner.Whitelist
{
    public class InstalledProgramWhitelist
    {
        public static readonly HashSet<string> Whitelist = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
"Microsoft Azure Compute Emulator - v2.9.7",
"Microsoft Visual Studio 2010 Tools for Office Runtime",
"Microsoft 365 Apps for enterprise - en-us",
"Microsoft Visio - en-us",
"Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-arm",
"vs_Graphics_Singletonx64",
"Microsoft Azure Compute Emulator - v2.9.7",
"Intel(R) Management Engine Driver",
"Microsoft Visual C++ 2005 Redistributable",
"IIS Express Application Compatibility Database for x64",
".NET for Android Templates",
"Microsoft .NET AppHost Pack - 9.0.0",
"Microsoft.NETCore.App.Runtime.Mono.android-arm64",
"Microsoft.NETCore.App.Runtime.Mono.iossimulator-x64",
"Windows PC Health Check",
"Microsoft .NET Host - 9.0.0",
"Microsoft.Maui.Controls",
"Microsoft ODBC Driver 17 for SQL Server",
"DiagnosticsHub_CollectionService",
"Microsoft.iOS.Runtime.iossimulator-arm64.net9.0_18.1",
"Microsoft ASP.NET Core 6.0.36 Targeting Pack",
"Dynamic Application Loader Host Interface Service",
"Microsoft.Android.Sdk.Windows",
"Microsoft ASP.NET Core 9.0.0 Targeting Pack",
"Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-x64",
"Intel(R) Management Engine Components",
"Microsoft.NETCore.App.Runtime.Mono.android-arm",
"Microsoft.iOS.Sdk.net8.0_17.0",
"Microsoft.iOS.Windows.Sdk.net9.0_18.1",
"Microsoft Update Health Tools",
"Microsoft ASP.NET Core 6.0.36 Shared Framework",
"Microsoft.NET.Workload.Mono.Toolchain.net7.Manifest",
"icecap_collection_x64",
"Microsoft.NETCore.App.Runtime.Mono.maccatalyst-arm64",
"Microsoft .NET Host FX Resolver - 9.0.0",
"Microsoft.NETCore.App.Runtime.Mono.android-x64",
"Microsoft.NETCore.App.Runtime.Mono.android-arm",
"Microsoft.MacCatalyst.Sdk.net9.0_18.0",
"Crystal Reports Basic Runtime for Visual Studio 2008",
"Application Verifier x64 External Package",
"Universal CRT Tools x64",
"Microsoft.iOS.Templates",
"Microsoft.NET.Sdk.Aspire.Manifest-8.0.100",
"Microsoft.NETCore.App.Runtime.Mono.maccatalyst-arm64",
"Microsoft.NET.Sdk.Maui.Manifest-9.0.100",
"Intel(R) Management Engine Components",
"Microsoft Windows Desktop Targeting Pack - 6.0.36",
"vs_minshellx64msi",
"Microsoft Visual C++ 2012 x64 Additional Runtime - 11.0.61030",
"Microsoft Visual C++ 2022 X64 Minimum Runtime - 14.42.34433",
"Microsoft .NET Toolset 9.0.101",
"Microsoft Azure PowerShell - April 2018",
"Microsoft.MacCatalyst.Ref.net9.0_18.1",
"Microsoft.Maui.Controls.Build.Tasks",
"Workflow Manager Tools 1.0 for Visual Studio",
"Microsoft Command Line Utilities 15 for SQL Server",
"Microsoft.iOS.Sdk.net8.0_18.0",
"Microsoft.MacCatalyst.Sdk.net9.0_18.1",
".NET MAUI SDK",
"Microsoft.NETCore.App.Runtime.Mono.android-x64",
"Microsoft.NET.Sdk.macOS.Manifest-9.0.100",
"Microsoft .NET AppHost Pack - 8.0.11",
"Microsoft.NETCore.App.Runtime.Mono.maccatalyst-x64",
"Microsoft.Maui.Essentials",
"Microsoft System CLR Types for SQL Server 2019",
"Microsoft.NET.Workload.Mono.Toolchain.Current.Manifest",
"Microsoft.NET.Workload.Emscripten.Current.Manifest",
"Microsoft.NET.Sdk.tvOS.Manifest-9.0.100",
"Microsoft.NETCore.App.Runtime.Mono.maccatalyst-x64",
"Microsoft Windows Desktop Runtime - 6.0.36",
"Microsoft.iOS.Sdk.net9.0_18.1",
"Microsoft.NETCore.App.Runtime.Mono.ios-arm64",
"Microsoft.NETCore.App.Runtime.Mono.android-arm64",
"Windows PC Health Check",
"Microsoft.NET.Workload.Mono.Toolchain.net6.Manifest",
"Microsoft.Android.Runtime.35.android-arm",
"Microsoft.iOS.Runtime.ios-arm64.net9.0_18.1",
"Workflow Manager Client 1.0",
"Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-arm",
"Microsoft.NETCore.App.Runtime.Mono.android-x86",
"VS JIT Debugger",
"Microsoft .NET AppHost Pack - 6.0.36",
"Intel(R) LMS",
"Microsoft Visual Studio Installer",
"Windows App Certification Kit Native Components",
"Microsoft.NET.Sdk.iOS.Manifest-9.0.100",
"Microsoft.NET.Sdk.Android.Manifest-9.0.100",
"Microsoft.NET.Workload.Emscripten.net7.Manifest",
"Microsoft.NET.Workload.Mono.Toolchain.net8.Manifest",
"Microsoft .NET AppHost Pack - 8.0.11",
"Microsoft .NET SDK 9.0.101",
"Microsoft .NET AppHost Pack - 9.0.0",
"Microsoft Azure Libraries for .NET – v2.9",
"vs_minshellinteropx64msi",
"Windows SDK DirectX x64 Remote",
"Microsoft.iOS.Windows.Sdk.net8.0_17.0",
"Microsoft.NETCore.App.Runtime.Mono.iossimulator-arm64",
"Microsoft.NET.Workload.Emscripten.net6.Manifest",
"Microsoft.Maui.Resizetizer",
"Microsoft.NETCore.App.Runtime.Mono.iossimulator-x64",
".NET MAUI SDK",
"Microsoft Visual C++ 2008 Redistributable - x64 9.0.30729.17",
"Microsoft .NET AppHost Pack - 6.0.36",
"Microsoft Web Deploy 4.0",
"Microsoft.iOS.Runtime.iossimulator-x64.net9.0_18.1",
"Microsoft Windows Desktop Runtime - 9.0.0",
"Microsoft.Android.Ref.35",
"Microsoft.Maui.Controls.Xaml",
"Microsoft.AspNetCore.Components.WebView.Maui",
"Office 16 Click-to-Run Licensing Component",
"Office 16 Click-to-Run Extensibility Component",
"Office 16 Click-to-Run Localization Component",
"Microsoft Azure Authoring Tools - v2.9.7",
"Microsoft.iOS.Windows.Sdk.net9.0_18.0",
"Microsoft .NET AppHost Pack - 8.0.11",
"Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-x86",
"Microsoft.NETCore.App.Runtime.Mono.android-x86",
"Microsoft .NET Targeting Pack - 6.0.36",
"Microsoft.Android.Sdk.Windows",
"Intel(R) Chipset Device Software",
"Microsoft .NET Runtime - 9.0.0",
"Microsoft Windows Desktop Targeting Pack - 9.0.0",
"Microsoft.NET.Runtime.MonoAOTCompiler.Task",
"Microsoft .NET Runtime - 8.0.11",
"Microsoft.iOS.Sdk.net9.0_18.0",
"Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-x86",
"IIS 10.0 Express",
"Microsoft.NETCore.App.Runtime.Mono.ios-arm64",
"Microsoft .NET Standard Targeting Pack - 2.1.0",
"Microsoft ASP.NET Core 8.0.11 Shared Framework",
"Microsoft.Android.Runtime.35.android-arm64",
"Microsoft.Maui.Controls.Core",
".NET MAUI Templates",
"IIS Express Application Compatibility Database for x86",
"Microsoft.MacCatalyst.Templates",
"Microsoft.iOS.Windows.Sdk.net8.0_18.0",
".NET MAUI Templates",
"NVIDIA Graphics Driver 457.51",
"NVIDIA GeForce Experience 3.20.2.34",
"NVIDIA Optimus Update 38.0.4.0",
"NVIDIA PhysX System Software 9.19.0218",
"NVIDIA Update 38.0.4.0",
"NVIDIA SHIELD Streaming",
"NVIDIA Install Application",
"NVIDIA ABHub",
"NVIDIA Backend",
"NVIDIA Container",
"NVIDIA TelemetryApi helper for NvContainer",
"NVIDIA LocalSystem Container",
"NVIDIA Message Bus for NvContainer",
"NVIDIA NetworkService Container",
"NVAPI Monitor plugin for NvContainer",
"NVIDIA Session Container",
"NVIDIA User Container",
"NVIDIA NodeJS",
"NVIDIA Watchdog Plugin for NvContainer",
"NVIDIA Telemetry Client",
"NVIDIA Virtual Host Controller",
"Nvidia Share",
"NVIDIA ShadowPlay 3.20.2.34",
"NVIDIA SHIELD Wireless Controller Driver",
"NVIDIA Update Core",
"NVIDIA Virtual Audio 4.13.0.0",
"Intel(R) Management Engine Components",
"Microsoft .NET 9.0 Templates 9.0.101",
"Microsoft .NET 8.0 Templates 8.0.404",
"Microsoft.Maui.Graphics",
"Microsoft.iOS.Ref.net9.0_18.1",
"Microsoft Windows Desktop Runtime - 8.0.11",
"Microsoft .NET Targeting Pack - 8.0.11",
"Microsoft Windows Desktop Targeting Pack - 8.0.11",
"Microsoft ASP.NET Core 9.0.0 Shared Framework",
"Microsoft .NET Targeting Pack - 9.0.0",
"Microsoft.NET.Workload.Emscripten.net8.Manifest",
"Application Verifier x64 External Package",
"Microsoft .NET Runtime - 6.0.36",
"Microsoft Visual Studio 2010 Tools for Office Runtime",
"Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.net9.0_18.1",
"Microsoft .NET AppHost Pack - 6.0.36",
"Microsoft Visual C++ 2012 x64 Minimum Runtime - 11.0.61030",
"Microsoft .NET AppHost Pack - 6.0.36",
"Microsoft.Android.Runtime.35.android-x64",
"Intel(R) Icls",
"Microsoft Workflow Diagnostic Pack for x64",
"Microsoft.NET.Runtime.MonoTargets.Sdk",
"Update for x64-based Windows Systems",
"Microsoft Visual C++ 2022 X64 Debug Runtime - 14.42.34433",
"Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-x64",
"Microsoft .NET 6.0 Templates 6.0.428",
"Microsoft ASP.NET Core 8.0.11 Targeting Pack",
"Microsoft.NETCore.App.Runtime.Mono.iossimulator-arm64",
"Microsoft.Maui.Core",
"Microsoft.Maui.Controls.Compatibility",
"Microsoft Visual C++ 2022 X64 Additional Runtime - 14.42.34433",
"Microsoft.Maui.Graphics.Win2D.WinUI.Desktop",
"Microsoft.MacCatalyst.Runtime.maccatalyst-x64.net9.0_18.1",
"Microsoft.MacCatalyst.Sdk.net8.0_17.0",
"vs_devenx64vmsi",
"Microsoft SQL Server 2019 LocalDB",
"Microsoft.NET.Runtime.MonoTargets.Sdk",
"Microsoft .NET AppHost Pack - 9.0.0",
"Microsoft.MacCatalyst.Sdk.net8.0_18.0",
"Microsoft Workflow Debugger v1.0 for amd64",
"Microsoft ASP.NET Core Module V2 for IIS Express",
"Microsoft.NET.Sdk.MacCatalyst.Manifest-9.0.100",
"vs_communityx64msi",
"Microsoft.NET.Runtime.MonoAOTCompiler.Task",
"VS Script Debugging Common",
"Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-arm64",
"VS WCF Debugging",
"Microsoft.Android.Runtime.35.android-x86",
"IntelliTraceProfilerProxy",
"Microsoft ASP.NET Core Module for IIS Express",
"Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-arm64",
"Unity Hub 2.4.4",
"Visual Studio Community 2022",
"Microsoft Edge",
"Microsoft Edge WebView2 Runtime",
"Windows Mobile Extension SDK Contracts",
"vs_clickoncesigntoolmsi",
"vs_filehandler_x86",
"Windows SDK for Windows Store Managed Apps Libs",
"Universal CRT Redistributable",
"Microsoft .NET Host - 9.0.0",
"Windows 11 Installation Assistant",
"Microsoft .NET CoreRuntime SDK",
"Microsoft .NET Framework 4.7.2 Targeting Pack",
"vs_CoreEditorFonts",
"Microsoft .NET Framework Cumulative Intellisense Pack for Visual Studio",
"WPTx64",
"Universal CRT Redistributable",
"Microsoft GameInput",
"Microsoft Exchange Web Services Managed API 2.1",
"Windows SDK Desktop Libs x86",
"Microsoft ASP.NET Core 8.0.11 Shared Framework",
"Microsoft ASP.NET Core 8.0.11 Targeting Pack",
"Microsoft .NET Framework 4.6 Targeting Pack",
"Windows App Certification Kit x64",
"SDK ARM Additions",
"Windows SDK",
"Windows SDK Desktop Libs arm",
"Windows SDK Desktop Headers arm",
"Microsoft Visual C++ 2012 Redistributable",
"vs_devenvsharedmsi",
"Windows SDK for Windows Store Apps Tools",
"Microsoft .NET Targeting Pack - 6.0.36",
"Universal CRT Tools x86",
"MSI Development Tools",
"Microsoft Windows Desktop Runtime - 8.0.11",
"Windows SDK Desktop Headers x64",
"WinRT Intellisense UAP - Other Languages",
"Open XML SDK 2.5 for Microsoft Office",
"Microsoft Workflow Debugger v1.0 for x86",
"Windows SDK Redistributables",
"WinRT Intellisense IoT - en-us",
"sptools_Microsoft.VisualStudio.Vsto.Msi",
"Microsoft .NET CoreRuntime For CoreCon",
"vs_Graphics_Singletonx86",
"Microsoft Visual Studio Setup WMI Provider",
"Windows SDK for Windows Store Apps Metadata",
"WinRT Intellisense Desktop - Other Languages",
"Microsoft .NET Framework 4.7.1 Targeting Pack",
"Windows SDK Signing Tools",
"sptools_Microsoft.VisualStudio.OfficeDeveloperTools.Msi",
"icecap_collectionresources",
"Microsoft Visual C++ 2017 Redistributable",
"Kits Configuration Installer",
"Microsoft Visual C++ 2022 X86 Debug Runtime - 14.42.34433",
"Windows SDK for Windows Store Apps DirectX x86 Remote",
"WinRT Intellisense PPI - Other Languages",
"Windows SDK for Windows Store Apps Contracts",
"Microsoft ASP.NET Core 6.0.36 Shared Framework",
"Windows SDK for Windows Store Apps",
"Microsoft .NET Targeting Pack - 8.0.11",
"WinRT Intellisense IoT - Other Languages",
"Visual C++ Library CRT Desktop Appx Package",
"Visual C++ Library CRT Desktop Appx Package",
"Microsoft ASP.NET Diagnostic Pack for Visual Studio",
"Windows Software Development Kit - Windows 10.0.22621.3233",
"vs_FileTracker_Singleton",
"Microsoft NetStandard SDK",
"Microsoft Visual C++ 2017 Redistributable",
"Windows App Certification Kit x64",
"Windows SDK for Windows Store Apps Headers",
"Windows SDK Modern Non-Versioned Developer Tools",
"Windows SDK Facade Windows WinMD Versioned",
"Windows Desktop Extension SDK Contracts",
"Microsoft .NET Targeting Pack - 9.0.0",
"WinRT Intellisense Mobile - en-us",
"Microsoft TestPlatform SDK Local Feed",
"Microsoft Visual C++ 2015-2022 Redistributable",
"Windows SDK DirectX x86 Remote",
"Microsoft ASP.NET Core 9.0.0 Shared Framework",
"Microsoft Visual C++ 2005 Redistributable",
"Windows SDK Desktop Libs x64",
"vs_BlendMsi",
"Microsoft Visual C++ 2022 X86 Additional Runtime - 14.42.34433",
"Windows SDK Desktop Libs arm64",
"Microsoft .NET Runtime - 6.0.36",
"Windows IoT Extension SDK Contracts",
"Microsoft .NET Framework 4.7.1 Doc Redirected Targeting Pack",
"Windows Team Extension SDK",
"Microsoft .NET Framework 4.8 SDK",
"WinRT Intellisense UAP - en-us",
"Windows SDK ARM Desktop Tools",
"Microsoft Windows Desktop Targeting Pack - 6.0.36",
"Microsoft ASP.NET Web Tools Packages 17.0 - ENU",
"Microsoft Windows Desktop Runtime - 6.0.36",
"Microsoft .NET Runtime - 9.0.0",
"Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.17",
"Microsoft .NET Runtime - 8.0.11",
"Microsoft .NET Framework 4.6.2 Targeting Pack",
"Microsoft Windows Communication Foundation Diagnostic Pack for x86",
"Windows Mobile Extension SDK",
"Windows SDK Desktop Tools arm64",
"Microsoft .NET Framework 4.8 Targeting Pack",
"Windows SDK Desktop Headers arm64",
"WPT Redistributables",
"vs_clickoncebootstrappermsires",
"windows_toolscorepkg",
"Microsoft Visual C++ 2012 x86 Additional Runtime - 11.0.61030",
"vs_communitysharedmsi",
"vs_tipsmsi",
"vs_minshellsharedmsi",
"WinRT Intellisense Desktop - en-us",
"Microsoft .NET Framework 4.7.2 Targeting Pack",
"vs_clickoncebootstrappermsi",
"SDK ARM Redistributables",
"Intel(R) Chipset Device Software",
"vs_vswebprotocolselectormsi",
"Microsoft .NET Framework 4.8 Targeting Pack",
"Microsoft Visual C++ 2012 x86 Minimum Runtime - 11.0.61030",
"ClickOnce Bootstrapper Package for Microsoft .NET Framework",
"VS Immersive Activate Helper",
"Project64 version 2.3.2.202",
"Windows SDK Desktop Tools x64",
"Microsoft Visual C++ 2022 X86 Minimum Runtime - 14.42.34433",
"Visual C++ Library CRT Appx Resource Package",
"Microsoft .NET Host FX Resolver - 9.0.0",
"WinRT Intellisense PPI - en-us",
"Windows SDK Modern Versioned Developer Tools",
"Microsoft UniversalWindowsPlatform SDK",
"Windows App Certification Kit SupportedApiList x86",
"Microsoft .NET Framework 4.6.2 Targeting Pack",
"IntelliTraceProfilerProxy",
"WinAppDeploy",
"Microsoft Visual C++ 2012 Redistributable",
"Windows SDK Desktop Tools x86",
"Microsoft Windows Desktop Targeting Pack - 9.0.0",
"Windows SDK for Windows Store Apps Libs",
"Crystal Reports Basic Runtime for Visual Studio 2008",
"Windows IoT Extension SDK",
"Microsoft Visual Studio Setup Configuration",
"vcpp_crt.redist.clickonce",
"Universal General MIDI DLS Extension SDK",
"Universal CRT Headers Libraries and Sources",
"sptools_Microsoft.VisualStudio.Vsto.Msi.Resources",
"Visual C++ Library CRT Appx Package",
"Windows Desktop Extension SDK",
"vs_githubprotocolhandlermsi",
"WPTx64",
"vs_communitymsires",
"icecap_collection_neutral",
"Windows SDK EULA",
"vs_SQLClickOnceBootstrappermsi",
"Visual C++ Library CRT Appx Package",
"Microsoft Visual C++ 2015-2022 Redistributable",
"Microsoft ASP.NET Core 9.0.0 Targeting Pack",
"Microsoft Windows Desktop Runtime - 9.0.0",
"Universal CRT Extension SDK",
"Xamarin Remoted iOS Simulator",
"vs_minshellmsires",
"Microsoft .NET Native SDK",
"Entity Framework 6.2.0 Tools  for Visual Studio 2022",
"vs_filehandler_amd64",
"Windows SDK AddOn",
"vs_minshellinteropsharedmsi",
"Visual C++ Library CRT ARM64 Appx Package",
"sptools_Microsoft.VisualStudio.Vsto.Msi.x64",
"Windows SDK Desktop Headers x86",
"Microsoft Windows Desktop Targeting Pack - 8.0.11",
"icecap_collectionresourcesx64",
"Windows Team Extension SDK Contracts",
"Visual C++ Library CRT Desktop Appx Package",
"Microsoft ASP.NET Core 6.0.36 Targeting Pack",
"Visual Studio Community 2022",
"Microsoft Edge",
"Microsoft Edge WebView2 Runtime",
"Windows Mobile Extension SDK Contracts",
"vs_clickoncesigntoolmsi",
"vs_filehandler_x86",
"Windows SDK for Windows Store Managed Apps Libs",
"Universal CRT Redistributable",
"Microsoft .NET Host - 9.0.0",
"Windows 11 Installation Assistant",
"Microsoft .NET CoreRuntime SDK",
"Microsoft .NET Framework 4.7.2 Targeting Pack",
"vs_CoreEditorFonts",
"Microsoft .NET Framework Cumulative Intellisense Pack for Visual Studio",
"WPTx64",
"Universal CRT Redistributable",
"Microsoft GameInput",
"Microsoft Exchange Web Services Managed API 2.1",
"Windows SDK Desktop Libs x86",
"Microsoft ASP.NET Core 8.0.11 Shared Framework",
"Microsoft ASP.NET Core 8.0.11 Targeting Pack",
"Microsoft .NET Framework 4.6 Targeting Pack",
"Windows App Certification Kit x64",
"SDK ARM Additions",
"Windows SDK",
"Windows SDK Desktop Libs arm",
"Windows SDK Desktop Headers arm",
"Microsoft Visual C++ 2012 Redistributable",
"vs_devenvsharedmsi",
"Windows SDK for Windows Store Apps Tools",
"Microsoft .NET Targeting Pack - 6.0.36",
"Universal CRT Tools x86",
"MSI Development Tools",
"Microsoft Windows Desktop Runtime - 8.0.11",
"Windows SDK Desktop Headers x64",
"WinRT Intellisense UAP - Other Languages",
"Open XML SDK 2.5 for Microsoft Office",
"Microsoft Workflow Debugger v1.0 for x86",
"Windows SDK Redistributables",
"WinRT Intellisense IoT - en-us",
"sptools_Microsoft.VisualStudio.Vsto.Msi",
"Microsoft .NET CoreRuntime For CoreCon",
"vs_Graphics_Singletonx86",
"Microsoft Visual Studio Setup WMI Provider",
"Windows SDK for Windows Store Apps Metadata",
"WinRT Intellisense Desktop - Other Languages",
"Microsoft .NET Framework 4.7.1 Targeting Pack",
"Windows SDK Signing Tools",
"sptools_Microsoft.VisualStudio.OfficeDeveloperTools.Msi",
"icecap_collectionresources",
"Microsoft Visual C++ 2017 Redistributable",
"Kits Configuration Installer",
"Microsoft Visual C++ 2022 X86 Debug Runtime - 14.42.34433",
"Windows SDK for Windows Store Apps DirectX x86 Remote",
"WinRT Intellisense PPI - Other Languages",
"Windows SDK for Windows Store Apps Contracts",
"Microsoft ASP.NET Core 6.0.36 Shared Framework",
"Windows SDK for Windows Store Apps",
"Microsoft .NET Targeting Pack - 8.0.11",
"WinRT Intellisense IoT - Other Languages",
"Visual C++ Library CRT Desktop Appx Package",
"Visual C++ Library CRT Desktop Appx Package",
"Microsoft ASP.NET Diagnostic Pack for Visual Studio",
"Windows Software Development Kit - Windows 10.0.22621.3233",
"vs_FileTracker_Singleton",
"Microsoft NetStandard SDK",
"Microsoft Visual C++ 2017 Redistributable",
"Windows App Certification Kit x64",
"Windows SDK for Windows Store Apps Headers",
"Windows SDK Modern Non-Versioned Developer Tools",
"Windows SDK Facade Windows WinMD Versioned",
"Windows Desktop Extension SDK Contracts",
"Microsoft .NET Targeting Pack - 9.0.0",
"WinRT Intellisense Mobile - en-us",
"Microsoft TestPlatform SDK Local Feed",
"Microsoft Visual C++ 2015-2022 Redistributable",
"Windows SDK DirectX x86 Remote",
"Microsoft ASP.NET Core 9.0.0 Shared Framework",
"Microsoft Visual C++ 2005 Redistributable",
"Windows SDK Desktop Libs x64",
"vs_BlendMsi",
"Microsoft Visual C++ 2022 X86 Additional Runtime - 14.42.34433",
"Windows SDK Desktop Libs arm64",
"Microsoft .NET Runtime - 6.0.36",
"Windows IoT Extension SDK Contracts",
"Microsoft .NET Framework 4.7.1 Doc Redirected Targeting Pack",
"Windows Team Extension SDK",
"Microsoft .NET Framework 4.8 SDK",
"WinRT Intellisense UAP - en-us",
"Windows SDK ARM Desktop Tools",
"Microsoft Windows Desktop Targeting Pack - 6.0.36",
"Microsoft ASP.NET Web Tools Packages 17.0 - ENU",
"Microsoft Windows Desktop Runtime - 6.0.36",
"Microsoft .NET Runtime - 9.0.0",
"Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.17",
"Microsoft .NET Runtime - 8.0.11",
"Microsoft .NET Framework 4.6.2 Targeting Pack",
"Microsoft Windows Communication Foundation Diagnostic Pack for x86",
"Windows Mobile Extension SDK",
"Windows SDK Desktop Tools arm64",
"Microsoft .NET Framework 4.8 Targeting Pack",
"Windows SDK Desktop Headers arm64",
"WPT Redistributables",
"vs_clickoncebootstrappermsires",
"Adobe Acrobat XI Pro",
"windows_toolscorepkg",
"Microsoft Visual C++ 2012 x86 Additional Runtime - 11.0.61030",
"vs_communitysharedmsi",
"vs_tipsmsi",
"vs_minshellsharedmsi",
"WinRT Intellisense Desktop - en-us",
"Microsoft .NET Framework 4.7.2 Targeting Pack",
"vs_clickoncebootstrappermsi",
"SDK ARM Redistributables",
"Intel(R) Chipset Device Software",
"vs_vswebprotocolselectormsi",
"Microsoft .NET Framework 4.8 Targeting Pack",
"Microsoft Visual C++ 2012 x86 Minimum Runtime - 11.0.61030",
"ClickOnce Bootstrapper Package for Microsoft .NET Framework",
"VS Immersive Activate Helper",
"Project64 version 2.3.2.202",
"Windows SDK Desktop Tools x64",
"Microsoft Visual C++ 2022 X86 Minimum Runtime - 14.42.34433",
"Visual C++ Library CRT Appx Resource Package",
"Microsoft .NET Host FX Resolver - 9.0.0",
"WinRT Intellisense PPI - en-us",
"Windows SDK Modern Versioned Developer Tools",
"Microsoft UniversalWindowsPlatform SDK",
"Windows App Certification Kit SupportedApiList x86",
"Microsoft .NET Framework 4.6.2 Targeting Pack",
"IntelliTraceProfilerProxy",
"WinAppDeploy",
"Microsoft Visual C++ 2012 Redistributable",
"Windows SDK Desktop Tools x86",
"Microsoft Windows Desktop Targeting Pack - 9.0.0",
"Windows SDK for Windows Store Apps Libs",
"Crystal Reports Basic Runtime for Visual Studio 2008",
"Windows IoT Extension SDK",
"Microsoft Visual Studio Setup Configuration",
"vcpp_crt.redist.clickonce",
"Universal General MIDI DLS Extension SDK",
"Universal CRT Headers Libraries and Sources",
"sptools_Microsoft.VisualStudio.Vsto.Msi.Resources",
"Visual C++ Library CRT Appx Package",
"Windows Desktop Extension SDK",
"vs_githubprotocolhandlermsi",
"WPTx64",
"vs_communitymsires",
"icecap_collection_neutral",
"Windows SDK EULA",
"vs_SQLClickOnceBootstrappermsi",
"Visual C++ Library CRT Appx Package",
"Microsoft Visual C++ 2015-2022 Redistributable",
"Microsoft ASP.NET Core 9.0.0 Targeting Pack",
"Microsoft Windows Desktop Runtime - 9.0.0",
"Universal CRT Extension SDK",
"Xamarin Remoted iOS Simulator",
"vs_minshellmsires",
"Microsoft .NET Native SDK",
"Entity Framework 6.2.0 Tools  for Visual Studio 2022",
"vs_filehandler_amd64",
"Windows SDK AddOn",
"vs_minshellinteropsharedmsi",
"Visual C++ Library CRT ARM64 Appx Package",
"sptools_Microsoft.VisualStudio.Vsto.Msi.x64",
"Windows SDK Desktop Headers x86",
"Microsoft Windows Desktop Targeting Pack - 8.0.11",
"icecap_collectionresourcesx64",
"Windows Team Extension SDK Contracts",
"Visual C++ Library CRT Desktop Appx Package",
"Microsoft ASP.NET Core 6.0.36 Targeting Pack",
"Visual Studio Community 2022",
"Microsoft Edge",
"Microsoft Edge WebView2 Runtime",
"Windows Mobile Extension SDK Contracts",
"vs_clickoncesigntoolmsi",
"vs_filehandler_x86",
"Windows SDK for Windows Store Managed Apps Libs",
"Universal CRT Redistributable",
"Microsoft .NET Host - 9.0.0",
"Windows 11 Installation Assistant",
"Microsoft .NET CoreRuntime SDK",
"Microsoft .NET Framework 4.7.2 Targeting Pack",
"vs_CoreEditorFonts",
"Microsoft .NET Framework Cumulative Intellisense Pack for Visual Studio",
"WPTx64",
"Universal CRT Redistributable",
"Microsoft GameInput",
"Microsoft Exchange Web Services Managed API 2.1",
"Windows SDK Desktop Libs x86",
"Microsoft ASP.NET Core 8.0.11 Shared Framework",
"Microsoft ASP.NET Core 8.0.11 Targeting Pack",
"Microsoft .NET Framework 4.6 Targeting Pack",
"Windows App Certification Kit x64",
"SDK ARM Additions",
"Windows SDK",
"Windows SDK Desktop Libs arm",
"Windows SDK Desktop Headers arm",
"Microsoft Visual C++ 2012 Redistributable",
"vs_devenvsharedmsi",
"Windows SDK for Windows Store Apps Tools",
"Microsoft .NET Targeting Pack - 6.0.36",
"Universal CRT Tools x86",
"MSI Development Tools",
"Microsoft Windows Desktop Runtime - 8.0.11",
"Windows SDK Desktop Headers x64",
"WinRT Intellisense UAP - Other Languages",
"Open XML SDK 2.5 for Microsoft Office",
"Microsoft Workflow Debugger v1.0 for x86",
"Windows SDK Redistributables",
"WinRT Intellisense IoT - en-us",
"sptools_Microsoft.VisualStudio.Vsto.Msi",
"Microsoft .NET CoreRuntime For CoreCon",
"vs_Graphics_Singletonx86",
"Microsoft Visual Studio Setup WMI Provider",
"Windows SDK for Windows Store Apps Metadata",
"WinRT Intellisense Desktop - Other Languages",
"Microsoft .NET Framework 4.7.1 Targeting Pack",
"Windows SDK Signing Tools",
"sptools_Microsoft.VisualStudio.OfficeDeveloperTools.Msi",
"icecap_collectionresources",
"Microsoft Visual C++ 2017 Redistributable",
"Kits Configuration Installer",
"Microsoft Visual C++ 2022 X86 Debug Runtime - 14.42.34433",
"Windows SDK for Windows Store Apps DirectX x86 Remote",
"WinRT Intellisense PPI - Other Languages",
"Windows SDK for Windows Store Apps Contracts",
"Microsoft ASP.NET Core 6.0.36 Shared Framework",
"Windows SDK for Windows Store Apps",
"Microsoft .NET Targeting Pack - 8.0.11",
"WinRT Intellisense IoT - Other Languages",
"Visual C++ Library CRT Desktop Appx Package",
"Visual C++ Library CRT Desktop Appx Package",
"Microsoft ASP.NET Diagnostic Pack for Visual Studio",
"Windows Software Development Kit - Windows 10.0.22621.3233",
"vs_FileTracker_Singleton",
"Microsoft NetStandard SDK",
"Microsoft Visual C++ 2017 Redistributable",
"Windows App Certification Kit x64",
"Windows SDK for Windows Store Apps Headers",
"Windows SDK Modern Non-Versioned Developer Tools",
"Windows SDK Facade Windows WinMD Versioned",
"Windows Desktop Extension SDK Contracts",
"Microsoft .NET Targeting Pack - 9.0.0",
"WinRT Intellisense Mobile - en-us",
"Microsoft TestPlatform SDK Local Feed",
"Microsoft Visual C++ 2015-2022 Redistributable",
"Windows SDK DirectX x86 Remote",
"Microsoft ASP.NET Core 9.0.0 Shared Framework",
"Microsoft Visual C++ 2005 Redistributable",
"Windows SDK Desktop Libs x64",
"vs_BlendMsi",
"Microsoft Visual C++ 2022 X86 Additional Runtime - 14.42.34433",
"Windows SDK Desktop Libs arm64",
"Microsoft .NET Runtime - 6.0.36",
"Windows IoT Extension SDK Contracts",
"Microsoft .NET Framework 4.7.1 Doc Redirected Targeting Pack",
"Windows Team Extension SDK",
"Microsoft .NET Framework 4.8 SDK",
"WinRT Intellisense UAP - en-us",
"Windows SDK ARM Desktop Tools",
"Microsoft Windows Desktop Targeting Pack - 6.0.36",
"Microsoft ASP.NET Web Tools Packages 17.0 - ENU",
"Microsoft Windows Desktop Runtime - 6.0.36",
"Microsoft .NET Runtime - 9.0.0",
"Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.17",
"Microsoft .NET Runtime - 8.0.11",
"Microsoft .NET Framework 4.6.2 Targeting Pack",
"Microsoft Windows Communication Foundation Diagnostic Pack for x86",
"Windows Mobile Extension SDK",
"Windows SDK Desktop Tools arm64",
"Microsoft .NET Framework 4.8 Targeting Pack",
"Windows SDK Desktop Headers arm64",
"WPT Redistributables",
"vs_clickoncebootstrappermsires",
"windows_toolscorepkg",
"Microsoft Visual C++ 2012 x86 Additional Runtime - 11.0.61030",
"vs_communitysharedmsi",
"vs_tipsmsi",
"vs_minshellsharedmsi",
"WinRT Intellisense Desktop - en-us",
"Microsoft .NET Framework 4.7.2 Targeting Pack",
"vs_clickoncebootstrappermsi",
"SDK ARM Redistributables",
"Intel(R) Chipset Device Software",
"vs_vswebprotocolselectormsi",
"Microsoft .NET Framework 4.8 Targeting Pack",
"Microsoft Visual C++ 2012 x86 Minimum Runtime - 11.0.61030",
"ClickOnce Bootstrapper Package for Microsoft .NET Framework",
"VS Immersive Activate Helper",
"Windows SDK Desktop Tools x64",
"Microsoft Visual C++ 2022 X86 Minimum Runtime - 14.42.34433",
"Visual C++ Library CRT Appx Resource Package",
"Microsoft .NET Host FX Resolver - 9.0.0",
"WinRT Intellisense PPI - en-us",
"Windows SDK Modern Versioned Developer Tools",
"Microsoft UniversalWindowsPlatform SDK",
"Windows App Certification Kit SupportedApiList x86",
"Microsoft .NET Framework 4.6.2 Targeting Pack",
"IntelliTraceProfilerProxy",
"WinAppDeploy",
"Microsoft Visual C++ 2012 Redistributable",
"Windows SDK Desktop Tools x86",
"Microsoft Windows Desktop Targeting Pack - 9.0.0",
"Windows SDK for Windows Store Apps Libs",
"Crystal Reports Basic Runtime for Visual Studio 2008",
"Windows IoT Extension SDK",
"Microsoft Visual Studio Setup Configuration",
"vcpp_crt.redist.clickonce",
"Universal General MIDI DLS Extension SDK",
"Universal CRT Headers Libraries and Sources",
"sptools_Microsoft.VisualStudio.Vsto.Msi.Resources",
"Visual C++ Library CRT Appx Package",
"Windows Desktop Extension SDK",
"vs_githubprotocolhandlermsi",
"WPTx64",
"vs_communitymsires",
"icecap_collection_neutral",
"Windows SDK EULA",
"vs_SQLClickOnceBootstrappermsi",
"Visual C++ Library CRT Appx Package",
"Microsoft Visual C++ 2015-2022 Redistributable",
"Microsoft ASP.NET Core 9.0.0 Targeting Pack",
"Microsoft Windows Desktop Runtime - 9.0.0",
"Universal CRT Extension SDK",
"Xamarin Remoted iOS Simulator",
"vs_minshellmsires",
"Microsoft .NET Native SDK",
"Entity Framework 6.2.0 Tools  for Visual Studio 2022",
"vs_filehandler_amd64",
"Windows SDK AddOn",
"vs_minshellinteropsharedmsi",
"Visual C++ Library CRT ARM64 Appx Package",
"sptools_Microsoft.VisualStudio.Vsto.Msi.x64",
"Windows SDK Desktop Headers x86",
"Microsoft Windows Desktop Targeting Pack - 8.0.11",
"icecap_collectionresourcesx64",
"Windows Team Extension SDK Contracts",
"Visual C++ Library CRT Desktop Appx Package",
"Microsoft ASP.NET Core 6.0.36 Targeting Pack",
"Microsoft OneDrive",
"Microsoft OneDrive",
"Microsoft Visual C++ 2022 X64 Additional Runtime",
"Microsoft .NET Framework 4.7.2",
"Microsoft .NET Framework 4.7.2",
"Microsoft Visual C++ 2022 X64 Minimum Runtime - 14.36.32532",
"Microsoft Visual C++ 2022 X86 Minimum Runtime - 14.36.32532",
"Update for Microsoft .NET Framework 4.7.2 (KB4087364)",
"Microsoft Visual C++ 2022 X86 Additional Runtime - 14.36.32532",
"Microsoft Visual C++ 2022 X86 Minimum Runtime - 14.36.32532",
"Update for Microsoft .NET Framework 4.7.2 (KB4087364)",
"Microsoft Visual C++ 2022 X86 Additional Runtime - 14.36.32532",
"Microsoft Visual C++ 2022 X86 Minimum Runtime - 14.36.32532",
"Update for Microsoft .NET Framework 4.7.2 (KB4087364)",
"Microsoft Visual C++ 2022 X86 Additional Runtime - 14.36.32532",
"Microsoft DirectX End-User Runtime",
"Microsoft DirectX Managed Assemblies",
"Microsoft Visual C++ 2013 x64 Additional Runtime - 12.0.40664",
"Microsoft Visual C++ 2010  x64 Redistributable - 10.0.40219",
"Microsoft Visual C++ 2022 X64 Additional Runtime - 14.36.32420",
"Microsoft Visual C++ 2012 x64 Additional Runtime - 11.0.61135",
"Microsoft Visual C++ 2013 x64 Minimum Runtime - 12.0.40664",
"Microsoft Visual C++ 2008 Redistributable - x64 9.0.30729.7523",
"Microsoft Visual C++ 2022 X64 Minimum Runtime - 14.36.32420",
"Microsoft Visual C++ 2012 x64 Minimum Runtime - 11.0.61135",
"Microsoft Visual C++ 2022 X86 Minimum Runtime - 14.36.32420",
"Microsoft Visual C++ 2022 X86 Additional Runtime - 14.36.32420",
"Microsoft Visual C++ 2013 x86 Minimum Runtime - 12.0.40664",
"Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.7523",
"Microsoft Visual C++ 2012 x86 Additional Runtime - 11.0.61135",
"Microsoft Visual C++ 2012 x86 Minimum Runtime - 11.0.61135",
"Microsoft Visual Basic/C++ Runtime (x86)",
"Microsoft Visual C++ 2013 x86 Additional Runtime - 12.0.40664",
"Microsoft Visual C++ 2010  x86 Redistributable - 10.0.40219",
"Microsoft Visual C++ 2022 X86 Minimum Runtime - 14.36.32420",
"Microsoft Visual C++ 2022 X86 Additional Runtime - 14.36.32420",
"Microsoft Visual C++ 2013 x86 Minimum Runtime - 12.0.40664",
"Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.7523",
"Microsoft Visual C++ 2012 x86 Additional Runtime - 11.0.61135",
"Microsoft Visual C++ 2012 x86 Minimum Runtime - 11.0.61135",
"Microsoft Visual Basic/C++ Runtime (x86)",
"Microsoft Visual C++ 2013 x86 Additional Runtime - 12.0.40664",
"Microsoft Visual C++ 2010  x86 Redistributable - 10.0.40219",
"Microsoft Visual C++ 2022 X86 Minimum Runtime - 14.36.32420",
"Microsoft Visual C++ 2022 X86 Additional Runtime - 14.36.32420",
"Microsoft Visual C++ 2013 x86 Minimum Runtime - 12.0.40664",
"Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.7523",
"Microsoft Visual C++ 2012 x86 Additional Runtime - 11.0.61135",
"Microsoft Visual C++ 2012 x86 Minimum Runtime - 11.0.61135",
"Microsoft Visual Basic/C++ Runtime (x86)",
"Microsoft Visual C++ 2013 x86 Additional Runtime - 12.0.40664",
"Microsoft Visual C++ 2010  x86 Redistributable - 10.0.40219",
        };
    }
}
