using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Wildlands_System_Scanner.Whitelist
{
    public class ProcessWhitelist
    {
        public static readonly List<string> Whitelist = new List<string>
        {
@"%WinDir%\system32\winlogon.exe",
@"%WinDir%\system32\svchost.exe",
@"%programfiles%\Microsoft Office\root\Office16\EXCEL.EXE",
@"%WinDir%\SystemApps\Microsoft.Windows.Search_cw5n1h2txyewy\SearchApp.exe",
@"%WinDir%\System32\RuntimeBroker.exe",
@"%WinDir%\system32\conhost.exe",
@"%WinDir%\System32\CompPkgSrv.exe",
@"%WinDir%\system32\fontdrvhost.exe",
@"%programfiles%\WindowsApps\Microsoft.GamingApp_2412.1001.25.0_x64__8wekyb3d8bbwe\XboxPcTray.exe",
@"%programfiles%\Microsoft Visual Studio\2022\Community\Common7\ServiceHub\Hosts\ServiceHub.Host.AnyCPU\ServiceHub.Host.AnyCPU.exe",
@"%programfiles%\WindowsApps\Microsoft.549981C3F5F10_4.2308.1005.0_x64__8wekyb3d8bbwe\Cortana.exe",
@"%WinDir%\System32\oobe\UserOOBEBroker.exe",
@"%programfiles%\WindowsApps\Microsoft.ZuneVideo_10.24111.10061.0_x64__8wekyb3d8bbwe\Video.UI.exe",
@"%programfiles%\Microsoft Visual Studio\2022\Community\Common7\ServiceHub\Hosts\ServiceHub.Host.dotnet.x64\ServiceHub.IdentityHost.exe",
@"%WinDir%\system32\dwm.exe",
@"%WinDir%\system32\taskhostw.exe",
@"%WinDir%\system32\sihost.exe",
@"%programfiles%\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\VBCSCompiler.exe",
@"%WinDir%\system32\NOTEPAD.EXE",
@"%localappdata%\Microsoft\OneDrive\OneDrive.exe",
@"%WinDir%\System32\spoolsv.exe",
@"%WinDir%\System32\SystemSettingsBroker.exe",
@"%WinDir%\system32\DllHost.exe",
@"%programfiles%\Microsoft Visual Studio\2022\Community\Common7\ServiceHub\Hosts\ServiceHub.Host.dotnet.x64\ServiceHub.Host.dotnet.x64.exe",
@"%WinDir%\helppane.exe",
@"%WinDir%\SystemApps\ShellExperienceHost_cw5n1h2txyewy\ShellExperienceHost.exe",
@"%WinDir%\System32\DriverStore\FileRepository\nvmd.inf_amd64_1408eaf9a25ed64f\Display.NvContainer\NVDisplay.Container.exe",
@"%WinDir%\system32\fontdrvhost.exe",
@"%WinDir%\system32\vmcompute.exe",
@"%WinDir%\system32\SearchProtocolHost.exe",
@"%programfiles%\NVIDIA Corporation\NvContainer\nvcontainer.exe",
@"%programfiles%\Microsoft Visual Studio\2022\Community\Common7\ServiceHub\Hosts\ServiceHub.Host.dotnet.x64\ServiceHub.TestWindowStoreHost.exe",
@"%WinDir%\system32\rundll32.exe",
@"%WinDir%\system32\SearchIndexer.exe",
@"%programfiles%\Microsoft Office\Root\Office16\SDXHelper.exe",
@"%WinDir%\system32\ApplicationFrameHost.exe",
@"%WinDir%\SystemApps\MicrosoftWindows.Client.CBS_cw5n1h2txyewy\TextInputHost.exe",
@"%programfiles%\Microsoft Visual Studio\2022\Community\Common7\IDE\PerfWatson2.exe",
@"%programfiles%\Microsoft Visual Studio\2022\Community\Common7\ServiceHub\controller\Microsoft.ServiceHub.Controller.exe",
@"%programfiles%\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe",
@"%WinDir%\System32\mousocoreworker.exe",
@"%programfiles%\Microsoft Visual Studio\2022\Community\Common7\IDE\devenv.exe",
@"%WinDir%\system32\lsass.exe",
@"%WinDir%\System32\DriverStore\FileRepository\nvmd.inf_amd64_1408eaf9a25ed64f\Display.NvContainer\NVDisplay.Container.exe",
@"%WinDir%\SysWOW64\DllHost.exe",
@"%programfiles%\Microsoft Office\Root\Office16\SDXHelper.exe",
@"%WinDir%\system32\wbem\wmiprvse.exe",
@"%WinDir%\SystemApps\Microsoft.LockApp_cw5n1h2txyewy\LockApp.exe",
@"%programfiles%\Microsoft Visual Studio\2022\Community\Common7\ServiceHub\Hosts\ServiceHub.Host.dotnet.x64\ServiceHub.DataWarehouseHost.exe",
@"C:\Program Files (x86)\NVIDIA Corporation\NvNode\NVIDIA Web Helper.exe",
@"%programfiles%\Microsoft Visual Studio\2022\Community\Common7\ServiceHub\Hosts\ServiceHub.Host.netfx.x64\ServiceHub.IntellicodeModelService.exe",
@"%WinDir%\System32\WUDFHost.exe",
@"%WinDir%\system32\ctfmon.exe",
@"%WinDir%\System32\DriverStore\FileRepository\nvmd.inf_amd64_1408eaf9a25ed64f\Display.NvContainer\NVDisplay.Container.exe",
@"%programfiles%\Microsoft SQL Server\90\Shared\sqlwriter.exe",
@"C:\Program Files (x86)\NVIDIA Corporation\NvNode\NVIDIA Web Helper.exe",
@"%programfiles%\NVIDIA Corporation\NvContainer\nvcontainer.exe",
@"%WinDir%\system32\SearchFilterHost.exe",
@"%WinDir%\ImmersiveControlPanel\SystemSettings.exe",
@"%WinDir%\SystemApps\MicrosoftWindows.Client.CBS_cw5n1h2txyewy\TextInputHost.exe",
@"%programfiles%\Microsoft Visual Studio\2022\Community\Common7\ServiceHub\Hosts\ServiceHub.Host.dotnet.x64\ServiceHub.IndexingService.exe",
@"%WinDir%\system32\vmms.exe",
@"%WinDir%\system32\fontdrvhost.exe",
@"%programfiles%\Microsoft Visual Studio\2022\Community\Common7\ServiceHub\Hosts\ServiceHub.Host.dotnet.x64\ServiceHub.RoslynCodeAnalysisService.exe",
@"%WinDir%\System32\GameBarPresenceWriter.exe",
@"%localappdata%\Microsoft\OneDrive\24.244.1204.0003\FileCoAuth.exe",
@"%WinDir%\system32\AUDIODG.EXE",
@"%programfiles%\Microsoft Visual Studio\2022\Community\Common7\ServiceHub\Hosts\ServiceHub.Host.dotnet.x64\ServiceHub.VSDetouredHost.exe",
@"%programfiles%\WindowsApps\Microsoft.Copilot_1.24122.48.0_x64__8wekyb3d8bbwe\CopilotNative.exe",
@"%WinDir%\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\StartMenuExperienceHost.exe",
@"%programfiles%\Microsoft Visual Studio\2022\Community\Common7\ServiceHub\Hosts\ServiceHub.Host.dotnet.x64\ServiceHub.ThreadedWaitDialog.exe",
@"%localappdata%\Microsoft\OneDrive\OneDrive.exe",
@"%programfiles%\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\MSBuild.exe",
@"C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\DiagnosticsHub.Collection.Service\StandardCollector.Service.exe",
@"%programfiles%\Common Files\Microsoft Shared\ClickToRun\OfficeClickToRun.exe",
@"%WinDir%\System32\AggregatorHost.exe",
@"%WinDir%\splwow64.exe",
@"%WinDir%\system32\LogonUI.exe",
@"%programfiles%\WindowsApps\Microsoft.GamingApp_2412.1001.25.0_x64__8wekyb3d8bbwe\XboxPcAppFT.exe",
@"%WinDir%\System32\DriverStore\FileRepository\mewmiprov.inf_amd64_d51901c26227fb29\WMIRegistrationService.exe",
@"%programfiles%\NVIDIA Corporation\NvContainer\nvcontainer.exe",
@"C:\Program Files\WindowsApps\Microsoft.Copilot_1.24123.47.0_x64__8wekyb3d8bbwe\CopilotNative.exe",
@"C:\WINDOWS\Explorer.EXE",
@"C:\Users\Cherokee Police\AppData\Local\Microsoft\OneDrive\24.244.1204.0003\FileCoAuth.exe",
@"C:\WINDOWS\system32\msiexec.exe",
@"C:\Program Files\Microsoft Office\root\Office16\WINWORD.EXE",
@"C:\Users\Cherokee Police\AppData\Local\Microsoft\OneDrive\OneDrive.exe",
@"C:\WINDOWS\system32\compattelrunner.exe",
@"C:\Program Files\Microsoft Office\root\vfs\ProgramFilesCommonX64\Microsoft Shared\OFFICE16\AI\ai.exe",
@"C:\Program Files\Common Files\Microsoft Shared\ClickToRun\AppVShNotify.exe",
@"C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorsvw.exe",
@"C:\Windows\system32\csrss.exe",
@"C:\Windows\system32\lsm.exe",
@"C:\Windows\system32\services.exe",
@"C:\Windows\System32\msdtc.exe",
@"C:\Windows\system32\csrss.exe",
@"C:\Windows\system32\sppsvc.exe",
@"C:\Windows\system32\wininit.exe",
@"C:\Windows\system32\wbem\WmiApSrv.exe",
@"C:\Windows\system32\taskeng.exe",
@"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorsvw.exe",
@"C:\Windows\system32\vssvc.exe",
@"C:\Windows\system32\taskhost.exe",
@"C:\Windows\system32\taskhostex.exe",
@"C:\Program Files\Windows Media Player\wmpnetwk.exe",
@"C:\Windows\system32\dashost.exe",
@"C:\Windows\system32\taskhost.exe",
@"C:\Program Files\Windows Defender\MpCmdRun.exe",
@"C:\Windows\system32\msiexec.exe",
@"C:\Windows\system32\taskhost.exe",
@"C:\Windows\system32\wininit.exe",
@"C:\Users\WildlandsPC\AppData\Local\Microsoft\Windows\InetHelper\node.exe",
@"C:\Windows\Explorer.EXE",
        }
        .Select(ExpandEnvironmentVariables)
        .ToList(); // Normalize all paths
    


        public static string ExpandEnvironmentVariables(string path)
        {
            return Environment.ExpandEnvironmentVariables(path).ToLowerInvariant();
        }
    }


}
