using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Wildlands_System_Scanner.Whitelist
{
    public class ScheduledTaskWhitelist
    {
        public static readonly List<string> TaskWhitelist = new List<string>
        {
    @"\Microsoft\Windows\CertificateServicesClient\SystemTask",
    @"\Microsoft\Windows\CertificateServicesClient\UserTask",
    @"\Microsoft\Windows\CertificateServicesClient\UserTask-Roam",
    @"\Microsoft\Windows\Chkdsk\ProactiveScan",
    @"\Microsoft\Windows\Chkdsk\SyspartRepair",
    @"\Microsoft\Windows\Clip\ClipESU",
    @"\Microsoft\Windows\Clip\License Validation",
    @"\Microsoft\Windows\Clip\LicenseImdsIntegration",
    @"\Microsoft\Windows\CloudExperienceHost\CreateObjectTask",
    @"\Microsoft\Windows\CloudRestore\Backup",
    @"\Microsoft\Windows\ConsentUX\UnifiedConsent\UnifiedConsentSyncTask",
    @"\Microsoft\Windows\Customer Experience Improvement Program\Consolidator",
    @"\Microsoft\Windows\Customer Experience Improvement Program\UsbCeip",
    @"\Microsoft\Windows\Data Integrity Scan\Data Integrity Check And Scan",
    @"\Microsoft\Windows\Data Integrity Scan\Data Integrity Scan",
    @"\Microsoft\Windows\Data Integrity Scan\Data Integrity Scan for Crash Recovery",
    @"\Microsoft\Windows\Defrag\ScheduledDefrag",
    @"\Microsoft\Windows\Device Information\Device",
    @"\Microsoft\Windows\Device Information\Device User",
    @"\Microsoft\Windows\Device Setup\Metadata Refresh",
    @"\Microsoft\Windows\DeviceDirectoryClient\HandleCommand",
    @"\Microsoft\Windows\DeviceDirectoryClient\HandleWnsCommand",
    @"\Microsoft\Windows\DeviceDirectoryClient\IntegrityCheck",
    @"\Microsoft\Windows\DeviceDirectoryClient\LocateCommandUserSession",
    @"\Microsoft\Windows\DeviceDirectoryClient\RegisterDeviceAccountChange",
    @"\Microsoft\Windows\DeviceDirectoryClient\RegisterDeviceLocationRightsChange",
    @"\Microsoft\Windows\DeviceDirectoryClient\RegisterDevicePeriodic24",
    @"\Microsoft\Windows\DeviceDirectoryClient\RegisterDevicePolicyChange",
    @"\Microsoft\Windows\DeviceDirectoryClient\RegisterDeviceProtectionStateChanged",
    @"\Microsoft\Windows\DeviceDirectoryClient\RegisterDeviceSettingChange",
    @"\Microsoft\Windows\DeviceDirectoryClient\RegisterDeviceWnsFallback",
    @"\Microsoft\Windows\DeviceDirectoryClient\RegisterUserDevice",
    @"\Microsoft\Windows\Diagnosis\RecommendedTroubleshootingScanner",
    @"\Microsoft\Windows\Diagnosis\Scheduled",
    @"\Microsoft\Windows\DirectX\DirectXDatabaseUpdater",
    @"\Microsoft\Windows\DirectX\DXGIAdapterCache",
    @"\Microsoft\Windows\DiskCleanup\SilentCleanup",
    @"\Microsoft\Windows\DiskDiagnostic\Microsoft-Windows-DiskDiagnosticDataCollector",
    @"\Microsoft\Windows\DiskDiagnostic\Microsoft-Windows-DiskDiagnosticResolver",
    @"\Microsoft\Windows\DiskFootprint\Diagnostics",
    @"\Microsoft\Windows\DiskFootprint\StorageSense",
    @"\Microsoft\Windows\DUSM\dusmtask",
    @"\Microsoft\Windows\EDP\EDP App Launch Task",
    @"\Microsoft\Windows\EDP\EDP Auth Task",
    @"\Microsoft\Windows\EDP\EDP Inaccessible Credentials Task",
    @"\Microsoft\Windows\EDP\StorageCardEncryption Task",
    @"\Microsoft\Windows\EnterpriseMgmt\MDMMaintenenceTask",
    @"\Microsoft\Windows\ExploitGuard\ExploitGuard MDM policy Refresh",
    @"\Microsoft\Windows\Feedback\Siuf\DmClient",
    @"\Microsoft\Windows\Feedback\Siuf\DmClientOnScenarioDownload",
    @"\Microsoft\Windows\File Classification Infrastructure\Property Definition Sync",
    @"\Microsoft\Windows\FileHistory\File History (maintenance mode)",
    @"\Microsoft\Windows\Flighting\FeatureConfig\ReconcileFeatures",
    @"\Microsoft\Windows\Flighting\FeatureConfig\UsageDataFlushing",
    @"\Microsoft\Windows\Flighting\FeatureConfig\UsageDataReporting",
    @"\Microsoft\Windows\Flighting\OneSettings\RefreshCache",
    @"\Microsoft\Windows\HelloFace\FODCleanupTask",
    @"\Microsoft\Windows\Input\LocalUserSyncDataAvailable",
    @"\Microsoft\Windows\Input\MouseSyncDataAvailable",
    @"\Microsoft\Windows\Input\PenSyncDataAvailable",
    @"\Microsoft\Windows\Input\TouchpadSyncDataAvailable",
    @"\Microsoft\Windows\InstallService\ScanForUpdates",
    @"\Microsoft\Windows\InstallService\ScanForUpdatesAsUser",
    @"\Microsoft\Windows\InstallService\SmartRetry",
    @"\Microsoft\Windows\InstallService\WakeUpAndContinueUpdates",
    @"\Microsoft\Windows\InstallService\WakeUpAndScanForUpdates",
    @"\Microsoft\Windows\International\Synchronize Language Settings",
    @"\Microsoft\Windows\LanguageComponentsInstaller\Installation",
    @"\Microsoft\Windows\LanguageComponentsInstaller\ReconcileLanguageResources",
    @"\Microsoft\Windows\LanguageComponentsInstaller\Uninstallation",
    @"\Microsoft\Windows\License Manager\TempSignedLicenseExchange",
    @"\Microsoft\Windows\Location\Notifications",
    @"\Microsoft\Windows\Location\WindowsActionDialog",
    @"\Microsoft\Windows\Maintenance\WinSAT",
    @"\Microsoft\Windows\Management\Autopilot\DetectHardwareChange",
    @"\Microsoft\Windows\Management\Autopilot\RemediateHardwareChange",
    @"\Microsoft\Windows\Management\Provisioning\Cellular",
    @"\Microsoft\Windows\Management\Provisioning\Logon",
    @"\Microsoft\Windows\Management\Provisioning\Retry",
    @"\Microsoft\Windows\Management\Provisioning\RunOnReboot",
    @"\Microsoft\Windows\Maps\MapsToastTask",
    @"\Microsoft\Windows\Maps\MapsUpdateTask",
    @"\Microsoft\Windows\MemoryDiagnostic\ProcessMemoryDiagnosticEvents",
    @"\Microsoft\Windows\MemoryDiagnostic\RunFullMemoryDiagnostic",
    @"\Microsoft\Windows\Mobile Broadband Accounts\MNO Metadata Parser",
    @"\Microsoft\Windows\MUI\LPRemove",
    @"\Microsoft\Windows\Multimedia\SystemSoundsService",
    @"\Microsoft\Windows\NetTrace\GatherNetworkInfo",
    @"\Microsoft\Windows\NlaSvc\WiFiTask",
    @"\Microsoft\Windows\Offline Files\Background Synchronization",
    @"\Microsoft\Windows\Offline Files\Logon Synchronization",
    @"\Microsoft\Windows\PI\Secure-Boot-Update",
    @"\Microsoft\Windows\PI\SecureBootEncodeUEFI",
    @"\Microsoft\Windows\PI\Sqm-Tasks",
    @"\Microsoft\Windows\Plug and Play\Device Install Group Policy",
    @"\Microsoft\Windows\Plug and Play\Device Install Reboot Required",
    @"\Microsoft\Windows\Plug and Play\Sysprep Generalize Drivers",
    @"\Microsoft\Windows\Power Efficiency Diagnostics\AnalyzeSystem",
    @"\Microsoft\Windows\Printing\EduPrintProv",
    @"\Microsoft\Windows\Printing\PrinterCleanupTask",
    @"\Microsoft\Windows\PushToInstall\LoginCheck",
    @"\Microsoft\Windows\PushToInstall\Registration",
    @"\Microsoft\Windows\Ras\MobilityManager",
    @"\Microsoft\Windows\RecoveryEnvironment\VerifyWinRE",
    @"\Microsoft\Windows\Registry\RegIdleBackup",
    @"\Microsoft\Windows\RemoteAssistance\RemoteAssistanceTask",
    @"\Microsoft\Windows\Servicing\StartComponentCleanup",
    @"\Microsoft\Windows\SettingSync\BackgroundUploadTask",
    @"\Microsoft\Windows\SettingSync\NetworkStateChangeTask",
    @"\Microsoft\Windows\SharedPC\Account Cleanup",
    @"\Microsoft\Windows\Shell\CreateObjectTask",
    @"\Microsoft\Windows\Shell\FamilySafetyMonitor",
    @"\Microsoft\Windows\Shell\FamilySafetyRefreshTask",
    @"\Microsoft\Windows\Shell\IndexerAutomaticMaintenance",
    @"\Microsoft\Windows\Shell\ThemesSyncedImageDownload",
    @"\Microsoft\Windows\Shell\UpdateUserPictureTask",
    @"\Microsoft\Windows\SoftwareProtectionPlatform\SvcRestartTask",
    @"\Microsoft\Windows\SoftwareProtectionPlatform\SvcRestartTaskLogon",
    @"\Microsoft\Windows\SoftwareProtectionPlatform\SvcRestartTaskNetwork",
    @"\Microsoft\Windows\SpacePort\SpaceAgentTask",
    @"\Microsoft\Windows\SpacePort\SpaceManagerTask",
    @"\Microsoft\Windows\Speech\HeadsetButtonPress",
    @"\Microsoft\Windows\Speech\SpeechModelDownloadTask",
    @"\Microsoft\Windows\StateRepository\MaintenanceTasks",
    @"\Microsoft\Windows\Storage Tiers Management\Storage Tiers Management Initialization",
    @"\Microsoft\Windows\Storage Tiers Management\Storage Tiers Optimization",
    @"\Microsoft\Windows\Subscription\EnableLicenseAcquisition",
    @"\Microsoft\Windows\Subscription\LicenseAcquisition",
    @"\Microsoft\Windows\Sysmain\HybridDriveCachePrepopulate",
    @"\Microsoft\Windows\Sysmain\HybridDriveCacheRebalance",
    @"\Microsoft\Windows\Sysmain\ResPriStaticDbSync",
    @"\Microsoft\Windows\Sysmain\WsSwapAssessmentTask",
    @"\Microsoft\Windows\SystemRestore\SR",
    @"\Microsoft\Windows\Task Manager\Interactive",
    @"\Microsoft\Windows\TextServicesFramework\MsCtfMonitor",
    @"\Microsoft\Windows\Time Synchronization\ForceSynchronizeTime",
    @"\Microsoft\Windows\Time Synchronization\SynchronizeTime",
    @"\Microsoft\Windows\Time Zone\SynchronizeTimeZone",
    @"\Microsoft\Windows\TPM\Tpm-HASCertRetr",
    @"\Microsoft\Windows\TPM\Tpm-Maintenance",
    @"\Microsoft\Windows\UNP\RunUpdateNotificationMgr",
    @"\Microsoft\Windows\UpdateOrchestrator\Backup Scan",
    @"\Microsoft\Windows\UpdateOrchestrator\Maintenance Install",
    @"\Microsoft\Windows\UpdateOrchestrator\MusUx_UpdateInterval",
    @"\Microsoft\Windows\UpdateOrchestrator\Reboot_AC",
    @"\Microsoft\Windows\UpdateOrchestrator\Reboot_Battery",
    @"\Microsoft\Windows\UpdateOrchestrator\Report policies",
    @"\Microsoft\Windows\UpdateOrchestrator\Schedule Maintenance Work",
    @"\Microsoft\Windows\UpdateOrchestrator\Schedule Scan",
    @"\Microsoft\Windows\UpdateOrchestrator\Schedule Scan Static Task",
    @"\Microsoft\Windows\UpdateOrchestrator\Schedule Wake To Work",
    @"\Microsoft\Windows\UpdateOrchestrator\Schedule Work",
    @"\Microsoft\Windows\UpdateOrchestrator\Universal Orchestrator Start",
    @"\Microsoft\Windows\UpdateOrchestrator\UpdateModelTask",
    @"\Microsoft\Windows\UpdateOrchestrator\USO_UxBroker",
    @"\Microsoft\Windows\UPnP\UPnPHostConfig",
    @"\Microsoft\Windows\USB\Usb-Notifications",
    @"\Microsoft\Windows\User Profile Service\HiveUploadTask",
    @"\Microsoft\Windows\WaaSMedic\PerformRemediation",
    @"\Microsoft\Windows\WCM\WiFiTask",
    @"\Microsoft\Windows\WDI\ResolutionHost",
    @"\Microsoft\Windows\Windows Error Reporting\QueueReporting",
    @"\Microsoft\Windows\Windows Filtering Platform\BfeOnServiceStartTypeChange",
    @"\Microsoft\Windows\Windows Media Sharing\UpdateLibrary",
    @"\Microsoft\Windows\WindowsColorSystem\Calibration Loader",
    @"\Microsoft\Windows\WindowsUpdate\Refresh Group Policy Cache",
    @"\Microsoft\Windows\WindowsUpdate\Scheduled Start",
    @"\Microsoft\Windows\WindowsUpdate\sihpostreboot",
    @"\Microsoft\Windows\WindowsUpdate\RUXIM\PLUGScheduler",
    @"\Microsoft\Windows\Wininet\CacheTask",
    @"\Microsoft\Windows\WlanSvc\CDSSync",
    @"\Microsoft\Windows\WOF\WIM-Hash-Management",
    @"\Microsoft\Windows\WOF\WIM-Hash-Validation",
    @"\Microsoft\Windows\Work Folders\Work Folders Logon Synchronization",
    @"\Microsoft\Windows\Work Folders\Work Folders Maintenance Work",
    @"\Microsoft\Windows\Workplace Join\Automatic-Device-Join",
    @"\Microsoft\Windows\Workplace Join\Device-Sync",
    @"\Microsoft\Windows\Workplace Join\Recovery-Check",
    @"\Microsoft\Windows\WwanSvc\NotificationTask",
    @"\Microsoft\Windows\WwanSvc\OobeDiscovery",
    @"\Microsoft\XblGameSave\XblGameSaveTask",
     @"\Intel PTT EK Recertification",
    @"\MicrosoftEdgeUpdateTaskMachineCore",
    @"\MicrosoftEdgeUpdateTaskMachineUA",
    @"\NvBatteryBoostCheckOnLogon_{B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}",
    @"\NvDriverUpdateCheckDaily_{B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}",
    @"\NVIDIA GeForce Experience SelfUpdate_{B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}",
    @"\NvNodeLauncher_{B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}",
    @"\NvProfileUpdaterDaily_{B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}",
    @"\NvProfileUpdaterOnLogon_{B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}",
    @"\NvTmRep_CrashReport1_{B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}",
    @"\NvTmRep_CrashReport2_{B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}",
    @"\NvTmRep_CrashReport3_{B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}",
    @"\NvTmRep_CrashReport4_{B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}",
    @"\OneDrive Reporting Task-S-1-5-21-1092161277-454068885-3468675754-1002",
    @"\OneDrive Reporting Task-S-1-5-21-1092161277-454068885-3468675754-1003",
    @"\OneDrive Standalone Update Task-S-1-5-21-1092161277-454068885-3468675754-1002",
    @"\OneDrive Standalone Update Task-S-1-5-21-1092161277-454068885-3468675754-1003",
    @"\OneDrive Standalone Update Task-S-1-5-21-1092161277-454068885-3468675754-500",
    @"\Agent Activation Runtime\S-1-5-21-1092161277-454068885-3468675754-1002",
    @"\Microsoft\Office\Office Automatic Updates 2.0",
    @"\Microsoft\Office\Office ClickToRun Service Monitor",
    @"\Microsoft\Office\Office Feature Updates",
    @"\Microsoft\Office\Office Feature Updates Logon",
    @"\Microsoft\Office\Office Performance Monitor",
    @"\Microsoft\VisualStudio\Updates\BackgroundDownload",
    @"\Microsoft\Windows\.NET Framework\.NET Framework NGEN v4.0.30319",
    @"\Microsoft\Windows\.NET Framework\.NET Framework NGEN v4.0.30319 64",
    @"\Microsoft\Windows\.NET Framework\.NET Framework NGEN v4.0.30319 64 Critical",
    @"\Microsoft\Windows\.NET Framework\.NET Framework NGEN v4.0.30319 Critical",
    @"\Microsoft\Windows\Active Directory Rights Management Services Client\AD RMS Rights Policy Template Management (Automated)",
    @"\Microsoft\Windows\Active Directory Rights Management Services Client\AD RMS Rights Policy Template Management (Manual)",
    @"\Microsoft\Windows\AppID\EDP Policy Manager",
    @"\Microsoft\Windows\AppID\PolicyConverter",
    @"\Microsoft\Windows\AppID\VerifiedPublisherCertStoreCheck",
    @"\Microsoft\Windows\Application Experience\MareBackup",
    @"\Microsoft\Windows\Application Experience\Microsoft Compatibility Appraiser",
    @"\Microsoft\Windows\Application Experience\PcaPatchDbTask",
    @"\Microsoft\Windows\Application Experience\PcaWallpaperAppDetect",
    @"\Microsoft\Windows\Application Experience\ProgramDataUpdater",
    @"\Microsoft\Windows\Application Experience\StartupAppTask",
    @"\Microsoft\Windows\ApplicationData\appuriverifierdaily",
    @"\Microsoft\Windows\ApplicationData\appuriverifierinstall",
    @"\Microsoft\Windows\ApplicationData\CleanupTemporaryState",
    @"\Microsoft\Windows\ApplicationData\DsSvcCleanup",
    @"\Microsoft\Windows\AppListBackup\Backup",
    @"\Microsoft\Windows\AppListBackup\BackupNonMaintenance",
    @"\Microsoft\Windows\AppxDeploymentClient\Pre-staged app cleanup",
    @"\Microsoft\Windows\AppxDeploymentClient\UCPD velocity",
    @"\Microsoft\Windows\Autochk\Proxy",
    @"\Microsoft\Windows\BitLocker\BitLocker Encrypt All Drives",
    @"\Microsoft\Windows\BitLocker\BitLocker MDM policy Refresh",
    @"\Microsoft\Windows\Bluetooth\UninstallDeviceTask",
    @"\Microsoft\Windows\BrokerInfrastructure\BgTaskRegistrationMaintenanceTask",
    @"\Microsoft\Windows\CertificateServicesClient\AikCertEnrollTask",
    @"\Microsoft\Windows\CertificateServicesClient\CryptoPolicyTask",
    @"\Microsoft\Windows\CertificateServicesClient\KeyPreGenTask",
    @"\Microsoft\VisualStudio\VSIX Auto Update",
    @"\Microsoft\VisualStudio\Updates\UpdateConfiguration_S-1-5-21-1092161277-454068885-3468675754-1002",
    @"\Microsoft\VisualStudio\Updates\UpdateConfiguration_S-1-5-21-1092161277-454068885-3468675754-1003",
    @"\Microsoft\Windows\Application Experience\AitAgent",
@"\Microsoft\Windows\Customer Experience Improvement Program\KernelCeipTask",
@"\Microsoft\Windows\Media Center\ActivateWindowsSearch",
@"\Microsoft\Windows\Media Center\ConfigureInternetTimeService",
@"\Microsoft\Windows\Media Center\DispatchRecoveryTasks",
@"\Microsoft\Windows\Media Center\ehDRMInit",
@"\Microsoft\Windows\Media Center\InstallPlayReady",
@"\Microsoft\Windows\Media Center\mcupdate",
@"\Microsoft\Windows\Media Center\MediaCenterRecoveryTask",
@"\Microsoft\Windows\Media Center\ObjectStoreRecoveryTask",
@"\Microsoft\Windows\Media Center\OCURActivate",
@"\Microsoft\Windows\Media Center\OCURDiscovery",
@"\Microsoft\Windows\Media Center\PBDADiscovery",
@"\Microsoft\Windows\Media Center\PBDADiscoveryW1",
@"\Microsoft\Windows\Media Center\PBDADiscoveryW2",
@"\Microsoft\Windows\Media Center\PeriodicScanRetry",
@"\Microsoft\Windows\Media Center\PvrRecoveryTask",
@"\Microsoft\Windows\Media Center\PvrScheduleTask",
@"\Microsoft\Windows\Media Center\RecordingRestart",
@"\Microsoft\Windows\Media Center\RegisterSearch",
@"\Microsoft\Windows\Media Center\ReindexSearchRoot",
@"\Microsoft\Windows\Media Center\SqlLiteRecoveryTask",
@"\Microsoft\Windows\Media Center\UpdateRecordPath",
@"\Microsoft\Windows\MemoryDiagnostic\CorruptionDetector",
@"\Microsoft\Windows\MemoryDiagnostic\DecompressionFailureDetector",
@"\Microsoft\Windows\MobilePC\HotStart",
@"\Microsoft\Windows\PerfTrack\BackgroundConfigSurveyor",
@"\Microsoft\Windows\RAC\RacTask",
@"\Microsoft\Windows\Setup\EOSNotify",
@"\Microsoft\Windows\Setup\EOSNotify2",
@"\Microsoft\Windows\Shell\WindowsParentalControls",
@"\Microsoft\Windows\Shell\WindowsParentalControlsMigration",
@"\Microsoft\Windows\SideShow\AutoWake",
@"\Microsoft\Windows\SideShow\GadgetManager",
@"\Microsoft\Windows\SideShow\SessionAgent",
@"\Microsoft\Windows\SideShow\SystemDataProviders",
@"\Microsoft\Windows\Tcpip\IpAddressConflict1",
@"\Microsoft\Windows\Tcpip\IpAddressConflict2",
@"\Microsoft\Windows\WindowsBackup\ConfigNotification",
@"\Microsoft\Windows Defender\MP Scheduled Scan",
@"\Optimize Start Menu Cache Files-S-1-5-21-35552198-3516316200-1963562390-1001",
@"\Microsoft\Windows\AppID\SmartScreenSpecific",
@"\Microsoft\Windows\Application Experience\AitAgent",
@"\Microsoft\Windows\Customer Experience Improvement Program\BthSQM",
@"\Microsoft\Windows\Customer Experience Improvement Program\KernelCeipTask",
@"\Microsoft\Windows\Customer Experience Improvement Program\Uploader",
@"\Microsoft\Windows\IME\SQM data sender",
@"\Microsoft\Windows\NetCfg\BindingWorkItemQueueHandler",
@"\Microsoft\Windows\PerfTrack\BackgroundConfigSurveyor",
@"\Microsoft\Windows\Plug and Play\Plug and Play Cleanup",
@"\Microsoft\Windows\RAC\RacTask",
@"\Microsoft\Windows\SettingSync\BackupTask",
@"\Microsoft\Windows\Setup\EOSNotify",
@"\Microsoft\Windows\Setup\EOSNotify2",
@"\Microsoft\Windows\Setup\SetupCleanupTask",
@"\Microsoft\Windows\Shell\FamilySafetyRefresh",
@"\Microsoft\Windows\Shell\FamilySafetyUpload",
@"\Microsoft\Windows\SkyDrive\Idle Sync Maintenance Task",
@"\Microsoft\Windows\SkyDrive\Routine Maintenance Task",
@"\Microsoft\Windows\SoftwareProtectionPlatform\SvcTrigger",
@"\Microsoft\Windows\TaskScheduler\Idle Maintenance",
@"\Microsoft\Windows\TaskScheduler\Maintenance Configurator",
@"\Microsoft\Windows\TaskScheduler\Manual Maintenance",
@"\Microsoft\Windows\TaskScheduler\Regular Maintenance",
@"\Microsoft\Windows\Windows Defender\Windows Defender Cache Maintenance",
@"\Microsoft\Windows\Windows Defender\Windows Defender Cleanup",
@"\Microsoft\Windows\Windows Defender\Windows Defender Scheduled Scan",
@"\Microsoft\Windows\Windows Defender\Windows Defender Verification",
@"\Microsoft\Windows\WindowsUpdate\AUFirmwareInstall",
@"\Microsoft\Windows\WindowsUpdate\AUScheduledInstall",
@"\Microsoft\Windows\WindowsUpdate\AUSessionConnect",
@"\Microsoft\Windows\WindowsUpdate\Scheduled Start With Network",
@"\Microsoft\Windows\Workplace Join\Automatic-Workplace-Join",
@"\Microsoft\Windows\WS\Badge Update",
@"\Microsoft\Windows\WS\License Validation",
@"\Microsoft\Windows\WS\Sync Licenses",
@"\Microsoft\Windows\WS\WSRefreshBannedAppsListTask",
@"\Microsoft\Windows\WS\WSTask",
@"\WPD\SqmUpload_S-1-5-21-35552198-3516316200-1963562390-1001",
        };
    }
}
