using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;

public class ServiceWhitelist
{
    public static string CleanWhitelist(string input, string pathPrefix)
    {
        string REGEXPR = input;

        // Example of cleaning input (modify based on exact requirements)
        REGEXPR = Regex.Replace(REGEXPR, "(?i)S[234] (AppMgmt|HidServ); %SystemRoot%\\\\System32\\\\(appmgmts|hidserv)\\.dll \\[X\\]\\v{2}", "");

        return REGEXPR;
    }

    public static readonly HashSet<string> WhitelistedServices = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
    {
        "iastor",
        ".net clr data",
        ".net clr networking",
        ".net data provider for oracle",
        ".net data provider for sqlserver",
        ".netframework",
        "_iomega_active_disk_service_",
        "{6080a529-897e-4629-a488-aba0c29b635e}",
        "{834170a7-af3b-4d34-a757-e05eb29ee96d}",
        "{85ccb53b-23d8-4e73-b1b7-9ddb71827d9b}",
        "{a7447300-8075-4b0d-83f1-3d75c8ebc623}",
        "{d31a0762-0ceb-444e-acff-b049a1f6fe91}",
        "{eda5f5d3-9e0f-4f4d-8a13-1d1cf469c9cc}",
        "2wirepcp",
        "3com 3crdag675b wireless lan pci adapter wlservice",
        "3com dmi agent",
        "3combootp",
        "3compxe",
        "3comtftp",
        "61883",
        "6to4",
        "aavmker4",
        "aawservice",
        "abiosdsk",
        "abp480n5",
        "ac97intc",
        "acdservice",
        "acedrv05",
        "acedrv07",
        "acer media server",
        "acermemusagecheckservice",
        "acpi",
        "acpiec",
        "acrotray",
        "ad-watch connect filter",
        "ad-watch real-time scanner",
        "ad-watch registry filter",
        "adaptec i/o manager server",
        "adaptec raid remote services agent",
        "adaptec storage manager notifier",
        "adaptec web server",
        "adobe lm service",
        "adobe version cue cs2",
        "adobe version cue cs3",
        "adobeactivefilemonitor4.0",
        "adobeactivefilemonitor5.0",
        "adobeversioncue",
        "adpu160m",
        "adpu320",
        "aec",
        "aegisp",
        "AeLookupSvc",
        "afd",
        "ageremodemaudio",
        "ageresoftmodem",
        "agp440",
        "aha154x",
        "aic116x",
        "aic78u2",
        "aic78xx",
        "alcxwdm",
        "alerter",
        "alg",
        "aliide",
        "alim1541",
        "altiris recovery solution agent",
        "altiris recovery solution fal stopper",
        "aluria spyware eliminator service",
        "amdagp",
        "AmdIde",
        "amdk7",
        "amdk8",
        "amdppm",
        "ami0nt",
        "amon",
        "amsint",
        "antivir service",
        "antivir update",
        "antivirscheduler",
        "antivirservice",
        "anydvd",
        "aol acs",
        "aol topspeedmonitor",
        "aolavupd",
        "aolservice",
        "apache",
        "apache2",
        "apphostsvc",
        "appmgmt",
        "ar5211",
        "arc",
        "arp1394",
        "asc",
        "asc3350p",
        "asc3550",
        "asp.net",
        "asp.net_1.1.4322",
        "asp.net_2.0.50727",
        "aspi32",
        "aspnet_state",
        "asuskbnt",
        "asuskeyboardservice",
        "aswmon2",
        "aswrdr",
        "aswtdi",
        "aswupdsv",
        "asyncmac",
        "atapi",
        "atdisk",
        "atheros configuration service",
        "ati",
        "ati external event utility",
        "ati hotkey poller",
        "ati remote wonder ii",
        "ati smart",
        "ati2mtag",
        "atiavaiw",
        "atiavpci",
        "atierecord",
        "atimpab",
        "atimtag",
        "atinevxx",
        "atinrvxx",
        "atirage3",
        "atitool",
        "atitunep",
        "ativraxx",
        "atixsaudio",
        "atkkeyboardservice",
        "atmarpc",
        "audiosrv",
        "audstub",
        "avast! antivirus",
        "avast! mail scanner",
        "avast! web scanner",
        "avfilter",
        "avg anti-rootkit",
        "avg anti-spyware driver",
        "avg anti-spyware guard",
        "avg clean driver",
        "avg6 service",
        "avg7alrt",
        "avg7core",
        "avg7rsw",
        "avg7rsxp",
        "avg7updsvc",
        "avgarcln",
        "avgascln",
        "avgclean",
        "avgcoresvc",
        "avgems",
        "avgfwsrv",
        "avgio",
        "avgmfx86",
        "avgntflt",
        "avgtdi",
        "avhook",
        "avp",
        "avp control centre service",
        "aw_host",
        "awhost32",
        "awlegacy",
        "awservice",
        "axinstsv",
          "b57w2k",
  "basic2",
  "battc",
  "bdfdll",
  "bdfsdrv",
  "bdfsfltr",
  "bdftdif",
  "bdrsdrv",
  "bdselfpr",
  "bdss",
  "beep",
  "belkin high-speed mode wireless g usb network adapter service",
  "belkin wireless usb network adapter service",
  "bits",
  "blueletaudio",
  "blueletscoaudio",
  "bocdrive",
  "bonjour service",
  "bridge",
  "bridgemp",
  "broadcom asf ip monitoring service v3.0.1",
  "brother xp spl service",
  "browser",
  "bt",
  "btaudio",
  "btcsrusb",
  "btdriver",
  "bthidenum",
  "bthidmgr",
  "bthmodem",
  "btkrnl",
  "btnetfilter",
  "btwdins",
  "btwusb",
  "c-dillacdac11ba",
  "c-dillasrv",
  "ca-messagequeuing",
  "ca isafe",
  "ca license client",
  "ca license server",
  "cachemanxp",
  "cachemgr",
  "caisafe",
  "catchme",
  "cavasm",
  "cbidf",
  "cbidf2k",
  "ccalib8",
  "ccdecode",
  "ccevtmgr",
  "ccproxy",
  "ccpwdsvc",
  "ccsetmgr",
  "cd20xrnt",
  "CdaC15BA",
  "CdaD10BA",
  "cdaudio",
  "cdfs",
  "cdr4_2k",
  "cdr4_xp",
  "cdralw2k",
  "cdrom",
  "cfosspeed",
  "cfosspeeds",
  "changer",
  "cisco systems, inc. vpn service",
  "cisvc",
  "citrix sma service",
  "citrix virtual memory optimization",
  "citrixwmiservice",
  "citrixxteserver",
  "clipsrv",
  "clr_optimization_v2.0.50727_32",
  "cmbatt",
  "cmdagent",
  "cmdide",
  "cmdmon",
  "cnxtdiag",
  "co_mon",
  "comodo anti-virus and anti-spyware service",
  "compbatt",
  "comsysapp",
  "contentfilter",
  "contentindex",
  "cpqarray",
  "cpqarry2",
  "cpqfcalm",
  "cpqfws2e",
  "crcdisk",
  "creative labs licensing service",
  "creative service for cdrom access",
  "crypkey license",
  "cryptsvc",
  "crystal event server",
  "crystal management server",
  "crystal program job server",
  "crystal report application server",
  "crystalaps",
  "crystalinputfileserver",
  "crystaloutputfileserver",
  "dac2w2k",
  "dac960nt",
  "dcomlaunch",
  "deckzpsx",
  "defragfs",
  "Dfs",
  "dhcp",
  "diamondcs process guard service v3.000",
  "disk",
  "dmadmin",
  "dmboot",
  "dmio",
  "dmload",
  "dmserver",
  "dmusic",
  "dnscache",
  "dot3svc",
  "dpti2o",
  "drmkaud",
  "dtscsi",
  "E1000",
  "eaphost",
  "el90xbc",
  "emu10k",
  "emu10k1",
  "entech",
  "ersvc",
  "es1371",
    "etrust antivirus realtime server",
  "etrust antivirus rpc server",
  "eventlog",
  "eventsystem",
  "evteng",
  "ewido anti-spyware 4.0 driver",
  "ewido anti-spyware 4.0 guard",
  "ewido security suite control",
  "ewido security suite guard",
  "exfat",
  "f-prot antivirus update monitor",
  "f-secure backweb lan access",
  "f-secure gatekeeper handler starter",
  "f-secure network request broker",
  "fallback",
  "fastfat",
  "fastuserswitchingcompatibility",
  "Fd16_700",
  "fdc",
  "fetnd5bv",
  "filemon701",
  "fips",
  "fireport",
  "flashpnt",
  "flpydisk",
  "fltmgr",
  "fontcache3.0.0.0",
  "fs_rec",
  "fsks",
  "ftdisk",
  "gameenum",
  "gearaspiwdm",
  "gearsecurity",
  "ghostsec",
  "giveio",
  "gmer",
  "gpc",
  "gusvc",
  "ha10kx2k",
  "hamachi",
  "hap16v2k",
  "hcf_msft",
  "hcmon",
  "hdaudbus",
  "helpsvc",
  "hidbatt",
  "hidserv",
  "hidusb",
  "hkmsvc",
  "hpn",
  "hpzid412",
  "hpzipr12",
  "hpzius12",
  "hsf_dp",
  "hsf_msft",
  "hsfhwbs2",
  "http",
  "httpfilter",
  "i2omgmt",
  "i2omp",
  "i8042prt",
  "ialm",
  "IASJet",
  "idrivert",
  "idsvc",
  "iirsp",
  "ikfileflt",
  "ikfilesec",
  "ikhfile",
  "ikhlayer",
  "iksysflt",
  "iksyssec",
  "imagedrv",
  "imagesrv",
  "imapi",
  "imapiservice",
  "incdfs",
  "incdpass",
  "incdrec",
  "incdrm",
  "incdsrv",
  "inetaccs",
  "ini910u",
  "inport",
  "intcazaudaddservice",
  "intelide",
  "intelppm",
  "interactivelogon",
  "ip6fw",
  "ipfilterdriver",
  "ipinip",
  "ipnat",
  "ipod service",
  "ipodservice",
  "ipsec",
  "ipsraidn",
  "irenum",
  "isapisearch",
  "isapnp",
  "isdrv120",
  "isdrv122",
  "k56",
  "kav monitor service",
  "kavsvc",
  "kbdclass",
  "kbdhid",
  "kl1",
  "klif",
  "kmixer",
  "kodakccs",
  "ksecdd",
  "ksthunk",
  "l8042pr2",
  "lanmanserver",
  "lanmanworkstation",
  "lbrtfdc",
  "ldap",
  "lexbces",
  "lhidflt2",
  "lhidusb",
  "licenseservice",
  "lightscribeservice",
  "liveupdate",
  "lmhosts",
  "lmouflt2",
  "lp6nds35",
  "lvckap",
  "lvmvdrv",
  "lvpr2mon",
  "lvusbsta",
  "lxbs_device",
  "lxbt_device",
  "lxbu_device",
  "lxbx_device",
  "lxby_device",
  "lxcc_device",
  "lxcccustomerconnect",
  "lxcd_device",
  "lxce_device",
  "lxcf_device",
  "lxcg_device",
  "lxcgcustomerconnect",
  "lxcj_device",
  "lxcr_device",
  "lxct_device",
  "lxdj_device",
  "lxrjd31d",
  "macromedia licensing service",
  "mbr",
  "mcafee agent",
  "mcafee antispyware service",
  "mcafee firewall",
  "mcafee hackerwatch service",
  "mcafee securitycenter update manager",
  "mcafee.com personal firewall service",
  "mcafeeantispyware",
  "mcafeeframework",
  "mcdbus",
  "mcdetect.exe",
  "mclogmanagerservice",
  "mclserviceatl",
  "mcmispupdmgr",
  "mcmscsvc",
  "mcnasvc",
  "mcods",
  "mcontrol",
  "mcp",
  "mcpromgr",
  "mcproxy",
  "mcrdsvc",
  "mcredirector",
  "mcshield",
  "mcsysmon",
  "mctaskmanager",
  "mctskshd.exe",
  "mcupdmgr.exe",
  "mcusrmgr",
  "mcvsrte",
  "mdm",
  "mdmxsdk",
  "messenger",
  "mfeavfk",
  "mfebopk",
  "mfehidk",
  "mferkdk",
  "mfesmfk",
  "mks_scan",
  "mksupdateint",
  "mksvirmonsvc",
  "mnmdd",
  "mnmsrvc",
  "modem",
  "modemcsa",
  "mouclass",
  "mouhid",
  "mountmgr",
  "mpe",
  "mpfirewl",
  "mpfp",
  "mpfservice",
  "mps9",
  "mraid35x",
  "mrxdav",
  "mrxsmb",
  "msdtc",
  "msdtc bridge 3.0.0.0",
  "msfs",
  "msiserver",
  "mskssrv",
  "mspclock",
  "mspqm",
  "mssmbios",
  "mstee",
  "mup",
  "my firewall plus",
  "mysql",
    "nabtsfec",
  "naiavfilter1",
  "naimagent32",
  "nalntservice",
  "napagent",
  "nav alert",
  "navap",
  "navapel",
  "navapsvc",
  "naveng",
  "navex15",
  "nbservice",
  "Ncrc710",
  "ndis",
  "ndistapi",
  "ndisuio",
  "ndiswan",
  "ndproxy",
  "nero backitup scheduler 3",
  "netbios",
  "netbt",
  "netdde",
  "netddedsdm",
  "netlogon",
  "netman",
  "netmnt",
  "nettcpportsharing",
  "nic1394",
  "nla",
  "nm",
  "nod32krn",
  "norman virus control on-access component",
  "norman virus control scheduler",
  "norman zanda",
  "norton antivirus server",
  "norton ghost",
  "norton internet security service",
  "norton personal firewall proxy service",
  "norton personal firewall service",
  "npfmntor",
  "npfs",
  "ntfs",
  "ntlmssp",
  "ntmssvc",
  "null",
  "nv",
  "nv_agp",
  "nv4",
  "nvatabus",
  "nvenetfd",
  "nvnetbus",
  "nvraid",
  "nwlnkflt",
  "nwlnkfwd",
  "ofcpfwsvc",
  "ofcservice",
  "officescannt listener",
  "officescannt realtime scan",
  "ohci1394",
  "ose",
  "p17",
  "panda antispam server service",
  "panda firewall",
  "panda firewall service",
  "panda function service",
  "panda pavkre",
  "panda pavprot",
  "panda preventium+ service",
  "panda software controller",
  "parport",
  "partmgr",
  "parvdm",
  "pav_security",
  "pav_service",
  "pavagente",
  "pavatscheduler",
  "pavdrv",
  "pavfnsvr",
  "pavprsrv",
  "pavreport",
  "pavsrv",
  "pc-cillin personalfirewall",
  "pci",
  "pcidump",
  "pciide",
  "pcmcia",
  "pcnet",
  "pcscnsrv",
  "pctavsvc",
  "pctfw1",
  "pctoolsfirewallplus",
  "pdagent",
  "pdcomp",
  "pdengine",
  "pdframe",
  "pdreli",
  "pdrframe",
  "perc2",
  "perc2hib",
  "perfdisk",
  "perfnet",
  "perfos",
  "perfproc",
  "pestpatrol remote",
  "pfc",
  "plugplay",
  "pml driver hpz12",
  "point32",
  "policyagent",
  "pptpminiport",
  "prevxagent",
  "prevxdriver",
  "prismxl",
  "processor",
  "procexp100",
  "procexp111",
  "procexp90",
  "procmon10",
  "profos",
  "protectedstorage",
  "protector plus anti-virus monitor service",
  "psched",
  "PEVSystemStart",
  "ptilink",
  "pxhelp20",
  "ql1080",
  "ql10wnt",
  "ql12160",
  "ql1240",
  "ql1280",
  "ql2100",
  "quick heal mail protection",
  "quick heal online protection",
  "quickhealfirewall",
  "rasacd",
  "rasauto",
  "rasl2tp",
  "rasman",
  "raspppoe",
  "raspti",
  "rassstp",
  "raysat3_4_6_18server",
  "raysatxsi5_0server",
  "rbfilter",
  "rdbss",
  "rdpcdd",
  "rdpdd",
  "rdpdr",
  "rdpnp",
  "rdpwd",
  "rdsessmgr",
  "redbook",
  "regdefend",
  "regmon701",
  "regspy",
  "remoteaccess",
  "remoteregistry",
  "rkhdrv31",
  "rksample",
  "rootmodem",
  "roxio upnp renderer 9",
  "roxio upnp server 9",
  "roxliveshare",
  "roxliveshare9",
  "roxmediadb",
  "roxmediadb9",
  "roxupnprenderer",
  "roxupnpserver",
  "roxwatch",
  "roxwatch9",
  "rpcapd",
  "rpclocator",
  "rpcss",
  "rrrspy",
  "rrspy",
  "rsvp",
  "rtl8023",
  "rtl8139",
  "rwbackupsrv",
  "s24eventmonitor",
  "s3psddr",
  "s3savagenb",
  "samss",
  "savrt",
  "savrtpel",
  "savscan",
  "sbservice",
  "scan",
  "scarddrv",
  "scardsvr",
  "schedule",
  "ScsiPort",
  "sdcoreservice",
  "sdhelper",
  "secdrv",
  "seclogon",
  "sens",
  "sentinel",
  "sentinelprotectionserver",
  "serenum",
  "serial",
  "servicemodelendpoint 3.0.0.0",
  "servicemodeloperation 3.0.0.0",
  "servicemodelservice 3.0.0.0",
  "sfloppy",
  "sfman",
  "sglfb",
  "sharedaccess",
  "shellhwdetection",
  "simbad",
  "sisagp",
  "smcservice",
  "smsvchost 3.0.0.0",
  "snac",
  "snoopfree",
  "snoopfreesvc",
  "softfax",
  "sonicatheaterinstallerservice",
  "sonicstage back-end service",
  "sonicstagemonitoring",
  "sonicwall agent service",
  "sonicwall_netextender",
  "sony scsi helper service",
  "sony tv tuner controller",
  "sony tv tuner manager",
  "sony tvta manager",
  "sony_ssm.sys",
  "sonypvu1",
  "sonytvc",
  "sonywbms",
  "sophos agent",
  "sophos anti-virus",
  "sophos anti-virus network",
  "sophos anti-virus update",
  "sophos autoupdate agent",
  "sophos autoupdate service",
  "sophos message router",
  "sophos sbe certification manager",
  "sophos sbe managementservice",
  "soundmax agent service (default)",
  "sparrow",
  "spbbcsvc",
  "speakerphone",
  "speedfan",
  "splitter",
  "spooler",
  "sr",
  "srservice",
  "srv",
  "ssdpsrv",
  "sstpsvc",
  "stisvc",
  "streamip",
  "svv",
  "swenum",
  "swmidi",
  "swprv",
  "swwd",
  "sym_hi",
  "sym_u3",
  "symantec antivirus",
  "symantec core lc",
  "symantecantibotagent",
  "symantecantibotdriver",
  "symantecantibotfilter",
  "symantecantibotshim",
  "symantecantibotwatcher",
  "symc810",
  "symc8xx",
  "symdns",
  "symevent",
  "symfw",
  "symids",
  "symidsco",
  "symlcbrd",
  "symmpi",
  "symredrv",
  "symsnap",
  "symtdi",
  "symwsc",
  "sysaudio",
  "sysmonlog",
  "sysplant",
    "tapisrv",
  "tcpip",
  "tdimsys",
  "tdpipe",
  "tdtcp",
  "teefer2",
  "termdd",
  "termservice",
  "tga",
  "themes",
  "tlntsvr",
  "tmcomm",
  "tones",
  "toside",
  "trkwks",
  "trufos",
  "tsddd",
  "udfs",
  "ufad-ws60",
  "ultra",
  "ultra66",
  "umwdf",
  "unlockerdriver5",
  "update",
  "upnphost",
  "ups",
  "us30sys",
  "usbaudio",
  "usbccgp",
  "usbehci",
  "usbhub",
  "usbohci",
  "usbprint",
  "usbscan",
  "usbstor",
  "usbuhci",
  "usnjsvc",
  "usnsvc",
  "usprserv",
  "v124",
  "vcomm",
  "vcommmgr",
  "vds",
  "vet-filt",
  "vet-rec",
  "veteboot",
  "vetefile",
  "vetfddnt",
  "vetmonnt",
  "vetmsgnt",
  "vga",
  "vgasave",
  "viaagp",
  "viaagp1",
  "viaide",
  "viaudio",
  "visual studio analyzer rpc bridge",
  "VMAUDIO",
  "vmauthdservice",
  "vmkbd2",
  "vmm",
  "vmnetadapter",
  "vmnetbridge",
  "vmnetdhcp",
  "vmnetuserif",
  "vmount2",
  "vmparport",
  "vmusb",
  "vmware",
  "vmware nat service",
  "vmx86",
  "vncmirror",
  "volsnap",
  "vpcnets2",
  "vproeventmonitor",
  "vsdatant",
  "vsmon",
  "vss",
  "vstor2",
  "vstor2-ws60",
  "vxd",
  "w32time",
  "w3svc",
  "w800bus",
  "w800mdfl",
  "w800mdm",
  "w800mgmt",
  "w800obex",
  "wanarp",
  "was",
  "wdica",
  "wdmaud",
  "webclient",
  "webrootadminconsole",
  "webrootcommagentservice",
  "webrootenterpriseclientservice",
  "webrootenterpriseupdateservice",
  "webrootspysweeperservice",
  "websense eim server",
  "websense network agent",
  "websense reporter scheduler",
  "websensecamreportserver",
  "websensecamserver",
  "websenseclientdeployservice",
  "websensecommunicationagent",
  "websensecpmcommunicationagent",
  "websensedcagent",
  "websenselogserver",
  "websensepolicyserver",
  "websenserealtimeanalyzer",
  "websenseusagemonitor",
  "websenseuserservice",
  "websensewfreportserver",
  "winachsf",
  "windows driver framework",
  "windows workflow foundation 3.0.0.0",
  "WinHttpAutoProxySvc",
  "winmgmt",
  "winsock",
  "winsock2",
  "wintrust",
  "wlsetupsvc",
  "wmdmpmsn",
  "wmi",
  "wmiaprpl",
  "wmiapsrv",
  "wmpnetworksvc",
  "wps",
  "wpshelper",
  "ws2ifsl",
  "wscsvc",
  "wstcodec",
  "wuauserv",
  "wudfpf",
  "wudfrd",
  "wudfsvc",
  "wwsecsvc",
  "wzcsvc",
  "xcomm",
  "xmlprov",
  "yukonwxp",
    "AppMgmt",
  "HidServ",
  "AcrSch2Svc",
  "AcPrfMgrSvc",
  "AcSvc",
  "DozeSvc",
  "Power Manager DBC Service",
  "SUService",
  "LENOVO.CAMMUTE",
  "LENOVO.MICMUTE",
  "LENOVO.TPKNRSVC",
  "TSSCoreService",
  "ac.sharedstore",
  "AdobeARMservice",
  "Adobe Version Cue CS3",
  "Adobe LM Service",
  "AffinegyService",
  "AgereModemAudio",
  "AEADIFilters",
  "AESTFilters",
  "AERTFilters",
  "afcdpsrv",
  "Akamai",
  "ALG",
  "AMD External Events Utility",
  "Apple Mobile Device",
  "Application Updater",
  "aspnet_state",
  "Ati External Event Utility",
  "astcc",
  "ssh-agent",
  "atashost",
  "Atheros Bt&Wlan Coex Agent",
  "ATService",
  "Autodesk Licensing Service",
  "BBSvc",
  "BBUpdate",
  "SeaPort",
  "BcmSqlStartupSvc",
  "BUNAgentSvc",
  "Bonjour Service",
  "btwdins",
  "BPowMon",
  "BWH32S",
  "DDNIOEMService",
  "CATmobile",
  "CinemaNow Service",
  "clr_optimization_v3.0.0.0",
  "Com4QLBEx",
  "Creative ALchemy AL1 Licensing Service",
  "Creative Audio Engine Licensing Service",
  "CTAELicensing",
  "cvhsvc",
  "DLPWD",
  "DLSDB",
  "dmadmin",
  "DpHost",
  "DsiWMIService",
  "FLEXnet Licensing Service",
  "FreeAgentGoFlex Service",
  "ehRecvr",
  "eDataSecurity Service",
  "ePowerSvc",
  "EvtEng",
  "ezSharedSvc",
  "FastUserSwitchingCompatibility",
  "FileOpenManagerSvc",
  "FLService",
  "FontCache",
  "FontCache3.0.0.0",
  "fsssvc",
  "FsUsbExService",
  "GamesAppService",
  "GameConsoleService",
  "gupdate",
  "gupdatem",
  "GoogleUpdaterInternalService",
  "gusvc",
  "GoogleChromeElevationService",
  "hasplms",
  "helpsvc",
  "hidserv",
  "HitachiBackupService",
  "HPM1210RcvFaxSrvc",
  "HP LaserJet Service",
  "hpqcxs08",
  "hpqddsvc",
  "HPSLPSVC",
  "hpsrv",
  "HPSIService",
  "HsfXAudioService",
  "HTTPFilter",
  "IAANTMON",
  "IAStorDataMgrSvc",
  "IBMPMSVC",
  "IDriverT",
  "idvc",
  "IntuitUpdateService",
  "IviRegMgr",
  "kraidsvc",
  "LBTServ",
  "LeapFrog Connect Device Service",
  "LightScribeService",
  "LMIGuardianSvc",
  "LMS",
  "MatSvc",
  "McciCMService",
  "Microsoft Groove Audit Service",
  "MozillaMaintenance",
  "MSCamSvc",
  "msiserver",
  "MSSQL\\$SPCS",
  "MSSQLServerADHelper",
  "nTuneService",
  "nvs",
  "odserv",
  "ose",
  "osppsvc",
  "PACSPTISVR",
  "pcCMService",
  "PenCommService",
  "PLFlash DeviceIoControl Service",
  "PLAVService",
  "PLAVFlash",
  "qbsvc",
  "RapportMgmtService",
  "RasAuto",
  "RegSrvc",
  "Roxio UPnP Renderer",
  "RpcSs",
  "SandraAgentSrv",
  "SeaPort",
  "sftlist",
  "sftvsa",
  "ShadowProtectSvc",
  "SkypeUpdate",
  "SQLBrowser",
  "STacSV",
  "Steam Client Service",
  "SwitchBoard",
  "TabletServicePen",
  "TeamViewer",
  "TPAutoConnSvc",
  "TrustedInstaller",
  "TuneUp.UtilitiesSvc",
  "TurboBoost",
  "VMTools",
  "VMUpgradeHelper",
  "Vongo Service",
  "vpnagent",
  "vs",
  "w3svc",
  "WatAdminSvc",
  "WDDMService",
  "wbengine",
  "WinHttpAutoProxySvc",
  "WPCSvc",
  "WMPNetworkSvc",
  "WPFFontCache",
  "WSearch",
  "XAudioService",
  "YahooAUService",
  "ZuneNetworkSvc",
                  "aelookupsvc",  // Add more services to exclude here, in lowercase
                "AJRouter",
                "alg",
                "appidsvc",
                "appinfo",
                "appmgmt",
                "appreadiness",
                "appvclient",
                "appxsvc",
                "assignedaccessmanagersvc",
                "audioendpointbuilder",
                "audiosrv",
                "autotimesvc",
                "axinstsv",
                "bdesvc",
                "bfe",
                "bits",
                "brokerinfrastructure",
                "btagservice",
                "bthavctpsvc",
                "bthserv",
                "camsvc",
                "cdpsvc",
                "certpropsvc",
                "clicktorunsvc",
                "clipsvc",
                "cloudidsvc",
                "comsysapp",
                "coremessagingregistrar",
                "cryptsvc",
                "cscservice",
                "dcomlaunch",
                "dcsvc",
                "defragsvc",
                "deviceassociationservice",
                "deviceinstall",
                "devquerybroker",
                "dhcp",
                "diagnosticshub.standardcollector.service",
                "diagsvc",
                "diagtrack",
                "dialogblockingservice",
                "dispbrokerdesktopsvc",
                "displayenhancementservice",
                "dmenrollmentsvc",
                "dmwappushservice",
                "dnscache",
                "dosvc",
                "dot3svc",
                "dps",
                "dsmsvc",
                "dssvc",
                "dusmsvc",
                "eaphost",
                "efs",
                "embeddedmode",
                "entappsvc",
                "eventlog",
                "eventsystem",
                "fax",
                "fdphost",
                "fdrespub",
                "fhsvc",
                "fontcache",
                "fontcache3.0.0.0",
                "frameserver",
                "gameinput service",
                "gameinputsvc",
                "gamingservices",
                "gamingservicesnet",
                "gpsvc",
                "graphicsperfsvc",
                "hgclientservice",
                "hidserv",
                "hns",
                "hvhost",
                "icssvc",
                "ikeext",
                "installservice",
                "iphlpsvc",
                "ipxlatcfgsvc",
                "jhi_service",
                "keyiso",
                "ktmrm",
                "lanmanserver",
                "lanmanworkstation",
                "lfsvc",
                "licensemanager",
                "lltdsvc",
                "lmhosts",
                "lsm",
                "lxpsvc",
                "mapsbroker",
                "mcpmanagementservice",
                "mdcoresvc",
                "mixedrealityopenxrsvc",
                "mpssvc",
                "msdtc",
                "msiscsi",
                "msiserver",
                "mskeyboardfilter",
                "naturalauthentication",
                "ncasvc",
                "ncbservice",
                "ncdautosetup",
                "netlogon",
                "netman",
                "netprofm",
                "netsetupsvc",
                "nettcpportsharing",
                "ngcctnrsvc",
                "ngcsvc",
                "nlasvc",
                "nsi",
                "nvagent",
                "ose64",
                "p2pimsvc",
                "p2psvc",
                "pcasvc",
                "peerdistsvc",
                "perceptionsimulation",
                "perfhost",
                "phonesvc",
                "pla",
                "plugplay",
                "pnrpautoreg",
                "pnrpsvc",
                "policyagent",
                "power",
                "printnotify",
                "profsvc",
                "pushtoinstall",
                "qwave",
                "rasauto",
                "rasman",
                "remoteaccess",
                "remoteregistry",
                "retaildemo",
                "rmsvc",
                "rpceptmapper",
                "rpclocator",
                "rpcss",
                "samss",
                "scardsvr",
                "scdeviceenum",
                "schedule",
                "scpolicysvc",
                "sdrsvc",
                "seclogon",
                "securityhealthservice",
                "semgrsvc",
                "sens",
                "sense",
                "sensordataservice",
                "sensorservice",
                "sensrsvc",
                "sessionenv",
                "sgrmbroker",
                "sharedaccess",
                "sharedrealitysvc",
                "shellhwdetection",
                "shpamsvc",
                "smphost",
                "smsrouter",
                "snmptrap",
                "spectrum",
                "spooler",
                "sppsvc",
                "sqlwriter",
                "ssdpsrv",
                "ssh-agent",
                "sstpsvc",
                "staterepository",
                "stisvc",
                "storsvc",
                "svsvc",
                "swprv",
                "sysmain",
                "systemeventsbroker",
                "tabletinputservice",
                "tapisrv",
                "termservice",
                "themes",
                "tieringengineservice",
                "timebrokersvc",
                "tokenbroker",
                "trkwks",
                "troubleshootingsvc",
                "trustedinstaller",
                "tzautoupdate",
                "uevagentservice",
                "uhssvc",
                "umrdpservice",
                "upnphost",
                "usermanager",
                "usosvc",
                "vacsvc",
                "vaultsvc",
                "vds",
                "vmcompute",
                "vmicguestinterface",
                "vmicheartbeat",
                "vmickvpexchange",
                "vmicrdv",
                "vmicshutdown",
                "vmictimesync",
                "vmicvmsession",
                "vmicvss",
                "vmms",
                "vsinstallerelevationservice",
                "vss",
                "vsstandardcollectorservice150",
                "w32time",
                "waasmedicsvc",
                "walletservice",
                "warpjitsvc",
                "wbengine",
                "wbiosrvc",
                "wcmsvc",
                "wcncsvc",
                "wdiservicehost",
                "wdisystemhost",
                "wdnissvc",
                "webclient",
                "wecsvc",
                "wephostsvc",
                "wercplsupport",
                "wersvc",
                "wfdsconmgrsvc",
                "wiarpc",
                "windefend",
                "winhttpautoproxysvc",
                "winmgmt",
                "winrm",
                "wisvc",
                "wlansvc",
                "wlidsvc",
                "wlpasvc",
                "wmansvc",
                "wmiapsrv",
                "wmiregistrationservice",
                "wmpnetworksvc",
                "workfolderssvc",
                "wpcmonsvc",
                "wpdbusenum",
                "wpnservice",
                "wscsvc",
                "wsearch",
                "wuauserv",
                "wwansvc",
                "xblauthmanager",
                "xblgamesave",
                "xboxgipsvc",
                "xboxnetapisvc",
                "aarsvc_9c69c",
                "bcastdvruserservice_9c69c",
                "bluetoothuserservice_9c69c",
                "captureservice_9c69c",
                "cbdhsvc_9c69c",
                "cdpusersvc_9c69c",
                "consentuxusersvc_9c69c",
                "credentialenrollmentmanagerusersvc_9c69c",
                "deviceassociationbrokersvc_9c69c",
                "devicepickerusersvc_9c69c",
                "devicesflowusersvc_9c69c",
                "messagingservice_9c69c",
                "onesyncsvc_9c69c",
                "pimindexmaintenancesvc_9c69c",
                "printworkflowusersvc_9c69c",
                "udkusersvc_9c69c",
                "unistoresvc_9c69c",
                "userdatasvc_9c69c",
                "wpnuserservice_9c69c",
                "aarsvc_1eb9739",
                "bcastdvruserservice_1eb9739",
                "bluetoothuserservice_1eb9739",
                "captureservice_1eb9739",
                "cbdhsvc_1eb9739",
                "cdpusersvc_1eb9739",
                "consentuxusersvc_1eb9739",
                "credentialenrollmentmanagerusersvc_1eb9739",
                "deviceassociationbrokersvc_1eb9739",
                "devicepickerusersvc_1eb9739",
                "devicesflowusersvc_1eb9739",
                "messagingservice_1eb9739",
                "onesyncsvc_1eb9739",
                "pimindexmaintenancesvc_1eb9739",
                "printworkflowusersvc_1eb9739",
                "udkusersvc_1eb9739",
                "unistoresvc_1eb9739",
                "userdatasvc_1eb9739",
                "wpnuserservice_1eb9739",
                "AsusUpdateCheck",
                "Intel(R) Capability Licensing Service TCP IP Interface",
                "Intel(R) TPM Provisioning Service",
                "MicrosoftEdgeElevationService",
                "NvContainerLocalSystem",
                "NvContainerNetworkService",
                "NVDisplay.ContainerLocalSystem",
                "AarSvc_21781c",
                "BcastDVRUserService_21781c",
                "BluetoothUserService_21781c",
                "CaptureService_21781c",
                "cbdhsvc_21781c",
                "CDPUserSvc_21781c",
                "ConsentUxUserSvc_21781c",
                "CredentialEnrollmentManagerUserSvc_21781c",
                "DeviceAssociationBrokerSvc_21781c",
                "DevicePickerUserSvc_21781c",
                "DevicesFlowUserSvc_21781c",
                "MessagingService_21781c",
                "OneSyncSvc_21781c",
                "PimIndexMaintenanceSvc_21781c",
                "PrintWorkflowUserSvc_21781c",
                "UdkUserSvc_21781c",
                "UnistoreSvc_21781c",
                "UserDataSvc_21781c",
                "WpnUserService_21781c",
                "AarSvc_8f8d78",
                "BcastDVRUserService_8f8d78",
                "BluetoothUserService_8f8d78",
                "CaptureService_8f8d78",
                "cbdhsvc_8f8d78",
                "CDPUserSvc_8f8d78",
                "ConsentUxUserSvc_8f8d78",
                "CredentialEnrollmentManagerUserSvc_8f8d78",
                "DeviceAssociationBrokerSvc_8f8d78",
                "DevicePickerUserSvc_8f8d78",
                "DevicesFlowUserSvc_8f8d78",
                "MessagingService_8f8d78",
                "OneSyncSvc_8f8d78",
                "PimIndexMaintenanceSvc_8f8d78",
                "PrintWorkflowUserSvc_8f8d78",
                "UdkUserSvc_8f8d78",
                "UnistoreSvc_8f8d78",
                "UserDataSvc_8f8d78",
                "WpnUserService_8f8d78",
                "AarSvc_dd02c",
                "BcastDVRUserService_dd02c",
                "BluetoothUserService_dd02c",
                "CaptureService_dd02c",
                "cbdhsvc_dd02c",
                "CDPUserSvc_dd02c",
                "ConsentUxUserSvc_dd02c",
                "CredentialEnrollmentManagerUserSvc_dd02c",
                "DeviceAssociationBrokerSvc_dd02c",
                "DevicePickerUserSvc_dd02c",
                "DevicesFlowUserSvc_dd02c",
                "MessagingService_dd02c",
                "OneSyncSvc_dd02c",
                "PimIndexMaintenanceSvc_dd02c",
                "PrintWorkflowUserSvc_dd02c",
                "UdkUserSvc_dd02c",
                "UnistoreSvc_dd02c",
                "UserDataSvc_dd02c",
                "WpnUserService_dd02c",
                "AarSvc_726c208",
                "BcastDVRUserService_726c208",
                "BluetoothUserService_726c208",
                "CaptureService_726c208",
                "cbdhsvc_726c208",
                "CDPUserSvc_726c208",
                "ConsentUxUserSvc_726c208",
                "CredentialEnrollmentManagerUserSvc_726c208",
                "DeviceAssociationBrokerSvc_726c208",
                "DevicePickerUserSvc_726c208",
                "DevicesFlowUserSvc_726c208",
                "MessagingService_726c208",
                "OneSyncSvc_726c208",
                "PimIndexMaintenanceSvc_726c208",
                "PrintWorkflowUserSvc_726c208",
                "UdkUserSvc_726c208",
                "UnistoreSvc_726c208",
                "UserDataSvc_726c208",
                "WpnUserService_726c208",
                "clr_optimization_v2.0.50727_64",
                "clr_optimization_v4.0.30319_32",
                "clr_optimization_v4.0.30319_64",
                "ehSched",
                "HomeGroupListener",
                "HomeGroupProvider",
                "IEEtwCollectorService",
                "IPBusEnum",
                "Mcx2Svc",
                "MMCSS",
                "NetMsmqActivator",
                "NetPipeActivator",
                "NetTcpActivator",
                "sppuinotify",
                "THREADORDER",
                "UI0Detect",
                "UxSms",
                "vmvss",
                "WcsPlugInService",
                "BthHFSrv",
                "HomeGroupListener",
                "HomeGroupProvider",
                "IEEtwCollectorService",
                "MMCSS",
                "THREADORDER",
                "TimeBroker",
                "UI0Detect",
                "WcsPlugInService",
                "WSService",
    };
}
