using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Wildlands_System_Scanner.Blacklist
{
    public class AppDataFolderBlacklist
    {
        // Predefined blacklist of folder names (case insensitive)
        private static readonly HashSet<string> _blacklistedFolders = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            // Add blacklisted folder names here
"\\#Short company name#",
"\\",
"\\%APPDA~1",
"\\.#",
"\\._Revolution_",
"\\.cache",
"\\.Flash",
"\\.iexplorer",
"\\.Java",
"\\.microsoft",
"\\.microsoft\\javajre6.cert",
"\\.Net Frarnework",
"\\.share",
"\\.smsniff",
"\\.SoQoR",
"\\.temp",
"\\.Xy.Client",
"\\@off@",
"\\[UPDATED 2011] PSN PINS!",
"\\__1",
"\\_421f3e69e6bf84087e3489c13957d0b2",
"\\{01E69986-A054-4C52-ABE8-EF63DF1C5211}",
"\\{16FF7A97-391D-4A55-BC79-C80FB14AADDA}",
"\\{1A086D87-252E-4CE2-9981-6D49EE56EFB3}",
"\\{2CF0B992-5EEB-4143-99C0-5297EF71F444}",
"\\{2EEE3GP2-I2JH-2G8C-81B2-XOU20I75S0L3}",
"\\{31A0CFC8-7A6D-491D-A5E1-4A6A32982D4C}",
"\\{337A6132-5934-4EBC-BB57-812BAF837DD0}",
"\\{372A86D5-CF82-414A-ADBE-6D4EF809B50B}",
"\\{5041550A-0F7E-436A-B85C-C9C98BF77E5F}",
"\\{5EA804FD-5E7A-4405-A638-CAFBD22489D9}",
"\\{81602EAB-622F-4845-BB06-8860FA56C595}",
"\\{899AA056-EBDC-440D-91D0-BFF4F5416A7C}",
"\\{A98543B9-9580-41DD-BC44-C2FDCF32BBE5}",
"\\{CA8CD71A-7992-4226-B949-0D7C9976D2F3}",
"\\{CB63A736-6B85-4456-BC62-156C369B55F4}",
"\\{D8F15717-5D3E-4E8E-82F5-BD568362E689}",
"\\{E00CABCC-3826-4C46-A699-81E9C67081ED}",
"\\{E216B4D8-BCF6-4AC5-B6B1-0040A80F04AD}",
"\\{EF4829DF-C276-4B85-BE94-89FAAAF31B77}",
"\\{OZQM6Y2S-MVZQ-45GU-LLKW-11PYH45SMR60}",
"\\{XP-%%UserName%%}",
"\\{XP-Administrator}",
"\\§root_system§",
"\\0",
"\\0049jeg",
"\\00CD1",
"\\01U79NB5DE2G2T2",
"\\0q8hb5",
"\\1",
"\\1%ADi",
"\\11",
"\\11595",
"\\1323",
"\\2 3",
"\\21ijvcle",
"\\23 Instant Alert",
"\\28077",
"\\2ACA5CC3-0F83-453D-A079-1076FE1A8B65",
"\\2drv",
"\\2ttntcjn",
"\\2YourFace",
"\\3 2",
"\\30249",
"\\360data",
"\\360inst\\360inst_16",
"\\360inst\\360inst_25",
"\\360SE",
"\\3t4jjter",
"\\42816",
"\\4k3c5g0s",
"\\57k1hn3q2",
"\\6",
"\\61473",
"\\61a60",
"\\6235GHJU",
"\\7910.org",
"\\8 0",
"\\88E40675",
"\\A folder",
"\\a5huy45ru",
"\\AAntivirus",
"\\Abosbe",
"\\abssas",
"\\absync",
"\\abusy",
"\\abxp2uele",
"\\Access File\\Worker",
"\\acerunner316",
"\\ACommander",
"\\activedbpack",
"\\Activedefaultlicense",
"\\actmgr",
"\\AD ON Multimedia",
"\\Adbede",
"\\addavesh",
"\\Addblocke",
"\\Additional Guard",
"\\Addobe",
"\\adhhh",
"\\adisp",
"\\Adobbe",
"\\Adobe\\AdobeUpdate",
"\\Adobe\\cdir",
"\\Adobe\\dlldrvvcl57",
"\\Adobe\\plugs",
"\\Adobe\\shed",
"\\Adobe\\vclmsdrv24",
"\\Adobe\\winmsvcl86",
"\\Adobe_Updates",
"\\Adobe32",
"\\Adobe64x4",
"\\Adobee",
"\\Adobeee",
"\\Adobeflash",
"\\AdobeUM\\vclvcldll21",
"\\AdobeUM\\winvcldll54",
"\\adobs",
"\\adprotect nospam",
"\\Adsl Software Limited",
"\\Adsl Software Limited\\WinSpywareProtect",
"\\ADSL Software Ltd",
"\\adsl",
"\\Adssite Advanced Toolbar",
"\\AdSubscribe",
"\\Adtrigger",
"\\Advanced Antispyware Solution",
"\\AdVantage",
"\\AdvTopC",
"\\Adware-Alert",
"\\AdwareAlert",
"\\AdwareBot",
"\\AdwareFREE",
"\\aeuy7hsdrt5u",
"\\afRL9gTXqUeIr",
"\\AGAVA TBP",
"\\Agence Exclusive",
"\\AgentSS",
"\\AgereCommonMgmt",
"\\aidtkcgdd",
"\\aipansaka",
"\\akcbls7jxjd",
"\\akf8dojd",
"\\Aldea",
"\\ALFA Wireless LAN Utility.exe",
"\\AlfaAntiVirus",
"\\alot",
"\\Alpha Antivirus",
"\\AlphaAnt",
"\\AlphaAV",
"\\AlphaWipe",
"\\ambooks",
"\\Ameba22",
"\\amoon",
"\\amoon2",
"\\anatulydller",
"\\Anti-Malware Lab",
"\\Anti-virus-Pro.com",
"\\anti",
"\\Antimalware PC Safety",
"\\AntiMalwareGuard",
"\\AntiMalwareSuite",
"\\AntiSpyBoss",
"\\AntiSpyware Pro",
"\\AntiSpyware2008",
"\\AntiSpywareBot",
"\\AntiSpywareControl",
"\\AntiSpywareDAT",
"\\AntiSpywareMaster",
"\\antiSpywaresuite",
"\\Antivir64",
"\\AntiVirus 2009 plus",
"\\Antivirus 2010 Security Centre",
"\\AntiVirus 2010",
"\\AntiVirus AntiSpyware 2011",
"\\AntiVirus Plus",
"\\antivirus protection 2012",
"\\Antivirus Protection 2012TM",
"\\Antivirus Protection",
"\\AntiVirus Solution 2010",
"\\AntiVirus Studio 2010",
"\\AntiVirus System 2011",
"\\AntiVirus",
"\\AntiVirus_AntiSpyware_2011",
"\\antivirus360",
"\\AntiVirus360Remover",
"\\AntiVirusForAll",
"\\AntiViruspcsuite",
"\\AnVir",
"\\anytven",
"\\apartpop",
"\\APManager",
"\\APMV",
"\\app",
"\\APP#",
"\\aPpA",
"\\appcatlibrary",
"\\appdata",
"\\appDataa",
"\\appdatta",
"\\appdllLang",
"\\AppDTA",
"\\AppleWebusb",
"\\Application Data",
"\\Application\\Steam",
"\\AppPaht",
"\\AppsData",
"\\appwsd8",
"\\archsoft",
"\\archsoftr",
"\\arcomdir",
"\\arename",
"\\ARManager",
"\\arnaudtlse",
"\\arop",
"\\arsinstrun",
"\\arzipexe",
"\\as",
"\\asdlfj3",
"\\asocks2",
"\\ASPNET Hosting Acess",
"\\athan",
"\\atidisp32",
"\\atmctlcmp",
"\\atmmsvcruntime",
"\\atmsp60",
"\\atmxmld9",
"\\attriview",
"\\audiocodec\\DAVID",
"\\audiohddrive",
"\\audiohddrivewin",
"\\audiontcmp",
"\\audionvrsClient",
"\\audiop2psound",
"\\audiorpcClient",
"\\AuShopInfo",
"\\Automated Content Enhancer",
"\\autorat",
"\\AV Protection 2012",
"\\AV1",
"\\AV2010",
"\\AvaFind Dat",
"\\AVDefender2011",
"\\AVDir",
"\\AVGSv",
"\\avicomdg",
"\\avinvwrmulti",
"\\aviwsGlade",
"\\AVOAVO",
"\\AVS",
"\\AVSystemCare",
"\\AVSystemShield",
"\\awServ",
"\\AXPDefender",
"\\AXPFixer",
"\\B3E85FAA-C316-40E0-BB3C-BF07959CAB7A",
"\\B48HJQTX",
"\\badhim",
"\\baidu\\hao123",
"\\Bang.sat-5-20",
"\\BarDiscover",
"\\BarQuery",
"\\barrakoda",
"\\BasicScan",
"\\BBBB",
"\\bbhpk",
"\\bBtzP0ycAiD",
"\\Bc",
"\\Bcceee.",
"\\bcdefg",
"\\Bcool",
"\\bcrdv",
"\\BDL+D",
"\\beerman006",
"\\befefbesbenesn",
"\\bergamot",
"\\Best Antivirus Software",
"\\Best Malware Protection",
"\\Best Virus Protection",
"\\BestBuyer",
"\\BestEstimation",
"\\BestPrediction",
"\\bfgtoolbar",
"\\bflixtoolbar",
"\\bhoinit",
"\\Bif0rost",
"\\biforst",
"\\Bifr",
"\\Bifroost",
"\\bifrosr",
"\\Bifrost",
"\\bifrot",
"\\Bifrott",
"\\BifroXx",
"\\BifSAG",
"\\biglinkband",
"\\Bilder",
"\\BILEVSE",
"\\billbarnett",
"\\binusarathomas",
"\\Biolka",
"\\Bionic",
"\\Bitrix Security",
"\\bits2",
"\\bJgLc01703",
"\\BlackBlood",
"\\Blammi",
"\\BlanchDisc",
"\\blcox",
"\\BlueFlare Antivirus",
"\\blueturtlegamesSA",
"\\bncgy",
"\\boancup",
"\\boank",
"\\boankiller",
"\\boanservice",
"\\bobtaco",
"\\boctkum",
"\\boersoft",
"\\bojbpscju",
"\\bondero",
"\\bootsys",
"\\bProtector",
"\\braddabug",
"\\browseaviruntime",
"\\browsenetClient",
"\\BrowserDiscover",
"\\browserpcGlade",
"\\BrowserZinc",
"\\BthMobilexx",
"\\BTManager",
"\\Buddy Search",
"\\BugsEraser",
"\\BuyNaviAuction",
"\\BVWALGP",
"\\bxodgod",
"\\By ana",
"\\byads0rt",
"\\bytewdownload",
"\\bzipfree",
"\\C-76947-8457-2745",
"\\C-Center",
"\\c11",
"\\C575E8A8-16E2-4C95-AE36-0BA9C90710B0",
"\\cacaoweb",
"\\CaoouupoonIItt",
"\\Cashfiesta",
"\\catactive3D",
"\\Catalyst",
"\\CatDBCommsman",
"\\CatDBcrtext",
"\\catiasdg",
"\\catp2pgfx",
"\\cbnsoulkjs",
"\\cbosuhhxi",
"\\cbpdteuw",
"\\CC",
"\\CCenter",
"\\ccepic",
"\\CCleaner Update",
"\\cclenre",
"\\CComponents",
"\\CdCommonTask",
"\\Ceache",
"\\cfea",
"\\cft",
"\\cGI\\ouOW",
"\\CheeryChickenSA",
"\\cheesebread",
"\\cho",
"\\chowd",
"\\chr0me",
"\\Chrome_updater",
"\\Chrome_Updt",
"\\ciotoli.it",
"\\ckgusoiehkjs",
"\\ckobxomej",
"\\classrider",
"\\cleanboan",
"\\Cleaner2009 Freeware",
"\\Cleaner2009",
"\\cleaninspector20",
"\\CleanPCTool",
"\\CleanUp Antivirus",
"\\CleanupTool",
"\\clearboan",
"\\clicki",
"\\Clickmania",
"\\ClickPotatoLite",
"\\ClickPotatoLiteSA",
"\\CLIENT SERVER RUNTIME PROCESS",
"\\client",
"\\Client\\Logs",
"\\CloudWeb",
"\\clubmember",
"\\cmmeenakshi",
"\\cnbzoj",
"\\cnyuurui",
"\\Codec-C",
"\\Codeclib",
"\\Codecv",
"\\coffeebaba",
"\\cogad",
"\\comaudiod8",
"\\CommFort_server",
"\\commonder",
"\\comodbc3d",
"\\comoqook",
"\\Company\\Product",
"\\completescan",
"\\Computer Defender 2009",
"\\comsys60",
"\\ConfidentUser",
"\\Config",
"\\confMapServices",
"\\conhost",
"\\containscaffeine",
"\\Content Management Wizard",
"\\ContentEraser",
"\\ContraVirus AntiSpam",
"\\Control-Center",
"\\Control Commander",
"\\Control Components",
"\\Control Manager",
"\\ControlCnt",
"\\ContrWare",
"\\cookies\\ie",
"\\coolerboot",
"\\countryselp",
"\\CQaJIviJfrGn",
"\\Cr",
"\\CRF001",
"\\CRLnetdsc",
"\\CRNJEUFU",
"\\crossnetpie2",
"\\crss",
"\\Crusader",
"\\cryptscruntime",
"\\csidpack",
"\\csrss",
"\\cssrs",
"\\CTFMON",
"\\ctl3duptools",
"\\ctlappdrv",
"\\ctlatmruntime",
"\\ctliepack",
"\\ctlwm64",
"\\ctlwssound",
"\\Ctrl-Center",
"\\CtrlCenter",
"\\CtrlCntr",
"\\CtrlComp",
"\\CtrlComponents",
"\\CTXfiHelp",
"\\cuckoo",
"\\cuntslut",
"\\Currnt ver",
"\\Customized Platform Advancer",
"\\cvrss",
"\\CWupdateService",
"\\CwxvBle",
"\\cxvncx",
"\\CYRDxGD",
"\\cysdast",
"\\CztMJfB",
"\\D-2785-7947-8747",
"\\D0otz9bjot",
"\\d0u5k2t3",
"\\d3davilibrary",
"\\d3dfontruntime",
"\\d3dwsmulti",
"\\Dacgee.",
"\\danasegarane",
"\\Darkbyte's Box",
"\\DataProtector",
"\\dataread",
"\\datfiles",
"\\datread",
"\\dbatmsound",
"\\DBControl",
"\\DBdLcOSrSdXpmKfEvs",
"\\dbGLAgent",
"\\dbphy",
"\\dbpxeiuuc",
"\\dbxmlLang",
"\\Dccggc.",
"\\dclogs",
"\\dddok",
"\\ddess",
"\\DealAssistant",
"\\dealcabby",
"\\Dealio",
"\\Deamuzl",
"\\DefaultTab\\DefaultTab",
"\\Defender",
"\\Desktop Security 2010",
"\\Desktop Security",
"\\Desktopicon",
"\\deskws97",
"\\Deus Cleaner",
"\\Deye 4_6",
"\\DezHOST",
"\\dfgfg",
"\\dfltappdmn",
"\\dfudhd",
"\\dfwav",
"\\dg40udyw",
"\\dgeds",
"\\dgYwaFD",
"\\dhelperocx",
"\\dhet2",
"\\dialpass",
"\\dIdNmFn07700",
"\\digifast",
"\\Digital Patrol",
"\\Digital Protection",
"\\dimop",
"\\Dir",
"\\Directcrtapi",
"\\DirectKeyword",
"\\DirectKeyword2",
"\\DirectMainOffice",
"\\DirectMobilesvc",
"\\Directory",
"\\DiscErrorFree",
"\\diskboan",
"\\DiskSizeSaver",
"\\DisplayDriverTEMP",
"\\Djamel",
"\\dll",
"\\dllcatLang",
"\\dlldesk60",
"\\dllhost",
"\\dllsp64",
"\\dllstream50",
"\\dlm",
"\\dmain3",
"\\dmnetlibrary",
"\\dmnvmcDirect",
"\\dmsh32",
"\\dmstoruntime",
"\\dnbxldyq",
"\\dobxkwyyqw",
"\\doctor\\nod",
"\\doctor\\phip",
"\\doctor\\win8",
"\\dotetUpdates",
"\\DoubleD",
"\\Down_LoadGet",
"\\Download and Sa",
"\\download2",
"\\DownLoadGet",
"\\DownloadnSave",
"\\DownloadSave",
"\\doylejoftexas",
"\\Dr HeX",
"\\DriveDefender",
"\\driver.media",
"\\drivers\\downld",
"\\drivers\\etc\\ntfs..",
"\\DRMobj32",
"\\drmrdhkrp",
"\\drops",
"\\drvxslek32k",
"\\ds56irjckt7ovy",
"\\dsaddadsa",
"\\Dual Matching",
"\\dual",
"\\duckload",
"\\dudu",
"\\duelcharge2",
"\\dv6173880x",
"\\dv680820x",
"\\dx10ac",
"\\dx10bac",
"\\dx10backup",
"\\dxasbac",
"\\dxdlls",
"\\DYA_ENATBKFMWMNEANCNP",
"\\DYA_NVHUDVINTJBEDVVKN",
"\\E-32948-2987-28740",
"\\EapGLAgent",
"\\EapPathpnp",
"\\EasyPop",
"\\EasyTime",
"\\ebgcpwqw",
"\\ediconfig",
"\\edxLabs",
"\\eehl",
"\\eghtmldialer",
"\\egowtsjhe",
"\\egroup",
"\\egxosyggs",
"\\eJavaV",
"\\EliteProtector",
"\\elloicomfc",
"\\eMlOo01700",
"\\engel",
"\\enigmabrand",
"\\Enterprise Suite",
"\\entsr",
"\\eoRezo",
"\\eq03dsq",
"\\erhy45eau",
"\\ericfleck",
"\\eromd",
"\\errclean",
"\\Error Safe Free",
"\\ErrorEasy",
"\\ErrorFighter",
"\\ErrorFix",
"\\ErrorInspector",
"\\ErrorKiller",
"\\ErrorRepairTool",
"\\ErrorSmart",
"\\ErrorSweeper",
"\\ErrorWiz",
"\\et_update",
"\\etbkjgfi",
"\\etc",
"\\euite",
"\\EvidenceEraser",
"\\evx.r3x",
"\\ExeceWine",
"\\execuples",
"\\EXEEXE",
"\\exoler",
"\\EXPLARER.EXE",
"\\explorateur",
"\\explorer",
"\\explorer.exe",
"\\explw",
"\\ExxRom",
"\\eyqeo2rq",
"\\eyswpy",
"\\ezLife",
"\\F-123DJ-WDJAD-2223",
"\\f0367yjd",
"\\faberge80",
"\\fabZeQJ",
"\\Facegame",
"\\facemoods.com",
"\\faretoraci",
"\\fast1cwf",
"\\fastad",
"\\FastSave",
"\\favoclicks",
"\\favoclip",
"\\favoricon",
"\\FCSB000063943",
"\\ffmpeag",
"\\fFpFiFi07700",
"\\fhfhhrthrth",
"\\field",
"\\FieryAds",
"\\FileDoumi",
"\\FileDown",
"\\filejoak",
"\\filename",
"\\filepds",
"\\Files\\FileB",
"\\FilterProgram",
"\\finalget",
"\\Findbasic",
"\\FinderQuery",
"\\FindLock",
"\\FindXplorer",
"\\fireboan",
"\\Firefox Temp",
"\\firefox@mozilla.com",
"\\FirefoxUpd",
"\\FirefoxupdatingUp",
"\\FixMenaces",
"\\FixThemNow",
"\\fjudid2",
"\\FKMonitor",
"\\FlashPlayerUpdate",
"\\Flipopia",
"\\Flv",
"\\FlvTube Toolbar",
"\\fndlck",
"\\Folder",
"\\FolderName",
"\\FolderName@O@",
"\\fontactived9",
"\\fontatmgfx",
"\\fontcomd8",
"\\fontperfmulti",
"\\Fontstlibrary",
"\\fordfyTtjf",
"\\forpeople",
"\\FrameWork\\Worker",
"\\freak",
"\\Free RuneScape DDoSer",
"\\FreeAccs.exe",
"\\FreeHotBabesScreensaver",
"\\freestartzipper",
"\\FreeWebToon",
"\\FREEzeFrog",
"\\froot",
"\\fuck",
"\\FUCKYOU",
"\\FunWebProducts",
"\\FUNwfhC",
"\\FunyMall",
"\\fwuxo",
"\\g",
"\\G13ENQVW",
"\\G467LNQV",
"\\GabPath",
"\\gadcom",
"\\GalileoCleaner",
"\\GameRaving Toolbar",
"\\Gatesss",
"\\gbqhf",
"\\gema",
"\\Gencontrol",
"\\General Antivirus",
"\\GeneralInfo",
"\\Genius\\firefox",
"\\GetModule",
"\\gfjbnermbv",
"\\GGeeniusCaooupon",
"\\ggsyysoet",
"\\Ghost Antivirus",
"\\Giblonhx",
"\\GiGa lnc\\GiGa Mini Crypter",
"\\Gmail",
"\\GmailHackerPro_Installer",
"\\gMozilla",
"\\GoAstro",
"\\GoldenAntiSpy",
"\\GoodFile",
"\\Google (TM) Toolbar_32 Service",
"\\Google Talk",
"\\Google\\Googles",
"\\Google\\T-Scan",
"\\Google\\Update\\1",
"\\Google\\Update\\Contemp",
"\\Google\\Update\\Start",
"\\Google\\Youtube BO",
"\\google_udapte",
"\\GoogleGoogle",
"\\GoogleNMore",
"\\GoogleToolbar",
"\\googleui",
"\\GoogleUpdat",
"\\gOoIgGi08505",
"\\Gool",
"\\Gooogle",
"\\Goorma",
"\\GoRecord2",
"\\govindasamy",
"\\gqakue",
"\\grdeveloper",
"\\GreatPrediction",
"\\greenmiler",
"\\grlEnKtFLHSjxGHRoj",
"\\Guard Pro",
"\\GuardSupport",
"\\gudfind",
"\\guyuming",
"\\gwr",
"\\hacked",
"\\hakkkkkha.exe",
"\\handapter",
"\\hantiat6",
"\\HardDriveGuard",
"\\hasc32",
"\\HBLite",
"\\HBLiteSA",
"\\hecta",
"\\Hegcge.",
"\\Help",
"\\helpSched",
"\\henrynguyen",
"\\hepta",
"\\heptalia",
"\\hex-5823-6893-6818",
"\\hhhh",
"\\HiddenDrivers",
"\\hidires",
"\\hidn",
"\\hiHi0LFfZ3gCC9o",
"\\HiSearch",
"\\hjcmer",
"\\hldtg",
"\\hmfypatg",
"\\hMiKm01200",
"\\HMJFZWC",
"\\hoffjert",
"\\Home Malware Cleaner",
"\\Home Safety Essentials",
"\\Host Process for Windows Services",
"\\HostProcess",
"\\hostsvr",
"\\HostWi32",
"\\Hotbar",
"\\Hotbar_Icons",
"\\HotbarSA",
"\\HottieStar Toolbar",
"\\HotTVPlayer",
"\\hsced",
"\\html",
"\\https",
"\\HubHelper",
"\\hubz",
"\\hvGoobb",
"\\hxougu",
"\\i",
"\\i18Pathlib",
"\\i2linzyr",
"\\ialotcfg",
"\\ialotsvc",
"\\iasmapDraw",
"\\iBfHf01306",
"\\icon",
"\\icosa",
"\\IdentitiesWindows",
"\\Iduse",
"\\IE",
"\\ie7",
"\\iecache",
"\\iemate",
"\\ienvmclang",
"\\IEresorce",
"\\IESafer",
"\\iexplorer",
"\\IFavorPop",
"\\ifugpb",
"\\Igfx",
"\\IHelper",
"\\IHG",
"\\ildCfKI",
"\\image.jpg",
"\\iMhQV0m",
"\\iMiCroDriv",
"\\imnothere",
"\\INEDNTL",
"\\InstallBrain",
"\\InstallDir",
"\\InstallDir\\Password",
"\\installShield12",
"\\installus",
"\\Instant Access",
"\\instarrun",
"\\Intelkx Folder",
"\\IntelsXex",
"\\Interboan",
"\\Internet Antivirus 2011",
"\\Internet Antivirus Pro",
"\\Internet Antivirus",
"\\Internet Security Essentials",
"\\Internet Security Suite",
"\\Internet Today",
"\\InternetExplorer",
"\\InternetGameBox",
"\\internett",
"\\inttemp",
"\\iochviewer",
"\\Iplap",
"\\iplus_down",
"\\Ipop",
"\\IQManager",
"\\iRTnQVisO",
"\\Isacut",
"\\isasss",
"\\Itutux",
"\\IUpd721",
"\\IVST Manager",
"\\IWingPop",
"\\Iwvok",
"\\izamain12",
"\\IzYngQyBVxDQNvJiiKSfHa",
"\\J-93219-1923-12901",
"\\jankucera",
"\\janmechtel",
"\\jasamninja",
"\\Java sun",
"\\Java suns",
"\\Java Update Sheduler",
"\\Java Update",
"\\Java\\J",
"\\java20_02",
"\\javaing",
"\\JavaMachine",
"\\Javas",
"\\Javatron",
"\\JavaUpdate.exe",
"\\javaupdater",
"\\JavaUpdates",
"\\JavaUpdating",
"\\JavaUpdtr",
"\\javaupload",
"\\Javaw",
"\\jawtp",
"\\JaydenisALegend",
"\\jBvEhQdr",
"\\jcvihdk",
"\\jdjfhgurnf",
"\\jeffirwin",
"\\jeuad",
"\\Jgosht",
"\\JGzSPlI",
"\\jhdhonza",
"\\ji82l",
"\\jimperry",
"\\JjlDownLoader",
"\\JJYORJi",
"\\JKGF",
"\\jLgfIpH",
"\\jmdDfKI",
"\\Jookz Toolbar",
"\\Jose.ray-3-26",
"\\joyshop02",
"\\jpK84W99",
"\\jrFgBf",
"\\jslguide",
"\\jupter",
"\\jusched",
"\\jvplk",
"\\jzqgooiz",
"\\k-one",
"\\k 36",
"\\k 40",
"\\K479GJKU",
"\\K5DFNTVW",
"\\K7LNUVWX",
"\\kakao2",
"\\Kaspersky_Key_Finder_(KKF",
"\\kbdactiveruntime",
"\\kbdctl50",
"\\kcoggshyxh",
"\\kctmon",
"\\keep",
"\\KEI",
"\\Kelly",
"\\Kellyhuizen",
"\\Kernal",
"\\kesinfoi",
"\\keyloggzz",
"\\keymatch",
"\\KeywordTab",
"\\kikin",
"\\KINyryc",
"\\Kiss_Fucked",
"\\kkk",
"\\kkpa",
"\\kkx4",
"\\kkz",
"\\kloger",
"\\Ksn",
"\\kupdate",
"\\KW",
"\\Kwanzy",
"\\Kwinzy",
"\\KwinzySearch",
"\\KwinzySrch",
"\\kwsafe",
"\\KwYuHVD",
"\\KYL",
"\\l0wsec",
"\\L3G!T-Labs\\jdvs",
"\\L5AKLPSX",
"\\L8r",
"\\lalallalaaa",
"\\LanFile",
"\\Large",
"\\larudainfo22",
"\\LastShopping",
"\\LastSun Ltd",
"\\lclfilcfg",
"\\lclstp32VM",
"\\lgmanger32",
"\\line5",
"\\linematch",
"\\LinkGuide",
"\\linkinside",
"\\liq2qg20",
"\\Live PC Care",
"\\Live Security Suite",
"\\livefloat",
"\\Local Windows\\cpu",
"\\Local Windows\\target",
"\\Local",
"\\Local\\Microsoft\\CurrentVersion",
"\\LocalAccountA",
"\\LocalData",
"\\localesentCMP",
"\\LocalLow",
"\\localntLang",
"\\localsclibrary",
"\\localstlibrary",
"\\lol",
"\\LoopSystem",
"\\Love",
"\\Low",
"\\LPCGSys",
"\\lpcyg",
"\\lPeLRksiOJKINxqxcDoF",
"\\LPJEHCG",
"\\LPNGYCG",
"\\LPONDYCG",
"\\LPORCG",
"\\LPPHPTCG",
"\\LPPYQFMCG",
"\\LPTHNTMCG",
"\\LPTSACG",
"\\LPUOXOCG",
"\\lsass.exe Data",
"\\lsassmin",
"\\lu5yar30",
"\\lua",
"\\LUDLUD",
"\\Lupita",
"\\LvHs4NdkNZW1zK0",
"\\lvsewangzhi",
"\\lwOcxluTOqsZtyHwcllkpMTaFSRhkn",
"\\lZMmJIk",
"\\m",
"\\m\\shared",
"\\macport",
"\\Macromidia",
"\\Macrosoft",
"\\MacroVirus",
"\\magescan",
"\\maghert",
"\\magpop",
"\\mahbot",
"\\MailSkinner",
"\\maldonado",
"\\Malware Catcher 2009",
"\\Malware Destructor 2009",
"\\MalwareBot",
"\\MalwareRemoval",
"\\MalwareRemovalBot",
"\\mapwinruntime",
"\\mapwm32",
"\\marchive",
"\\MarteData",
"\\master",
"\\masterboan",
"\\MateCon",
"\\mattrohlf",
"\\mcnoeig",
"\\MDestrSys",
"\\mdply3d",
"\\media_player3",
"\\MediaPlayer",
"\\medina0",
"\\meetjaydeep3",
"\\memoryky",
"\\MemoThis",
"\\memothispop",
"\\menacerescue",
"\\mendingtool",
"\\meow four dale link",
"\\meow locks dale plan",
"\\Messanger",
"\\Messenger\\Drivers",
"\\MessengerLog 360",
"\\MessengerSkinner",
"\\metalrocker12",
"\\mfccrtEnum",
"\\MgQVzlibwt",
"\\mgyvSoN",
"\\micbrower",
"\\MicOffice",
"\\Micrasoft Player",
"\\Micro",
"\\MicroLab",
"\\MicroLab\\MyEngi",
"\\Micromedia",
"\\micropsoft",
"\\Microsof_Commonds",
"\\microsofft",
"\\Microsoft-Driver-5237-5783",
"\\Microsoft-Update-Service-2568-6479-5400",
"\\Microsoft Core",
"\\Microsoft Corporation\\2007 Microsoft Office system",
"\\Microsoft Corporation\\Microsoft® Windows® Operating System",
"\\Microsoft Login System",
"\\Microsoft Network Host Module",
"\\Microsoft PData",
"\\Microsoft Profiles",
"\\Microsoft Security Essentials",
"\\Microsoft Security",
"\\Microsoft Services",
"\\Microsoft Softwares Updater",
"\\Microsoft Task Service",
"\\Microsoft Users",
"\\Microsoft Windows App",
"\\Microsoft Windows Defender",
"\\Microsoft Windows",
"\\Microsoft\\_ZZZZCertifiededd",
"\\Microsoft\\Address Book\\autofmt.exe",
"\\Microsoft\\Address Book\\scardsvr.exe",
"\\Microsoft\\bfFfqkDz",
"\\Microsoft\\bin\\w32pl",
"\\Microsoft\\CCHACK MD5",
"\\Microsoft\\Conpates",
"\\Microsoft\\Crypto\\DES64v5",
"\\Microsoft\\Do",
"\\Microsoft\\dtPaper",
"\\Microsoft\\dtsc",
"\\Microsoft\\DVX",
"\\Microsoft\\FineTop",
"\\Microsoft\\firefox",
"\\Microsoft\\gczevafla",
"\\Microsoft\\Google",
"\\Microsoft\\Hostprozess fur Windows-Dienste",
"\\microsoft\\iehelper",
"\\Microsoft\\InSets",
"\\Microsoft\\Installer\\{19644868-3D1B-4017-AFBD-23A5F14F98BC}",
"\\Microsoft\\Installer\\{3E7402FC-C3F1-428D-AE03-D88F8DD1AF6F}",
"\\Microsoft\\Installer\\{54B462E4-0FBC-487E-A298-4071E19EBB70}",
"\\Microsoft\\Installer\\{C5FB8CD0-37DF-407E-8618-73B188201CCD}",
"\\Microsoft\\Installer\\msupdates",
"\\Microsoft\\Ipbyfpy",
"\\Microsoft\\Iso64",
"\\Microsoft\\Killerr",
"\\microsoft\\leeni4",
"\\Microsoft\\Lzapnmnm",
"\\Microsoft\\Media Index\\Drivers",
"\\Microsoft\\Media Player\\Licence",
"\\Microsoft\\Messenger",
"\\Microsoft\\Microsoft",
"\\Microsoft\\msdlldrv47",
"\\Microsoft\\MSDN\\7.0\\index\\á\\fixed",
"\\Microsoft\\Network\\DLLs",
"\\Microsoft\\nexus20",
"\\microsoft\\office\\system",
"\\microsoft\\office\\userdata",
"\\Microsoft\\Office15",
"\\microsoft\\pctools",
"\\Microsoft\\pejedih",
"\\Microsoft\\rundownplay",
"\\Microsoft\\SD\\L",
"\\Microsoft\\SmartTool",
"\\Microsoft\\svchost",
"\\Microsoft\\tvxbk24",
"\\Microsoft\\VfxdSys Drivers",
"\\Microsoft\\W6health",
"\\Microsoft\\webpass",
"\\Microsoft\\WinCache",
"\\Microsoft\\WindowEzSearch",
"\\Microsoft\\Windows Ez2pop",
"\\Microsoft\\Windows Firewall",
"\\Microsoft\\Windows linkplus",
"\\Microsoft\\Windows\\{10120012-0120-1100-1001-00110011}",
"\\Microsoft\\Windows\\{SSSPUNLQ-NLEJ-AEJO-QVHL-15589789}",
"\\Microsoft\\Windows\\DataProtector\\Ant",
"\\Microsoft\\Windows\\dllcache",
"\\Microsoft\\Windows\\Microsoft Windows Update",
"\\Microsoft\\Windows\\plugin",
"\\Microsoft\\Windows\\User Account Control",
"\\Microsoft\\Windows\\UserClass",
"\\Microsoft\\Windows\\windir",
"\\Microsoft\\Windows\\Windows SwFish32",
"\\Microsoft\\Windows\\WinHost",
"\\Microsoft\\winsrv64",
"\\Microsoft\\WinTools",
"\\Microsoft\\wuauclt",
"\\Microsoft\\wwuozr",
"\\Microsoft\\Xeylrh",
"\\Microsoft\\zsiynw",
"\\Microsoft\\Zxkohqlp",
"\\microsoft_caches",
"\\Microsoft_Update_2001",
"\\Microsoft_Updater",
"\\Microsoft_Updates",
"\\Microsoft_Updates_2011",
"\\Microsoft_Updates_2011_2012",
"\\microsoft257",
"\\microsoft334",
"\\microsoft38",
"\\MicrosoftCriticalSecurity",
"\\MicrosoftOffiece",
"\\Microsofts",
"\\MicrosoftSafe",
"\\MicrosoftServicesWin",
"\\MicrosoftSystems",
"\\MicrosoftUpdater",
"\\MicrosoftWindows",
"\\Microsoftz",
"\\Microssoft",
"\\MicroST",
"\\MicroUpdat",
"\\micrrosoft",
"\\Micrsoft",
"\\minetalop",
"\\mingxumsft",
"\\Mini Search",
"\\Minoral",
"\\MiserXPlayer",
"\\Miswrosoftzs",
"\\mlog",
"\\mm-archive",
"\\mm",
"\\mmcbrowse97",
"\\mmck",
"\\mmcnt97",
"\\mmcwinDirect",
"\\mn-archive",
"\\mnrhost",
"\\moaace",
"\\moayadmal",
"\\MobinSkills",
"\\ModenKuc",
"\\Modules",
"\\moka",
"\\Montorgueil",
"\\Moz1",
"\\Mozarella",
"\\Mozilla\\Extensions\\{ec8030f7-c20a-464f-9b0e-13a3a9e97384}\\textlinks@gamevance.com",
"\\Mozilla\\Extensions\\ExtAccelerate",
"\\Mozilla\\Firefox\\Core",
"\\MozillaSoft",
"\\MozinSpons",
"\\Mp3Tube Toolbar",
"\\MPGfInl",
"\\MPK",
"\\mplf",
"\\MpMsEngX64",
"\\Mr_CF",
"\\Ms Office Agent",
"\\MS",
"\\MS.MSDNQTR.v90.ru_1058_MValidator",
"\\Ms_dir_",
"\\MSA",
"\\MSBV4",
"\\MSBV5",
"\\msconfig",
"\\MSDCSC1",
"\\MSef32",
"\\MSICRD",
"\\msiexeca.exe",
"\\msngr",
"\\msnmessanger",
"\\msnmsgr",
"\\msnmsgrs.exe",
"\\MSoft",
"\\msplyi2d",
"\\msplyi4d",
"\\msplyid",
"\\mspotinc",
"\\msrrasLang",
"\\msservice",
"\\MSupdt",
"\\msuwarn",
"\\msvcdmCMP",
"\\msvd32srv",
"\\msvmon32l",
"\\mswd",
"\\msxmlctlDirect",
"\\msxmlmapdirect",
"\\multicode",
"\\MultiDownload",
"\\murtazagandhi",
"\\My Security Engine",
"\\My Security Shield",
"\\My Security Wall",
"\\My Supervisor",
"\\myCleanerPC",
"\\MyDefencePro 4.0",
"\\MyFolder",
"\\MyGet",
"\\MyIEData",
"\\myPic.exe",
"\\mziparch",
"\\N1",
"\\n2lcqdt0",
"\\N9u5c",
"\\Name",
"\\Namours Wow",
"\\nanokeybuilder",
"\\nanolink",
"\\nanosequence",
"\\nanoshop",
"\\nanumiservice",
"\\narchive",
"\\nbt",
"\\ncapexc",
"\\nCkLoJd07700",
"\\NdTVNm",
"\\nede",
"\\nederap",
"\\Need Files",
"\\nelson2010",
"\\netable8",
"\\NetHome",
"\\NetMon",
"\\NetNucleous",
"\\NetNucleous\\ActiveCollector",
"\\NetPumper",
"\\NETT",
"\\netzn",
"\\Newatl",
"\\NewBack",
"\\newxx",
"\\nfo",
"\\NfzTNDirrp",
"\\NHZWscntpBSTo",
"\\NI.GSCNS",
"\\nidle",
"\\nigger",
"\\nightupdate",
"\\NissWeb",
"\\nitinmala",
"\\NMLOG",
"\\nnsss",
"\\No",
"\\nodechtwo",
"\\nol",
"\\nona",
"\\nonorisrez",
"\\Noroeste",
"\\NosMost",
"\\Notepad.exe",
"\\NowayVirus",
"\\nsv",
"\\nswide",
"\\ntappdrv",
"\\ntatm50",
"\\NtBlckr",
"\\ntias64",
"\\NTRTscan",
"\\ntshdg",
"\\ntspecd",
"\\ntstream97",
"\\nviedia",
"\\nvrsctl97",
"\\nvrsdmruntime",
"\\nvwrfont50",
"\\nvwroleClient",
"\\nvwrspd9",
"\\nvwrsqCMP",
"\\nvwrstream60",
"\\NYSkUqalqnyQemnwVQ",
"\\NZellTV",
"\\O14",
"\\OAV",
"\\Object_inside22",
"\\oceantwelve",
"\\octa",
"\\odbcactivepack",
"\\odbckbd32",
"\\OfferBox",
"\\oHSkHvF",
"\\OK",
"\\Okel",
"\\Omega AntiVir",
"\\oneclickservice",
"\\OnlinePCGuard",
"\\onsup",
"\\OpenCloud Antivirus",
"\\OpenCloud Security",
"\\OpenShopper",
"\\OpenTab",
"\\oplsvc",
"\\opseter",
"\\optimaspeed",
"\\Orator",
"\\ortej",
"\\ox0lfpew",
"\\oxygener",
"\\p2pbrowseLang",
"\\p2psys64",
"\\p4p",
"\\P68KPRST",
"\\P9AFMUXY",
"\\pach",
"\\PadsOPZ",
"\\palstech",
"\\pantiSpyware09.com",
"\\pasusbord",
"\\paulkimmel",
"\\PAV",
"\\PAYMYRENT",
"\\PC-Antispy",
"\\pc-care3",
"\\PC-Cleaner",
"\\PC Clean Pro",
"\\PC Live Guard",
"\\PC Security 2011",
"\\PC Security Guardian",
"\\PC Security",
"\\PC",
"\\pc\\faq",
"\\PCAntiMalware",
"\\PCAntiVirusPro",
"\\PCenter",
"\\PCFix",
"\\PCHealthKeeper",
"\\PCLGSys",
"\\PCM Defender",
"\\PCommander",
"\\PCPrivacyDefender Freeware",
"\\PCPrivacyTool",
"\\PCQWQXLG",
"\\PCROAULTLG",
"\\PCSecureSystem",
"\\PCSuperCharger",
"\\PCTotalDefender",
"\\PCTurbo Pro Free",
"\\PCVirusless",
"\\PCXSTXNJELG",
"\\pdYoKsgH",
"\\pentalia",
"\\perfnvwr64",
"\\perfsqdrv",
"\\perfsyssound",
"\\perfwsruntime",
"\\Personal AntiVirus",
"\\Personal Internet Security 2011",
"\\Personal Security Sentinel",
"\\PersonalAntiSpy",
"\\PersonalAV",
"\\Php",
"\\PiaCkNsaavoeaItt",
"\\PickaVamMaterina2",
"\\PickaVamMaterina3",
"\\picsvr",
"\\pidle",
"\\pinter",
"\\pixelsk",
"\\pLan",
"\\platinum",
"\\Platrium",
"\\PlatriumSA",
"\\PlatriumWeather",
"\\plljoaT",
"\\PlusLineGO",
"\\PnPDeviceMon",
"\\PnPDeviceMonitor",
"\\poinbag",
"\\PoMobile",
"\\pord32",
"\\Presto TuneUp",
"\\PriceGong",
"\\pridl",
"\\Privacy Center",
"\\Privacy components",
"\\Privacy Redeemer",
"\\Privacy Watcher",
"\\privacyclick",
"\\PrivacyConductor",
"\\PrivacyControl",
"\\PrivacyGuard",
"\\PrivacyWarrior",
"\\PRMQZ5J8",
"\\Propellerhead Software\\ReCycle",
"\\Properties",
"\\Properties\\Work",
"\\Properties\\Worker",
"\\PropMgrAsync",
"\\ProtectHD",
"\\protectingtool",
"\\ProtectionComplete",
"\\ptidl",
"\\ptTtFyRO",
"\\pubfilntf",
"\\puchi",
"\\pulsmint",
"\\Pupaotn",
"\\Purchased",
"\\purecoaix",
"\\PzVBpMbeCfohtKd",
"\\qband",
"\\qmacro\\temp\\3F3F3F3F3F3F3F3F3F3F3F3F3F3F",
"\\QUAD Backups",
"\\QueryBrowser",
"\\QueryExplorer",
"\\QueryScan",
"\\QueryService",
"\\QuestBasic",
"\\QuestBrowse",
"\\QuestBrowser",
"\\QuestBrwSearch",
"\\QuestDns",
"\\QuestResult",
"\\QuestScan",
"\\QuestService",
"\\QuestUrl",
"\\QuickDownloadPack",
"\\QuickNetSupport",
"\\QuickZone2",
"\\QW2010",
"\\R56DEFTY",
"\\Rabio",
"\\RainStorm",
"\\Rapid Antivirus",
"\\RapidGet",
"\\rasole64",
"\\ratamahata",
"\\raymund",
"\\Razer\\Worker",
"\\RD Platinum v5.0",
"\\real-con",
"\\real player",
"\\Real Windows Folder",
"\\realsafe\\qwf",
"\\Realtekss",
"\\Recycle",
"\\RECYCLER",
"\\recyclerr",
"\\RedLabells",
"\\redload",
"\\RedShotss",
"\\Reg-Tool",
"\\regdite",
"\\regedit",
"\\RegFixPro",
"\\RegistryBot",
"\\RegistryClever",
"\\RegistryFox",
"\\RegistrySmart",
"\\regsdkrl32",
"\\RegSweep",
"\\RegTool",
"\\Remote",
"\\Repay",
"\\ResultBar",
"\\ResultBrowse",
"\\ResultBrowser",
"\\ResultDns",
"\\ResultScan",
"\\ResultTool",
"\\ResultUrl",
"\\rewwedx",
"\\rfgerg",
"\\rimosyrez",
"\\rip",
"\\RiVZyZkewt",
"\\rklp",
"\\rmhcxsn",
"\\rmx32",
"\\rndl64",
"\\rolypop",
"\\RootSys",
"\\rpcatm97",
"\\rpcwinGlade",
"\\Rsbot2-27",
"\\RST Antivirus 2010",
"\\rst6is56t67",
"\\rstodifu",
"\\ruarchive",
"\\RubarEngine",
"\\RULkNsq",
"\\rundll32",
"\\Runescape",
"\\rushmore",
"\\S-1-5-31-1286970278978-5713669491-166975984-320",
"\\S-3685-5437-5687",
"\\S24",
"\\S567KMNQ",
"\\s8cja",
"\\sacache",
"\\sacache\\7",
"\\sacfilter34",
"\\sadfasdfasdf",
"\\Safe",
"\\SafeHardDrive",
"\\SafePCTool",
"\\SalesMon",
"\\salesmonitor",
"\\Samples",
"\\SanctionedMedia",
"\\sansunglg",
"\\SaoveAs",
"\\sarinst",
"\\saropix600",
"\\saurai",
"\\SaveByClick",
"\\saypoint",
"\\SBSi\\funkeyS",
"\\sbsndmf",
"\\SBUSA",
"\\ScanBasic",
"\\ScanQuery",
"\\scdata",
"\\SCleaner",
"\\scottlewis",
"\\scsdatb",
"\\scv",
"\\scvhost",
"\\sdcbbc",
"\\sdchcf",
"\\sdctade",
"\\sdv",
"\\Search-NewTab",
"\\searchfree",
"\\searchma",
"\\searchqutb",
"\\searchtoolbarcorp",
"\\SEC",
"\\Secure-Soft AV",
"\\Secure-Soft Bot",
"\\Secure-Soft Stealer",
"\\Secure Solutions",
"\\SecureExpertCleaner",
"\\SecurePCCleaner",
"\\SecuriSoft SARL",
"\\Security Antivirus",
"\\Security Essentials 2011",
"\\Security Essentials Ultimate Pack",
"\\Security Guard",
"\\Security Inspector 2010",
"\\Security Master AV",
"\\Security Master",
"\\Security Monitor 12",
"\\Security Monitor 2012",
"\\Security Solution 2011",
"\\Security Solution 2012",
"\\Security Solution",
"\\Security Solution1",
"\\Security Solutions 2011",
"\\Security_Solution_2011",
"\\Security2009",
"\\SeekApp",
"\\Seekdns",
"\\seekeen",
"\\SeekService",
"\\semanatiba",
"\\sendismem0",
"\\server",
"\\serverKL",
"\\service.exe",
"\\service2",
"\\ServiceExtras",
"\\Sesty",
"\\Settingss",
"\\SetupMalwareRemoval",
"\\SevenLink",
"\\sfsdatq",
"\\sFyQzWG",
"\\sgftyjk",
"\\sgrunt",
"\\shactivesound",
"\\ShamrockSpringSA",
"\\share helper",
"\\Share",
"\\shavbjki",
"\\shdcore32mgr",
"\\shddatq",
"\\shekpfr",
"\\Sheliks.exe",
"\\sheujrki",
"\\shntslh",
"\\ShopGateAuction",
"\\ShopperReports3",
"\\shoppingad",
"\\ShoppingReport",
"\\ShoppingReport2",
"\\shoppinguard.com",
"\\shotjumb",
"\\showlink",
"\\shrpcpack",
"\\shsqasw",
"\\shwmClient",
"\\silin",
"\\simpcvt",
"\\siz",
"\\Sizsly",
"\\Skipe",
"\\skrype",
"\\Sky-Banners",
"\\skypee",
"\\slave",
"\\sliatekit",
"\\smapcore17",
"\\Smart-Ads-Solutions",
"\\smart-pop",
"\\Smart-Shopper",
"\\Smart Engine",
"\\Smart Internet Protection 2011",
"\\Smart Security",
"\\Smart Virus Eliminator",
"\\SmartBar",
"\\SmartDefender PRO",
"\\smartfinder",
"\\SmartShopper",
"\\SMBRTAV",
"\\SMDYISJKAV",
"\\smes",
"\\SMICFD",
"\\SMILAV",
"\\Sms Activator",
"\\smshotadd56",
"\\SMVESys",
"\\snkbot42",
"\\sockz",
"\\softarch",
"\\SoftConsulting",
"\\softdocumentxlb10",
"\\softdocumentxlb14",
"\\softdocumentxlb24",
"\\SoftLand Ltd",
"\\Softmsn",
"\\SogouExplorer",
"\\Solt Lake Software",
"\\sorethd",
"\\sp",
"\\sp1",
"\\SpaceQuery",
"\\spagna",
"\\SpamBlocker",
"\\SpamBlockerUtility",
"\\SpamBlockerUtility_Icons",
"\\SpamNuker",
"\\sparknia",
"\\SpeedDownload",
"\\SpeedRunner",
"\\SPHZE128",
"\\spool",
"\\spoolsv",
"\\Spruce",
"\\Spruce\\WinCheck",
"\\Spy Protector",
"\\SpyBossProFull.msi",
"\\Spycar",
"\\SpyFighter",
"\\SpyFree 3.5",
"\\SpyGuarder",
"\\SpyGuardPro",
"\\spyprotector",
"\\Spyware Fighter",
"\\SpywareBot",
"\\SpywareRemover",
"\\SpywareRemover2009",
"\\sqnvrsdrv",
"\\sr45iu56u",
"\\srcheng",
"\\srjolew",
"\\srtserv",
"\\srvprc",
"\\srvsms",
"\\ss",
"\\SS_Check",
"\\SSaaveSAle",
"\\SSaveAs",
"\\SSHTL",
"\\Start",
"\\startup",
"\\Starware",
"\\Starware316",
"\\stdeskLang",
"\\Stend",
"\\stolocalruntime",
"\\stoperfDraw",
"\\storage1",
"\\Storageprotector",
"\\Storm\\update\\%windowsname%",
"\\stoshclient",
"\\streamctl3dsound",
"\\Street-Ads",
"\\Strong Malware Defender",
"\\sub",
"\\subgatelong",
"\\SudoPlanet",
"\\Sukoku",
"\\sumMoTR",
"\\Sun\\unistall",
"\\SunKB",
"\\SunOS",
"\\SurfAccuracy",
"\\Surround Software Solutions",
"\\sv2hlqch",
"\\svc",
"\\Svccost",
"\\svcdatw",
"\\svchost",
"\\svchost.exe",
"\\Svchost22",
"\\svchost32",
"\\svchost64",
"\\Svchosts",
"\\SvcHostt",
"\\svchosttt",
"\\svchostwindows",
"\\svckl",
"\\svcost",
"\\svddatq",
"\\svdgrba",
"\\svghanx",
"\\svhdatq",
"\\svhost",
"\\svhust",
"\\svnMpUS",
"\\svsdata",
"\\svsqasw",
"\\svuohea",
"\\svvhost",
"\\SwissRoll",
"\\swkws",
"\\sWPDNSE14",
"\\Swsooue",
"\\swsqasw",
"\\Sxcp\\svchost.exe",
"\\syetem",
"\\Sym32",
"\\syn",
"\\syrkglh",
"\\sys",
"\\sys1",
"\\sys32",
"\\sys32s",
"\\sysapp",
"\\sysapp32",
"\\sysbrowseclient",
"\\SysCleaner",
"\\syscmss.exe",
"\\sysctl3ddg",
"\\sysdasw",
"\\sysdat",
"\\sysdat.",
"\\sysdata",
"\\sysdatr",
"\\sysdats",
"\\sysesentDirect",
"\\SysFld",
"\\sysk",
"\\syslog32",
"\\SysLogger",
"\\SysManager",
"\\sysmapd9",
"\\sysnvrssound",
"\\Sysobjnet",
"\\sysproc64",
"\\syssnt",
"\\sysss",
"\\syst",
"\\syst32",
"\\SystdowsService",
"\\SystdowsSffervice",
"\\System 32",
"\\System Data Configuration",
"\\System Data",
"\\System Defender",
"\\System Doctor Free",
"\\System File\\Winlogin",
"\\system of pc",
"\\System Process Handler",
"\\System Smart Security",
"\\system\\verona",
"\\System23",
"\\system32",
"\\SYSTEM32update",
"\\System34",
"\\System86",
"\\SystemDefender",
"\\Systemerrorfixer",
"\\SystemFeed",
"\\systemfile",
"\\SystemHelper",
"\\systemin",
"\\SystemMapserv",
"\\SystemOptimizer2008",
"\\SystemPro",
"\\SystemProc",
"\\SYSTEMRESTORE",
"\\Systems",
"\\Systems\\ACDSee\\Igebo.ddf%SESSIONNAME%",
"\\SystemStore",
"\\SystemWindows",
"\\Systemx86",
"\\systemxx",
"\\systhem",
"\\systim32",
"\\Sysutils_Update",
"\\syswin",
"\\syswinGlade",
"\\Syysix",
"\\t",
"\\t3e0ilfioi3684m2nt3ps2b6lru",
"\\tabbrowsing",
"\\TabDiscover",
"\\tabquery",
"\\tacoloverg",
"\\Tally software LTD",
"\\tapiapiplugin",
"\\tarantula",
"\\target folder",
"\\Target Marketing Agency",
"\\Task Mngr",
"\\tasker",
"\\taskhosts",
"\\taskjmgrr",
"\\Taskmgr",
"\\taskmgr.exe",
"\\taskmsr",
"\\taskre",
"\\taskset",
"\\tatss",
"\\tazebama",
"\\tbjfg",
"\\tcpMapUsb",
"\\td",
"\\Tec",
"\\tecmod",
"\\TeeveeWatch",
"\\Tencent\\AXSEF",
"\\Tencent\\CXSEF",
"\\terningupp",
"\\test",
"\\testmashit.exe",
"\\Textual Content Provider",
"\\theaskingman",
"\\TheBflix",
"\\Thinstall\\svchos",
"\\ThreatNuker",
"\\THUNK HOLE CAKE",
"\\Tiger Install",
"\\tissuee",
"\\tIVrzONyx0",
"\\TKT",
"\\tmp-3",
"\\TNfcyVt",
"\\toastpop",
"\\Tool-Store-Stealer",
"\\Tool-Store Reloaded",
"\\Toolbar4",
"\\toplusband",
"\\topsyncdoc",
"\\total_pack",
"\\Toulethallow",
"\\Touletwhrite",
"\\tradio",
"\\tradio_updater",
"\\trinatelink",
"\\tRmLDzLc",
"\\Trojansfilter",
"\\truepod",
"\\trumisore",
"\\TrustedAntiVirus",
"\\TrustedProtection",
"\\TrusteerHelp",
"\\tszyz0nh",
"\\Twain",
"\\twain_32",
"\\tx",
"\\U-2535-6853-8747",
"\\ubot",
"\\ubotcompile47320",
"\\UdCiMbI",
"\\uFast Download Manager",
"\\ufr_files",
"\\uhc",
"\\uioqzp",
"\\ULTGSys",
"\\Ultimate Cleaner",
"\\Ultimate Defender",
"\\Ultimate Fixer",
"\\Ultimate System Guard",
"\\Ultra Antivir2009",
"\\ultra",
"\\um84WwQXSgj",
"\\Unilessss",
"\\Uninstall_Security",
"\\UnionTablettt",
"\\Unoeilsurtoi",
"\\Update's",
"\\update\\bot",
"\\Update10",
"\\updaterc",
"\\Updateregulatorx32",
"\\updates",
"\\Updatez",
"\\upsqCMP",
"\\Uptana",
"\\UqhCBsmkkJeHPx.exe",
"\\url",
"\\userComms80",
"\\UserGrupo",
"\\usrdesk60",
"\\Usulta",
"\\utcry",
"\\UtilEventWan",
"\\utilnara",
"\\utilndown_n",
"\\utilpds",
"\\UuNnTtIiL",
"\\Uwored",
"\\uWsrTBSEI",
"\\V@G",
"\\validzip",
"\\VAP",
"\\vBifrost",
"\\vcdui",
"\\vcry",
"\\vcxydsiager",
"\\vDdevwoE",
"\\veBfithpSAb.exe",
"\\VHTBCLCVLROOK",
"\\VichatterX",
"\\VideoEgg",
"\\vidmon",
"\\VidShake",
"\\vigaze",
"\\viri",
"\\Virus Alarm",
"\\Virus Doctor",
"\\Virus Melt",
"\\Virus Shield 2009",
"\\Virus Sweeper",
"\\vlbrz2u4",
"\\Volcano Security Suite",
"\\VooMuuSA",
"\\VSCodecPRO",
"\\VTVQWMZX",
"\\vu",
"\\vu931",
"\\VundoFixTool",
"\\Vvtbrse",
"\\vWord",
"\\VzWJrYnjU",
"\\w4si6r57i",
"\\wangdun",
"\\WCw",
"\\wDtecwD",
"\\wdxsrvxl",
"\\WeatherDPA",
"\\Web Search Operator",
"\\Web__Rebates",
"\\Webalta",
"\\webFlashUp",
"\\WebMediaPlayer",
"\\webnd",
"\\webnetad",
"\\website.com",
"\\Weemi",
"\\welylive",
"\\WerPingGood",
"\\WHelp",
"\\WhereSphere",
"\\whitepixel",
"\\wiaservc",
"\\WideSearch",
"\\willarchive",
"\\WIN-0035-7453-6114",
"\\WIN-2045-7453-2214",
"\\Win-Vice",
"\\Win Antivir 2008",
"\\Win Updt",
"\\win",
"\\WIN00CD1A40",
"\\win32",
"\\win992",
"\\winaddtool",
"\\Winamps",
"\\WinAnonymous",
"\\winantispyware 2007",
"\\winapp\\Winapp for Windows",
"\\WinbioTools",
"\\winbiz",
"\\Winbooterr",
"\\WinButler",
"\\winclb64",
"\\Wind Optimizer",
"\\WinDe",
"\\windef",
"\\WinDefe",
"\\WinDefence",
"\\windefender",
"\\WinDefender\\Windows Rundll32",
"\\WinDefendersss",
"\\windefenderV",
"\\WINdefnder",
"\\Windir",
"\\WinDir.Cmos",
"\\WinDir\\Atpor",
"\\Windirsv",
"\\windlog",
"\\windol",
"\\windos mac",
"\\Window{Upda2e",
"\\windowatmg",
"\\WindowDefenderProgram",
"\\WindownUpdate",
"\\windows-updater",
"\\Windows (TM) Update Service",
"\\Windows (TM) Updates",
"\\Windows Additional Guard",
"\\Windows Audio Driver\\audihod",
"\\Windows Def",
"\\Windows Defender",
"\\windows defender1",
"\\Windows Defenders",
"\\Windows Enterprise Defender",
"\\Windows Enterprise Suite",
"\\Windows Explorer",
"\\Windows firewall agent system",
"\\Windows Guard Pro",
"\\Windows Internet Name Service",
"\\Windows PC Defender",
"\\Windows Protection Suite",
"\\Windows Registry",
"\\Windows Rundll32",
"\\Windows Security Server",
"\\Windows Security Suite",
"\\windows security",
"\\Windows Services",
"\\Windows System Defender",
"\\Windows System Suite",
"\\Windows Task Manager",
"\\Windows Update",
"\\Windows Updats",
"\\Windows Wizard",
"\\windows",
"\\Windows\\Logger",
"\\Windows\\sluts",
"\\windows18",
"\\Windows231",
"\\windows33",
"\\WindowsApplication1",
"\\windowsclick",
"\\WindowsData",
"\\WindowsDef",
"\\WindowsDefender",
"\\WindowsFirewall",
"\\WindowsFirewalls",
"\\WindowsInternet",
"\\WindowsMicrosoftUpdater",
"\\WindowsPurchaseHelper",
"\\WindowsReg",
"\\WindowsSecurity 3.0.1",
"\\WindowsSecurityApplication",
"\\WindowsService",
"\\WindowsShield",
"\\WindowsTN",
"\\Windowsupdate",
"\\WindowsUpdater2",
"\\WindowsUpdatezz",
"\\windowviewcon",
"\\windowx58h",
"\\windrvswld",
"\\windrvswld83",
"\\Windupdate",
"\\Windupdt",
"\\WindUpdtes",
"\\WindUptres",
"\\windws",
"\\winelwske95",
"\\WinError",
"\\WinFix Master",
"\\winggo",
"\\WINGPSys",
"\\WingSearch",
"\\WinIFixer.com",
"\\winjwws92",
"\\WinkZink",
"\\winlock.exe",
"\\winlog inlalallalaaa",
"\\winlog",
"\\winlogn",
"\\Winlogon",
"\\winlogonr",
"\\winlsp",
"\\winnvwrlibrary",
"\\winpcdoctor",
"\\winpds2",
"\\winpdsutil",
"\\winpnp",
"\\winrar",
"\\winrecbin",
"\\WinRege",
"\\winrig",
"\\WinRoq",
"\\winsafe",
"\\WinSecureAv",
"\\WinSecurity360",
"\\WinsPop",
"\\WINSPSys",
"\\WinSpyControl",
"\\WINSSSys",
"\\WinSxSey",
"\\WINSYS32",
"\\WinSyst",
"\\WinTool",
"\\WinUpd",
"\\WinUpd.",
"\\winupdat",
"\\winupdate",
"\\winupdate8",
"\\WinUpdater",
"\\WinUpdates",
"\\WinUpdatr",
"\\WinUpdats",
"\\winupdt",
"\\WinUpdtr",
"\\WinUpdts",
"\\winuppdate",
"\\winUserdsc",
"\\winusrdrv",
"\\winvv",
"\\WinwebSecurity",
"\\winwin",
"\\WinX Security Center",
"\\winxarj",
"\\WinXDefender",
"\\WinXProtector",
"\\winxrar",
"\\winxzip",
"\\winyi",
"\\winzipsoft",
"\\WinZr",
"\\wisebase\\wiseie",
"\\wiseie_downer",
"\\wiw",
"\\wlem61omg",
"\\WLIDSCO",
"\\wMEoWYsVaoyTg",
"\\WmiModules",
"\\wmiPadMusic",
"\\wmiPadnt5",
"\\wmnetgfx",
"\\wmpnetwk",
"\\wmrpcd9",
"\\wmstreamsound",
"\\wnlogon",
"\\WO8",
"\\Wol\\IrDI",
"\\WolfRam AntiVirus",
"\\womanbayc",
"\\wordl",
"\\world-archive",
"\\world of crash",
"\\worlduarchive",
"\\worldxarchive",
"\\WORM",
"\\wPCAH1",
"\\WPCDSys",
"\\wrqwrw",
"\\wsclbClient",
"\\wsnpoem",
"\\wss2012",
"\\WSYSSSys",
"\\WtmCopyProtect",
"\\wupdate",
"\\wwww",
"\\Wx Shop2Win",
"\\wxDfast",
"\\Wyeke",
"\\wyyo",
"\\WZRqTxv",
"\\x10bac",
"\\x22",
"\\xarchive",
"\\Xbins",
"\\XC-SSU-2741-UHSID",
"\\xebzzotvqmm2tyeub1zw2jtpajpzynxs2",
"\\Xenocode\\Sandbox\\Bifrost Hack By M.T.J .exe",
"\\Xenocode\\Sandbox\\iGrabber",
"\\xercle",
"\\xgs",
"\\xHCfvOi",
"\\XintaCasa",
"\\XLJDVSoLjp",
"\\xllloader31",
"\\xmlaudioGlade",
"\\xmlie64",
"\\xmlmap97",
"\\xmlp2pGame",
"\\xors32",
"\\xpcom64",
"\\XPdefender",
"\\xpiastools",
"\\xpmap64",
"\\XpsEPSC",
"\\xspecmod",
"\\xssend2",
"\\xvic",
"\\xwwsnoo",
"\\xx\\xx",
"\\XXqMLit",
"\\xxt3adbcobrc1b3bhhqmaiy2cgoz3pdm2",
"\\xXx",
"\\y01kqwaf",
"\\y3onF4amHsJfLg",
"\\yBsSuZX",
"\\Ybvu",
"\\yCtSvaY",
"\\yesboan",
"\\yhmgd",
"\\ylog",
"\\Your Protection",
"\\Yourprivacyguard",
"\\yPeRgCsxvfQM24Row4",
"\\ys",
"\\YSOIFRMpkDscfvrioo",
"\\YUM",
"\\yxz",
"\\zack",
"\\Zango TvTimes",
"\\Zango",
"\\ZangoSA",
"\\zApps",
"\\zarchive",
"\\ZcTsVzx",
"\\zdsafnafo",
"\\zgi0w4fq",
"\\Zinaps7",
"\\Ziniky",
"\\ZinkSeek",
"\\zipexecute",
"\\zipfreerun",
"\\ZipIcon",
"\\zipportrun",
"\\zipustartfree",
"\\zipvalid",
"\\zitian",
"\\zmb4xlgx",
"\\zrtzrto",
"\\ztdirgfo",
"\\ZtWbolU",
"\\Zuad",
"\\Zwangi",
"\\Zwangie",
"\\zwangisearch",
"\\ZwangiSrch",
"\\ZwankySearch",
"\\Zwunzi",
"\\zzghn4r6f",
"\\BBccoaol",
"\\BBcooly",
"\\SaveyAsi",
"\\Bflix shop2win",
"\\CCouddecc-Vi",
"\\GeynnIusCCouupone",
"\\CouponnIt",
"\\CyoDoeec-V",
"\\Microsoft\\W64",
"\\Capturalate",
"\\SurfersSaver",
"\\vRTczl",
"\\AmL1wi",
"\\GeeniUsaCoupOne",
"\\Power-Antivir-2009",
"\\Reversecoing",
"\\Dll Runner",
"\\InstallDir",
"\\Wx- Shop2Win",
"\\wxDownload",
"\\wXDaowwneloAd",
"\\wxxDDoowwnload",
"\\CertifiedToolbar",
"\\senseulize",
"\\wsgCr",
"\\Windows.cvs",
"\\WX ShooP2Win",
"\\-WindowUpdate",
"\\windos",
"\\FoldermName",
"\\DRbKK",
"\\WIOIUKUKCNAG",
"\\BIFIT_A",
"\\SystemWindowsFirewall",
"\\boyhh",
"\\usystemeesree",
"\\oxmHw",
"\\WQFZQ",
"\\xtiDt",
"\\winupdate13",
"\\Explorar32",
"\\@dun",
"\\Windows Operating System Stats",
"\\CGI\\CG",
"\\CGI\\UFA",
"\\WindowsHost",
"\\poclbm",
"\\2lqM74wJF",
"\\tEx2XJG8",
"\\PriceeKyeaper",
"\\rundll2 32",
"\\{Emissary}",
"\\bUpmDd6E8NR",
"\\cishct",
"\\Explorer01",
"\\servergeht",
"\\WindowsPE",
"\\gogle",
"\\msservices",
"\\xhmH2zsEB",
"\\jusch",
"\\MicrosoftOffice",
"\\wpB7YySZUim",
"\\OHdZ0Qt0w9E",
"\\BoanSafe",
"\\AdbUpd",
"\\Adobe Flash Updater",
"\\Kiwybo",
"\\Microsoft\\Trats",
"\\wshomenetworks",
"\\{6F6F679E-9D8A-44EB-9836-E27B8D14A424}",
"\\inersexmin",
"\\Miningtrip",
"\\winaudioservice",
"\\Windows Startup Application",
"\\Windows Update Services",
"\\WindowsPED",
"\\win-proz",
"\\confost Libs",
"\\SearchNewTab",
"\\smartcompare",
"\\System33",
"\\win36",
"\\csrss",
"\\le0wOoHOKXb",
"\\hgfyftfvcuh",
"\\Java Org",
"\\WindowsPEx",
"\\X86PC\\skin",
"\\WindowsPExE",
"\\WinSvchost64",
"\\bootingpro",
"\\quickcheoap",
"\\linematch",
"\\WinDefenders\\min",
"\\AdobeD",
"\\2433f433",
"\\Java Software",
"\\system\\cgminer",
"\\LEaWxOqxt6B",
"\\mappelatrernativer",
"\\YpToXc6",
"\\RegSvcs",
"\\Aunijj Ldt",
"\\xJ16bNKD",
"\\LG\\cpu",
"\\test",
"\\opensearchGT",
"\\Windows Hostprozess",
"\\WindowssDefendersTT",
"\\DnsBasic",
"\\WinDefenders",
"\\Files\\svchost",
"\\cgminer-3.0.1-windows",
"\\WindowsLogon",
"\\honorzone",
"\\WindowsLogonS",
"\\SubFolderName",
"\\WindowsLogonSS",
"\\Microsoft\\Word\\kernels\\phatk",
"\\Microsoft\\Word\\kernels\\phatk2",
"\\Microsoft\\Word\\kernels\\poclbm",
"\\ctfmn",
"\\Dirty",
"\\UpdateWin",
"\\QVzlibwt",
"\\Acrobat",
"\\Microupdate",
"\\HipPop",
"\\Window modus",
"\\.net",
"\\WindowsLogonSSS",
"\\system.32",
"\\Microsoft_Update_2012",
"\\WindowsDefencer",
"\\cliprun.exe",
"\\WindowsLogonA",
"\\Microsoft 2011",
"\\WinOffer",
"\\Adobex86",
"\\WindowsFilessc",
"\\5yKHi7bidrv",
"\\8Q3O7Dh",
"\\brWqae9",
"\\DYHMrdaS",
"\\pK52vIEf",
"\\SLgd3Ux4zEI",
"\\yqD8a0UaWkn",
"\\KlzHuG",
"\\DownLowApp",
"\\cZSnkBb4C6L",
"\\LgPUyk",
"\\visuallabs",
"\\Mm1JwI",
"\\SFC3QMnEhnj",
"\\FI9ChR",
"\\gdi_drv",
"\\vHz4aMJBX",
"\\dCGvscfC5TYpSCa",
"\\J52uHDe4Yf",
"\\nameoffolder",
"\\Windows Sec Data",
"\\WindowsLogged",
"\\jawax",
"\\GUBOOK",
"\\maxboan",
"\\swagger",
"\\OcmVV",
"\\i.am.s.e.xe.s - kopie",
"\\searchqutoolbar",
"\\Wicrosoft\\Mindows",
"\\seavenshayree",
"\\WrafBwtl7",
"\\Inttel",
"\\0VIE6TPqH",
"\\1XJG8URrIls",
"\\7Drdp9W9",
"\\9VEJnZWP",
"\\cq7l6p",
"\\eAQCZDFh0wMwVT",
"\\pooler-cpuminer-2.3.2-win32",
"\\SEB3QMnEgn",
"\\taskngr",
"\\oFtOF",
"\\gSPIda0Ru1",
"\\msesecurity",
"\\W0mjcxuMl",
"\\3h2lqL63w",
"\\AcompanyXXX",
"\\dgVoodoo",
"\\PriceGong",
"\\8rwSEB2PLm",
"\\adobeupd10",
"\\windefdrv",
"\\windefdrv.exe",
"\\windefmgr",
"\\windefmgr.exe",
"\\windefsch",
"\\windeftsk",
"\\EznIy",
"\\ifdstore",
"\\nCMuu",
"\\SafeSaver",
"\\CostMin",
"\\BetterSoft\\OptimizerPro",
"\\adobev",
"\\Microsoft\\DLL\\icxml",
"\\Microsoft\\DLL\\lust",
"\\Microsoft\\DLL\\mdata",
"\\Microsoft\\DLL\\msys",
"\\Microsoft\\DLL\\socket",
"\\WinlogonSetup",
"\\QkYsj",
"\\Microsoft\\EasyOn",
"\\B3QMnEgnjx0",
"\\quickcheapo",
"\\eUpdate\\0D1C4AEF5229452186AB25FB5285A35D",
"\\eUpdate\\53BEBE48A69E4e879DC1D3846A22527F",
"\\F8gbptK9eme",
"\\joyshopping01",
"\\nQXS6bsR",
"\\WindowsFiless",
"\\Winodws Runtime",
"\\WTBaS1dsWlVaR3BrVmxF",
"\\System Idle Process",
"\\Adobe64x",
"\\B4c6lpG5",
"\\ccostmiN",
"\\ccoustomin",
"\\coastmin",
"\\CoestmiN",
"\\SettingsWin",
"\\Microsoft Windows System",
"\\LJFurl",
"\\Microsoft\\SView",
"\\Microsoft\\SysWOW_amd64",
"\\Microsoft\\Windows\\MsLocal",
"\\Systenne",
"\\2vCyL43P7x",
"\\costmmin",
"\\srvhostr",
"\\allmywebtb",
"\\adobelightnw",
"\\Kelg9231uxPf",
"\\Microsoft Computer",
"\\Windowsmsc",
"\\BTC",
"\\InstallRootSystem",
"\\2099",
"\\adobelightcy",
"\\Application Verifier",
"\\B4c7lpG6",
"\\fStQc",
"\\minerz",
"\\Nvidias Sound",
"\\Tnup0472DHYo",
"\\Penwes",
"\\eorezo",
"\\FreeSoftToday",
"\\freesofttoday_jp_2",
"\\MicrosoftO15",
"\\Nt32lnstall",
"\\7AHDQUdC",
"\\DarkCrypt-GUI",
"\\freesofttoday_fr_3",
"\\Microsoft\\Windows\\DyoB6WJ78S",
"\\MWinHT",
"\\G9hc14quLb",
"\\SmtoCFXn",
"\\Adobecy",
"\\CleanFree",
"\\FlashPlayer Plugin",
"\\Java SE Platform Updater",
"\\WinUSB3Drv32",
"\\GoogleUpdate",
"\\PangPangClean",
"\\.hu-minecraft.net",
"\\534546456",
"\\ChromeUped",
"\\MicrosoftServer",
"\\profected",
"\\windowsleep",
"\\MnImLc",
"\\ChangeME",
"\\UnitSwitch",
"\\videosaver",
"\\GenericAddon",
"\\Lbuddy",
"\\Password-Assistant",
"\\ShowPass",
"\\SneakPic",
"\\{D09FB2FC-118A-4369-8C6E-96FE8A0D4298}",
"\\GoogleChrome",
"\\troyano2",
"\\Adobe32x",
"\\Folder Nam",
"\\ShoppingChip",
"\\wizardrian",
"\\Microsoft\\SysWOW_32",
"\\adobelightnw2",
"\\GoogleUpdater",
"\\RlsnBFWm",
"\\Vjtcc",
"\\xLWFE",
"\\BasicServe",
"\\Adobe86",
"\\FFolder Name",
"\\YC",
"\\bProtectorForWindows",
"\\System.dll",
"\\okitspace",
"\\AdobeSystems",
"\\FOJFOJ",
"\\iniweblink",
"\\MacromediaFlesh",
"\\MacromideaFlash2014",
"\\Microsoft\\Posix\\ntw32",
"\\Microsoft\\Sys32",
"\\Microsoft\\XMMC\\apds",
"\\MicrosoftO9",
"\\MicrosolfDLL",
"\\O09",
"\\silncy",
"\\WINstls",
"\\Adobex32",
"\\Config datas",
"\\localsyslib",
"\\exLibris",
"\\naudio32",
"\\PowerQuest\\lcdmedia",
"\\tt",
"\\Ad0be",
"\\Slick Savings",
"\\winnwcg",
"\\macromediaflesh",
"\\Microsoft\\comonn",
"\\SearchN",
"\\{WINDOWS-9871641354F1AD5FA4D68A6A54F6F}",
"\\Adobex32x",
"\\cos3",
"\\SaveSense",
"\\SaveSenseLive",
"\\JavaUptade",
"\\KeyPang",
"\\litecoinsforgood",
"\\Adobex86x",
"\\WindowssDrivers",
"\\zTIcTl",
"\\Adobe Updater Startup Utility",
"\\Microsoft\\lib\\syslink",
"\\WindowsPID",
"\\Local\\Windows Host Controller",
"\\LocalLow\\Gigantic Savings",
"\\LocalLow\\Savings Hero",
"\\europd",
"\\nmsc",
"\\GUeNN",
"\\._.minerLC",
"\\helper2",
"\\KFMKFM",
"\\[FOLDER2DROP]",
"\\sqlsrv32",
"\\Explorer",
"\\MS Service",
"\\Adobex64x",
"\\uurhngf",
"\\Windows Audio Device Graph Isolation",
"\\WindowsServicess",
"\\ShoppingChip",
"\\Dllconfig",
"\\WndowsDefencer",
"\\FlashPlayer Insatll",
"\\usbsys32",
"\\wuaclt",
"\\YHTGFRRFVB",
"\\0",
"\\360Safa",
"\\VideoDrivers\\CPU\\x64",
"\\VideoDrivers\\CPU\\x86",
"\\Adobe\\Flash Player\\DSHs",
"\\Identities\\crsscmgr",
"\\SearchProtect",
"\\Winclean performap",
"\\Windows net-clean",
"\\Win sys filter",
"\\WindowsUp",
"\\Adobe System Incorperated and its licensors",
"\\AdobeCorporation",
"\\QkrmAEVl",
"\\jhgvy76765guhb0",
"\\D394D188-BAC7-4e03-8FAF-389A4D7EC6F4",
"\\updatebroser",
"\\winit",
"\\wnstallDir",
"\\ciscvur",
"\\scriptjscrhome",
"\\winUpdatetemp",
"\\OipkyBTj",
"\\sys23",
"\\windowunitpop",
"\\NetworkWidget",
"\\ChromeUpds",
"\\jkgkjgk",
"\\nVKeU",
"\\KdkgtxPf",
"\\mPSR52rQ",
"\\wncmanager",
"\\8BIERVeD",
"\\8CJESWeD",
"\\VideoDrivers\\CPU\\x64",
"\\VideoDrivers\\CPU\\x86",
"\\Windows Update24.5",
"\\2vCyLP7x",
"\\cattnuug",
"\\Microsoft Defenders",
"\\microsoft incorporated company usa",
"\\MicrosoftCoreUpdateEngine",
"\\WindowsFormsApplication1",
"\\ValueApps\\IE",
"\\AnyClick",
"\\AnyClickUP",
"\\gldsys",
"\\Micosoft32",
"\\Microsoft\\DLL\\msql",
"\\MS-MicrosoftOffice",
"\\nimrou",
"\\DVDFab9\\regrecord\\Windows\\Update",
"\\contre strike 1.6",
"\\EelguyPf",
"\\Ggnz1573NQ8y",
"\\Key Folder",
"\\microosoft",
"\\Microsoft\\Crypto\\DSS\\MachineKeys\\GuangKeyPan",
"\\mBIERVdC",
"\\Microsoft\\Windows\\svchost",
"\\SaveClicker",
"\\WiseManager\\CGMInerDLLs",
"\\MinerdIdle",
"\\Safe_nots",
"\\comhost",
"\\complad",
"\\Complitly",
"\\byybwan04as",
"\\m9dt734hfbjh",
"\\winupdr",
"\\iavvao",
"\\Adobe\\Taskil",
"\\shchost",
"\\tZ62gkB0",
"\\{7EAAFBB9-2051-44B5-A11D-DEE4D6CA7409}",
"\\{A75C1176-8D6E-4B20-921A-46FD23436A86}",
"\\{A7B1B9FC-80F6-4345-A6DA-B27892B3ECAA}",
"\\47d13651aa67406e8764a5c795b226bf",
"\\SearchZone",
"\\Savepop",
"\\MOpop",
"\\Windows Deffense",
"\\Windows Net Data",
"\\MySearch",
"\\Trusted Publisher\\SW-Booster",
"\\CouponSignal",
"\\GoogleChr",
"\\GorillaPrice",
"\\Tbccint",
"\\NoVooIT",
"\\PayAHacker",
"\\Popper",
"\\Fast And Safe",
"\\Mozilla\\Firefox\\extensions\\{124d001a-bdcb-472f-aa59-bbe7e4bc3204}",
"\\ma-config.com",
"\\htjibvtyc",
"\\illhhjmrv",
"\\ddcjxqepc",
"\\SubFolder",
"\\sxratlel",
"\\wotfqpx2i2j3",
"\\wrokykbtmd",
"\\ulampxkad",
"\\6e958a80feb239af",
"\\7",
"\\adobler",
"\\bmjwidjyinyoszu",
"\\bzriujpnwttye",
"\\clftxboofmx",
"\\CoupSeek",
"\\czcgwvvyppjaurq",
"\\diovzrets",
"\\ehslgllvhldfux",
"\\ejodqlnqg",
"\\ensiwpqbgcid",
"\\ftosdferlf",
"\\fujjppgdtitw",
"\\ggnjcnoi",
"\\gjqwyalunchx",
"\\Heuvxou",
"\\hjfptwjjxx",
"\\hpocihpzmv",
"\\imonyjyk",
"\\ipejabmvctdnap",
"\\itvfdjaeiti",
"\\jsulbye",
"\\jyjmxpfv",
"\\kjscuryrr",
"\\kqeltjqvub",
"\\kyrmtzn",
"\\llmloafkskona",
"\\lslcgleesqik",
"\\ltstrtswajiem",
"\\Microsoft\\i",
"\\mmtqrxgm",
"\\mrxfohjztzw",
"\\numgjreyz",
"\\phfxivpbz",
"\\pjmjpvqns",
"\\ptwenvudvad",
"\\qhohyyafcedexm",
"\\qhukbjoyihvvzw",
"\\qjtzoavs",
"\\qknldkbmqumvfy",
"\\qmqxirnokbvelf",
"\\raffaagttmbw",
"\\sbfeffrwafn",
"\\sciofcyueslyz",
"\\snodnlvb",
"\\swnxlftjs",
"\\tdsxpxxxgwer",
"\\thgcrnhrcddnpd",
"\\trztezs",
"\\twpurbqnnwf",
"\\uubrgxpqnts",
"\\viwpwqpoxhpwmpz",
"\\wlpoxbqnhqbt",
"\\wxxtdyaylfk",
"\\xwmywzumje",
"\\yhectiwbp",
"\\zylagehex",
"\\volsbjadaykecz",
"\\vyqnvqckjritk",
"\\wdlyutvvyb",
"\\taskhost",
"\\Microsoft\\Windows\\9EAs3nADUl",
"\\sdfdgrfghg",
"\\WinSyserSoftMng",
"\\srvshosts.exe",
"\\AntiV",
"\\ive Update",
"\\javax",
"\\lyricsgizm",
"\\MicrosoftUpdateSrv",
"\\rr434et",
"\\Service Host",
"\\ShopperPro",
"\\sjbksgrrk2v",
"\\Sum\\Encryp",
"\\Surf Protect",
"\\WebGeniuos",
"\\Windows NetShield",
"\\WindowsUpgrade",
"\\Windowsx",
"\\WinSyserSoftMng",
"\\bod3uk0n.rsn",
"\\Browser Protect",
"\\Context2pro",
"\\Deal-Dropper",
"\\Deals Plugin",
"\\DynamicPricer",
"\\Guard\\res",
"\\Hero_Fighterb",
"\\lyricsgizm",
"\\Microsoft\\Adobe",
"\\SaveClicker",
"\\Uptodown_EN",
"\\Windows BT Icons",
"\\JavaUpdat",
"\\ArkimGejuy",
"\\m9dt734hfbjh",
"\\Es-Un",
"\\pennybeepro",
"\\gKRN04nM",
"\\oTOJX1js",
"\\WizLine",
"\\Setupobject",
"\\onlysearch",
"\\com.flash.WidgetBrowser",
"\\Intelismart webbing",
"\\mozzila",
"\\ms.net.svchost",
"\\MSBitDefender",
"\\SendShC",
"\\svchsot",
"\\SYSTEM32Folder",
"\\WeBbaiNg",
"\\Win Update Scheduler",
"\\WindowsDir",
"\\WinUpdateFunction",
"\\Trusted Publisher\\GS_Booster",
"\\AdobeR",
"\\AdobeReader",
"\\AdobeReader15.0",
"\\AdobeUpdates",
"\\avirra",
"\\conhost86",
"\\Drivstarts",
"\\getithd",
"\\goldsnnv5",
"\\JavaUDate",
"\\JavaUpdate",
"\\jre8",
"\\MCommon",
"\\Microsoft Embedded",
"\\Microsoft Extensions",
"\\Microsoft Update",
"\\Microsoft\\DLL\\ffx",
"\\Microsoft\\SDL",
"\\Microsoft\\Windows\\Adobe",
"\\Microsoft\\Windows\\Deep Layers",
"\\Microsoft\\Windows\\kernel",
"\\Microsoft\\Windows\\Last Items",
"\\Microsoft\\Windows\\LiveUpdata_Mem",
"\\Microsoft\\Windows\\MSI93153",
"\\Microsoft\\xprPlugin",
"\\Mircosoft",
"\\Mozila",
"\\msconfg",
"\\MSDCSC",
"\\MSDHOSTJB",
"\\MSHOSTJDBX",
"\\MSI93153",
"\\MSscrt",
"\\NET Framework",
"\\OfferInstaller",
"\\skypecon",
"\\svcho",
"\\SxyGrl",
"\\TaskServ",
"\\UpdateDriverV4",
"\\UpdateDriverV5",
"\\updatr32",
"\\Wind0ws",
"\\Windows64",
"\\WindowsMB",
"\\WindowsMM",
"\\WindowsPro",
"\\Windpws_Update",
"\\winservices",
"\\wInstallsdk",
"\\winsys",
"\\WinSysDriv",
"\\{584cabc6-b3f0-4d52-b7e2-3ffbf17c3258}",
"\\{7B12A9C8-C5C0-3200-7000-EF98CBAE67}",
"\\{AFCFB568-9CD7-46E2-B95D-E339BD741E9D}",
"\\about\\Data",
"\\Adblocker",
"\\Adobeupdate",
"\\ChromeUpdates",
"\\csfconfig",
"\\DRPSu",
"\\EavUa",
"\\Flash Temp",
"\\flashsrv",
"\\FrameworkUpdate7",
"\\ftecdr4",
"\\JavasUpdate",
"\\Loydip",
"\\lyricsgizm2",
"\\Microsoft\\bin\\set",
"\\Microsoft\\bin\\srcd",
"\\Microsoft\\bin\\syslink",
"\\Microsoft\\DLL\\chmdata",
"\\Microsoft\\DLL\\host",
"\\Microsoft\\DLL\\srcd",
"\\Microsoft\\Media\\chmdata",
"\\PriceLess",
"\\Redis",
"\\ruer",
"\\ServerProces",
"\\Sever2",
"\\Sistem\\1",
"\\snchost",
"\\SystemDriversReserved",
"\\vschost",
"\\Webbing",
"\\Windows Assistance",
"\\windowscoldfix",
"\\Winpdate",
"\\System\\Emoticons",
"\\System\\Skins",
"\\6b407430",
"\\LXTNavi",
"\\WinFixex",
"\\ZXTMagic",
"\\browser_agent",
"\\erge_Data",
"\\addplore",
"\\Adobe\\kernel",
"\\AnyProtectEx",
"\\atualizaaowins2014",
"\\atualizadowdowindws2014r",
"\\BestWebVault",
"\\configsf",
"\\Conhost DLL Base",
"\\CoolFixe",
"\\CoolFixeConfig",
"\\DeepCoolFixe",
"\\Default Applicatione",
"\\Default Folder",
"\\DirtyWindows Softwares",
"\\dts\\mydts",
"\\GooglePlug",
"\\Java8",
"\\JavaMP",
"\\Microsoft\\FoxPlugin",
"\\Microsoft\\lib",
"\\Microsoft\\Windows\\System32",
"\\MicrosoftSec",
"\\MicrosoftVision",
"\\MsMpE32",
"\\nomhhrbgerytbvy",
"\\Offercrowd",
"\\SkypEEMotuicons",
"\\SlimPrice",
"\\SmartOnes",
"\\sockscln",
"\\webbora",
"\\WindowsUpd",
"\\BuyNsave",
"\\Media-belong",
"\\Media-body",
"\\Media-consist",
"\\Media-exit",
"\\Media-gas",
"\\Media-jump",
"\\Media-phrase",
"\\Media-pride",
"\\Media-record",
"\\Media-teach",
"\\Media_disagree",
"\\Media_fire",
"\\Media_seem",
"\\Mediaspite",
"\\MicrosoftServices",
"\\taskkmgr",
"\\AdobeF",
"\\Adobeu",
"\\aeygccfnfs",
"\\asr_capp",
"\\asr_emon",
"\\asr_ices",
"\\asr_isvc",
"\\asr_sc",
"\\asr_supd",
"\\autogsvc",
"\\autoider",
"\\autopher",
"\\bitmsg.db-journal",
"\\bootethc",
"\\boothare",
"\\bootnger",
"\\bootrint",
"\\boottray",
"\\calcmsg",
"\\calcress",
"\\calcsc",
"\\charemon",
"\\charping",
"\\charreg",
"\\chkdexec",
"\\chkdices",
"\\chkdipv6",
"\\autosass",
"\\autoSRVR",
"\\cisvmem",
"\\cisvnime",
"\\ckcncapp",
"\\ckcnstat",
"\\cleasmui",
"\\cleasrvc",
"\\clicnet1",
"\\clipemon",
"\\clipunas",
"\\cmdetup",
"\\cmdtify",
"\\cmstinit",
"\\cmstpand",
"\\cmstsmgr",
"\\cmststat",
"\\Common Files\\windows\\systema",
"\\Common Temp",
"\\Common\\LuaRT",
"\\compipv6",
"\\compnet1",
"\\compqsvc",
"\\conidump",
"\\conights",
"\\conisass",
"\\contexnt",
"\\convac32",
"\\cscrntsd",
"\\csrsatch",
"\\csrshone",
"\\ctfmider",
"\\ddesator",
"\\debunet",
"\\debuript",
"\\defrnet",
"\\defrript",
"\\defrrsm",
"\\dianbkup",
"\\diskcapp",
"\\dllhetup",
"\\dllhkman",
"\\dllholsv",
"\\dmadedos",
"\\dplakrnl",
"\\dpvsdstr",
"\\dpvsedir",
"\\dqlabfxhe",
"\\drwanger",
"\\drwapan",
"\\drwatify",
"\\duklhfb",
"\\dumpsc",
"\\dvdpay32",
"\\dvdpkman",
"\\dvduices",
"\\dvdukeys",
"\\dvdureg",
"\\dwwiqsvc",
"\\evenedos",
"\\evenfmon",
"\\evenkrnl",
"\\expabkup",
"\\expaSRVR",
"\\explr",
"\\fastckup",
"\\fcsass",
"\\findkrnl",
"\\findmem",
"\\fingsmgr",
"\\ftlmssny",
"\\GpCooupun",
"\\gpregsvc",
"\\ipv6emon",
"\\lightify",
"\\loadtbs",
"\\locaexec",
"\\lsasinit",
"\\lsassupd",
"\\MAPIbkup",
"\\MAPIhost",
"\\MAPIinst",
"\\MAPIokup",
"\\MAPIol32",
"\\memcapp",
"\\memtify",
"\\mewmni",
"\\Microsoft\\sofa",
"\\Microsoft\\svs",
"\\microsoft_ser.exe",
"\\migpdump",
"\\migpedit",
"\\migputou",
"\\Minerd",
"\\mnmshost",
"\\mnmsutou",
"\\mobskmgr",
"\\monero",
"\\mplacapp",
"\\mqbkinst",
"\\mqsvckup",
"\\mqsvkman",
"\\mqsvsmui",
"\\mqtgethc",
"\\mscdunas",
"\\msghost",
"\\msgstrt",
"\\msiecmgr",
"\\msieconf",
"\\msiegini",
"\\msiegsvc",
"\\MsScc32",
"\\mstiider",
"\\net1krnl",
"\\netadow",
"\\ntbantsd",
"\\ntoskman",
"\\ntosvr32",
"\\ntsdsmgr",
"\\rdshlist",
"\\rdshvr32",
"\\rimosystetre",
"\\RollingPop",
"\\rsmscmgr",
"\\runoec32",
"\\schtolsv",
"\\scxhost",
"\\sesskman",
"\\sethol32",
"\\SettingsHost",
"\\smss-DoOoM-privacy",
"\\SMVBNTS",
"\\sndvolsv",
"\\svchostss123",
"\\System Volume Information",
"\\System_KrciVr",
"\\systemlog32",
"\\SysUpdNC",
"\\taskkman",
"\\TaskOne",
"\\Windows32",
"\\WindowsHelp",
"\\WindowsSystem32",
"\\signtab",
"\\iexplore",
"\\Microsoft\\Windows\\Dll",
"\\nwscadow",
"\\pathcmgr",
"\\sdchost",
"\\adobelightcg",
"\\{cfds32}",
"\\{E02vers1}",
"\\360DrvMgr",
"\\AdobeS",
"\\adpwzcusecdl",
"\\Adobe FlashPlayer Software",
"\\atckup",
"\\atsass",
"\\atsol",
"\\attrcapp",
"\\attrdctr",
"\\attrimon",
"\\autoclip",
"\\autogoff",
"\\autontfs",
"\\autrueboyz",
"\\blasasks",
"\\blasdstr",
"\\blasfmon",
"\\bootosk",
"\\caclclip",
"\\caclkdsk",
"\\caclosk",
"\\chextension",
"\\cidacomp",
"\\clipysvr",
"\\cmdlconv",
"\\cmdldsvr",
"\\cmdlhost",
"\\cmdltvwr",
"\\compgoff",
"\\comphare",
"\\contckup",
"\\convpsrv",
"\\dcomator",
"\\dcomdump",
"\\dcomntsd",
"\\ddeseset",
"\\ddesntsd",
"\\dfrgtvol",
"\\diskec32",
"\\diskskey",
"\\dllhltMc",
"\\doskokup",
"\\dplarcp",
"\\dpvsemon",
"\\dpvstvwr",
"\\drwtcapp",
"\\dumpclip",
"\\dumphare",
"\\evenager",
"\\evenltMc",
"\\eventvol",
"\\excpsrpa",
"\\expafunc",
"\\fcokup",
"\\fcstat",
"\\finddsvr",
"\\fltMider",
"\\logoexec",
"\\lprerif",
"\\lprhone",
"\\lprstat",
"\\lprtvol",
"\\lsassync",
"\\magnhare",
"\\magnuota",
"\\memhone",
"\\memuota",
"\\Morcrosoft",
"\\mounnsta",
"\\mplafunc",
"\\mpnoasks",
"\\mqottqso",
"\\msginst",
"\\msgnw16",
"\\narrsmgr",
"\\nbtsokup",
"\\nslocapp",
"\\ntbaedit",
"\\osunnsta",
"\\Presasks",
"\\proqcapp",
"\\proqhare",
"\\qappubst",
"\\rasphost",
"\\raspover",
"\\rexestrt",
"\\Safe_nots_gh",
"\\save. oan",
"\\scarcapp",
"\\schterif",
"\\sigvec32",
"\\svchcapp",
"\\svostsi",
"\\sxchost",
"\\user1",
"\\WinDCOMSvcMgrV2",
"\\Windows Update 8",
"\\bigdaddyhyestor",
"\\Sysfiles",
"\\Microsoft\\CryptoBit",
"\\MSRTCT1",
"\\winsvsdir",
"\\FSMdpnIXptv",
"\\mntat",
"\\msepd",
"\\Sleep bottom",
"\\uloxyhideqejejif",



        };
        public static void ScanForBlacklistedItems()
        {
            string appDataPath = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);

            Console.WriteLine("Scanning AppData for blacklisted files and folders...");

            try
            {
                // Scan for blacklisted folders
                string[] directories = Directory.GetDirectories(appDataPath, "*", SearchOption.AllDirectories);

                foreach (string directory in directories)
                {
                    string folderName = Path.GetFileName(directory);

                    if (_blacklistedFolders.Contains(folderName))
                    {
                        Logger.Instance.LogPrimary($"Blacklisted folder found: {directory}");
                        // Optionally, take action (e.g., delete or quarantine the folder)
                        // Directory.Delete(directory, true); // Be cautious with this line!
                    }
                }
            }
            catch (UnauthorizedAccessException ex)
            {
                Console.WriteLine($"Access denied to some directories: {ex.Message}");
            }
            catch (PathTooLongException ex)
            {
                Console.WriteLine($"File or directory path too long: {ex.Message}");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred during scanning: {ex.Message}");
            }

            Console.WriteLine("Scan complete.");
        }
    }
}
