using System;
using System.Collections.Generic;
using System.IO;

namespace Wildlands_System_Scanner.Blacklist
{
    public class DesktopFileBlacklist
    {
        public static void ScanForBlacklistedFiles()
        {
            // Predefined blacklist of file names (case insensitive)
            HashSet<string> blacklistedFiles = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
            {
"-d743~1.lnk",
"plug&play.lnk",
"Spyware&Malware Protection.url",
"1e40~1.lnk",
"61ef~1.lnk",
"6a3d~1.lnk",
"7e3e~1.lnk",
"8ffc~1.lnk",
"AntiSpywareSuite.lnk",
"askearth17.exe",
"bravesentry.lnk",
"c2f4~1.lnk",
"chat now.lnk",
"click-run-for-live-sex.exe",
"comet cursor.lnk",
"ecsiin.stub.exe",
"ei.exe",
"esplora.lnk",
"exp1orer.lnk",
"feee.exe",
"filgmo.exe",
"Find Spyware Remover.lnk",
"Free Online Dating.lnk",
"free plasma tv.lnk",
"Go to Casino.lnk",
"installer_en.exe",
"instant access.lnk",
"internetgamebox.lnk",
"join the orgy.lnk",
"Magicantispy.lnk",
"movieland terms.lnk",
"movieland.url",
"nocreditcard.lnk",
"Online Shopping.url",
"play poker online.lnk",
"playercodec1000.exe",
"poker shortcut.lnk",
"prutpct.exe",
"prutsct.exe",
"ptech.exe",
"qualitycodec.589.exe",
"Remove Adware.url",
"searchus.exe",
"Sex Personals.url",
"skytown.exe",
"sudoplanet.lnk",
"System Live Protect.lnk",
"tagasaurus.exe",
"Video Slots.url",
"VirusLocker.lnk",
"webmediaplayer.lnk",
"xinstall.exe",
"yinstall.exe",
"GoRecord 2.lnk",
"38a1~1.lnk",
"4bb6~1.lnk",
"88ea~1.lnk",
"crazy girls.lnk",
"012A~1.LNK",
"AntiSpywareBot.lnk",
"AVSystemCare.lnk",
"Free PC Wallpapers.lnk",
"PCTurboPro.lnk",
"Sexxxpassport.lnk",
"spamblockerutility.exe",
"UDefender_Installer.exe",
"BestsellerAntivirus.lnk",
"StorageProtector.lnk",
"Live Safety Center.lnk",
"Online Security Guide.lnk",
"OnlineHelpmate unregistered.lnk",
"MalwareAlarm.lnk",
"Security Caution.URL",
"Security Updates.URL",
"Online Security Center.URL",
"MBS Account Manager.lnk",
"Hot internet offers.lnk",
"WinReanimator.lnk",
"Anti Virus Pro spyware remover.lnk",
"WinIFixer.lnk",
"AntiSpywareDeluxe.lnk",
"Online Security Guide.url",
"Security Troubleshooting.url",
"AntiSpywareShield.lnk",
"Important.htm",
"files.exe",
"SpyShredder.lnk",
"abc32.dll",
"arm32.dll",
"bot.dll",
"ivn4.dll",
"spywarescanner.lnk",
"Advanced XP Defender.lnk",
"SystemDefender.lnk",
"Advanced XP Fixer.lnk",
"SpyBurner.lnk",
"AntiSpywareExpert.lnk",
"Raila Odinga.gif",
"BEST free galleries.url",
"SUPER P0RN.url",
"BDSM galleries.URL",
"CP illegal content.URL",
"Uncensored porn.URL",
"AXPFixer.lnk",
"XPSecurityCenter.lnk",
"Explorev.exe",
"QQmussi.exe",
"Girls.exe",
"FREE SEX WEB CAM.url",
"Antivirus Master.lnk",
"SEXY TEENS.url",
"AntiSpywareMaster.lnk",
"holywood stuff film.zip.exe",
"Privacy Redeemer.lnk",
"Download programs.url",
"Games.url",
"Translator.url",
"Videos.url",
"XP-Guard.lnk",
"SpywareDestructor.lnk",
"sexe69.lnk",
"Free MP3 Search.url",
"Free Porn.url",
"Search Online.url",
"VIP Casino.url",
"Cheap Pharmacy Online.url",
"Rapid Antivirus.lnk",
"AntiSpywareXP2009.lnk",
"SudoPlanet.lnk",
"Bkav2006.exe",
"Internet Antivirus.lnk",
"VideoSpeedy.lnk",
"SMS TRAP.url",
"Antivirus 360.lnk",
"System Security.lnk",
"QUAD Registry Cleaner.lnk",
"A360.lnk",
"Trojan Guarder.lnk",
"XP-Shield.lnk",
"Personal Antivirus.lnk",
"AntivirusXP.lnk",
"PCenter.lnk",
"System Security 2009.lnk",
"Advanced Virus Remover.lnk",
"Cheap Software.url",
"MP3 Download.url",
"EZ-Tracks.com.lnk",
"Windows Security Suite.lnk",
"Malware Professional.lnk",
"Secret Service.lnk",
"WiniFighter.lnk",
"MalwareRemovalBot.lnk",
"Windows Protection Suite.lnk",
"Antispyware.lnk",
"Contraviro.lnk",
"Perfect Optimizer.lnk",
"SaveSoldier.lnk",
"SaveDefense.lnk",
"SystemCop.lnk",
"QuickHealCleaner.lnk",
"Documents.exe",
"SaveKeeper.lnk",
"PC-Optimizer.lnk",
"Original-Solitaire.lnk",
"AntivirusPro_2010.lnk",
"mercasexo.url",
"MacroVirus.lnk",
"Windows PC Defender.lnk",
"SecureWarrior.lnk",
"AV Care.lnk",
"SafeFighter.lnk",
"TrustCop.lnk",
"Security Tool.lnk",
"install_sbd_en.exe",
"Volcano Security Suite.lnk",
"Personal Protector.lnk",
"SpySpotter.lnk",
"AntiMalware_Pro.lnk",
"Registry Doktor 4.1.lnk",
"Antivirus Doktor 4.1.lnk",
"AntiMalware_Pro.lnk",
"Security Tool.lnk",
"Additional Guard.lnk",
"KeepCop.lnk",
"ECONOMIE meditatie online bacalaureat si admitere ASE.lnk",
"REAnti.lnk",
"AntiMalware Support.lnk",
"AntiMalware.lnk",
"Security Central.lnk",
"AntiTroy.lnk",
"Internet Security 2010.lnk",
"Safety Anti-Spyware 3.lnk",
"AntivirusBEST.lnk",
"RegSweep.lnk",
"ErrorSweeper.lnk",
"Control center.lnk",
"ACProtect.lnk",
"RegistryFox.lnk",
"ProtectSoldier.lnk",
"tvlook.lnk",
"RegGenie.lnk",
"PC Doc Pro v5.lnk",
"Advanced Spy.lnk",
"AdvancedCleaner Free.lnk",
"Ctrl-Center.lnk",
"SpyKill.lnk",
"Repair Registry Pro.lnk",
"Antimalware Defender.lnk",
"Privacy Center.lnk",
"Control-Center.lnk",
"Spyware Nuker XT.lnk",
"Your PC Protector.lnk",
"Advanced Defender.lnk",
"Security essentials 2010.lnk",
"Personal Anti Malware.lnk",
"uISGRLFile.dat",
"Maileet.lnk",
"Scan Virus.lnk",
"FREE BonziBUDDY.url",
"Click Here For Your Free Gift!.url",
"Free Screensavers & Wallpapers.url",
"Listen To Relaxing Piano Favorites.url",
"Send Free eCards!.url",
"FLV Direct Player.lnk",
"1nternet Explorer.lnk",
"Antimalware Doctor.lnk",
"Security Guard.lnk",
"Control Components.lnk",
"BuddyCheck.lnk",
"Security essentials 2010.lnk",
"Digital Protection Support.lnk",
"Digital Protection.lnk",
"CtrlComponents.lnk",
"Internet Explorer.nak",
"System Bodyguard.lnk",
"DaNa.exe",
"Webhack.exe",
"Coopen.lnk",
"xoboiu",
"My Security Engine.lnk",
"Antivirus7.lnk",
"A-fast Antivirus.lnk",
"I-Q Manager.lnk",
"TrustDoctor.lnk",
"Personal Anti Malware Center.lnk",
"GuardWWW.lnk",
"Data Protection.lnk",
"Data Protection Support.lnk",
"freesexxx.lnk",
"Live Security Suite.lnk",
"ErrorSmart.lnk",
"AdBlaster.lnk",
"AKM Antivirus 2010 Pro.lnk",
"ByteDefender.lnk",
"SystemArmor.lnk",
"XJR Antivirus.lnk",
"Security Master AV.lnk",
"My Web Cam.exe",
"Spyware Cleaner.lnk",
"Sysinternals Antivirus.lnk",
"Internet Explorer.ink",
"Anticare.lnk",
"Defense Center Support.lnk",
"Defense Center.lnk",
"Voice Fucker.lnk",
"SafetyPC.lnk",
"NEOBOX.lnk",
"Pilot Install.EXE",
"QuickDownloadPack.lnk",
"Hotmail Checker.lnk",
"Best Spyware Scanner.lnk",
"IPClear.lnk",
"QUALITY PORN.url",
"Access Members Area.exe",
"Wireshark Antivirus.lnk",
"Internet Explorer.IE",
"My Security Shield.lnk",
"Intrenet  Explorer.lnk",
"Advanced Security Tool 2010.lnk",
"Antivirus Support.lnk",
"Antivir Solution Platinum.lnk",
"Hottest Shows On The Net.lnk",
"Live XXX Shows!.lnk",
"Win7 AV.lnk",
"ÇÃ·¹ÀÌÆÄÀÏ Æò»ý¹«Á¦ÇÑ´Ù¿î.url",
"¹«·áÀÚ·á½Ç À¯Æ¿½ÃÆ¼.url",
"ÌÔ±¦¹ºÎï.url",
"ÀÚ·áÃµ±¹ ÆÄÀÏÆË.lnk",
"¼îÇÎ ½ºÆ®¸®Æ®, 11¹ø°¡.url",
"G¸¶ÄÏ ÇÃ·¯½º.url",
"1µî´çÃ· ·Î¶ÇÅ¥ºê.lnk",
"7ÀÏ°£°øÂ¥ MP3´Ù¿î.LNK",
"SMS1000°Ç ¹Ù·Îº¸³»±â.lnk",
"¹þ¹þÓÎÏ·ºÐ.lnk",
"ÃÖ½Å¿µÈ­ Áñ°ÜÃ£±â.url",
"ÂÌÉ«µ¼º½.url",
"ÌÔ ±¦ Íø.url",
"¶¹¿ÍCSÆ½Ì¨.lnk",
"É¨À×ÓÎÏ·.lnk",
"¿Á¼Ç ¹Ù·Î°¡±â.url",
"Èãpàé âåñåëî.lnk",
"µçÓ°.url",
"ÓÎÏ·.url",
"ÇÊÅõµ¥ÀÌ ¹Ù·Î°¡±â.lnk",
"´Ù¿îÅ¬·´ ¹«Á¦ÇÑ´Ù¿î·Îµå.url",
"26pkÍòÄÜµÇÂ½Æ÷.lnk",
"Å¬¶ó¿ìµåÀ¥ ½ÇÇà.lnk",
"ÔÚÏßµçÓ°µçÊÓ.lnk",
"¸Ä±äÄãµÄÒ»Éú.url",
"ÌÔ±¦¹ºÎïA.url",
"Ãâ·ÑµçÓ°C.url",
"¸Ä±äÄãµÄÒ»Éú.url",
"ÌÔ±¦¹ºÎïA.url",
"Ãâ·ÑµçÓ°C.url",
"ÌÔ±¦.url",
"ÍøÖ·Ö®¼Ò.url",
"ÀÖÍÁ»ØºÏÖÆQ°æÍøÓÎ.lnk",
"ÌÔ±¦Íø - ÌÔ£¡ÎÒÏ²»¶.lnk",
"¶·Ð·ÓÎÏ·Íø.lnk",
"Î÷ÓÎ¡¤ÏÉ½£.ink",
"Intenet Exploer.ink",
"ÌÔ±¦Íø½ñÈÕÌØ¼ÛÇø.ink",
"ÓÎÏ·´óÈ«.ink",
"°Ù¶ÈÓÎÏ·´óÌü.lnk",
"ÍøÖ·µ¼º½.url",
"¸Ä±äÄãµÄÒ»Éú.url",
"¹«Á¦ÇÑ´Ù¿î.lnk",
"ÃÖ½Å ¿µÈ­ ¹«·á °¨»ó.lnk",
"ÈÕ×¬300ÔªÏîÄ¿.lnk",
"ÕæÇ®ÆåÅÆÓÎÏ·.lnk",
"¸ßÇåµçÓ°.lnk",
"ÌÔ±¦ÈÈÂô.lnk",
"Internet Explorer.NewIE",
"Malware Destructor.lnk",
"¶àÌØÈí¼þÕ¾.lnk",
"IronDefense.lnk",
"RegistryClever.lnk",
"IronDefender.lnk",
".bestie0",
"Internet Explorer.bestie",
"Internet Expleror.url",
"Antivirus8.lnk",
"ÍæÓÎÏ·.exe",
"Internet Exploner.url",
"ÊäÈë·¨ÉèÖÃ¹¤¾ß.lnk",
"ÖÐÒ½ÌìÏÂ.Lnk",
"µð½ºÅ©Å¬¸°.lnk",
"Withmp3.lnk",
"ShieldSoldier.lnk",
"Message For My Princess.scr",
"Message For My Princess.txt",
"ShieldSoldier.lnk",
"Smart Engine.lnk",
"ÇÁ·ÎÅØÆ®ÀÎÆ÷.lnk",
"ÇÊÅõµ¥ÀÌ ¹Ù·Î°¡±â.lnk",
"IDº¸¾È.lnk",
"Ð¡ÓÎÏ·.url",
"ClubhardcoreLycos.lnk",
"Anti-Virus Elite.lnk",
"Gerenciador Financeiro.url",
"System Tool 2011.lnk",
"HDD Defragmenter.lnk",
"Security Essentials 2011.lnk",
"Disk Defrag.lnk",
"Smart Security.lnk",
"ScanZero.lnk",
"Quick Defragmenter.lnk",
"PCClear_Plus.lnk",
"PCClearSophos.lnk",
"Win Defrag.lnk",
"ThinkPoint.lnk",
"Check Disk.lnk",
"Ultra Defragger.lnk",
"Win Defragmenter.lnk",
"Win HDD.lnk",
"Hard Drive Diagnostic.lnk",
"Internet Security Suite.lnk",
"HDD Plus.lnk",
"Anti-Virus Professional.lnk",
"ÃÊ½ºÇÇµå ¹«ÇÑ ´Ù¿î·Îµå.lnk",
"HDD Rescue.lnk",
"Personal Security Sentinel.lnk",
"HDD Tools.lnk",
"Spy-Speed.lnk",
"Defragmenter.lnk",
"SmartBoan.lnk",
"Win Scanner.lnk",
"HDD Low.lnk",
"Personal Internet Security 2011.lnk",
"Quick System Cleaner.lnk",
"AntiVirus System 2011.lnk",
"Palladium.lnk",
"HDD Fix.lnk",
"Memory Fixer.lnk",
"IE AntiVirus 3.4.lnk",
"Fast Disk.lnk",
"Disk OK.lnk",
"Good Memory.lnk",
"Memory Optimizer.lnk",
"My Disk.lnk",
"Disk Optimizer.lnk",
"Smart Internet Protection 2011.lnk",
"Windows Disk.lnk",
"Auction.lnk",
"Search.lnk",
"¦+¦ª¦+-(.exe",
"MoneyMakerBot.lnk",
"SERVER\\Serv.exe",
"Internat Explorar.game",
"odnoklassniki.ru.lnk",
"Internet Security Essentials.lnk",
"AVG Antivirus 2011.lnk",
"Disk Recovery.lnk",
"Disk Repair.lnk",
"Scanner.lnk",
"Security Defender.lnk",
"Win Disk.lnk",
"Windows Scan.lnk",
"HDD Fix.lnk",
"Memory Fixer.lnk",
"Internet Defender.lnk",
"AntiVirus AntiSpyware 2011.lnk",
"Internet Defender.lnk",
"Win Scan.lnk",
"Windows Tool.lnk",
"svcgost.exe",
"Smart Defragmenter.lnk",
"Internet Explorer.du",
"Internet Explorer.msm4",
"NETVISION.lnk",
"cacaoweb.exe",
"Best Malware Protection.lnk",
"E-set Antivirus 2011.lnk",
"Windows Diagnostic.lnk",
"System Security 2009.lnk",
"level0.exe",
"level0.jpg",
"Internat Explorer.lnk",
"Internat Explorer.URL",
"Antivirus AntiSyware 2011.lnk",
"Intrenet  Exqlorer.lnk",
"Windows Repair.lnk",
"SafePrivate.lnk",
"Internet.tt",
"Internat Explorer.IE",
"BitDefender 2011.lnk",
"Antimalware Tool.lnk",
"Windows Fix Disk.lnk",
"Windows Recovery.lnk",
"Windows Restore.lnk",
"vicube.lnk",
"server.exe",
"Setup.exe",
"crypter.exe",
"ÌÔ±¦Íø.ÌØ¼Û.tep",
"ljxwjkdqlw.tmp",
"MR.AnEnO.lnk",
"PC Security Guardian.lnk",
"XP Police Antivirus.LNK",
"akte-pixde.lnk",
"Internat Exlparor.om",
"Internat Explorer.jgp",
"Internat Explorer.ogc",
"Internet Explorar.of",
"Internat Exlporar.op",
"Internet Explorar.ofc",
"Internat Exlporer.vo",
"Turkojan 4.0.lnk",
"Security Solution 2011.lnk",
"Intrenet Explorer.lnk",
"Raila Odinga.gif",
"vaccineu.lnk",
"Windows XP Recovery.lnk",
"Antivirus Center.lnk",
"Security Center.lnk",
"Windows 7 Recovery.lnk",
"Windows Vista Recovery.lnk",
"Internet Exqlorer.exe",
"System Smart Security.lnk",
"Milestone Antivirus.lnk",
"Security_Solution_2011.lnk",
"MastaPorn.lnk",
"Internet Explorer.IE",
"DOWNLOAD 5000.COM - FREE SOFTWARE, GAMES, TOOLS.lnk",
"OPEN SCREENSAVER.COM - HUNDREDS OF FREE SCREENSAVERS.lnk",
"Porno Links XP.lnk",
"Windows XP Repair.lnk",
"wowshell.lnk",
"Internet. Explorer..lnk",
"TagASaurus.exe",
"Sunhay.exe",
"Windows XP Restore EDS.txt",
"Windows XP Restore.lnk",
"GuaGua DanceShows.lnk",
"GuaGua KPlayer.lnk",
"Milestone Antivirus.exe.txt",
"Security Central.lnk",
"Security Essentials 2011.lnk",
"Wireshark Antivirus.lnk",
"System Diagnostic.lnk",
".bestie0",
"Internet Explorer.bestie",
"Memory Optimizer.lnk",
"nurungzi ¹Ù·Î°¡±â.lnk",
"Internat Exlporar.vo",
"Windows XP Fix.lnk",
"Security Solution.lnk",
"System Repair.lnk",
"Bkav2006.exe",
"Internet Explorer.html",
".lnk",
"IE.wri",
"Internat  Explorer.ogc",
"Internat Explorar.oc",
"Malware Protection.lnk",
"Internet  Explorar.ofc",
"Internet Expleror.hdh",
"Antimalware Doctor.lnk",
"Internet Exlporer.1mk",
"Security Essentials Ultimate Pack.lnk",
"Zentom System Guard.lnk",
"-.lnk",
"nudetube.com.lnk",
"pornotube.com.lnk",
"youporn.com.lnk",
"Your PC Protector.lnk",
" Intarnot   Explarer .lnk",
"BlueFlare Antivirus.LNK",
" Intornet   Explarer .lnk",
"Internet Protection.lnk",
"Search.lnk",
"Internet  Explorar.of",
"JMHL Loader.lnk",
"Security Solution1.lnk",
"online security guide.url",
"security troubleshooting.url",
"Security Protection.lnk",
" Intornat   Explarer .lnk",
"Cheap Pharmacy Online.url",
"Cheap Software.url",
"Internet Exploerr.tt",
"Internet Explorer.url",
"MP3 Download.url",
"MP3 to RingTone Gold.lnk",
"Search Online.url",
"SMS TRAP.url",
"VIP Casino.url",
"XP Cleaner.lnk",
"Security_Solution_2011.lnk",
"Improve Your PC.lnk",
"Explorer.tt",
"Internet Explorar.ov",
"Mes Amatrices.lnk",
"DofusBeta.lnk",
"Internet Explorer.dc1",
"Win Defrag.lnk",
".url",
"Coopen.lnk",
"Internet Explorer.NewIE",
"871E~1.URL",
"WolfRam AntiVirus.lnk",
"Free Mobile Ringtones.url",
"Antivirus Pro.lnk",
"AntiVirus_AntiSpyware_2011.lnk",
"Security Master AV.lnk",
"My Security Shield.lnk",
"Security Defender.lnk",
"Home Safety Essentials.lnk",
"Anti-Malware Lab.lnk",
"Advanced Security Tool 2010.LNK",
"Smart119.lnk",
"OpenCloud Antivirus.lnk",
"Internet  Explorer.io",
"ADOBE READER 9.qa",
"Internet  Explorer.qa",
"SHORTCUT TO TRACEMON.EXE.qa",
"Internet Explorer.io",
"Internet Explorer.pq0",
"KeyProwler.LNK",
"HDD Repair.lnk",
"Master Utilities.lnk",
"OpenCloud Security.lnk",
"PC Repair.lnk",
"System Recovery.lnk",
"SEX EXPLORER.lnk",
"Install AVSystemCare .lnk",
"readme.eml",
"Data Recovery.lnk",
" Intarnat   Explarer .lnk",
" Intornet   Explaror .lnk",
"Live Security Suite.lnk",
"MastaGirls.lnk",
" Internet Explorer .lnk",
"BEST DATING SITE IN THE NET.lnk",
"BEST DATING SITES CATALOGUE.lnk",
"BEST ONLINE DATING CHAT ROOMS.lnk",
"BEST ONLINE DATING MAGAZINE.lnk",
"BEST ONLINE DATING WEBCAMS.lnk",
"Internat Explor.html",
"Internat  Explorer.EOU",
"Internat  Explorer.rnk762",
"Security Tool.lnk",
"System Defender.lnk",
"Virus Shield 2009.lnk",
"Hot_Netherlands.lnk",
"ErrorKiller.lnk",
"Internat  Explorer.rnk6",
"Internot Exploror.exe",
"AV Guard Online.lnk",
"Guard Online.lnk",
"Asiansexfest.exe",
"Buy Prot-X PC Shield 2012.lnk",
"GirlsHost.exe",
"Guard Online .lnk",
"Lesbians.exe",
"Meet4Sex.exe",
"Pammyvideo.exe",
"Pornoland.exe",
"Sizzle.exe",
"SohoSexShop.exe",
"Strangesex.exe",
"The Adult Channel.exe",
"Internet Explorer.iop",
"Intrenet  Explerer .lnk",
"¡¡Internet¡¡¡¡Explorer¡¡.lnk",
"Cloud Protection.lnk",
"Buy Advanced PC Shield 2012.lnk",
"Security Guard 2012.lnk",
"Smart Defender PRO.lnk",
"Internat Explorer.dll",
"smartdefender pro.lnk",
"AV Protection Online.lnk",
"Malware Destructor 2009.lnk",
"Antivirus System PRO.lnk",
"My Security Engine.lnk",
"Windows Additional Guard.lnk",
"Antivirus Soft Platinum.lnk",
"Security Antivirus.lnk",
"Virus Sweeper.lnk",
"Installer VirusGarde .lnk",
"Platinum Antivirus.lnk",
"mzone-1334.exe",
"Security Solutions 2011.lnk",
"Contraviro.lnk",
"MyPornPics.zip.exe",
"Internat Explorar.lnk",
"¡¡Internet¡¡Explorer¡¡.lnk",
"Internet  Explorer.mf",
"Windows\\desktop.exe",
"caca2\\holaa.jpg",
"caca2\\server.exe",
"kPrivacy.lnk",
"test\\svchost.exe",
"Message For My Princess.scr",
"AV Security 2012.lnk",
"Internet Exlporer.jnk",
"½ºÅ¸ÇÙ°¨Áö±â.lnk",
"¹«·á¹®ÀÚ Give2SMS.lnk",
"CleanCatch.lnk",
"Open LanFile.lnk",
"antispy protector 2009.lnk",
"My Security Wall.lnk",
"Virus Melt.lnk",
"Anti-Porn.lnk",
"Cheap Holiday Travel.url",
"Free Online Music.url",
"System Fix.lnk",
"AV Protection 2011.lnk",
"²¥°ÔÍøÂçµçÊÓ.lnk",
"DBClean.lnk",
"MyCing.lnk",
"Windows PC Defender.lnk",
"Cloud AV 2012.lnk",
"Privacy Protection.lnk",
"Antivirus Master.lnk",
"SafeVaccine.lnk",
"System Check.lnk",
"Fuckhouse.exe",
"Buy Ultimate PC Shield.lnk",
"FREE BonziBUDDY.url",
"Porn2Peer.lnk",
"MicroVaccine.lnk",
"MYLOVE111.lnk",
"Security Monitor.lnk",
"Internet Security Guard.lnk",
".bt",
"Interne.tt",
"Windows Disk.lnk",
"WinHeal Utilities.lnk",
"Home Malware Cleaner.lnk",
"Strong Malware Defender.lnk",
"VaccineTop.lnk",
"Windows Shield Tool.lnk",
"Windows Smart Warden.lnk",
"hotsex.lnk",
"Windows Threats Destroyer.lnk",
"Internet Explroer.lnk",
"Windows Personal Detective.lnk",
"Best Virus Protection.lnk",
"Windows Performance Catalyst.lnk",
"Windows Personal Doctor.lnk",
"Windows Functionality Checker.lnk",
"Hot_Tarts_ca.lnk",
"Windows Tools Patch.lnk",
"Internet Security.lnk",
"Windows Managing System.lnk",
"XXXmpeg_tr.lnk",
"Intarnat Explarar.lnk",
"Windows No-Risk Center.lnk",
"Windows Security Kit.lnk",
"Windows Antihazard Solution.lnk",
"Windows Health Keeper.lnk",
"Windows Problems Stopper.lnk",
"Windows Guardian Angel.lnk",
"Windows Process Director.lnk",
"Windows AntiHazard Helper.lnk",
"best bdsm p0rn.url",
"gay fetish sex.url",
"HackSearcher.lnk",
"sexxx.lnk",
"Windows No-Risk Agent.lnk",
"Windows Defending Center.lnk",
"Windows Trouble Taker.lnk",
"Windows First-Class Protector.lnk",
"Gay_Sexy_nl.lnk",
"Windows Activity Debugger.lnk",
"Windows First-Class Proctector.lnk",
"Mijn Virtualwonder.exe",
"Windows Warding System.lnk",
"Cheap Cigarettes.url",
"Currency Trading.url",
"EasyDates.lnk",
"Windows Shielding Utility.lnk",
" ANONYMOUS WEB SURFING!.url",
" Hottest-teen Tgp.url",
" PROTECT YOUR ONLINE PRIVACY!.url",
" Youngest girls TGP.url",
"HotVideo_ie.lnk",
"Windows Custodian Utility.lnk",
"Windows Care Taker.lnk",
"Antimalware PC Safety.lnk",
"Windows AntiHazard Center.lnk",
"Windows Attacks Defender.lnk",
"Windows Attacks Preventor.lnk",
"Windows Basic Antivirus .lnk",
"Windows Debug Center.lnk",
"Windows Firewall Constructor.lnk",
"Windows Guard Angel.lnk",
"Windows Malware Sleuth.lnk",
"Windows PRO Scanner.lnk",
"Windows Risk Minimizer.lnk",
"Windows Safety Tweaker.lnk",
"Windows Smart Partner.lnk",
"Windows Software Keeper.lnk",
"Windows Software Saver.lnk",
"Windows Telemetry Center.lnk",
"Windows Trojans Inspector.lnk",
"Windows Efficiency Reservoir.lnk",
"Cashfiesta.lnk",
"Windows Stability Maximizer.lnk",
"MSDCSC\\a7a.exe",
"Windows Cleaning Tools.lnk",
"Windows Component Protector.lnk",
"Windows Antibreaking System.lnk",
"Hardcore.url",
"Simalach.lnk",
"Windows Crucial Scanner.lnk",
"online spyware test.url",
"Windows Protection Unit.lnk",
"Windows Antivirus Patch.lnk",
"Windows Guard Solutions.lnk",
"SMART_HDD.lnk",
"Windows Pro Rescuer.lnk",
"Windows Safety Toolkit.lnk",
"Windows Performance Adviser.lnk",
"svchost.exe",
"Windows Premium Guard.lnk",
"Windows Foolproof Protector.lnk",
"Windows Safety Checkpoint.lnk",
"Windows Safety Manager.lnk",
"Windows High-End Protection.lnk",
"Windows Safety Module.lnk",
"Windows High-End Protection.lnk",
"Windows Recovery Series.lnk",
"Windows Safety Module.lnk",
"Windows Daily Adviser.lnk",
"ds-eu\\ds-eu.exe",
"Hash-epu\\Hash-epu.exe",
"datass\\datass.exe",
"Best Antivirus Software.lnk",
"Total Anti Malware Protection.lnk",
"Windows Pro Web Helper.lnk",
"hazha\\msdcsc.exe",
"Beyond Domaining Domain Development and Content Mini Sites.LNK",
"Fullmovies com 1 Affiliate Program For Movie Downloads.LNK",
"Windows Pro Solutions.lnk",
"Amazing Anal.url",
"Windows Abnormality Checker.lnk",
"Playboy_de.lnk",
"Windows Advanced User Patch.lnk",
"Windows Be-on-Guard Edition.lnk",
"Windows Internet Booster.lnk",
"Windows ProSecurity Scanner.lnk",
"Windows Sleek Performance.lnk",
"FREE Ringtone Click Here!.url",
"Hot_Pleasure.lnk",
"XXX Porn.url",
"Windows Secure Surfer.lnk",
"Windows Web Secure Kit.lnk",
"Data_Recovery.lnk",
"2162~1.URL",
"A7D3~1.URL",
"WallHack by wopox.lnk",
"ÄÄ¿ÀÇÁ.lnk",
"Windows Pro Safety Release.lnk",
"seksokulu.lnk",
"Windows Multi Control System.lnk",
"System Protection Tools.lnk",
"Windows Private Shield.lnk",
"Windows Pro Safety.lnk",
"Windows Guard Tools.lnk",
"HornyGirls_es.lnk",
"Windows Defence Counsel.lnk",
"Windows Safety Maintenance.lnk",
"Windows Antivirus Rampart.lnk",
"Windows Ultimate Security Patch.lnk",
"Personal Antivirus.lnk",
"Live Security Platinum.lnk",
"Windows Malware Firewall.lnk",
"Live Security Platinum Support Site.url",
"Windows Safety Wizard.lnk",
"Windows Turnkey Console.lnk",
"Windows Pc Aid.lnk",
"Windows Maintenance Suite.lnk",
"FreeFreeFree.lnk",
"Make Money.lnk",
"Windows Custom Safety.lnk",
"Windows Privacy Module.lnk",
"Windows Instant Scanner.lnk",
"ClearVaccine.lnk",
"Adult_Partners.lnk",
"Asian Sluts.url",
"Crack.lnk",
"Download Internet_Download_Manager_v_6.lnk",
"Download IP_Man__2008_.lnk",
"Download Winning_Eleven_7.lnk",
"Live PC Care.lnk",
"Hot Teen movies.url",
"AntivirusXP.lnk",
"__morteza_z_v_.exe",
"Windows Maintenance Guard.lnk",
"Windows Proactive Safety.lnk",
"FileVaccine.lnk",
"Live Security Platinum Support Site.url",
"Windows Advanced Toolkit.lnk",
"Windows Control Series",
"Windows Pro Defence.lnk",
"VitaVaccine.lnk",
"Windows Proprietary Advisor.lnk",
"Live Sex.exe",
"Windows Interactive Security.lnk",
"Windows Web Commander.lnk",
"VaccineForce.lnk",
"Windows Expert Series.lnk",
"Windows Security System.lnk",
"Windows Virtual Angel.lnk",
"Windows Web Combat.lnk",
"Windows Premium Defender.lnk",
"Windows Virtual Firewall.lnk",
"Windows Security Renewal.lnk",
"e1xplorer.lnk",
"Windows Active Guard.lnk",
"Anonimous Serfing.url",
"Hot Dream.lnk",
"Hot_Tarts_es.lnk",
"iexplor.lnk",
"Sex Forum.url",
"HotWetLove.lnk",
"System Error Fixer.url",
"Windows Interactive Safety.lnk",
"Windows Antivirus Release.lnk",
"Windows Virtual Security.lnk",
"Windows Anti-Malware Patch.lnk",
"Windows Secure Workstation.lnk",
"MastaBlondes.lnk",
"NOD Enabler.lnk",
"Windows Safety Series.lnk",
"Sexnow.exe",
"SexNow.lnk",
"Download [GAY]_Shank_-_VOstFR_-_DVDrip.lnk",
"Download Avatar_Full_3D_(Stereoscopic_Side.by.Side)_1080p_Dual-Audio.lnk",
"Download Call_of_Duty_Black_Ops-SKIDROW.lnk",
"Download Driver_Genius_Professional_11_0_0_1128+Crack+SerialA4_rar.lnk",
"Download Fantastic_Farm.lnk",
"Download Mcafee_AntiVirus_2010(included_licence_key).lnk",
"Download OReilly_Machine_Learning_for_Hackers_2012_eBook_repackb00k.lnk",
"Download Plug_Ins.lnk",
"Download SeePassword_v2.lnk",
"Download Snow_White_and_the_Huntsman__2012__DVDScR_XviD_AC3___AGCX.lnk",
"Cigarettes Discount.lnk",
"Group Sex.lnk",
"Phentermine.lnk",
"Porn Dvd.lnk",
"Viagra.lnk",
"Antivirus Live Platinum.lnk",
"Get Films Now Information.lnk",
"HardcoreVideos_au.lnk",
"krering39x.lnk",
"LiveSexCam_ca.lnk",
"Hardcore Sex.url",
"Hot_jp.lnk",
"instant access.lnk",
"Buy Win 8 Security System.lnk",
"File Recovery.lnk",
"Windows Security System.lnk",
"Anal Sex.url",
"Gay Studs.url",
"Hot_Tarts_de.lnk",
"Softteen-HOT.lnk",
"MSDCSC\\msdcsc.exe",
"Inteenet Explooer.lnk",
"goodthinxx.lnk",
"PC Defender Plus.lnk",
"trojaner.exe",
"bradesco-cadastro-concluido.exe",
"Chisel.exe",
"Sexleksaker.lnk",
"scolt.exe",
"Internat Exp1orer.n",
"Internet Exlporar.lnk",
"LiveSexCam_hk.lnk",
"SessoXXX.lnk",
"pornaccess-1.lnk",
"winupdate.exe",
"sexy nazi.exe",
"System Progressive Protection Support Site.url",
"System Progressive Protection.lnk",
"XP Defender.lnk",
"VaccineTek.lnk",
"jbest00000.lnk",
"VirtualVaccine.lnk",
"LimitVaccine.lnk",
"Vaccine7.LNK",
"GayXxXHunks.lnk",
"Sexfilms.exe",
"DeskVaccine.lnk",
"Hardcore Fucking.url",
"Hot Amateurs.url",
"True Butts.url",
"22find.lnk",
"gay_sexy.lnk",
"Intrenet  Explorer.lnk",
"netspyprotrial.zip",
"Teen Babes.url",
"uch_angl_yaz_shk_2kl_biboletova_file.zip",
"www.limit-no-sesso.com.lnk",
"Continuare Titan Poker setup.lnk",
"Continue Abdio Free MP4 Player Installation.lnk",
"Continue avast! Free Antivirus Installation.lnk",
"Continue CorelDRAW Installation.lnk",
"Continue Document.Editor Installation.lnk",
"Continue DWG Converter. Installation.lnk",
"Continue EagleGet Installation.lnk",
"Continue Hacking Passwords Installation.lnk",
"Continue MediaHuman Audio Converter Installation.lnk",
"Continue Microsoft WorldWide Telescope Beta Installation.lnk",
"Continue PDF Shaper Installation.lnk",
"Continue QRP Viewer Installation.lnk",
"Continue Registry Life Installation.lnk",
"Continue Restorer2000 Installation.lnk",
"Continue Spark Browser Installation.lnk",
"Continue SpeedyiTunes Installation.lnk",
"Continue Tor Installation.lnk",
"Continue UNetBootIN Installation.lnk",
"Continue Usejump Installation.lnk",
"Continue Zelda_.rmskin Installation.lnk",
"njRAT.exe",
"RUN AFTER CONIFG-HACK FILES.exe",
"Intrenet Expolrer.lnk",
"WhiteVaccine.lnk",
"System Doctor 2014 support.url",
"System Doctor 2014.lnk",
"Inetimer Explorer.lnk",
"1337 Hax0r.bat",
"PC Defender 360.lnk",
"24x7 Help.lnk",
"Yugoslavia_sex.lnk",
"EZDownloader.lnk"

            };

            // Path to the Desktop directory
            string desktopPath = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);

            Console.WriteLine("Scanning files on Desktop...");

            try
            {
                // Get all files in the Desktop directory
                string[] files = Directory.GetFiles(desktopPath, "*.*", SearchOption.TopDirectoryOnly);

                // Check each file against the blacklist
                foreach (string file in files)
                {
                    string fileName = Path.GetFileName(file);

                    if (blacklistedFiles.Contains(fileName))
                    {
                        Logger.Instance.LogPrimary($"Blacklisted file found: {file}");
                        // Optionally, take action (e.g., delete or quarantine the file)
                        // File.Delete(file); // Be cautious with this line!
                    }
                }
            }
            catch (UnauthorizedAccessException ex)
            {
                Console.WriteLine($"Access denied to the Desktop directory: {ex.Message}");
            }
            catch (PathTooLongException ex)
            {
                Console.WriteLine($"File path too long: {ex.Message}");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred during scanning: {ex.Message}");
            }

            Console.WriteLine("Scan complete.");
        }
    }
}
