using System;
using System.Collections.Generic;
using System.IO;

namespace Wildlands_System_Scanner.Blacklist
{
    public class LocalAppDataFolderBlacklist
    {
        public static void ScanForBlacklistedFolders()
        {
            // Predefined blacklist of Local AppData folder names (case insensitive)
            HashSet<string> blacklistedFolders = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
            {
"activedbpack",
"Adobe updater",
"AlphaWipe",
"AntiVirus Plus",
"appcatlibrary",
"atmctlcmp",
"atmmsvcruntime",
"atmsp60",
"atmxmld9",
"audiontcmp",
"audionvrsClient",
"audiop2psound",
"audiorpcClient",
"Automated Content Enhancer",
"AutoStylingPlugin",
"avicomdg",
"avinvwrmulti",
"aviwsGlade",
"browseaviruntime",
"browsenetClient",
"browserpcGlade",
"catiasdg",
"catp2pgfx",
"CloudWeb",
"comaudiod8",
"Communication Today",
"comodbc3d",
"comsys60",
"cryptscruntime",
"ctlappdrv",
"ctlatmruntime",
"ctliepack",
"ctlwm64",
"ctlwssound",
"Customized Platform Advancer",
"d3davilibrary",
"d3dfontruntime",
"d3drpc32",
"d3dwsmulti",
"dbatmsound",
"dbxmlLang",
"deskws97",
"dllcatLang",
"dlldesk60",
"dllsp64",
"dllstream50",
"dmnetlibrary",
"dmnvmcDirect",
"dmsh32",
"dmstoruntime",
"DoubleD",
"Downloaded Installations\\{5B00B6A7-3352-415F-A7C2-ABCCCEC5383E}",
"Downloaded Installations\\{99EB2353-C368-42D5-AFEA-1F956E079C38}",
"Downloaded Installations\\{E5FF35CB-AAE1-4CD6-BFDE-D0BCE9CCBA4C}",
"Downloaded Installations\\{F9B9ED60-8ABE-4008-A452-AC24A7B0AE52}",
"drvxslek32k",
"esentsttools",
"eyswpy",
"fontactived9",
"fontatmgfx",
"fontcomd8",
"fontcomruntime",
"fontperfmulti",
"Fontstlibrary",
"GameBrinking Toolbar",
"GameRaving Toolbar",
"GamezJoint Toolbar",
"GamezMission Toolbar",
"Gameztar Toolbar",
"GamiePlay Toolbar",
"HandyGamez Toolbar",
"hjcmer",
"HottieArcade Toolbar",
"HottieArea Toolbar",
"HottieStar Toolbar",
"hxougu",
"iasmapDraw",
"ienvmclang",
"ieusr50",
"ifugpb",
"Internet Content Updater",
"Internet Saving Optimizer",
"Internet System Controller",
"Internet Today",
"JuicyJoint Toolbar",
"JuicyJunction Toolbar",
"JuicyPalace Toolbar",
"kbdactiveruntime",
"kbdctl50",
"lclfilcfg",
"live 64 math does",
"Live Content Advancer",
"Live Enterprise Suite",
"localesentCMP",
"localntLang",
"localsclibrary",
"localxmlruntime",
"LuckyEstimation",
"MacroAV",
"mapwinruntime",
"mapwm32",
"mdply3d",
"Media Access Startup",
"Microsoft Security Essentials",
"microsoft\\internet explorer\\filters",
"mmcbrowse97",
"mmcnt97",
"mmcwinDirect",
"msplyi2d",
"msrrasLang",
"msvcdmCMP",
"msxmlctlDirect",
"msxmlmapdirect",
"mtg",
"My Security Engine",
"ntappdrv",
"ntatm50",
"ntias64",
"ntshdg",
"nvrsctl97",
"nvrsdmruntime",
"nvwroleClient",
"nvwrspd9",
"nvwrsqCMP",
"nvwrstream60",
"odbckbd32",
"p2pbrowseLang",
"p2psys64",
"p2pxmld8",
"perfnvwr64",
"perfsqdrv",
"perfsyssound",
"perfwsruntime",
"PornaZtar Toolbar",
"PrivacyKit",
"pubmedia32db",
"qip",
"RADIO_USA",
"rasole64",
"regsdkrl32",
"rndl64",
"rpcatm97",
"rpcwinGlade",
"searchfree",
"shactivesound",
"shrpcpack",
"shwmClient",
"sqnvrsdrv",
"stdeskLang",
"stolocalruntime",
"stoperfDraw",
"stoshclient",
"streamctl3dsound",
"streamsp60",
"sysapp32",
"sysbrowseclient",
"sysctl3ddg",
"sysesentDirect",
"sysmapd9",
"sysnvrssound",
"syswinGlade",
"Target Marketing Agency",
"TempDIR",
"Textual Content Provider",
"Textual Media Service",
"upsqCMP",
"usrdesk60",
"Web Search Assistant",
"Web Search Operator",
"winclb64",
"windrvswld83",
"winelwske95",
"winjwws92",
"winnvwrlibrary",
"winusrdrv",
"wmnetgfx",
"wmrpcd9",
"wmstreamsound",
"wsclbClient",
"wsnpoem",
"Xenocode\\Sandbox\\UBot_Standalone",
"xmlaudioGlade",
"xmlie64",
"xmlmap97",
"xmlp2pGame",
"xpcom64",
"xpiastools",
"xpmap64",
"t3e0ilfioi3684m2nt3ps2b6lru",
"{BBDE46F8-5605-F5A0-AC45-61089EC1F601}",
"DRMNetVdm",
"Windows Internet Name Service",
"Microsoft\\Windows Winpad",
".#",
"smartfinder",
"kbdnetsvc",
"OpenShopper",
"ServicePack",
"{2B36EA7D-AC3F-008E-6A95-524974F4D4A3}",
"MyData",
"awnlprtc",
"MSNUserOffice",
"hantiat6",
"ieCommsInit",
"smpEventHelper",
"DevPadclass",
"WinPadapi",
"eventCommonmon",
"i18cfgTask",
"SmartAuthenticationClock",
"advapispl",
"advMapMusic",
"mfccfgNotifier",
"Programas-GRATIS.net",
"AppMapCres",
"Microsoft\\WindowEzSearch",
"Microsoft\\Windows linkplus",
"SyncPathMgmt",
"xercle",
"01U79NB5DE2G2T2",
"goodtrans",
"Windows Server",
"AgereComms32",
"fxcfgSvcs",
"jclass",
"odbccrtSched",
"linkinside",
"CatDBcrtext",
"dbWebhid",
"enterpop2",
"HandlerMainlib",
"del",
"lanNetdlg",
"msobjCtrl",
"se",
"setup4",
"tcpCommsInit",
"AgerePath64",
"HpPadcdrom",
"AcroCommonMusic",
"Hpcfgserv",
"WinWebHelper",
"tapiapiplugin",
"C575E8A8-16E2-4C95-AE36-0BA9C90710B0",
"fontmsrDirect",
"confUserTime",
"setup3",
"usbGLTrust",
"appMouseMusic",
"AsyncCommonspl",
"CdCommonTask",
"ClipobjServ",
"i18Pathlib",
"rVzWJrYn",
"SGxBAr",
"BthMobilexx",
"CdPathLite",
"CvtGLTray",
"dBdEhjPcRS",
"hhaikAIVCl",
"AsyncPathAgent",
"jgeqycgpk",
"rasWIdb",
"SysNetPort",
"userComms80",
"advmapServices",
"DesktopEventCmds",
"DevEventds",
"olePathCres",
"tcpmapman",
"DRMWImon",
"CRLnetdsc",
"DirectMobilesvc",
"winmapSnap",
"wmiPadnt5",
"ArVzWJrY",
"dllnvwrdrv",
"kbdodbctools",
"ktsdobdc",
"winup64",
"confMapServices",
"dbGLAgent",
"EapGLAgent",
"SystemMapserv",
"AcroPadnt5",
"admin.exe",
"i18Commsnet",
"mciMainplugin",
"advNetAgent",
"AppMouseLite",
"appWebpnp",
"com2gom",
"compatEventmon",
"CvtmapSupport",
"WdMapCres",
"appGLspl",
"AppleCommsRpl",
"backwall",
"DfrgMapdsc",
"Directcrtmon",
"DRMMapOffice",
"eventUserxx",
"eventWebmm",
"MICROSOFT\\WINDOWS EZ2POP",
"odbcCommsdll32",
"Securityx86_x64.dll",
"userobjdlg",
"UtilnetMusic",
"VzWJrYnjU",
"{FFD13701-7010-E421-9CE4-0DB8C731A0A1}",
"Jgosht",
"spup97",
"XintaCasa",
"backwall",
"MicrosoftWindows",
"._Revolution_",
"dd80",
"smart-pop",
"splashant",
"v1",
"Topblast",
"BArVzWJrY",
"xBArVzWJ",
"MossySkySA",
"Minibar",
"luserout",
"uninstl",
"kesinfoi",
"Toulethallow",
"ResearchBits",
"comoqook",
"Google\\Chrome\\User Data\\Default\\Extensions\\nbjalljmflcleoebdcbkfendfbajflei",
"livefloat",
"WinLogon",
"s00rk",
"advobj3xx",
"truepod",
"Windows Defender\\Analizer",
"xpeadup7",
"Mikrosoft",
"Recycle",
"Microsoft\\MicrosoftData",
"Unilessss",
"mycinein",
"xBArVzW",
"ghqqpgv",
"hcwgxmjt5",
"assembly\\tmp",
"Dard-Shayari-3",
"wiirjobwnalo",
"yxwjioafthao",
"service2",
"bohoirlau",
"ckck",
"wxizugaqv",
"vtjxyfxgvyvft",
"wiiuuhhdemnahl",
"xpobjext",
"AcroMouse80",
"AppIs",
"AppleHelpARM",
"BluetoothapiCtrl",
"CvtnetPlay",
"eapWIdsc",
"h4jatuuf",
"HpCommsppm",
"lannetIde",
"qtvwthmdft",
"uigndkjn",
"vyxojapohqrflk",
"wliecrt0yzy4",
"wriubsshqqz",
"cgz6o1sarq3",
"jsohcqzpakoxwy",
"rrqetqdqeb",
"syujqogmrai6lvg1",
"ModenRoil",
"enterpop",
"ymlyjrfwpozh",
"kbtkoepkuolnw",
"maokigfrzcxildr",
"rnjpuov",
"ecsciao9cdzynhr",
"winpnp",
"cxcniqxxg",
"$GPATH",
"jgkzcevdicptap",
"vbprtboswr",
"cmutmsedkmtfmq",
"rqxnsrssznelzqg",
"wqakkvmmdlnu",
"yjknybr",
"elwgmtctuotpy",
"rnfgtrslkfdkg",
"BiosUpdate",
"blueturtlegamesSA",
"WinUpdate",
"ModenQuick",
"Wizeni",
"01U79NB5DE2G2T2AWC",
"Ipop",
"MozinScale",
"Hegcge.",
"EIcon",
"directsearch",
"EapHelpserv",
"MicrosoftToppoint",
"OutlookPluss",
"ClickSystemToolbar",
"ModinHeps",
"bizpop",
"EoRezo",
"MSoft",
"openkeyword",
"zerowins",
"Browseforchange",
"Sthels",
"ShamrockSpringSA",
"CouponDropDown",
"I Want This",
"VMware\\Identities",
"VMware\\Microsoft",
"VMware\\Mozilla",
"HippoGeekSA",
"ZeroCoool",
"slink",
"SnappyDeeSA",
"EasyPop",
"WideSearch",
"ArVzWJrYn",
"{4AQO4PS1-KWIN-TJ97-1CNP-8517G05MATGZ}",
"Dounsfr",
"Savings Sidekick",
"Vid-Saver",
"tiptw",
"Bluetoothh",
"WebEdit",
"Winscare",
"stlocal50",
"AA",
"winolepack",
"WinAid",
"shsqsound",
"VidShakeSA",
"XPeria3g",
"dealcabby",
"GamesLeapSA",
"Goenjoy",
"TeeveeWatchSA",
"MobinSkills",
"BrightBreezeSA",
"Microsoft\\winsrv64",
"WinsManager",
"lollipop",
"FFoxDost",
"WinsPop",
"Google\\Chrome\\User Data\\Default\\Extensions\\agjhcnakilliakbimljljjhdgcahnkpd",
"Google\\Chrome\\User Data\\Default\\Extensions\\ahighnpdjgomnhbdgifbddhmljpleeii",
"Google\\Chrome\\User Data\\Default\\Extensions\\bfgnhokocpolpmgfhkmejhebjffbkobi",
"Google\\Chrome\\User Data\\Default\\Extensions\\dbnmldohjalplmpanngmlffmpoofcaea",
"Google\\Chrome\\User Data\\Default\\Extensions\\digfjgjpfhkonkckmkihkonljajcpomi",
"Google\\Chrome\\User Data\\Default\\Extensions\\ffhlojaklemjipikkljpmefkknjgfdjp",
"Google\\Chrome\\User Data\\Default\\Extensions\\fidpfigokpoglhkdfohkmpknigjebjmh",
"Google\\Chrome\\User Data\\Default\\Extensions\\gjahdogncjigfcanoefkjeamojkakfhg",
"Google\\Chrome\\User Data\\Default\\Extensions\\hkedlchiicpdmckbcamfpjhhmffgmond",
"Google\\Chrome\\User Data\\Default\\Extensions\\ihnkbmkomfochmlmkhojjflmemoacljh",
"Google\\Chrome\\User Data\\Default\\Extensions\\kjejhdpmfngkihaacbmhmffalpdjhmlm",
"Google\\Chrome\\User Data\\Default\\Extensions\\knikfdlhadnigopbooddgmmmeiikcdpk",
"Google\\Chrome\\User Data\\Default\\Extensions\\lcaflbdnfmknjngohcodinlafcemijip",
"Google\\Chrome\\User Data\\Default\\Extensions\\ljddkiabkpehpeokllcnaliigfjkkcaa",
"Google\\Chrome\\User Data\\Default\\Extensions\\mfopfenlobkfohbkbnmanmiccbballpe",
"Google\\Chrome\\User Data\\Default\\Extensions\\mlfbilgmjgkljonnpmklpeiapabcbbaa",
"Google\\Chrome\\User Data\\Default\\Extensions\\ncabkdbfekilifjehhndchdjmoafjaab",
"Application DataJrwoypy",
"CertifiedToolbar",
"SimplyTech\\Toolbar",
"Microsoft\\VMware",
"Securityapiplugin",
"SecuritymapEnum",
"bacon",
"clickup",
"amtmqlv",
"2433f433",
"TopArcadeHits",
"usercfgusb",
"usrobjMusic",
"appmarket-",
"NativemapInterval",
"sysCommonInterval",
"WhiteSmoke_B",
"windowviewcon",
"DProtect",
"SRycwglGly",
"degxct7M",
"TGQ0HE3M",
"VpwsFJ0r",
"asXPrj72JU",
"Pzor1nIYC6",
"windowpurchase",
"windowstab",
"KbiIZ2EZ",
"startertv_fr_12",
"fnLn5PstuuR",
"windisplay",
"WindwUpdate",
"WindwUpdate",
"TBHostSupport",
"X3e25TfH",
"zB4ewJh3wk",
"l00t1",
"EAEVQjqbSjY",
"Mining",
"Windows Host Controller",
"searchlike",
"cgminer",
"BXTuLoea",
"Start Savin",
"windowviewcone",
"playnowradio",
"SysPathServ",
"OperateExplorer",
"Plus500",
"Savings Season",
"Flo0oder_Dmar7",
"Browse Safe",
"Browser Hero",
"Coupon Alerts",
"Coupon Champ",
"Coupon Champion",
"Coupon Server Helper",
"Coupon Server",
"Discount Buddy",
"Discount Dragon",
"DropinSavings",
"Gigantic Savings",
"Gossiper",
"Instant Savings App",
"Majestic Savings",
"Mario_Foreverb",
"ProtectedBrowsing",
"RadioTotal3",
"Rope In Sales",
"SafetySearch",
"Savings Avenger",
"Savings Explorer",
"Savings Hen",
"Savings Wizard",
"SB_Tool_Bar",
"Sharp Savings",
"SlamDunk Savings",
"speedtest127",
"Supreme Savings Helper",
"Surf Safely",
"Atomic Savings",
"Browsing Protection",
"Deal Boat",
"Deal Slider",
"Download Helper",
"FreeOnlineRadioPlayerRecorder_V1",
"Fun_Media_Bar_V9",
"Lightning Savings",
"Savings Vault",
"SweetTunes1",
"Tbccint",
"Windows Deffense",
"Coupon Locker",
"Coupon Waterfall",
"protectedsurf",
"protectedsurf",
"Savings Hero",
"._LiveCode_",
"Bee Coupons",
"Browser Warden",
"Savings Champion",
"svsh",
"Savings Wave",
"storegid",
"newplayer",
"ContextFree",
"speedtest199",
"Microsoft\\Internet Explorer\\imagestore\\vfqzeqr",
"BrowserSafeguard",
"Coupon Companion",
"Shopping Sidekick",
"Solid Savings",
"pennybeepro",
"Savings Addon",
"BrowserProtector",
"Discount Dragon (Staging Test)",
"FlashContainer\\bin\\bfg32",
"FlashContainer\\bin\\bfg64",
"FlashContainer\\dll",
"shsys",
"Ghost Security Suite_is1",
"GoldenCrossss",
"Microsoft\\WinU",
"rasCommonCtrl",
"svchost",
"WINDOWS",
"winWebSvcs",
"Browser Champion",
"Browser Guardian",
"ConvertAd",
"Default Folder",
"DevenportUpdater",
"jusched",
"mojie",
"Playbryte",
"Software Refresher",
"TebeInteresno",
"Microsoft Config",
"Mr_CF_Mutation.U",
"Mr_CF_Mutation.UltimaWeapon",
"LXTNavi",
"WinFixex",
"ZXTMagic",
"Slick Savings",
"TheCompany\\Another World",
"TheCompany\\RuffNTumble",
"Clean Browser",
"Search Defense",
"Surfing Safeguard",
"wincheck",
"Media-accuse",
"Media-bother",
"Media-discipline",
"Media-distribute",
"Media-exit",
"Media-finger",
"Media-mouth",
"Media-shoe",
"Media-wall",
"Media_buddy",
"Media_contribute",
"Media_impress",
"Media_secure",
"Mediaserve",
"Mediatransition",
"Browse Secure",
"clicup",
"Coupon Samurai",
"Coupon Slider",
"Deal Spy",
"Deal Vault",
"DeSmuME",
"newtab",
"NTManager",
"Surf Safer",
"Tiger Savings",
"Broadway Partners Browse Safe Split Test",
"defender01",
"GoogleChromeService",
"GoogleChromeUpdater",
"Install Daddy Browser Champion Split Test",
"KeyCoupons",
"Offercrowd",
"Search Safer",
"shesent50",
"SmartWeb",
"taskdwm",
"Web Safeguard",
"Web Warden",
"WindowsCloudService",
"WindowsLocalHostProcess",
"WindowsServiceClouder",
"AppData\\Local\\Hall_charge",

            };

            // Path to the Local AppData directory
            string localAppDataPath = @"C:\Users\12565\AppData\Local";

            Console.WriteLine($"Scanning folders in {localAppDataPath}...");

            try
            {
                // Ensure the directory exists
                if (!Directory.Exists(localAppDataPath))
                {
                    Console.WriteLine($"Directory not found: {localAppDataPath}");
                    return;
                }

                // Get all subdirectories in Local AppData directory
                string[] directories = Directory.GetDirectories(localAppDataPath, "*", SearchOption.AllDirectories);

                // Check each folder against the blacklist
                foreach (string directory in directories)
                {
                    string folderName = Path.GetFileName(directory);

                    if (blacklistedFolders.Contains(folderName))
                    {
                        Logger.Instance.LogPrimary($"Blacklisted folder found: {directory}");
                        // Optionally, take action (e.g., delete or quarantine the folder)
                        // Directory.Delete(directory, true); // Be cautious with this line!
                    }
                }
            }
            catch (UnauthorizedAccessException ex)
            {
                Console.WriteLine($"Access denied to some directories: {ex.Message}");
            }
            catch (PathTooLongException ex)
            {
                Console.WriteLine($"Folder path too long: {ex.Message}");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred during scanning: {ex.Message}");
            }

            Console.WriteLine("Scan complete.");
        }
    }
}
