using System;
using System.Collections.Generic;
using System.IO;

namespace Wildlands_System_Scanner.Blacklist
{
    public class ProgramFilesX86FolderBlacklist
    {
        public static void ScanForBlacklistedFolders()
        {
            // Predefined blacklist of folder names in Program Files (x86) (case insensitive)
            HashSet<string> blacklistedFolders = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
            {
"diskfree",
"moviebox",
"pornoplayer",
"purityscan",
"ucmore - the search accelerator",
"videobox",
"bravesentry",
"Outerinfo",
"XXXAccess",
"ad-protect",
"VirusLocker",
"freevideo",
"Brave-Sentry",
"GoAstro",
"GoRecord 2",
"InternetGameBox",
"MessengerSkinner",
"SudoPlanet",
"WebMediaPlayer",
"BestsellerAntivirus",
"StorageProtector",
"OnlineHelpmate",
"HDD Low",
"SecureFighter",
" Eco AntiVirus",
"007 Anti-Spyware",
"123Keylogger Software",
"2M Free Tetris",
"AAntivirus",
"AccessMV",
"Active Security",
"Ad-Ware Pro",
"Addicting Block",
"Addwere.com",
"Adio Registry Optimizer",
"Adparatus",
"AdSafer",
"Advanced XP Defender",
"AdvancedCleaner Free",
"AdvancedPrivacyGuard",
"AdvancedPrivacySuite",
"Advansed Spyware Detector",
"Adware Alert",
"Adware Away",
"Adware Patrol",
"Adware Pro",
"Adware Professional",
"Adware Remover",
"Adware_Pro",
"AdwareAlert",
"AdwareBlocker.com",
"AdwareBot",
"AdwareCatch.com",
"AdwareCatcher.com",
"AdwareCheck.com",
"AdwareCops.com",
"AdwareCrusher.com",
"AdwareDestroyer.com",
"AdwareDetect.com",
"AdwareDetector.com",
"AdwareEraser.com",
"AdwareFREE",
"AdwareGuard.com",
"AdwareInspector.com",
"AdwarePro",
"AdwareShield.com",
"AdwareTerminator.com",
"AdwareWipe.com",
"AdwareZapper.com",
"AdWash.com",
"AIM Monitor Sniffer",
"AlertSpy",
"AlfaAntiVirus",
"AlfaBR",
"AlfaDivx",
"Alfampeg",
"Alpha Antivirus",
"AlphaAnt",
"AlphaAV",
"ANG AntiVirus 09",
"Anonymous Friend",
"Anti-Spam Bastion",
"Anti-Virus-1",
"Anti-Virus Professional",
"Anti-Virus&Spyware",
"Anti Spam Boy",
"Anti Virus Armor",
"Anti Virus Pro Spyware remover",
"AntiAdd",
"AntiAID",
"AntiKeep",
"AntimalwareDefender",
"AntiMalwareGuard",
"AntiMalwarePro",
"AntiMalwareSuite",
"Antispy Protector 2009",
"AntiSpy",
"AntiSpyBoss",
"AntispyKnight",
"AntispyStorm",
"AntiSpyware 2010",
"AntiSpyware Pro",
"AntiSpyware2008",
"AntiSpywareControl",
"AntiSpywareDeluxe",
"AntiTrojan Pro",
"AntiTrojanPro",
"AntiTroy",
"Antivir64",
"AntiVirProtect",
"Antivirus 2010 Security Centre",
"AntiVirus Agent Pro 1.00",
"AntiVirus Doktor 2009",
"Antivirus PC 2009",
"AntiVirus Plasma",
"AntiVirus Pro",
"AntiVirus Protection",
"AntiVirus_Pro",
"antivirus360",
"AntiVirusBEST",
"AntiVirusForAll",
"AntiViruspcsuite",
"AntiVirusPro2009",
"AntiVirusXP",
"APcDefender",
"APCProtect",
"APcSafe",
"APcSecure",
"aquaplay",
"Ardamax Keylogger",
"Ares Gold",
"ArmorDefender",
"ASC-AntiSpyware",
"Astrum AntiVirus Pro 3.6",
"ASWPro",
"AV AntiSpyware",
"AV",
"AV2010",
"AVDefender2011",
"AVGT",
"avrlab",
"avrlabs",
"AVSystemShield",
"BestHD",
"BHVideo",
"BitAccelerator",
"BitDownload",
"BitGrabber",
"BitRoll",
"BlanchDisc",
"BlockDefense",
"BlockKeeper",
"BlockProtector",
"BlockScanner",
"BlockWatcher",
"BlueRaTech",
"BrowserAccelerator",
"Bug Doctor",
"BugsDestroyer",
"BugsEraser",
"Casino King",
"Casino Tropez",
"Cheat Engine 5.1.1",
"CHMSaver",
"Cleanator",
"CleanPCTool",
"CleanupTool",
"clearpc2",
"ClickPotato",
"CLmuv",
"CLxdiv",
"code2master",
"code3master",
"code4master",
"Computer Defender 2009",
"ConfidentSurf",
"ConfidentUser",
"Content Cleaner",
"ContentEraser",
"ContrWare",
"Convert2Play",
"Crusader",
"DataHealer",
"DecodingHQ",
"Defence Center",
"DefendAPc",
"Desktop Defender 2010",
"DesktopLightning",
"Deus Cleaner",
"DigitalHQ",
"DioCleaner",
"Direct access to MastaPorn -- HOT!",
"DiscErrorFree",
"DiskSizeSaver",
"DivoCodec",
"DivxAccess",
"DivxFree",
"Doctor Adware Pro",
"Doctor Adware",
"doctorpc",
"DomPlayer",
"doublevaccine",
"Dr. Guard",
"DrAntispy",
"DriveDefender",
"DrProtection",
"drsave",
"DVDConv",
"DVDextraPL",
"DVDTool",
"DvidPL",
"eAntiVirusPro",
"Easy Spyware Cleaner",
"ecleansoft",
"EliteProtector",
"EndTheSpyware.com",
"ErrClean",
"Error Eraser",
"Error Nuker",
"Error Repair Professional",
"Error Safe Unregistered Version",
"ErrorClean",
"ErrorEasy",
"ErrorFighter",
"ErrorFix",
"ErrorKiller",
"ErrorRepairTool",
"ErrorSmart",
"ErrorSweeper",
"ErrorWiz",
"Evidence Eliminator",
"EvidenceEraser",
"ExpertAntiVirus",
"ExpressVids",
"extravideo",
"ezPorn",
"EZVideo",
"FileFix Professional 2009",
"FilterProgram",
"Fix Tool",
"FixMenaces",
"FixThemNow",
"Foxie Suite",
"Free Registry Cleaner For Vista",
"FreeHDPlay",
"GalaPlayer",
"GALTWARE",
"Gear Box Computers Software\\SpyBoss Pro Full",
"General AntiVirus",
"Get-Torrent",
"Ghost Antivirus",
"GimMePorn",
"GoldenAntiSpy",
"greatdefender",
"Green  AV",
"GuardCenter",
"GuardPcs",
"HardDriveGuard",
"HDextra",
"HDExtrem",
"HDPlugin",
"HDQuality",
"HDriveSweeper",
"HDtvcodec",
"help_clear",
"homeview",
"HOT Dialer",
"i-CashBack",
"ICQ Monitor Sniffer",
"IGuardPc",
"IHateAdware.com",
"IMMonitor AIM Spy",
"IMMonitor ICQ Spy",
"IMMonitor MSN Spy",
"IMMonitor MySpaceIM Spy",
"IMMonitor Yahoo Messenger Spy",
"Immunizr",
"iNETBLOCK",
"InfeStop",
"InfinityOptimizer",
"Inprivacy",
"Instant Spyware Removal",
"InSysSecure",
"Intelinet",
"Internet Explorer Guide V3",
"Internet Explorer wiznavi guide",
"KasperskyKeyGen",
"Keepcop",
"KillSpy",
"KillTheSpyware.com",
"KvmSecure",
"Lark AntiSpyware",
"LinkSafeness",
"Live Enterprise Suite",
"LiveAntispy",
"LiveProtection",
"LookForPorn",
"MacroAV",
"MacroVirus",
"Malware Defender 2009",
"malware Defense",
"Malware Doctor",
"MalwareBot",
"MalwareCrush",
"MalwareDestructor",
"MalwareMonitor",
"MalwarePro",
"MalwareRemoval",
"MalwareRemover.com",
"MalwareSweeper.com",
"MASTER ANTI Virus",
"Master Keystroke Logger",
"mediaview",
"MegaPorn",
"menacerescue",
"MendingTool",
"MoviesPlay",
"mProtect",
"MS AntiSpyware 2009",
"MSN Messenger Monitor Sniffer",
"MultiDefender",
"Muvexer",
"MyComGuard",
"MyPcSecure",
"MySpaceIM Monitor Sniffer",
"Nava Shield",
"Netcom3",
"NetPumper",
"Newfolder Fix Wizard",
"-=F=a=sdn",
"NoMalware",
"NowayVirus",
"OmegaPlay",
"OnlineGuard",
"OnlinePCGuard",
"P AntiSpyware 09",
"P2Pcontrol",
"PAL Spyware Remover",
"Paladin Antivirus",
"PatchupPlus",
"PC-Antispy",
"pc-care",
"PC-Cleaner",
"PC Clean Pro",
"PC Defender",
"PC Health Plan",
"PC Privacy2",
"PC Scout",
"PC_AntiSpyware2010",
"PC_Security2009",
"PCAntiMalware",
"PCAntiVirusPro",
"PcBoanPlus2",
"PCClear_Plus",
"pcdoumi2010",
"PcGuide",
"PCHealthKeeper",
"PCPrivacyCleaner",
"PCPrivacyDefender Freeware",
"PCprotectar",
"pcsafety",
"PcSecureNet",
"PCSecureSystem",
"pcsprotector",
"PcsSecure",
"PCSuperCharger Free",
"PCTotalDefender",
"pcvaccine",
"PCVirusless",
"Performance Optimizer",
"Personal AntiVirus",
"Personal Guard 2009",
"PersonalAntiSpy",
"PersonalAV",
"PersSecurity",
"Pestbot",
"PestTrap",
"PlayAllDVD",
"PLDivX",
"PluginDL",
"PluginVideo",
"PlusCodec",
"PornCleanser",
"pornvid",
"Preeda Software\\System Defend Antivirus 2010",
"PremierOpinion",
"Privacy center",
"Privacy Commander",
"Privacy components",
"Privacy Guarantor",
"Privacy Protection Suite 2.1",
"Privacy Watcher",
"PrivacyConductor",
"PrivacyControl",
"PrivacyKit",
"privacykorea",
"PrivacyWarrior",
"Pro AntiSpyware 2009",
"Pro Download Manager",
"ProtectDefender",
"ProtectHD",
"ProtectingTool",
"Protection cube",
"Protection System",
"ProtectionComplete",
"ProtectPcs",
"ProtectSoldier",
"PyroAntiSpy",
"qSearchHelp",
"Quick Registry Repair",
"QuickInstallPack",
"QuickTiming",
"QuickWatch",
"QuickyPlaeyr",
"RaptorDefence",
"RealAV",
"REAnti",
"REFOG Personal Monitor",
"Reg-Tool",
"RegFixPro",
"Registry Admin",
"Registry Defender Platinum",
"Registry Defender",
"Registry Doc 2006",
"Registry Doktor 2009",
"Registry Elite",
"Registry Helper",
"Registry Mighty",
"Registry Victor",
"Registry_Doktor 4.1",
"RegistryBot",
"RegistryCleaner_Pro",
"RegistryCleanerPro",
"RegistryDoctor2008",
"RegistryDoktor 4.1",
"RegistryFox",
"RegistrySmart",
"RegSweep",
"RegTidy 2009",
"RegTool",
"RelevantKnowledge",
"RESpyWare",
"RST Antivirus 2010",
"safe-pc",
"SafeFighter",
"SafeHardDrive",
"SafePcAv",
"SafePCTool",
"SaferScan",
"SafeStrip",
"SafetyKeeper",
"safeup2",
"safevaccine",
"SaveArmor",
"SaveDefender",
"SaveKeep",
"Scan119",
"Search And Destroy",
"SearchPorn",
"SearchSpy",
"Sec Software LCC",
"Secure PC Solutions\\1 Click Spy Clean",
"SecureCleaner",
"SecureExpertCleaner",
"SecureFighter",
"SecureFileShredder",
"SecureKeeper",
"SecurePcAv",
"SecurePCCleaner",
"SecureVeteran",
"SecureWarrior",
"Security 2009",
"Security Central",
"Security Mechanic",
"security119",
"SecurityFighter",
"SecuritySoldier",
"SelectiveAdmission",
"sexvid",
"ShieldSafeness",
"ShopperReports",
"SiteAdware",
"SiteEntry",
"SiteTicket",
"Smart Defender PRO",
"Smart Security",
"SmartShopper",
"SmartSoftware",
"Smiley District",
"Soft-Central SC-KeyLog",
"SoftBarrier",
"SoftCop",
"SoftSafeness",
"SoftSoldier",
"SoftStronghold",
"SoftVeteran",
"SoftwareDoctor",
"SpamBlockerUtility",
"Spy-Kill",
"Spy-Rid remover",
"Spy Doc Pro v5.2.0",
"spy protector",
"Spy Sniper",
"SpyDevastator",
"SpyEraser",
"SpyFlusher.com",
"SpyGuarder",
"SpyGuardPro",
"SpyPolice.com",
"SpySnipe",
"SpyStriker.com",
"spyvc",
"Spyware Cleaner 2009 V3.04",
"Spyware Cleaner 2010 V4.05",
"Spyware Nuker XT",
"Spyware Process Detector",
"Spyware Stormer",
"SpywareBot",
"SpywareCatch.com",
"SpywareCatcher.com",
"SpywareCops.com",
"SpywareGuard.com",
"SpywareIsolator",
"SpywareLocker",
"SpywarePolice.com",
"SpywarePro",
"SpywareRemover",
"SpywareRemover2009",
"SpywareSeeker.com",
"SpywareShield.com",
"SpywareSoftStop",
"SpywareStriker.com",
"SpywareSweeper",
"SpywareWipe.com",
"SpyWarp",
"SpyWatchE",
"SpyWipe.com",
"SsaeCom",
"ssaecom2010",
"Stiratel",
"StopBot.com Software",
"StopingSpy",
"Sunshine Spy",
"Swift Cleaner",
"Swift Software",
"SwiftPorn",
"SysCleaner",
"Syscleanerpro.com Software",
"SysDefence",
"SysDefenders",
"SysProtector",
"System Doctor Unregistered Version",
"System Guard 2009",
"System Protector",
"SystemDefender",
"SystemErrorFixer",
"SystemFighter",
"SystemOptimizer2008 Free",
"SystemTuner",
"SystemVeteran",
"SystemWarrior",
"The Last Defender",
"The Registry Sentinel",
"The Web Sentinel",
"TheDefend",
"TheSpyBot",
"ThreatNuker",
"TonsOfPorn",
"Torrent101",
"TorrentSoftware",
"Total Protect 2009",
"Total Virus Protection",
"TotalAntiSpyware.com Software",
"totalvid",
"Trace Sweeper",
"TRE AntiVirus",
"Trojansfilter",
"TrustCop",
"TrustedAntiVirus",
"TrustedProtection",
"TrustFighter",
"TrustNinja",
"TrustSoldier",
"TrustWarrior",
"TVHDX",
"ubervid",
"Ultimate Defender",
"Unigray AntiVirus",
"UnVirex",
"VaccineCenter",
"vaccineclear",
"vacpro",
"VideoKey",
"VideoPack",
"VideoPorn",
"vipantiSpyware",
"Virus Remover Professional",
"Virus2Bye",
"Virus3Bye",
"Virus3Out",
"Virusbye",
"viruscatch",
"VirusIsolator",
"VirusOut",
"VirusRanger",
"VirusRescue",
"virussol",
"VirusStop",
"virustop",
"VsSpy",
"VundoFixTool",
"WatchPorn",
"webHancer",
"WebSpyShield",
"WhenU",
"Win Antivir 2008",
"Win AntiVirus",
"Win Security 360",
"WinAnonymous",
"WinBlueSoft",
"WinCleaner 2009",
"WinDefender",
"Windows Anti-Virus Mate",
"Windows Police Pro",
"Windows Smart Security",
"WinFix Master",
"winguard",
"WiniBlueSoft",
"WiniGuard",
"WiniShield",
"WinPCDoctor",
"WinSecureAv",
"WinSpyControl",
"WinSpyKiller",
"WinSpywareProtect",
"WinZix",
"WistaAntiVirus",
"WMagister",
"XDenSer Software",
"XP antiVirus",
"XPdefender",
"XPProtectionCenter",
"XpyBurner",
"XXXHoliday",
"XXXPlugin",
"XXXSoft",
"Yahoo Messenger Monitor Sniffer",
"Yourprivacyguard",
"Zango Applications",
"MalwareAlarm",
"AVSystemCare",
"Internet Speed Monitor",
"KeyToPorn",
"WinXDefender",
"Awola",
"ADSTechnology",
"AntiSpywareBot",
"AntiSpywareSuite",
"kktone",
"PCPrivacyTool",
"PCTurboPro",
"WebMediaPlayer",
"Magicantispy",
"SpyKillerPro",
"ChristmasPorn",
"WinReanimator",
"engagesidebar",
"SpyAway",
"PerfectCleaner",
"WinIFixer",
"Hotbar",
"WinXProtector",
"AntiSpywareShield",
"Adzgalore Games Collection",
"Zango",
"BulletProofSoft.com",
"Spyware-Secure",
"Turkojan",
"SpyShredder",
"Hide Real IP",
"AntispySpider",
"PronVideo",
"SpywareScanner",
"Awola6",
"SpyBurner",
"AntiSpywareExpert",
"SpyMaxx",
"PestSweeper",
"WinX Security Center",
"PlayMP3z",
"Advanced XP Fixer",
"lake",
"XPSecurityCenter",
"Seekmo",
"AntiSpywareMaster",
"Total Innovations, Inc. Software",
"Privacy Redeemer",
"Halloween10",
"antonladyleg",
"GIGAPorn",
"XPGuard",
"SpywareDestructor",
"47AC~1",
"eKerberos",
"BingoVideo",
"Rapid Antivirus",
"Pornovid",
"Bach Khoa Antivirus",
"supervid",
"Setup Wizard",
"videosoft",
"videoplay",
"QUAD Utilities",
"coolplay",
"freshplay",
"DigitalLabs",
"WatchFree",
"PlayMe",
"System Security",
"Zinaps7",
"PlayMYDVD",
"System Security",
"UNICCodec",
"HeroCodec",
"XPShield",
"Platrium",
"ViScanPro",
"FullMovies",
"UltraVideo",
"AlfaHD",
"Malware Professional",
"WiniFighter",
"Windows Antivirus Pro",
"MalwareRemovalBot",
"Wind Optimizer",
"Antispyware",
"3wPlayer",
"AntiVirus360Remover",
"Contraviro",
"Perfect Optimizer",
"Total Security",
"Smart2Virus",
"SaveSoldier",
"Smart Virus Eliminator.lnk",
"SaveDefense",
"SystemCop",
"QuickHealCleaner",
"SaveKeeper",
"PC-Optimizer",
"AV Care",
"Vimedic",
"Personal Protector",
"AntiVirus Plus",
"AntiMalware_Pro",
"XP Privacy Pro",
"SnackMan",
"FaceCooker",
"Spyware Remover",
"VaccineSystem",
"Repair Registry Pro",
"Navi Search 2",
"Antimalware Defender",
"VKSaver",
"Your PC Protector",
"Antispyware Shield Pro",
"Spy-Speedy",
"Advanced Defender",
"comdoumi",
"Maileet",
"ANTIVIR Antivirus",
"CreditCop",
"Scan Virus",
"FLV Direct Player",
"Antimalware Doctor",
"User Protection",
"SeekingAlpha",
"Digital Protection",
"Coopen",
"SystemBodyguard",
"TrustDoctor",
"Your Protection",
"GuardWWW",
"Data Protection",
"Live Security Suite",
"SystemArmor",
"XJR Antivirus",
"AKM Antivirus 2010 Pro",
"MedicCop",
"PatchUp_Plus",
"Spyware Cleaner",
"Spycheck",
"SpyOut",
"TrueScan",
"safeguardplus",
"AV7.0",
"Sysinternals Antivirus",
"CursorZone",
"Anticare",
"Protection Center",
"Defense Center",
"Windows Firewall",
"NEOBOX",
"ByeClean",
"CodeDoctor",
"Vi2medic",
"Best Spyware Scanner",
"IpClear",
"CleanUp",
"Advanced Defender",
"Ardamax Keylogger",
"Advanced Spy",
"Win Security 360",
"Da Vinci",
"Barrio Trojan 5.0",
"UCmore XP - The Search Accelerator",
"SudoPlanet",
"Mach7.lnk",
"CleanVirus",
"QuickDownloadPack",
"P2Pcontrol",
"adcare",
"security119",
"MyInfoGuard",
"VCatch",
"Wireshark Antivirus",
"AVClean",
"Barrio Trojan 5.0",
"Adware-Alert",
"AnVi",
"Desktop Security",
"Antivir Solution Platinum",
"¹þ¹þÓÎÏ·ºÐ",
"É¨À×ÓÎÏ·",
"AÇÁ·ÎÅØÆ®",
"°Ù¶ÈÓÎÏ·´óÌü",
"Ò»ÆðÀ´ÒôÀÖÖúÊÖ",
"¿£Á©º§",
"È¨ÇÁ·ÎÅØÆ®",
"ÖÜÄ©ÓÎÏ·ºÐ×Ó",
"¶óÀÌºê¿Â¿¡¾î",
"ÍøÂçÓÅ»¯¼ÓËÙÆ÷",
"ÇØÇÇ·Î¶Ç",
"°Ù¶È³¬¼¶ËÑ°Ô",
"Ò»ÆðÀ´ÒôÀÖÖúÊÖ",
"IE°²È«×¨¼Ò",
"Ò»ÆðÀ´ÒôÀÖÖúÊÖ",
"ÇÁ¶óÀÌ¹ö½ÃÅ¬¸°",
"ÇÁ·ÎÅØÆ®ÀÎÆ÷",
"¹þ¹þÓÎÏ·ºÐ",
"Malware Destructor",
"RegistryClever",
"Malware Destructor",
"AV8",
"howcodec",
"µð½ºÅ©Å¬¸°",
"AntiVirus Studio 2010",
"IDº¸¾È",
"AntiVirus 2010",
"AntiVirus Solution 2010",
"System Tool",
"HDD Defragmenter",
"Disk Defrag",
"Security Inspector 2010",
"Debugs",
"Quick Defragmenter",
"PCClear_Plus",
"PCClearSophos",
"spycare",
"V2accine2010",
"Win Defrag",
"Win HDD",
"Check Disk",
"Ultra Defragger",
"Win Defragmenter",
"Hard Drive Diagnostic",
"HDD Diagnostic",
"HDD Plus",
"AntiMalware Pro",
"HDD Rescue",
"Windows System",
"HDD Tools",
"Spy-Speed",
"Defragmenter",
"SmartBoan",
"±¸¸£¸¶",
"AntiVirus System 2011",
"liveboan",
"WindowVaccine",
"Memory Fixer",
"SystemPro",
"SystemPro",
"My Disk",
"Fast Disk",
"Instant Spyware Remover",
"VirusVaccine",
"MessengerLog 360",
"Scanner",
"Disk OK",
"Good Memory",
"Memory Optimizer",
"Disk Optimizer",
"Windows Scan",
"Windows Disk",
"W9tndQqx2",
"pchd",
"ZeroVaccine",
"Windows One Click",
"AntiVirus System 2011",
"Disk OK",
"Disk Recovery",
"Disk Repair",
"Fast Disk",
"HDD Low",
"Memory Optimizer",
"Scanner",
"Win Disk",
"Windows Disk",
"Windows Scan",
"Disk Optimizer",
"HDD Fix",
"Memory Fixer",
"AntiVirus AntiSpyware 2011",
"AntiVirus AntiSpyware 2011",
"Win Scan",
"Windows Tool",
"ÇÁ·ÎÅØÆ®PC",
"Smart Defragmenter",
"Win Scan",
"UCmore XP  - The Search Accelerator",
"Windows Repair",
"Windows Restore",
"PC2Safe",
"NewClean2",
"Desktop Security",
"Windows System",
"Goorma",
"Security Solution 2011",
"vaccineu",
"FileClean",
"keepprotect",
"Windows XP Recovery",
"Windows 7 Recovery",
"Windows Vista Recovery",
"vc2008",
"Milestone Antivirus",
"firstvaccine",
"Direct access to MastaPorn -- HOT!",
"netvaccine",
"Windows XP Repair",
"Windows XP Restore",
"GuaGua DanceShows",
"Windows 7 Repair",
"Windows Vista Repair",
"Wireshark Antivirus",
"Security Solution",
"bizvaccine",
"System Diagnostic",
"Memory Optimizer",
"infoclear",
"Windows XP Fix",
"Windows 7 Fix",
"Windows Vista Fix",
"System Repair",
"CodeScan",
"DualVaccin",
"DualVaccine",
"boanmanager",
"Zentom System Guard",
"BlueFlare Antivirus",
"mykeeper",
"Sysinternals Antivirus",
"BlueFlare Antivirus",
"JMHL Loader",
"Security Solution1",
"realchecker",
"OpenCap",
"Security_Solution_2011",
"DefenseVirus",
"WolfRam AntiVirus",
"AntiVirus_AntiSpyware_2011",
"stip",
"Windows System\\Yes00",
"Windows System\\Yes00",
"Pc-Medical",
"OpenCloud Antivirus",
"speedvaccine",
"PatchUp_Plus",
"personal_party",
"Security Solution 2012",
"realcleaner",
"HDD Repair",
"Master Utilities",
"OpenCloud Security",
"PC Repair",
"RClean",
"Antivirus Soft Platinum",
"applicationIDE",
"Direct access to MastaGirls -- HOT!",
"Windupdt",
"boancheck",
"boancheck",
"perfectcure",
"Advanced PC Shield 2012",
"Clean-Top",
"vaccinecom",
"windowsliveprotect",
"Data Restore",
"Guard Online",
"Cloud Protection",
"AV Guard Online",
"Security Guard 2012",
"System Restore",
"dr-info",
"smartdefender pro",
"ModernPlus",
"FastScan",
"AV Protection Online",
"realclean",
"Antivirus System PRO",
"c-Nav",
"pczero",
"NVirusKorea",
"System Security  2011",
"CHMSaver",
"MozenComs",
"MozenKill",
"ModenKuc",
"Security Defender",
"Open Cloud AV",
"Clarity Seek Service",
"fileboan",
"Shop to Win 11",
"kPrivacy",
"windowpc",
"CleanPC",
"Smart Flash Recovery",
"privacyup",
"NaviSearch",
"zerocop",
"AV Security 2012",
"¼¿ÇÁÇÁ¶óÀÌ¹ö½Ã",
"ÇÁ·ÎÅØÆ®ÄÚµå",
"CleanCatch",
"B4AE~1",
"C91C~1",
"37CE~1",
"7FD6~1",
"C73F~1",
"Windows Live Winup",
"LanFile",
"ResearchBits",
"boanking",
"System Fix",
"vprotector",
"NDoctorCom",
"00CD1A401",
"MyInfoGuard",
"topboan",
"Advanced Defender",
"AntiVirus Plus",
"AV Protection 2011",
"Cloud AV 2012",
"System Fix",
"AÇÁ·ÎÅØÆ®",
"Shop to Win 15",
"PCKeeper",
"BoanKorea",
"Save Keys",
"smartsafer",
"Startups",
"purevaccine",
"speedcheck",
"purevaccine",
"speedcheck",
"1-2-3 Spyware Free",
"myLinker",
"Spy Fighter Pro",
"Desktop Security 2010",
"primevaccine",
"microvaccine",
"Security Monitor",
"info-care",
"Shop to Win 21",
"System Check",
"Saveboan",
"CodeClinic",
"Anti Virus Armor",
"winguard",
"Microsoft\\Service32.lnk",
"boanguard",
"EzHelper",
"Direct access to Pousse Pousse -- HOT!",
"74630177",
"safe_vaccine",
"boandefender",
"litevaccine",
"WinHeal Utilities",
"Antivirus Protection",
"cool-pc",
"internetboan",
"VaccineTop",
"goodvaccine",
"Direct access to Nuit de Feu -- HOT!",
"Jhoos",
"privacyg",
"svchost",
"turbopc",
"Antivirus Protection 2012",
"365boan",
"wisepc",
"powerboan",
"GoodScan",
"Antivirus Protection 2012TM",
"Hack Searcher Beta",
"MMyBoan2012",
"boankeeper",
"boaninfo",
"mastervaccine",
"totalboan",
"Smart Antivirus 2009",
"livesafer",
"ClickSystemToolbar",
"realspeed",
"AV Protection 2012",
"E-nrgyPlus",
"boanguide",
"perfectboan",
"proguard",
"check119",
"Wizeni",
"topchecker",
"vaccineupdate",
"checkvaccine",
"fastvaccine",
"protectpc",
"boanupgrade",
"mysafer",
"vaccinecode",
"Live Security Platinum",
"ClearVaccine",
"FileVaccine",
"Live Security Platinum",
"VitaVaccine",
"winliveprotect",
"VaccineForce",
"vaccinepc",
"smartspeed",
"WindowBoanPatch",
"controlspeed",
"AkrsC",
"vaccinepower",
"vaccinehelper",
"Win 8 Security System",
"WinsPop",
"SecureW2",
"defencevaccine",
"mypcclean",
"save-boan",
"speedbooting",
"pcfaster",
"BoanCenter",
"Download and Sa",
"Virtual Camara",
"PC Defender Plus",
"Facehack",
"BasicSafe",
"speedwindow",
"codevaccine",
"GhostVaccine",
"topscan",
"onlinevaccine",
"WindowSafe",
"PCSafe",
"windowcom",
"vaccinedoctor",
"VaccineTek",
"UpdateVaccine",
"CE95~1",
"multiclears",
"VirtualVaccine",
"windowfaster",
"TDVWYU",
"LimitVaccine",
"BrowseToSave",
"Search-NewTab",
"23 Instant Alert",
"DDoweNNloAd. and. Sia",
"DeskVaccine",
"Downloaadd AAnd SSa",
"DOwnloadd Anadd Sa",
"PickuNsaveItt",
"PieckNsavvEoIt",
"SaoveAs",
"SSaaveSAle",
"SSaveAs",
"SSeuarch-yNewTab",
"CaoouupoonIItt",
"PiaCkNsaavoeaItt",
"CyoDoeec-V",
"Wx- Shop2Win",
".print Client Windows",
"PriceeKyeaper",
"SearchNewTab",
"SmartCompare",
"VaUdiixx",
"vaccineclass",
"WhiteVaccine",
"quickcheoap",
"MainVaccine",
"System Doctor 2014",
"njRAT",
"boanclub",
"boanweb",
"speedcleaner",
"windowchecker",
"MiscrosoftSecure",
"boanlite",
"easyprotect",
"livecleaner",
"PC Defender 360",
"24x7 Help",
"controlpc",
"Freesofttoday",
"Direct access to Barre De Fer -- HOT!",
"StarterTV",
"SaveSense",
"vaccineauto",
"Power Pigeon 4.1 Demo",
"Tuto4PC",
"MYBESTOFFERSTODAY",
"Wajam",
"EZDownloader",
"Browser Warden",
"BrowserProtector",
"pc-fast",

            };

            // Path to the Program Files (x86) directory
            string programFilesX86Path = @"C:\Program Files (x86)\";

            Console.WriteLine($"Scanning folders in {programFilesX86Path}...");

            try
            {
                // Ensure the directory exists
                if (!Directory.Exists(programFilesX86Path))
                {
                    Console.WriteLine($"Directory not found: {programFilesX86Path}");
                    return;
                }

                // Get all directories in Program Files (x86) and subdirectories
                string[] directories = Directory.GetDirectories(programFilesX86Path, "*", SearchOption.AllDirectories);

                // Check each folder against the blacklist
                foreach (string directory in directories)
                {
                    string folderName = Path.GetFileName(directory);

                    if (blacklistedFolders.Contains(folderName))
                    {
                        Logger.Instance.LogPrimary($"Blacklisted folder found: {directory}");
                        // Optionally, take action (e.g., delete or quarantine the folder)
                        // Directory.Delete(directory, true); // Be cautious with this line!
                    }
                }
            }
            catch (UnauthorizedAccessException ex)
            {
                Console.WriteLine($"Access denied to some directories: {ex.Message}");
            }
            catch (PathTooLongException ex)
            {
                Console.WriteLine($"Folder path too long: {ex.Message}");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred during scanning: {ex.Message}");
            }

            Console.WriteLine("Scan complete.");
        }
    }
}
