using System;
using System.Collections.Generic;
using System.IO;

namespace Wildlands_System_Scanner.Blacklist
{
    public class ProgramFilesFileBlacklist
    {
        public static void ScanForBlacklistedFiles()
        {
            // Predefined blacklist of file names in Program Files (case insensitive)
            HashSet<string> blacklistedFiles = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
            {
"38a1~1.lnk",
"7da7~1.lnk",
"88ea~1.lnk",
"sursen live update.lnk",
"012A~1.LNK",
"Uninstall.lnk",
"IE Defender 2.2.lnk",
"Advanced XP Defender.lnk",
"Malware Protector 2008.lnk",
"IE AntiVirus 3.3.lnk",
"your sexy cam.zip.exe",
"Download programs.url",
"Games.url",
"Translator.url",
"Videos.url",
"7e3e~1.lnk",
"vm18.LNK",
"Windows Security Suite.lnk",
"Windows Protection Suite.lnk",
"Contraviro.lnk",
"Smart Virus Eliminator.lnk",
"Security Tool.lnk",
"Volcano Security Suite.lnk",
"SpySpotter.lnk",
"Security Tool.lnk",
"Additional Guard.lnk",
"Live Sex.lnk",
"ProtectSoldier.lnk",
"Live Sex.lnk",
"Security Guard.lnk",
"CleanUp Antivirus.lnk",
"Internet Explorer.nak",
"Live Sex.lnk",
"Intrenet Expleror.url",
"My Security Engine.lnk",
"AdBlaster.lnk",
"ByteDefender.lnk",
"Internet Explorer .url",
"Internet Explorer.IE",
"My Security Shield.lnk",
"Antivir Solution Platinum.lnk",
"Win7 AV.lnk",
"×ÀÃæ±ãÇ©.lnk",
"ImageReady Patch\\Patch.cmd",
"Accessories\\magic graphices maker.zip.exe",
"accwiz.exe",
"actmovie.exe",
"ahui.exe",
"alg.exe",
"append.exe",
"arp.exe",
"asr_fmt.exe",
"asr_ldm.exe",
"asr_pfu.exe",
"at.exe",
"atmadm.exe",
"auditusr.exe",
"autochk.exe",
"autoconv.exe",
"autofmt.exe",
"autolfn.exe",
"blastcln.exe",
"bootcfg.exe",
"bootok.exe",
"bootvrfy.exe",
"cacls.exe",
"calc.exe",
"charmap.exe",
"chkdsk.exe",
"chkntfs.exe",
"cidaemon.exe",
"cipher.exe",
"cisvc.exe",
"ckcnv.exe",
"cleanmgr.exe",
"cliconfg.exe",
"clipbrd.exe",
"clipsrv.exe",
"conime.exe",
"control.exe",
"csrss.exe",
"ctfmon.exe",
"dcomcnfg.exe",
"ddeshare.exe",
"debug.exe",
"defrag.exe",
"dfrgfat.exe",
"dfrgntfs.exe",
"diskpart.exe",
"diskperf.exe",
"dmadmin.exe",
"dmremote.exe",
"doskey.exe",
"dosx.exe",
"dplaysvr.exe",
"dpnsvr.exe",
"dpvsetup.exe",
"driverquery.exe",
"drwatson.exe",
"drwtsn32.exe",
"dumprep.exe",
"dvdplay.exe",
"dvdupgrd.exe",
"dwm.exe",
"dwwin.exe",
"dxdiag.exe",
"edlin.exe",
"esentutl.exe",
"eudcedit.exe",
"eventvwr.exe",
"expand.exe",
"explorer.exe",
"extrac32.exe",
"fastopen.exe",
"fixmapi.exe",
"fontview.exe",
"forcedos.exe",
"freecell.exe",
"help.exe",
"hostname.exe",
"iexplore.exe",
"java.exe",
"javaw.exe",
"javaws.exe",
"krnl386.exe",
"locator.exe",
"logagent.exe",
"logman.exe",
"logoff.exe",
"logonui.exe",
"lsass.exe",
"lsm.exe",
"mmc.exe",
"msgdvmn.exe",
"mshearts.exe",
"mshta.exe",
"msnmsgr.exe",
"mspaint.exe",
"narrator.exe",
"net.exe",
"net1.exe",
"netdde.exe",
"netsh.exe",
"netstat.exe",
"nlsfunc.exe",
"notepad.exe",
"nslookup.exe",
"ntbackup.exe",
"ntkrnlpa.exe",
"ntoskrnl.exe",
"ntsd.exe",
"ntvdm.exe",
"odbcad32.exe",
"odbcconf.exe",
"openfiles.exe",
"osk.exe",
"perfmon.exe",
"ping.exe",
"ping6.exe",
"powercfg.exe",
"PresentationHost.exe",
"print.exe",
"progman.exe",
"proquota.exe",
"proxycfg.exe",
"qwinsta.exe",
"rasautou.exe",
"rasdial.exe",
"rasphone.exe",
"rdpclip.exe",
"rdsaddin.exe",
"rdshost.exe",
"regedit.exe",
"regedt32.exe",
"regini.exe",
"route.exe",
"routemon.exe",
"rundll32.exe",
"runonce.exe",
"rwinsta.exe",
"savedump.exe",
"scardsvr.exe",
"schedul2.exe",
"schtasks.exe",
"SearchIndexer.exe",
"secedit.exe",
"services.exe",
"sessmgr.exe",
"SLsvc.exe",
"smss.exe",
"sndrec32.exe",
"sndvol32.exe",
"sol.exe",
"spider.exe",
"splwow64.exe",
"spnpinst.exe",
"spoolsv.exe",
"svchost.exe",
"sysedit.exe",
"syskey.exe",
"sysocmgr.exe",
"taskeng.exe",
"TASKMAN.EXE",
"Taskmgr.exe",
"tourstart.exe",
"twunk_16.exe",
"twunk_32.exe",
"userinit.exe",
"utilman.exe",
"verifier.exe",
"vssadmin.exe",
"vssvc.exe",
"WgaTray.exe",
"winhelp.exe",
"winhlp32.exe",
"wininit.exe",
"winlogon.exe",
"winmine.exe",
"winspool.exe",
"winver.exe",
"wlcomm.exe",
"wmpnscfg.exe",
"wowdeb.exe",
"wowexec.exe",
"wpabaln.exe",
"wpnpinst.exe",
"write.exe",
"wscntfy.exe",
"wuauclt.exe",
"wuauclt1.exe",
"wupdmgr.exe",
"xcopy.exe",
"Desktop Security.lnk",
".bestie0",
"Internet Explorer.bestie",
"AntiVirus Studio 2010.lnk",
"Internet Explore.lnk",
"Internet Explorer.fon",
"ShieldSoldier.lnk",
"AntiVirus\\Activate AntiVirus.lnk",
"AntiVirus\\AntiVirus.lnk",
"AntiVirus\\Help AntiVirus.lnk",
"AntiVirus\\How to Activate AntiVirus.lnk",
"Smart Engine.lnk",
"AntiVirus 2010.lnk",
"saveinf.exe",
"Debugs\\lsass.exe",
"Smart Security.lnk",
"Security Inspector 2010.lnk",
"ThinkPoint.lnk",
"Security Shield.lnk",
"Internet Security Suite.lnk",
"Personal Security Sentinel.lnk",
"Personal Internet Security 2011.lnk",
"AntiVirus System 2011.lnk",
"Palladium.lnk",
"HDD Fix.lnk",
"IE AntiVirus 3.4.lnk",
"Security Master AV.lnk",
"Smart Internet Protection 2011.lnk",
"Internet Security Essentials.lnk",
"AntiVirus AntiSpyware 2011.lnk",
"Internet Explorer.du",
"Best Malware Protection.lnk",
"System Security\\System Security 2009 Support.lnk",
"System Security\\System Security 2009.lnk",
"Internat Explorer.lnk",
"Internat Explorer.URL",
"Intrenet  Exqlorer.lnk",
"Internat Explorer.IE",
"PC Security Guardian.lnk",
"Security Shield.lnk",
"AviraCantTagMe.exe",
"Security Solution 2011.lnk",
"System Smart Security.lnk",
"DOWNLOAD5000.COM - FREE SOFTWARE, GAMES, TOOLS.lnk",
"Free Games.lnk",
"Free Screensavers.lnk",
".bestie0",
"Internet Explorer.bestie",
"Security Solution.lnk",
"winlogon.exe",
"Internet Explorer.html",
"Internet Explorer.IE",
"Internet Explorer.url",
"Program.exe",
"AntiVirus_AntiSpyware_2011.lnk",
".lnk",
"Security Solution1.lnk",
"tbico.ico",
"Internet Explorer.css",
"Internet Explorer.msm4",
"Security_Solution_2011.lnk",
"Internet Explorer.NewIE",
"OfferBox Browser.lnk",
"authcabaudit.exe",
"Security Master AV.lnk",
"My Security Shield.lnk",
"My Security Shield.lnk",
"Home Safety Essentials.lnk",
"Anti-Malware Lab.lnk",
"Windows System\\smith.exe",
"Windows System\\smith_root.exe",
"Windows System\\start.exe",
"Master Utilities\\Master Utilities.lnk",
"Master Utilities\\Uninstall Master Utilities.lnk",
"Security Solution 2012.lnk",
"Dofus.exe",
"Startupfile.exe",
"svchost.exe",
"funpics.exe",
"cfgscanres.exe",
"citi.exe",
"devmgrauth.exe",
"ntfsbootdev.exe",
"stip\\stip.lnk",
"UpdateDrv.exe",
"oracle_svr.exe",
"Security Tool.lnk",
"Virus Shield 2009.lnk",
"Hot_Netherlands.lnk",
"Security Sphere 2012.lnk",
"Sex.lnk",
"Startup2.exe",
"StartupMise A Jour.exe",
"Virus Doctor.lnk",
"My Security Engine.lnk",
"CleanUp Antivirus.lnk",
"HornyCam_il.lnk",
"Security Antivirus.lnk",
"Virus Sweeper.lnk",
"Windows Protection Suite.lnk",
"HornyGirls.lnk",
"centerpackdns.exe",
"Contraviro.lnk",
"config\\svchost.exe",
"ringtones.exe",
"Windows\\Msn.exe",
"My Security Wall.lnk",
"Virus Melt.lnk",
"System Fix",
"Windows PC Defender.lnk",
"MSDCSC\\msdcsc.exe",
"svchost.lnk",
"INTERNET EXPLORER.Ink",
"Startup.lnk",
"Startupminecraftunban.exe",
"Common Files\\Java\\svchost.exe",
"StartuprBot.exe",
"Adobe\\adobe_atieclx.exe",
"Startupbif-serv.exe",
"aconti.lnk",
"Desktop Security 2010.lnk",
"System Check\\System Check.lnk",
"System Check\\Uninstall System Check.lnk",
"Desktop Security.lnk",
"Malware Protector 2008.lnk",
"MYLOVE111.lnk",
"Home Security Solutions.lnk",
"Security Monitor.lnk",
"Internet Security Guard.lnk",
"server.exe",
"SexCams.lnk",
"WetGirls_in.lnk",
"Windows\\Services.exe",
"Antivirus Protection.lnk",
"Home Malware Cleaner.lnk",
"Strong Malware Defender.lnk",
"Windows Shield Tool.lnk",
"Windows Smart Warden.lnk",
"hotsex.lnk",
"Windows Threats Destroyer.lnk",
"Windows Personal Detective.lnk",
"Internet Explroer.lnk",
"Best Virus Protection.lnk",
"Hot Sex Software.lnk",
"Windows Performance Catalyst.lnk",
"Windows Personal Doctor.lnk",
"start\\xunLei.exe",
"Windows\\startupservices.exe",
"Windows Functionality Checker.lnk",
"Hot_Tarts_ca.lnk",
"Windows Tools Patch.lnk",
"Windows Managing System.lnk",
"Windows Safety Tweaker.lnk",
"Windows Risk Minimizer.lnk",
"XXXmpeg_tr.lnk",
"HardcoreVideos_gb.lnk",
"VideoGirls_jp.lnk",
"Windows No-Risk Center.lnk",
"Windows Security Kit.lnk",
"Windows Antihazard Solution.lnk",
"Windows Health Keeper.lnk",
"Windows Problems Stopper.lnk",
"Download programs.exe",
"Windows Process Director.lnk",
"Windows Process Director.lnk",
"Windows AntiHazard Helper.lnk",
"Antivirus Protection 2012TM.lnk",
"Windows No-Risk Agent.lnk",
"Windows Defending Center.lnk",
"Windows Trouble Taker.lnk",
"Gay_Sexy_nl.lnk",
"Windows Activity Debugger.lnk",
"Windows First-Class Proctector.lnk",
"Cantik.exe",
"Godmessage.lnk",
"HardcoreVideos_it.lnk",
"HotOrgy_it.lnk",
"HotVideo_ie.lnk",
"Image.exe",
"Imoet.exe",
"Windows Shielding Utility.lnk",
"Hardcore Dildoshow.lnk",
"exsplorer.lnk",
"x Adulti'.lnk",
"Windows Care Taker.lnk",
"Antimalware PC Safety.lnk",
"Smart Fortress 2012.lnk",
"Windows AntiHazard Center.lnk",
"Windows Antihazard Solution.lnk",
"Windows Attacks Defender.lnk",
"Windows Attacks Preventor.lnk",
"Windows Basic Antivirus.lnk",
"Windows Debug Center.lnk",
"Windows Firewall Constructor.lnk",
"Windows Guard Angel.lnk",
"Windows Malware Sleuth.lnk",
"Windows Personal Detective.lnk",
"Windows PRO Scanner.lnk",
"Windows Protection Master.lnk",
"Windows Risk Minimizer.lnk",
"Windows Shield Tool.lnk",
"Windows Smart Partner.lnk",
"Windows Smart Warden.lnk",
"Windows Software Keeper.lnk",
"Windows Software Saver.lnk",
"Windows Telemetry Center.lnk",
"Windows Trojans Inspector.lnk",
"Windows Efficiency Reservoir.lnk",
"Cashfiesta.lnk",
"Windows Stability Maximizer.lnk",
"Windows Component Protector.lnk",
"StartupKeylogger.exe",
"StartupUploader.exe",
"Windows Antibreaking System.lnk",
"Sexy_Hot.lnk",
"Windows Crucial Scanner.lnk",
"Epicbot52O\\Epicb0t.exe",
"Windows Protection Unit.lnk",
"Windows Antivirus Patch.lnk",
"MYLIVE2.lnk",
"Windows Guard Solutions.lnk",
"SMART HDD\\SMART HDD.lnk",
"SMART HDD\\Uninstall SMART HDD.lnk",
"Windows Pro Rescuer.lnk",
"Windows Safety Toolkit.lnk",
"Windows Performance Adviser.lnk",
"Windows Premium Guard.lnk",
"Windows Antibreaking System.lnk",
"Windows Antivirus Patch.lnk",
"Windows Foolproof Protector.lnk",
"Windows Guard Solutions.lnk",
"Windows Performance Adviser.lnk",
"Windows Premium Guard.lnk",
"Windows Pro Rescuer.lnk",
"Windows Safety Checkpoint.lnk",
"Windows Safety Manager.lnk",
"Windows Safety Toolkit.lnk",
"Windows Stability Maximizer.lnk",
"Windows High-End Protection.lnk",
"Windows Safety Module.lnk",
"Windows High-End Protection.lnk",
"Windows Recovery Series.lnk",
"Windows Safety Module.lnk",
"MSDCSC\\microsft.exe",
"Windows Daily Adviser.lnk",
"xpsservices.exe",
"Best Antivirus Software.lnk",
"Total Anti Malware Protection.lnk",
"Windows Pro Web Helper.lnk",
"Windows Pro Solutions.lnk",
"Chrome.exe",
"Windows Abnormality Checker.lnk",
"Windows Advanced User Patch.lnk",
"Windows Be-on-Guard Edition.lnk",
"Windows Daily Adviser.lnk",
"Windows Internet Booster.lnk",
"Windows Pro Solutions.lnk",
"Windows Pro Web Helper.lnk",
"Windows ProSecurity Scanner.lnk",
"Windows Sleek Performance.lnk",
"Playboy_de.lnk",
"System\\setup.exe",
"Windows Be-on-Guard Edition.lnk",
"Windows Secure Surfer.lnk",
"Windows Web Secure Kit.lnk",
"Windows Pro Safety Release.lnk",
"QW22\\qw.exe",
"seksokulu.lnk",
"Windows Multi Control System.lnk",
"System Protection Tools.lnk",
"Windows Guard Tools.lnk",
"HardcoreVideos_nl.lnk",
"HotOrgy_nl.lnk",
"HotSexy_Now.lnk",
"Windows Defence Counsel.lnk",
"Windows Safety Maintenance.lnk",
"Windows Antivirus Rampart.lnk",
"Windows Ultimate Security Patch.lnk",
"Windows Safety Wizard.lnk",
"Windows Turnkey Console.lnk",
"Windows Pc Aid.lnk",
"Windows Maintenance Suite.lnk",
"microsoft\\microsoft.exe",
"Windows Custom Safety.lnk",
"Windows Privacy Module.lnk",
"Windows Media Player\\msdcsc.exe",
"Windows Instant Scanner.lnk",
"Windows Maintenance Guard.lnk",
"Windows Proactive Safety.lnk",
"WinMoviePlugin.lnk",
"Windows Advanced Toolkit.lnk",
"WetGirls_fr.lnk",
"DirectX\\OpenGL.exe",
"Windows Control Series",
"Windows Pro Defence.lnk",
"Windows Proprietary Advisor.lnk",
"Windows Interactive Security.lnk",
"Windows Web Commander.lnk",
"Windows Expert Series.lnk",
"Startup%%\\serverzz.exe",
"Windows Virtual Angel.lnk",
"Windows Web Combat.lnk",
"Windows Premium Defender.lnk",
"Windows Virtual Firewall.lnk",
"Windows Security Renewal.lnk",
"e1xplorer.lnk",
"Windows Active Guard.lnk",
"Windupdate\\Winupdate.exe",
"Windows Interactive Safety.lnk",
"Windows Antivirus Release.lnk",
"Windows Virtual Security.lnk",
"Windows Anti-Malware Patch.lnk",
"Internet Explorer.exe",
"Windows Media Center.exe",
"Windows Secure Workstation.lnk",
"Windows Safety Series.lnk",
"krering39x.lnk",
"Sizzling_Blondes_gr.lnk",
"SexCams_au.lnk",
"Tips Kesehatan.exe",
"Internet Explorer.nak",
"Startuphello.exe",
"Ultra Antivir2009.lnk",
"goodthinxx.lnk",
"Sweden_sex.lnk",
"windows.exe",
"AsbMay\\rEd W0LFSysInfo.exe",
"system32\\windows.exe",
".0",
"Internat Exp1orer.n",
"LiveSexCam_hk.lnk",
"AV360\\update.exe",
"AV360\\updates.exe",
"pornaccess-1.lnk",
"Privatissimo.lnk",
"FreeDial\\FreeDial.lnk",
"FreeTV\\FreeTV.lnk",
"StartupFace.exe",
"start up\\explor.exe",
"start up\\svc.exe",
"windows\\msdcsc.exe",
"moduli1.lnk",
"SecurityScan\\SecurityScan.lnk",
"SecurityScan\\Uninstall.lnk",
"Main\\system.exe",
"svshost.lnk",
"Gta Casa.exe",
"MSDCSC\\WindowsUpdate.exe",
"vchostds.exe",
"MSDCSC\\Update.exe",
"BrowserDefender\\Uninstall BrowserDefender.lnk",
"Yugoslavia_sex.lnk",
"nttntnbbb.exe",
".IE0",
"WINUP\\update.exe",
"Accessories\\rgen.dll",
"Accessories\\servicesnb.exe",
"AntiSoft\\Uninstall.lnk",
"LiteWindow\\Homepage.url",
"LiteWindow\\LiteWindow.lnk",
".url",
"AntiVirus System 2011.lnk",
"Descargar programas.exe",
"Descargar programas.url",
"Download programs.url",
"Downloads.url",
"Easy Speed PC on the Web.lnk",
"Easy Speed PC.lnk",
"Games.url",
"Giochi.url",
"GoodSync.lnk",
"GoodSync_Uninstall.lnk",
"Internet Explorer.iex",
"IPMSG for Win32.lnk",
"Juegos.url",
"Khazande Persian.lnk",
"Ladda ner program..url",
"ManyCamStandaloneSetup.exe",
"MixPad Multitrack Recording Software.lnk",
"My picture.exe",
"My picture.lnk",
"My picture.pif",
"Ncstudio.lnk",
"Network Chat.lnk",
"new shortcut.lnk",
"Ohjelmien lataus.url",
"ojpcekwmqsg.htm",
"OUTLOOK EXPRESS.Ink",
"Pelit.url",
"PPStream.lnk",
"Programme downloaden.url",
"qjdrunbzyqga.htm",
"Scaricare programmi.url",
"Spelen.url",
"Spiele.url",
"Startup2C325E0889B379AB8E4283CC90304A31.bin",
"The Name 'o Matic.lnk",
"Traducteur.url",
"Traductor.url",
"Traduttore.url",
"Translator.url",
"Trillian.lnk",
"tuddnf.htm",
"Uninstall.lnk",
"Vertaler.url",
"Videos.url",
"Videot.url",
"WavePad Sound Editor.lnk",
"WINDOWS MEDIA PLAYER.Ink",
"Words fly at you.lnk",
            };

           // Predefined allowlist of legitimate file paths (case insensitive)
            HashSet<string> allowlist = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
            {
                @"C:\Program Files\Android\jdk\jdk-8.0.302.8-hotspot\jdk8u302-b08\bin\java.exe",
                @"C:\Program Files\Android\jdk\jdk-8.0.302.8-hotspot\jdk8u302-b08\bin\javaw.exe",
                @"C:\Program Files\Android\jdk\jdk-8.0.302.8-hotspot\jdk8u302-b08\jre\bin\java.exe",
                @"C:\Program Files\Android\jdk\jdk-8.0.302.8-hotspot\jdk8u302-b08\jre\bin\javaw.exe",
                @"C:\Program Files\Common Files\Oracle\Java\javapath\java.exe",
                @"C:\Program Files\Common Files\Oracle\Java\javapath\javaw.exe",
                @"C:\Program Files\Common Files\Oracle\Java\javapath_target_1309359\java.exe",
                @"C:\Program Files\Common Files\Oracle\Java\javapath_target_1309359\javaw.exe",
                @"C:\Program Files\Google\Chrome\Application\chrome.exe",
@"C:\Program Files\Internet Explorer\iexplore.exe",
@"C:\Program Files\Java\jdk-22\bin\java.exe",
@"C:\Program Files\Java\jdk-22\bin\javaw.exe",
@"C:\Program Files\Windows Media Player\wmpnscfg.exe",
@"C:\Program Files\WindowsApps\Microsoft.Paint_11.2411.471.0_x64__8wekyb3d8bbwe\PaintApp\mspaint.exe",
@"C:\Program Files\WindowsApps\Microsoft.WindowsNotepad_11.2410.21.0_x64__8wekyb3d8bbwe\Notepad\Notepad.exe",
            };

            // Path to the Program Files directory
            string programFilesPath = @"C:\Program Files\";

            Console.WriteLine($"Scanning files in {programFilesPath}...");

            try
            {
                // Ensure the directory exists
                if (!Directory.Exists(programFilesPath))
                {
                    Console.WriteLine($"Directory not found: {programFilesPath}");
                    return;
                }

                // Get all files in Program Files and subdirectories
                string[] files = Directory.GetFiles(programFilesPath, "*.*", SearchOption.AllDirectories);

                // Check each file against the blacklist
                foreach (string file in files)
                {
                    string fileName = Path.GetFileName(file);

                    // Skip files that are in the allowlist
                    if (allowlist.Contains(file))
                    {
                        Console.WriteLine($"Allowlisted file skipped: {file}");
                        continue;
                    }

                    // Flag files in the blacklist
                    if (blacklistedFiles.Contains(fileName))
                    {
                        Logger.Instance.LogPrimary($"Blacklisted file found: {file}");
                        // Optionally, take action (e.g., delete or quarantine the file)
                        // File.Delete(file); // Be cautious with this line!
                    }
                }
            }
            catch (UnauthorizedAccessException ex)
            {
                Console.WriteLine($"Access denied to some directories: {ex.Message}");
            }
            catch (PathTooLongException ex)
            {
                Console.WriteLine($"File path too long: {ex.Message}");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An error occurred during scanning: {ex.Message}");
            }

            Console.WriteLine("Scan complete.");
        }
    }
}